### PR TITLE
[Bug fix] Fixes lightning infill with sparse infill width set to 0 causes "divide by zero" fatal error

### LINKED ISSUE #3567: Lightning infill with sparse infill width set to 0 causes "divide by zero" fatal error
### OrcaSlicer Version

1.9.0

### OS version

Windows 10

### Additional system information

CPU: AMD Ryzen 7 3700X
RAM: 32GB
GPU: Nvidia RTX 3060

### Printer

Bambu Lab A1

### How to reproduce

1. Go to the Strength tab, then infill, and change the sparse infill pattern to Lightning
2. Go to the Quality tab, then line width, and change the sparse infill width to 0 (which should mean it uses the default line width)
3. Try to slice a print, it will give an error and will fail to slice.

### Actual results

The error given is:
```
A fatal error occurred: "Divide by zero"
Please save your project and restart the application.
```
image

This same exact error also happens with Bambu Studio 1.8.2.56 if you follow the same steps.

The error does not occur if you do not use lightning infill, or if you use a line width other than 0.
For example using a line width of 0 with the "line" infill type works fine, and using a line width in either absolute (0.42mm) or percent (105%) terms with lightning infill also works fine.

### Expected results

The object should slice using the default line width field, as it does when using infills other than lightning.

### Project file & Debug log uploads

[cube lightning infill bug.zip](https://github.com/SoftFever/OrcaSlicer/files/13865663/cube.lightning.infill.bug.zip)
[debug_Mon_Jan_08_19_45_22_21204.log.zip](https://github.com/SoftFever/OrcaSlicer/files/13865664/debug_Mon_Jan_08_19_45_22_21204.log.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

### PR DESCRIPTION
**Pull request by igiannakas**
Fixes #3567.

Firstly attempt to set it to the default line width. If that is not provided either, set it to a sane default based on the nozzle diameter.

### CODE REVIEW

**Comment by discip** [comment]
@igiannakas
If you put one of the following terms **`close, closes, closed, fix, fixes, fixed, resolve, resolves, resolved`** in front of the corresponding **issue** even **PR** the it will be automatically closed once this PR gets merged.

e.g.:
Change _`Fix for #3567.`_ to **`Fixes #3567.`**.

For reference see:
https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

**Comment by discip** [comment]
@igiannakas
If you put one of the following terms **`close, closes, closed, fix, fixes, fixed, resolve, resolves, resolved`** in front of the corresponding **issue** even **PR** the respective issue or PR will be automatically closed once this PR gets merged.

e.g.:
Change _`Fix for #3567.`_ to **`Fixes #3567.`**.

For reference see:
https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

**Comment by discip** [comment]
@igiannakas
If you put one of the following terms **`close, closes, closed, fix, fixes, fixed, resolve, resolves, resolved`** in front of the corresponding **issue**, or even **PR**, the respective issue or PR will be automatically closed once this PR gets merged.

e.g.:
Change _`Fix for #3567.`_ to **`Fixes #3567.`**.

For reference see:
https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

**Comment by igiannakas** [comment]
> @igiannakas If you put one of the following terms **`close, closes, closed, fix, fixes, fixed, resolve, resolves, resolved`** in front of the corresponding **issue**, or even **PR**, the respective issue or PR will be automatically closed once this PR gets merged.
> 
> e.g.: Change _`Fix for #3567.`_ to **`Fixes #3567.`**.
> 
> For reference see: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

Nice I didn’t know that!!

**Comment by discip** [comment]
@igiannakas
Sorry, I did not get right away why you changed the title. 😅
There seems to be a misunderstanding here.

You need to include the term **`Fixes #3567`** in your first comment rather than in the headline.

So the line _`Fix for #3567.`_ in the initial comment should be changed to **`Fixes #3567.`**.

It has not to be the first line though.

kind regards

**Comment by igiannakas** [comment]
> @igiannakas Sorry, I did not get right away why you changed the title. 😅 There seems to be a misunderstanding here.
> 
> You need to include the term **`Fixes #3567`** in your first comment rather than in the headline.
> 
> So the line _`Fix for #3567.`_ in the initial comment should be changed to **`Fixes #3567.`**.
> 
> It has not to be the first line though.
> 
> kind regards

Ah silly me! Thank you!

**Comment by discip** [comment]
No problem.
You are welcome! 😃👍

**Review by SoftFever — APPROVED** [review]
Looks good.
Thanks man!

**Pull request merged**
