### PR TITLE
3D Honeycomb - switch direction at smallest bridge point, rather than every layer

### PR DESCRIPTION
**Pull request by gringer**
This is an update to my 3D Honeycomb / Truncated Octahedron infill code to make the infill pattern a lot stronger, and more likely to hold at very low infill percentages. The only bridging happens at the square horizontal faces, and only once per direction change. I have also made pattern density tweaks to make the infill percent better match the extruded density.

While the pattern does exclude two hexagonal walls with each direction, the strength should be similar to a fully-filled truncated octahedron pattern because the diamond verticals are preserved, and *much* stronger than the current implementation.

### CODE REVIEW

**Comment by gringer** [comment]
Sure, here are a couple of images that demonstrate the new changes:

bridge_fix_animation

3dhoneycomb_bridge_fix

FWIW, this was fixed in Slic3r in [2018](https://github.com/slic3r/Slic3r/issues/4045), but that was shortly *after* Slic3r was forked for PrusaSlicer.

**Comment by SoftFever** [comment]
@gringer 
This is nice. Even though its geometry is that of a honeycomb, the way it prints and the benefits it provides are more similar to gyroid. Plus, it prints faster than gyroid!

This would be a great addition to the infill patterns. I'd prefer it to be added as a new infill pattern instead of replacing the current '3D honeycomb'; maybe call it 'Truncated Octahedron'?
Let me know what you think.

image
Screenshot 2024-03-13 224254

**Comment by Eldenroot** [comment]
Yes, please - do not change the current one but add a new infill pattern, I like it!

**Comment by igiannakas** [comment]
So if I get this right; this pattern doesnt overlap itself, same as gyroid, right? If so that's fantastic! A faster alternative is great :)!!

**Comment by gringer** [comment]
This fixes many bugs in the existing pattern. It's the same pattern, just an update. It should replace the existing 3D honeycomb pattern because the existing pattern is too weak. Both patterns have identical geometry, with direction switching for half the pattern time. The only difference is that this one switches direction less frequently (i.e. at the smallest bridge point rather than every layer).

For the existing pattern to work at all, it needed to have special bridge extrusion settings, which means that its speed is different from other infill, and its line width is harder to change.

There's no benefit in keeping the existing pattern.

See a mechanical comparison of the patterns here by @unicornswag:

https://forum.prusa3d.com/forum/prusaslicer/prusaslicers-3d-honeycomb-infill-is-sub-optimal/

**Comment by gringer** [comment]
> So if I get this right; this pattern doesnt overlap itself, same as gyroid, right? If so that's fantastic! A faster alternative is great :)!!

Yes, the truncated octahedron pattern in the 3D Honeycomb infill is quite similar to gyroid. It's basically a straight version of it, i.e. what gyroid would look like if the sine waves were replaced with lines having 45º direction changes.

Unlike gyroid, it has no direction changes in mid air, and therefore is likely to have fewer stringing issues for very low infill percentages (e.g. 5%). Due to being straight lines rather than sine waves it also has a smaller GCode footprint, which can help a bit with printer reliability when printing from an attached computer.

**Comment by SoftFever** [comment]
> > I'd prefer it to be added as a new infill pattern instead of replacing the current '3D honeycomb'; maybe call it 'Truncated Octahedron'?
> 
> This is a bug fix, not a feature request. It's the same pattern, just an update. We discussed the naming of this when the pattern was first introduced into Slic3r, and it was decided to call it "3D honeycomb" rather than "truncated octahedron (3D)". At that time there were no other 3D patterns:
> 
> [slic3r/Slic3r#1646 (comment)](https://github.com/slic3r/Slic3r/issues/1646#issuecomment-50535989)
> 
> I agree that because there are now other 3D patterns, it would make more sense to call it Truncated Octahedron, but that would touch a few more files.
> 
> This fixes many bugs in the existing pattern. It should replace the existing 3D honeycomb pattern because the existing pattern is too weak. Both patterns have identical geometry (i.e. they're both truncated octahedrons), with direction switching for half the pattern time. The only difference is that this one switches direction less frequently (i.e. at the smallest bridge point rather than every layer).
> 
> For the existing pattern to work at all, it needed to have special bridge extrusion settings, which means that its speed is different from other infill, and its line width is harder to change.
> 
> There's no benefit in keeping the existing pattern.
> 
> See a mechanical comparison of the patterns here by @unicornswag:
> 
> https://forum.prusa3d.com/forum/prusaslicer/prusaslicers-3d-honeycomb-infill-is-sub-optimal/

Wow, 10 years ago? You rock! Given that, yeah we don't need to revisit the naming discussion.

Personally, I haven’t used the current Honeycomb 3D infill due to the bridging issues. I’m confident your new 3D honeycomb will become a favorite among many users. 

Regarding the replacement, unless we receive feedback suggesting a valid use case for the old version, I’m all for replacing it with the new Honeycomb 3D as well.

**Review by SoftFever — APPROVED** [review]
Looks good

**Comment by SoftFever** [comment]
Merged.
Thanks @gringer

**Comment by SoftFever** [comment]
Quick testing results show very high quality, even at high printing speeds.

image
Filament: PETG 
Infills printing speed: at 126 mm/s

image

**Comment by SoftFever** [comment]
And of course I have to try 200 mm/s infill speed as well :)
image

**Comment by igiannakas** [comment]
Nice one! New default infill this 🎉

**Pull request merged**
