### PR TITLE
Update orca_bot.yml

### PR DESCRIPTION
**Pull request by Eldenroot**
Just for discussion :)

Also would be nice to set a different style of "stale" label, maybe with an icon... it is quite not visible on smartphone anr Github app.

### CODE REVIEW

**Comment by SoftFever** [comment]
Hi @Eldenroot 
Thank you for the proposal. Could you please provide some details about the differences? Screenshots would be appreciated, as it's quite challenging to imagine the changes just from the code ;)

**Comment by Eldenroot** [comment]
Hi @SoftFever 

Just minor improvements and few comments in code for better readability (and possible much easier extension in future). 

**Highlights:**
- commented code
- updated to v9 of action module
- change "completed" to "not planned" for auto closed issues
- skip stale label for draft PRs + assigned issues + assigned PRs + PRs/issues added into milestones
- auto delete PRs on stale PRs and 
- now the stale function for PRs is disabled, but the code is ready and just change the period for PR from -1 to whatever you want

It should work fine, there are no major changes from your previous version.

I hope that I have covered all and all is wrote above.

**Review by SoftFever — APPROVED** [review]
Looks good.

**Comment by Eldenroot** [comment]
Happy to help!

**Pull request merged**
