### PR TITLE
kor translation update

### PR DESCRIPTION
**Pull request by crwusiz**

### CODE REVIEW

**Comment by SoftFever** [comment]
@crwusiz 
Thanks, can you take a look that these errors?
```
Run echo $PWD
/home/runner/work/OrcaSlicer/OrcaSlicer
./localization/i18n/ko/OrcaSlicer_ko.po:6604:43: syntax error
./localization/i18n/ko/OrcaSlicer_ko.po:11984: missing 'msgstr' section
./localization/i18n/ko/OrcaSlicer_ko.po:11985:2: syntax error
msgfmt: found 3 fatal errors
Error: Process completed with exit code 1.
```

**Comment by crwusiz** [comment]
> @crwusiz Thanks, can you take a look that these errors?
> 
> ```
> Run echo $PWD
> /home/runner/work/OrcaSlicer/OrcaSlicer
> ./localization/i18n/ko/OrcaSlicer_ko.po:6604:43: syntax error
> ./localization/i18n/ko/OrcaSlicer_ko.po:11984: missing 'msgstr' section
> ./localization/i18n/ko/OrcaSlicer_ko.po:11985:2: syntax error
> msgfmt: found 3 fatal errors
> Error: Process completed with exit code 1.
> ```

sorry..i fix this...!

**Comment by crwusiz** [comment]
#, c-format, boost-format
msgid ""
"Density of internal sparse infill, 100% turns all sparse infill into solid "
"infill and internal solid infill pattern will be used"
msgstr ""
"내부 드문 채우기의 밀도, 100% tu모든 드문 채우기를 솔리드로 바꿉니다 채우기 "
"및 내부 솔리드 채우기 패턴이 사용됩니다"

=====================
If you do not enter the 100% turns translation as 100% tu, an error will occur

I think we need to change the turn's word so that it doesn't crash in the c-format.

**Comment by SoftFever** [comment]
> #, c-format, boost-format msgid "" "Density of internal sparse infill, 100% turns all sparse infill into solid " "infill and internal solid infill pattern will be used" msgstr "" "내부 드문 채우기의 밀도, 100% tu모든 드문 채우기를 솔리드로 바꿉니다 채우기 " "및 내부 솔리드 채우기 패턴이 사용됩니다"
> 
> ===================== If you do not enter the 100% turns translation as 100% tu, an error will occur
> 
> I think we need to change the turn's word so that it doesn't crash in the c-format.

We can also remove this line so that it won't complain
`#, c-format, boost-format`

**Review by SoftFever — APPROVED** [review]
Thanks

**Pull request merged**
