### PR TITLE
WIP: Outline with OpenGL core profile

### PR DESCRIPTION
**Pull request by Noisyfox**
This is a combination of #6492 and #6621 for testing purpose only. And this is the version that works on macOS.

### CODE REVIEW

**Comment by Noisyfox** [comment]
@discip could you give this PR a test and see if this solves the artifact?

**Comment by discip** [comment]
Will do as soon as compiling is done. 😊

**Comment by discip** [comment]
Unfortunately no improvement. 😞

By the way:
## Thank you very much for taking on this effort. 👍

**Comment by Noisyfox** [comment]
Close this as #6492 has been merged

**Pull request closed without merging**
