### PR TITLE
Display Commit ID Used for Build in AboutDialog

### PR DESCRIPTION
**Pull request by ElectricalBoy**
This PR adds the commit ID used for build in the `AboutDialog`. This should be especially useful when determining on what (nightly) build an issue is occurring.

Screenshot

_Resolves #5935_

### CODE REVIEW

**Comment by SoftFever** [comment]
While I like the idea, I can't stand the text appears there -_-!
Maybe show it only for nightly build?

**Comment by buzzhuzz** [comment]
I too like revision ID for nightly builds only.

Also, having that nightly builds are intended for testing and bug reports, I'd add revision hash as overlay right onto corner of 3D scene view like this (bottom right corner):

Screenshot from 2024-07-22 19-16-09

**Comment by SoftFever** [comment]
> > While I like the idea, I can't stand the text appears there -_-!
> > Maybe show it only for nightly build?
> 
> Is there a separate flag that only nightly builds have enabled? Or is it just the layout of things that you are not comfortable with?

One solution is to use CMake option and preprocess flag, ref to: https://stackoverflow.com/a/10364240
Then in the CI/CD, enable this option if it's a nightly build

**Comment by SoftFever** [comment]
@ElectricalBoy 
I'm closing it for now.
Feel free to re-open it whenever you feel ready

**Pull request closed without merging**
