### PR TITLE
StatusPanel

### PR DESCRIPTION
**Pull request by gobau**
- machine control page & AMS Page Width FIx
- MISC Panel Heghit FIX
- other font progress persent fix
- Korean languge Fix

BEFORE
image

AFTER 
image

### CODE REVIEW

**Comment by SoftFever** [comment]
Hi @gobau 
Thank you.
I have merged latest BS 1.7.4 UI related changes to the dev branch.
Could you verify if this issue still persist in the latest dev branch?

**Comment by gobau** [comment]
image
Unfortunately,
This problem seems to be caused by the difference between the size of the NotoSans KR font and the HarmonyOS_Sans_SC font.

**Comment by SoftFever** [comment]
It's strange, it's fine on my machine.
We have similar situations in this PR #1909
I wonder what could cause the problem.
image

**Comment by gobau** [comment]
OS Windows 11
Build build_release_vs2022.bat

As a result of debugging
Because of line 11 of Label.cpp.

If you reduce the font size a little, it will be solved.

Example

#ifndef __APPLE__
    size = size * 3 / 4;
#endif

OR 

#ifdef __linux__
    size = size * 4 / 5;
#endif

#ifdef __WINDOWS__
    size = size * 3 / 4;
#endif

**Comment by gobau** [comment]
You have made changes to this content.

**Comment by gobau** [comment]
image

**Comment by Hotsolidinfill** [comment]
Hi @gobau and @SoftFever 
I think this happened because the character heights between fonts are different.

HarmonyOS-0NotoSans-0
And because of the code below, fonts are loaded according to the default language of the operating system (ex.window11)
If operating systems with other languages like English or Chinese ​​as default, Noto Sans KR font does not be loaded.
- I think the code below will need to be modified in the future.

in Label.cpp

    wxString face = "HarmonyOS Sans SC";

    // Check if the current locale is Korean
    if (wxLocale::GetSystemLanguage() == wxLANGUAGE_KOREAN) {
        face = "Noto Sans KR";
    }
I'm going to make a PR after work that change font (which has similar font height with HarmonyOS Sasn SC).

**Comment by Hotsolidinfill** [comment]
@gobau @SoftFever 
Could you check the PR #1957 ?
I don't have BBL printer so can't fully check.

**Comment by SoftFever** [comment]
Thanks @Hotsolidinfill 
Your code changes look good to me.
Since I couldn't reproduce these issues on my machine from the beginning, I can't verify if this will fix the issues on your end.

On another note, the font seems a bit too thin in my opinion. However, the UI now displays a consistent font for Korean, so I don't see it as an issue.
image

For comparison, here are the Chinese and Japanese fonts.
The Harmony font should support CJK. I'm wondering why it displays Chinese and Japanese without issues, but encounters problems with Korean...
image
image

**Comment by Hotsolidinfill** [comment]
@SoftFever 
I thought it was strange too, so I looked into it.
GlyphRangesKorean is like below
        0x3131, 0x3163, // Korean alphabets
        0xAC00, 0xD7A3, // Korean characters

I found Harmony OS Sans SC font doesn't contain any Korean letters.
Sadly, this means that the font actually only supports CJ among CJKs.

-HarmonyOS Sans SC


-NanumGothic


I will try to find a font with a similar thickness and height. However, please understand that it may take some time as the conditions are strict.

**Comment by SoftFever** [comment]
closed as we have concluded in https://github.com/SoftFever/OrcaSlicer/pull/1957

**Pull request closed without merging**
