### PR TITLE
Show wireframe in MMU painter gizmo

### LINKED ISSUE #607: Viewing the mesh in Paint mode
[Feature request] When using "Paint" with the "Triangle" tool, have the possibility to visualise the mesh of the part to be coloured.

### PR DESCRIPTION
**Pull request by Noisyfox**
Now you can press Alt+Shift+Enter to show wireframe in MMU paint gizmo:

778460b112b0e33944eaafdccfd9415e

Adopted from BBS

Fix #607

### CODE REVIEW

**Review by SoftFever — APPROVED** [review]
Nice!

**Comment by Eldenroot** [comment]
Is there any "Icon" for toggle on/off?

**Comment by Noisyfox** [comment]
> Is there any "Icon" for toggle on/off?

Nope, only shortcut at the moment.

**Comment by Eldenroot** [comment]
Because normal user cannot know about this shortcut.

**Comment by Noisyfox** [comment]
image
This will show you the available shortcuts.

**Comment by Eldenroot** [comment]
OK, thx. anyway an icon would be nicer :) Maybe in future, step by step. There are other things to do (with higher priority). Keep good work!

**Pull request merged**
