### PR TITLE
Update Purge Profiles for BBL Printers

### PR DESCRIPTION
**Pull request by giveen**
I'm not the author of the profiles, but they are highly regarded as one of the best changes to purge profiles. it looks like the author went off Printables (where there was lots of comments) onto Makerworld.

@SoftFever 

https://makerworld.com/en/models/91241

### CODE REVIEW

**Comment by zbergus** [comment]
Perhaps adding additional profiles for this would be the way to go. The changes to the gcode would bring the filament up 2mm before cutting it so it saves 2mm but then it's required to change the purge amount to somewhere between 0.3-0.5 so there is additional steps. 

Also it should be warned that although this profile saves a considerable amount of purge waste there is still bleeding during dark/light colour changes (from personal experience) unless you calibrate each of your colours since.

**Comment by giveen** [comment]
> Perhaps adding additional profiles instead of overwriting the main profiles for this would be the way to go. The changes to the gcode would bring the filament up 2mm before cutting it so it saves 2mm but then it's required to change the purge amount to somewhere between 0.3-0.5 so there is additional steps.
> 
> Also it should be warned that although this profile saves a considerable amount of purge waste there is still bleeding during dark/light colour changes (from personal experience) unless you calibrate each of your colours.

Wouldn't take much to make a "Reduce Purge" Profile as an option.

**Comment by SoftFever** [comment]
Hmm, another way is that we can add a gcode variable and UI checkbox so users can turn on/off `retraction_before_cut` behavior in machine settings.
In the custom gcode, we can use `if` block to control the behavior:
```
{if retraction_before_cut}
; add retraction gcode
{endif}
```

**Comment by SoftFever** [comment]
the only concern I have is that the maintaince cost is very high whenever updating BBL profiles

**Comment by giveen** [comment]
I see a huge benefit to the profile, as long as people dont go around tweaking things so it may/may not mess up the GCODE.

Perhaps, as you suggested, a checkbox to activate it? Or just a completely separate profile option?

**Comment by SoftFever** [comment]
> I see a huge benefit to the profile, as long as people dont go around tweaking things so it may/may not mess up the GCODE.
> 
> Perhaps, as you suggested, a checkbox to activate it? Or just a completely separate profile option?

I prefer the checkbox.
Let me know if you need help for that.

**Comment by giveen** [comment]
> > I see a huge benefit to the profile, as long as people dont go around tweaking things so it may/may not mess up the GCODE.
> > Perhaps, as you suggested, a checkbox to activate it? Or just a completely separate profile option?
> 
> I prefer the checkbox. Let me know if you need help for that.

I literally have no idea how to do that, lol. Sorry.

**Pull request closed without merging**
