### PR TITLE
Fixed spanish translation and kingroon profiles added

### PR DESCRIPTION
**Pull request by tadeu2**
Fixed a lot of spanish strings and expressions from last translation, Kingroon profile added.

### CODE REVIEW

**Review by SoftFever — APPROVED** [review]
LGTM

**Comment by SoftFever** [comment]
Thanks @tadeu2. Appreciate it.

The changes look good.

In the future, it would be great to have two PRs in cases like this (one for translation and one for Kingroon profiles) so that it's easy to track.

**Comment by tadeu2** [comment]
Ok, sorry. I will do.

**Comment by SoftFever** [comment]
> Ok, sorry. I will do.

Not at all.
Really appreciate your work :)

**Pull request merged**
