### PR TITLE
Adds rotate on stl import

### LINKED ISSUE #1412: Auto Orient / Rotate model on import
**Is your feature request related to a problem? Please describe.**
Superslicer has a feature to auto-orient / rotate models on import. It's very handy for those of us who use different infill angles than 45 degrees.

**Describe the solution you'd like**
A printer setting to set the angle at which models should be imported at.

**Describe alternatives you've considered**
No real alternatives besides manually rotating every single model I import (no bueno).

**Additional context**

image
image

### PR DESCRIPTION
**Pull request by iitsalex**
Adds support for auto rotate on import for stls. Very handy for those who don't use 45 degrees as their standard infill direction (mostly for corexy printers if you want to use both motors for infill moves).

Added screenshot: 
image

Closes #1412

### CODE REVIEW

**Comment by SoftFever** [comment]
@iitsalex 
Thank you for working on this.
I can see this could be handy feature.

However, I have concerns to add it as a print setting.
The idea place to add this IMHO is to add this as orient tool like the `Auto orient` tool.
image

**Comment by jeremytodd1** [comment]
I'm looking forward to this feature, however, I'll toss in my two cents.

I like the idea of adding it to the top toolbar, though I don't think we should force everyone to always see the button as a majority of people wont use it often enough to justify it.

Instead of adding it as a whole separate button to the top toolbar, what if we add it as an option under the "Auto-arrange" button? For example:

auto-rotate

**Comment by SoftFever** [comment]
> I'm looking forward to this feature, however, I'll toss in my two cents.
> 
> I like the idea of adding it to the top toolbar, though I don't think we should force everyone to always see the button as a majority of people wont use it often enough to justify it.
> 
> Instead of adding it as a whole separate button to the top toolbar, what if we add it as an option under the "Auto-arrange" button? For example:
> 
> auto-rotate


I was debating with myself between this approach and the extra button when I was typing my previouse comment.
I'm okay with either way.  
I will leave it to you :)

**Comment by iitsalex** [comment]
The main thing that his accomplishes is that it allows auto-orientation. Having a button doesn't really accomplish that unfortunately.

**Comment by SoftFever** [comment]
> The main thing that his accomplishes is that it allows auto-orientation. Having a button doesn't really accomplish that unfortunately. @SoftFever

Hi @iitsalex 
Auto orentation is actually a problem here unfortunately.
I would debate that only a few people want to rotate 45 for some models.
They are models we shouldn't rotate e.g. calibration models.

**Comment by iitsalex** [comment]
> > The main thing that his accomplishes is that it allows auto-orientation. Having a button doesn't really accomplish that unfortunately. @SoftFever
> 
> Hi @iitsalex Auto orentation is actually a problem here unfortunately. I would debate that only a few people want to rotate 45 for some models. They are models we shouldn't rotate e.g. calibration models.

The only one I can see that would be problematic would be the max flow since it's a large model. Other calibrations seem to be just fine, based on my testing.

**Comment by iitsalex** [comment]
I should also note that the default rotation is 0 degrees, so normal printer profiles will be unaffected by this change. But yes, unexpected behavior with auto-rotation is no fun. Super slicer has some complications with this here and there, particularly with the retraction test(s).

**Comment by discip** [comment]
Here are my 2 cents:

How about adding another option in settings like **`Add`** above the `Downloads` entry, with a checkbox in front of the line **`rotate by 45° along z`**, together with a modified icon (45° bottom right) in the top bar if the corresponding checkbox is ticked.

**Comment by discip** [comment]
@SoftFever
@iitsalex
Here are my 2 cents:

How about adding another option in settings like **`Add`** above the `Downloads` entry, with a checkbox in front of the line **`rotate by 45° along z`**, together with a modified icon (45° bottom right) in the top bar if the corresponding checkbox is ticked.

**Comment by jeremytodd1** [comment]
The more I think about it, the more I believe that adding a button to the top bar isn't the correct way to go.

For this setting, people typically fall under two categories. 
1) They always have it enabled. 
2) They always have it disabled.

I think it's best if it doesn't clutter up the top menu bar as it's not something that people will change very often.

**Comment by iitsalex** [comment]
> The more I think about it, the more I believe that adding a button to the top bar isn't the correct way to go.
> 
> For this setting, people typically fall under two categories.
> 
> 1. They always have it enabled.
> 2. They always have it disabled.
> 
> I think it's best if it doesn't clutter up the top menu bar as it's not something that people will change very often.

Whole heartedly agree. It's non intrusive for those who don't use it, since it's defaulted to 0. And it's automatic and easy to let it do its thing as a setting per-printer.

**Comment by jeremytodd1** [comment]
I believe if people have a need for this setting, chances are they probably know what they're doing a bit more than the average user. If this is the case, they most likely have their own profiles setup specifically for 45 degree slicing, as well as other profiles for when they want to slice at 0 degrees.

IMO, this should just simply be a checkbox in the Process Profiles section.

**Comment by iitsalex** [comment]
> I believe if people have a need for this setting, chances are they probably know what they're doing a bit more than the average user. If this is the case, they most likely have their own profiles setup specifically for 45 degree slicing, as well as other profiles for when they want to slice at 0 degrees.
> 
> IMO, this should just simply be a checkbox in the Process Profiles section.

Checkbox doesn't allow for negative 45 degrees, and people may want a non-45 degree rotation. But yes, generally 45 degree is most common.

**Comment by iitsalex** [comment]
I should also note this is lovingly ported over from SuperSlicer. It's mentioned on the original issue but forgot to mention it here.

**Comment by SoftFever** [comment]
The consideration here is that this pertains to a model layout/rotation operation.  It is not part of the print setting.
It falls under the same category of operations as `Auto orient`, `Move`, and `Rotate`. 
Logically(and avoid confusing users), if we want to incorporate this handy feature proposed by this PR, it should be named as `Auto rotate` and have a similar tool button on top, just like the other operations.

FWIW, we can achieve a similar effect by pressing Ctrl + A to select all models on the plate, and then pressing Page UP or Page Down to rotate 45 degrees with each keystroke.
But a dedicated toolbar button would be handy and more visible to users.

**Comment by iitsalex** [comment]
Here is the related PR where printer-specific configuration was decided upon for Superslicer:
https://github.com/supermerill/SuperSlicer/pull/1709

**Comment by iitsalex** [comment]
Also added screenshot of existing implementation/location to original comment above.

**Comment by jeremytodd1** [comment]
I'd say about 75% of my prints are at 45 degrees. The other 25% are at 0 degrees because they're large first layer objects and they wont fit the print sheet if I rotate them.

I do see the reasoning with sticking it in the Printer Profile section, but I personally would find it annoying having to go there and turn the setting off 25% of the time.

I think there is a happy medium between all of our opinions on this, and we need to figure out what that is lol.

**Comment by SoftFever** [comment]
I'm not opposed to the 45-degree feature. If people like it and believe it's helpful, that's fine.

My perspective is primarily from a UX standpoint and ensuring consistent operation logic. This isn't a slicing parameter. Given that we have very similar operations (like 'Auto Rotate' to place the model on the bed), it makes more sense to position the new button in the same area to maintain consistency and reduce confusion.

A button in this place would be ideal and handy IMO:
Icon is from @discip comment
image

**Comment by jeremytodd1** [comment]
Softfever, would it be possible to have it remember the state of the button between sessions? If I enable that button for this current session, close out of Orca and then later open Orca again, would I have to re-enable that button again?

**Comment by iitsalex** [comment]
As @jeremytodd1 mentioned, I wouldn't even bother with this enhancement if it wasn't automatic by nature. I still think that generally speaking it's a "printer" setting since the kinematics of a printer usually dictate how you want to orient the part. I don't *really* mind if it was put under "special mode" as todd mentioned, but I still fail to see why it's any better than per-printer basis. If someone wanted to have this setting on many slicing profiles, they would have to set it per-profile. That could be a benefit, but it's overall a downside for my personal workflow. 

I know that my workflow is based on what I'm used to, which was superslicer so I understand that we might be able to improve upon the original design. I will say, many people will be swapping from superslicer to orca, so they might be in the same predicament as me.

**Comment by jeremytodd1** [comment]
>If someone wanted to have this setting on many slicing profiles, they would have to set it per-profile. 

Agree with this 100%. I'd be happy with having the button on the menu bar like SoftFever is saying (for the people that might want to rotate once in a while to help with rear same placements or something like that), but I think if this feature is ported in that it's pretty crucial to also have a setting in a profile (whether that be in the printer profile or in the process profile, it doesn't matter) where people can just enable it and forget it.

The whole idea of the feature request is to automate this step of the process for the people that constantly use it. If you _only_ have a button on the top menu bar that isn't a whole lot better than the current process of manually rotating the parts.

**Comment by SoftFever** [comment]
> As @jeremytodd1 mentioned, I wouldn't even bother with this enhancement if it wasn't automatic by nature. I still think that generally speaking it's a "printer" setting since the kinematics of a printer usually dictate how you want to orient the part. I don't _really_ mind if it was put under "special mode" as todd mentioned, but I still fail to see why it's any better than per-printer basis. If someone wanted to have this setting on many slicing profiles, they would have to set it per-profile. That could be a benefit, but it's overall a downside for my personal workflow.
> 
> I know that my workflow is based on what I'm used to, which was superslicer so I understand that we might be able to improve upon the original design. I will say, many people will be swapping from superslicer to orca, so they might be in the same predicament as me.

But what's wrong to put the option in the appconfig? It's a perfect place to put an option of 'rotate 45 after importing a model` , isn't it?
We still have the auto rotation behavior and are not confusion.

**Comment by iitsalex** [comment]
> Sorry if this frustrates you. I hope you understand where my concerns are coming from.
@SoftFever definitely not frustrated, as @jeremytodd1 said, it's best to have these viewpoints and conversations come up now rather than later. Concerns about going forward are a sign that we care about the end result haha.

I see the reasoning that we wouldn't want to bloat the app, but todd mentioned that this would be an advanced parameter, something that users will never see unless they want to. Having it as an appconfig would limit users to either use it or not use it, which destroys the user experience for advanced users, who may want to use it 75% of the time and 25% not use it, as todd mentioned.

**Comment by iitsalex** [comment]
After writing the previous comment, I do realize that there is some lenience in deciding the "correct" place to put the setting when you take into account the idea that people will often tightly couple their infill orientation with their print orientation. So technically speaking the slicing profiles that utilize a specific angle of infill will want a specific angle of part orientation, meaning that you can't *really* reuse slicing profiles unless you *want* to match infill angle and part orientation for some reason. Some people may want that, but I can't cater to *everyones* desires.

Speaking in a lazy manner, porting this over from SuperSlicer and keeping the same behavior follows the "if it ain't broke, don't fix it" mantra. Would make it easier for people to swap from SuperSlicer to OrcaSlicer so the behavior operates they way they expect. Just kinda spitballing 🤷

**Comment by jeremytodd1** [comment]
I do agree with you for that at this point. Printer profiles would be the best location to have the setting. That is where it makes the most sense.

**Comment by SoftFever** [comment]
> Do you agree that generally speaking users would tie their kinematics to the orientation they wish to import their models?

I have two main perspectives on this:

1. I'm not entirely convinced that printing at 45 degrees is optimal for CoreXY. To date, there's no solid evidence supporting this idea. The argument about a single motor doesn't hold much weight in my view. With modern firmware, I don't believe coordinating multiple motors would have any noticeable impact on print quality. Consider printers like the Annex K3 and the VzBot AWD CoreXXYY – they both produce high-quality prints. Personally, I haven't seen any tangible benefits from printing at a 45-degree angle.
2. Even if we assume there's a benefit to the 45-degree orientation, its usefulness would largely depend on the specific shape of the print.


Back to topic, on a second thought, I don't object to add this option to printer settings.

**Comment by SoftFever** [comment]
I'm closing this PR for now. 
Feel free to reopen it whenever it's ready.

**Comment by l-ejs-l** [comment]
why was this closed? a lot of people really want this feature. Just do it like in superslicer and if you dont want to use it.. just dont. Please give us this functionallity, so anoying to rotate every print!

**Comment by Eldenroot** [comment]
I vote for printer settings

**Comment by iitsalex** [comment]
@l-ejs-l @Eldenroot Thanks for reminding me about this one. I do agree that printer settings makes the most sense, but ultimately it depends on what @SoftFever is okay with merging in. I can update the code review to the latest build but it's up to them to merge it in.

**Comment by l-ejs-l** [comment]
@Eldenroot If you add this on printer settings it should be fine i think, @SoftFever in one of his comments said it should be fine so no issues for merge.

**Comment by iitsalex** [comment]
Created a new CR [here](https://github.com/SoftFever/OrcaSlicer/pull/3116) since I can't re-open this one.

**Pull request closed without merging**
