### PR TITLE
QoL: Make sidebar collapsible, resizable, movable, floatable and dockable

### PR DESCRIPTION
**Pull request by Noisyfox**
image
image

You can now drag the sidebar to the left or right, or float.
If you ever messed up with the layout, there is a reset to default layout option in the view menu.

Update: Now you can collapse the side bar too:
fd23613b72245bfd42b133a80b50c50b
9edd1b2910164ac0f732a3513117ce11

### CODE REVIEW

**Comment by tlhintoq** [comment]
> Though I'm not so sure how useful this could be after playing with this for a while. I guess the most useful feature is to allow resizing the sidebar on small screens.

Hopefully this means I can float it, then extend it past a single monitor. (See #2889 )
It would be useful for folks with stacked monitors to extend the sidebar (as well as the main window), in order to see the entire side bar at once and end the continuous scrolling up and down.

image

**Comment by tlhintoq** [comment]
> > Hopefully this means I can float it, then extend it past a single monitor. (See #2889 )
> 
> I saw that one, unfortunately I couldn't debug that as I currently have only single monitor. Will definitely take a look as soon as I have any chance.

Well if there's anything I can do to help/test just let me know.  For example, if you notice code that looks like its forcing a snap-to, comparing against monitor height, etc. and want it tested after commenting it out - let me know.

**Comment by StuSerious** [comment]
I like to keep the sidebar open in a secondary vertical monitor.

I'd be willing to test multi-monitor setups if needed :)

**Comment by tlhintoq** [comment]
> > I like to keep the sidebar open in a secondary vertical monitor.
> 
> Does the current build support dragging the side bar to a second monitor?

Who are you asking  and what do you mean by 'current'?
Because in 1.8.1 public release the side bar doesn't seem to pull off at all.

{hint}
Would really love to see a 1.8.2 put out to the public considering how many fixes have been brought up in the last 72 hours.  Plenty of us with multiple monitors that would give feed back on this and other UI elements.
{/hint}

**Comment by Noisyfox** [comment]
> > > I like to keep the sidebar open in a secondary vertical monitor.
> > 
> > 
> > Does the current build support dragging the side bar to a second monitor?
> 
> Who are you asking and what do you mean by 'current'? Because in 1.8.1 public release the side bar doesn't seem to pull off at all.
> 
> {hint} Would really love to see a 1.8.2 put out to the public considering how many fixes have been brought up in the last 72 hours. Plenty of us with multiple monitors that would give feed back on this and other UI elements. {/hint}

The build of current PR.

**Comment by SoftFever** [comment]
> Though I'm not so sure how useful this could be after playing with this for a while. I guess the most useful feature is to allow resizing the sidebar on small screens.

I'm on the same boat.
But I see no harm in adding this capability since it won't disrupt current user habits.
Well done 💯

**Review by SoftFever — APPROVED** [review]
Looks good

**Comment by SoftFever** [comment]
Multi monitors supporting is fine👍
image

**Comment by igiannakas** [comment]
@SoftFever looks like the merge wasn't successful on Main for this - can't compile the main branch on Mac. Throws errors in the platter.cpp file. Same for the CICD pipeline - hasn't compiled OSX for some reason.

**Comment by SoftFever** [comment]
Hmmm I managed to build it in my Mac. I will double check once I get home

**Comment by SoftFever** [comment]
@igiannakas 
That's strange...
Screenshot 2023-12-08 at 10 20 12 PM

**Comment by igiannakas** [comment]
Looks like it’s working now :)

**Comment by discip** [comment]
I'm not sure if the following issue isn't caused by another commit, but unfortunately it doesn't quite work on Linux (Manjaro).

image

**Comment by SoftFever** [comment]
yeah, It's a CICD issue, I've fixed it.

**Pull request merged**
