### PR TITLE
Styrene Butadiene Styrene (SBS) - Template and profiles for Bambu

### PR DESCRIPTION
**Pull request by dgauche**
# Description

Addresses: [issue 5980 ](https://github.com/SoftFever/OrcaSlicer/issues/5980)

- Added Styrene Butadiene Styrene (SBS) to templates allowing you to create specific configurations of the filament
- Added Generic SBS to Bambu Printers

This is a very popular filament in South Africa with multiple manufacturers.

Examples:
https://www.filx.co.za/products/sbs/
https://dc3dprinters.co.za/product/sa-filament-sbs-plus-1-75mm-white-750g/

# Screenshots/Recordings/Graphs
Screenshot 2024-07-28 at 21 18 32
Screenshot 2024-07-28 at 21 19 28
Screenshot 2024-07-28 at 21 18 51

### CODE REVIEW

**Comment by dgauche** [comment]
@SoftFever could you please review?

**Review by seanrademeyer — APPROVED** [review]

**Comment by dgauche** [comment]
I can see that the flatpack build failed, it is however not clear to me why, or if that matters.  I have built this for mac locally and it seems that for the automated testing it also builds for all the other platforms.... @SoftFever  I would appreciate some guidance here. Thanks.

**Comment by dgauche** [comment]
Thanks @ElectricalBoy that checks out.

**Review by SoftFever — APPROVED** [review]
Looks good
Thank you

**Pull request merged**
