### PR TITLE
Add splash screen toggle

### PR DESCRIPTION
**Pull request by Ocraftyone**

### CODE REVIEW

**Review by SoftFever — APPROVED** [review]
Looks good 👍

**Comment by SoftFever** [comment]
merged, thanks!

**Comment by ajaytanna** [comment]
In all the Nighlies. Alpha and Beta versio prebuilt binaries for MacOS Arm64 including today 1.9.0 version the splash screen is a black box. In release version 1.8.0 and 1.8.1 it always shows the splash image as it should. This is on MacOS Sonoma 14.2.1 on. an M2Pro

**Comment by Ocraftyone** [comment]
> In all the Nighlies. Alpha and Beta versio prebuilt binaries for MacOS Arm64 including today 1.9.0 version the splash screen is a black box. In release version 1.8.0 and 1.8.1 it always shows the splash image as it should. This is on MacOS Sonoma 14.2.1 on. an M2Pro 

Please open a new issue as this seems to be unrelated to this PR. This only added the option to turn it off and did not change any other rendering code.

**Pull request merged**
