### PR TITLE
Reworked Toolbar icons

### PR DESCRIPTION
**Pull request by yw4z**
Screenshot-20240304041606

Screenshot-20240304023526

• All icons pixel perfect now
• Some icons uses 40x40 instead 39x40. That caused blurry images
• All icons redesigned or tweaked to fit to square. all visible as equal size now
• I tried to keep constinency between icons with using same arrow shapes, line width, proportions

• Reworked "Add Object". Resized cube to fill icon frame. Used isometric cube for better visual
• Reworked "Add Plate".Resized bed sheet to fill icon frame. Changed badge to fit nicely with icon frame
• Reworked "Auto Orient" and "Lay on Surface". It highlights object's edge/surface instead of all object. Added an * for auto because user cannot read auto text on that
• Designed new icons for "Split to Objects" and "Split to Parts". old ones just used letters and they are not representing functions
• Designed new icons for "Move, "Rotate", "Scale". Used same object at their center to increase similarity between them. Tried to increase similarity because all transform functions
• "Cut","Emboss". Simplified
• Measure > Added arrows to fill icon frame so it will look same size with other icons
• Assembly > Merged puzzle parts to increase size of icon to matching size of icon with others
• Seam Painting > Used same isometric cube on "Add Object" to improve constinency between icons

• Total size for changed icons reduced 92,6KB to 34,9kb

### CODE REVIEW

**Comment by yw4z** [comment]
also there is a bug on toolbar placement that causes blurry images. i described in here
https://github.com/SoftFever/OrcaSlicer/issues/4328

**Comment by yw4z** [comment]
Screenshot-20240304040630

• Added a badge for Support painting and Seam painting to indicate they are similar type of functions
• And this change will increase seperation between mesh boolean and support painting icons

**Comment by Eldenroot** [comment]
Better to use brush icon on these two?

**Comment by yw4z** [comment]
@Eldenroot here draw few alternatives for painting


Screenshot-20240304193434

that area is only 12x12px so it drawing must be simple as possible. spray is also looks nice to me

**Comment by yw4z** [comment]
here is a version with caliper for measure function

Screenshot-20240305030206

i didnt commit latest changes yet, let me know your thoughts

also i noticed this order would be better for toolbar icons
Screenshot-20240305031523

**Pull request closed without merging**
