### PR TITLE
Remove icons from titlebar menubar

### PR DESCRIPTION
**Pull request by yw4z**
# Description

• Removed icons from File and More menu. so they will look like menu bar similar to ribbon interface and look more natural
• Looks more modern with less clutter
• Does not requires new translations
• Added extra spacing so text looks like centered to buttons
• Didn't removed icons from source. i can remove them if requested
> topbar_file.svg
> topbar_dropdown.svg

# Screenshots/Recordings/Graphs

Before vs After
Screenshot-20240513131326

Here is an alternative version with calibration menu moved to menubar section (Not included commit)

330018196-7ff3386e-001f-4fa9-b20d-f30faf0ff77a

## Tests

Tested on windows 10

### CODE REVIEW

**Comment by SoftFever** [comment]
> # Description
> • Removed icons from File and More menu. so they will look like menu bar similar to ribbon interface and look more natural • Looks more modern with less clutter • Does not requires new translations • Added extra spacing so text looks like centered to buttons • Didn't removed icons from source. i can remove them if requested
> 
> > topbar_file.svg
> > topbar_dropdown.svg
> 
> # Screenshots/Recordings/Graphs
> Before vs After Screenshot-20240513131326
> 
> Here is an alternative version with calibration menu moved to menubar section (Not included commit)
> 
> 330018196-7ff3386e-001f-4fa9-b20d-f30faf0ff77a
> 
> ## Tests
> Tested on windows 10

Thanks man.
I prefer the alternative proposal a lot :)
image

**Comment by SoftFever** [comment]
> I think the alternative is the nicest looking option.
> 
> IMO, the icons for file/calibration/more are not needed. Icons + Text just adds unnecessary clutter to the menu bar. Just the text looks great and clean.
> 
> Most programs do not have both icons and text for the main menu bar items.

I would agree with you if this is a conventional menu bar, that usually only contains text.
But here for Orca, icon+text look much better

**Comment by yw4z** [comment]
@SoftFever i'm thinking same with @jeremytodd1 . menus without icons look more natural and modern

**Comment by yw4z** [comment]
Screenshot-20240530035839

@SoftFever moved calibration menu to menubar section

**Comment by SoftFever** [comment]
> Screenshot-20240530035839
> 
> @SoftFever moved calibration menu to menubar section

Thanks @yw4z 
I prefer to keep the icons. Can we add back the icons?

**Pull request closed without merging**
