### PR TITLE
Various fix & improvements to collapse sidebar

### PR DESCRIPTION
**Pull request by Noisyfox**
image

1. Make the collapse button smaller
2. Fix button color in dark mode
3. Add tooltip
4. Fix sidebar collapse hotkey
5. Other small bugfixes

### CODE REVIEW

**Comment by Noisyfox** [comment]
Just noticed a small issue. Gonna fix it tomorrow morning.

**Comment by Eldenroot** [comment]
Please implement undo history from Prusaslicer.

**Comment by Noisyfox** [comment]
> Please implement undo history from Prusaslicer.

Could you raise another ticket or point me to an existing one? Thanks.

**Comment by Eldenroot** [comment]
https://github.com/SoftFever/OrcaSlicer/issues/2425

**Review by SoftFever — APPROVED** [review]
Cool!

**Comment by discip** [comment]
@Noisyfox
Unfortunately I'm facing an issue even after this fix on Linux (Manjaro).

This is how it looks immediately after a fresh start and when switching from one setting menu to another (e.g.: **`Quality`** > **`Speed`**) or from **`Global`** > **`Objects`**.

image

image

**Comment by Noisyfox** [comment]
> @Noisyfox Unfortunately I'm facing an issue even after this fix on Linux (Manjaro).
> 
> This is how it looks immediately after a fresh start and when switching from one setting menu to another (e.g.: **`Quality`** > **`Speed`**) or from **`Global`** > **`Objects`**.
> 
> image
> 
> image

When did this start?

**Comment by discip** [comment]
It started with this #2972.

And I'm on

```
DISTRIB_ID="ManjaroLinux"
DISTRIB_RELEASE="23.1.0"
DISTRIB_CODENAME="Vulcan"
DISTRIB_DESCRIPTION="Manjaro Linux"

Kernel: Linux 6.3.13-2-MANJARO
```

**Comment by Noisyfox** [comment]
> It started with this #2972.
> 
> And I'm on
> 
> ```
> DISTRIB_ID="ManjaroLinux"
> DISTRIB_RELEASE="23.1.0"
> DISTRIB_CODENAME="Vulcan"
> DISTRIB_DESCRIPTION="Manjaro Linux"
> 
> Kernel: Linux 6.3.13-2-MANJARO
> ```

Which desktop env? Plasm? Xfce or Gnome?

**Comment by Noisyfox** [comment]
> It started with this #2972.
> 
> And I'm on
> 
> ```
> DISTRIB_ID="ManjaroLinux"
> DISTRIB_RELEASE="23.1.0"
> DISTRIB_CODENAME="Vulcan"
> DISTRIB_DESCRIPTION="Manjaro Linux"
> 
> Kernel: Linux 6.3.13-2-MANJARO
> ```

Hmmmm I'm not able to find a download link to a specific version.

**Comment by discip** [comment]
Sorry, I missed your post.

Try this:
https://download.manjaro.org/gnome/23.0.4/manjaro-gnome-23.0.4-231015-linux65.iso

**Comment by Noisyfox** [comment]
> Sorry, I missed your post.
> 
> Try this: https://download.manjaro.org/gnome/23.0.4/manjaro-gnome-23.0.4-231015-linux65.iso

Yeah that's what I end up downloading.

**Comment by Noisyfox** [comment]
image
Hmmmm it works fine on my VM.

**Comment by Noisyfox** [comment]
> Oh sorry, 😅 I already got totally used to the fact that I'm always getting the following message:
> 
> ```
> use system SSL certificate: /etc/ssl/certs/ca-certificates.crt
> To manually specify the system certificate store, set the SSL_CERT_FILE environment variable to the correct CA and restart the
> application
> Do you want to continue?
> ```
> 
> Maybe this has to do something with it. 🤷🏻‍♂️
> 
> One more thing: I'm running my 3840 x 2160 4K screen at 2048 x 1152 both (16:9).
> 
> Also the splash is only a black square. 😊 But as I said, I got used to it, as all essential parts worked.

BTW are you using the one you built yourself or use the prebuilt binary from github?

**Comment by discip** [comment]
I'm using your builds form github.

**Comment by discip** [comment]
> BTW are you using the one you built yourself or use the prebuilt binary from github?

I'm using your builds form github.

**Comment by discip** [comment]
> I already got totally used to the fact that I'm always getting the following message:

For some reason I forgot to mention, that this message only pops up when I start OrcaSlicer.

> BTW are you using the one you built yourself or use the prebuilt binary from github?

I'm using your builds form github.

**Comment by Noisyfox** [comment]
> For some reason I forgot to mention, that this message only pops up when I start OrcaSlicer.

This is normal on Linux.



> I'm using your builds form github.

Have you tried the latest master build?

**Comment by Noisyfox** [comment]
> I'm running my 3840 x 2160 4K screen at 2048 x 1152 both (16:9).

How did you manage to do that?

**Comment by discip** [comment]
> How did you manage to do that?

image

**Comment by discip** [comment]
I have tried the latest master build and unfortunately the issue is still there.

**Comment by discip** [comment]
@Noisyfox
## It's fixed! 👍🏻

**Comment by discip** [comment]
@Noisyfox
Sorry to bother you again on this but the issue I reported here https://github.com/SoftFever/OrcaSlicer/pull/3044#issuecomment-1848767969 is back in [0f2a223](https://github.com/SoftFever/OrcaSlicer/actions/runs/7300261688).
Maybe even earlier.

thanks in advance

**Comment by discip** [comment]
After [Revert to WxWidgets 3.1.5 (#3249)](https://github.com/SoftFever/OrcaSlicer/actions/runs/7307508790) this is fixed for the most part.
Currently only resizing the sidebar triggers this malfunction.

**Comment by discip** [comment]
@Noisyfox
## First of all, I wish you a Happy New Year! 😀

Any idea what could be causing this yet?

**Comment by Noisyfox** [comment]
> @Noisyfox
> 
> ## First of all, I wish you a Happy New Year! 😀
> Any idea what could be causing this yet?

No idea... I still couldn't reproduce it.

**Comment by discip** [comment]
@Noisyfox
Could I help somehow by providing additional data?
 
<details>
  <summary>
    <b>setup</b>
  </summary>

OS | CPU | GPU | RAM | SSD
:-:|:-:|:-:|:-:|:-:
[Manjaro x64 (Gnome)](https://manjaro.org/download/) | Ryzen 9 7950X3D | XFX 7900&nbsp;XTX | G.Skill Flare X5 32 GB (EXPO&nbsp;I&nbsp;enabled) | Samsung 990 Pro 2&nbsp;TB

</details>

**Comment by discip** [comment]
@Noisyfox
Could I somehow help solve this issue by providing additional data?
 
<details>
  <summary>
    <b>setup</b>
  </summary>

OS | CPU | GPU | RAM | SSD
:-:|:-:|:-:|:-:|:-:
[Manjaro x64 (Gnome)](https://manjaro.org/download/) | Ryzen 9 7950X3D | XFX 7900&nbsp;XTX | G.Skill Flare X5 32 GB (EXPO&nbsp;I&nbsp;enabled) | Samsung 990 Pro 2&nbsp;TB

</details>

**Pull request merged**
