### PR TITLE
Rename tab_auxiliary_avtice.svg to tab_auxiliary_active.svg

### PR DESCRIPTION
**Pull request by discip**
Most likely this is a typo.

### CODE REVIEW

**Comment by kleinwareio** [comment]
I think you missed a line, as this file must be referenced by something...

https://github.com/SoftFever/OrcaSlicer/blob/922d4656052fe091872d737f09a656a70ee1cae3/src/slic3r/GUI/MainFrame.cpp#L1107

**Comment by discip** [comment]
@kleinwareio
### Thanks! 👍🏻

**Comment by discip** [comment]
Should be fixed by: #4368

**Review by SoftFever — APPROVED** [review]
Thanks

**Pull request merged**
