### PR TITLE
don't create HEADER_BLOCK_START if using BTT_TFT thumbnails

### LINKED ISSUE #5855: Model sketches have disappeared in Gcode since version 2.1( BIGTREETECH tft v3.1)
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.1

### Operating System (OS)

Windows

### OS Version

windows 11

### Additional system information

_No response_

### Printer

Artillery SX1

### How to reproduce

starting from version 2.1 the picture disappeared in the settings, I also can’t select a type

there were settings
2.0

2.1 

### Actual results

are added at the beginning of the line that does not work with Gcode

### Expected results

remove these lines at the very beginning

### Project file & Debug log uploads

no

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by discip**
For some time now, the generation of thumbnails when using the BTT_TFT format is not working because the first line of the G-code does not start with the generated thumbnail.

So I tried to bypass the generation of the **`HEADER_BLOCK_START`** using an if statement.

But unfortunately I am not skilled enough to do this myself because it does not compile.

Maybe someone can help me with this. 😊

@Noisyfox
@igiannakas
@cochcoder

# @igiannakas provided the code for this PR that made it work! 👍

This should fix #5855

Thanks in advance

### CODE REVIEW

**Comment by igiannakas** [comment]
Why not wrap the problem part with a condition like this:
if (format != GCodeThumbnailsFormat::BTT_TFT) {.....}

**Comment by discip** [comment]
> Why not wrap the problem part with a condition like this: if (format != GCodeThumbnailsFormat::BTT_TFT) {.....}

Yes, that is definitely the better approach, but unfortunately the main issue lies in the fact, that the expression **`format`** can not be interpreted.
Since I'm not a programmer, the terms I used may not be necessarily right. 😅

**Comment by discip** [comment]
@SoftFever
Do you mind solving this for me? 😊 Please.

**Comment by discip** [comment]
@vovodroid
I hope you don't mind me asking you for help.
Unfortunately I'm not able to figure it out myself. 😅

**Comment by discip** [comment]
I hope you don't mind if I ask you for help.
Unfortunately, I'm not able to figure it out myself. 😅

**Comment by discip** [comment]
@vovodroid
I hope you don't mind if I ask you for help.
Unfortunately, I'm not able to figure it out myself. 😅

**Comment by vovodroid** [comment]
I have no clue about this functionality))).

**Comment by igiannakas** [comment]
@discip ill take a look to check what the right format variable is. Most likely a m_config class variable somewhere. I’m not on my computer right now but will be today so I’ll check it out

**Comment by igiannakas** [comment]
OK I've taken a look at it. This is how you could check the thumbnail format:

```
    // Orca: Don't output Header block if BTT thumbnail is identified in the list
    // Get the thumbnails value as a string
    std::string thumbnails_value = print.config().option<ConfigOptionString>("thumbnails")->value;
    // search string for the BTT_TFT label
    bool has_BTT_thumbnail = (thumbnails_value.find("BTT_TFT") != std::string::npos);
    
    if(!has_BTT_thumbnail){
        [...existing logic that we dont want triggered when a BTT TFT thumbnail type is found...]
    }
```

**Comment by discip** [comment]
@igiannakas
# Thank you very much! 👍
Hopefully I've implemented your suggestions correctly. 😅

**Comment by igiannakas** [comment]
Give it a thorough test with and without a BTT image thumbnail - it looks like it should work but I haven’t tested the full logic, just the thumbnail parsing to identify the BTT part :)

**Comment by discip** [comment]
# @igiannakas
# You are brilliant! 😃👍
## Works just like expected!

**Comment by igiannakas** [comment]
Haha no worries :)

the code above is pretty simple but should give you some insight into how the configuration values are managed in orca ;) learning for the next one :)

**Comment by discip** [comment]
@SoftFever
Now this PR is ready for review.

**Comment by SoftFever** [comment]
Thank both of you!
Looks good

**Review by SoftFever — APPROVED** [review]

**Comment by Marcos2BR** [comment]
Anyone else having issues with thumbnail in OrcaSlicer_Windows_Installer_V2.3.0-dev.exe with BTT TFT ? (I have the tft-v3 3.5" with Marlin 2.1.3-b1)
BTT TFT35 V3

here the thumbnail only appears if I edit the gcode file and change “Line Feed” to “Carriage Return+Line Feed”
side by side
REPLACE LF by CR LF


my files
- cura_3D.gcode ;Generated with Cura 5.9.0 + BTT TFT Plugin
- OrcaV2.3.0-dev.gcode; Generated with Orca V2.3.0-dev
- OrcaV2.3.0-dev-REPLACE CRLF.gcode; Generated with Orca V2.3.0-dev edited with Notepad++

[thumbnails btt-tft.zip](https://github.com/user-attachments/files/18071945/thumbnails.btt-tft.zip)

I hope I was able to explain

**Comment by discip** [comment]
@Marcos2BR
Yeah I know, unfortunately I noticed this too.
But I is not related to the PR and I don't know where this regression stems from.

Originally @Ocraftyone solved this issue. Some change in the code seems to override what he implemented there.
See here: https://github.com/Ocraftyone/OrcaSlicer-Ocraftyone/blob/cb8866b4783506565dfd9b5c8b0414b62147a23b/src/libslic3r/GCode/Thumbnails.hpp#L65-L68

I'm not quite sure, but maybe @Noisyfox or @igiannakas are willing to help out. 😊

**Comment by Rsoft1976** [comment]
HI !!!

 I don't understand anything, it doesn't work for me in LF mode, there is no picture, but with CRLF there is a picture.

The question then is that for one it works this way, for another it works differently. What could this be connected with?

BTT TFT v3 3.5 screen

**Comment by Rsoft1976** [comment]
Yes, I forgot to mention that the pictures work in version 2.0 of the program, but starting with version 2.1 they stopped working. I couldn't figure it out for a long time. They gave me a link to this topic and I found out why, indicating above.

**Comment by discip** [comment]
@buzzhuzz
Sorry to bother you Sir,
but I have no idea whom to ask about this, maybe you could tackle this issue.
I tried to figure that out myself, but since I'm no programmer I couldn't do it. 😅

Basically the line endings of the generated thumbnail in the g-code need to be **`CR` `LF`** as pointed out here https://github.com/SoftFever/OrcaSlicer/issues/1894#issuecomment-1760505159, which worked previously but at some point parts of the code were reworked and as a side effect currently something overrides all line endings to be **`LF`**.
For reference please see here: https://github.com/SoftFever/OrcaSlicer/pull/7488#issuecomment-2530672850

This might also be helpful:
https://github.com/SoftFever/OrcaSlicer/issues/1894
https://github.com/SoftFever/OrcaSlicer/pull/2405

Thanks in advance
kind regards

**Comment by buzzhuzz** [comment]
@discip , I've tracked it down to the G-code post processor, [GCodeProcessor::run_post_process()](https://github.com/SoftFever/OrcaSlicer/blob/2ea2ab08de921cce8dd8400a647f6772a7121a7f/src/libslic3r/GCode/GCodeProcessor.cpp#L4372C6-L4372C40) function.

Seems that function is not careful (or not care at all) about line endings. With next patch applied, which essentially renders function useless, output gcode file has CR LF (0x0d 0x0a) line endings for BTT_LCD thumbnails.

Debug patch:
```
diff --git a/src/libslic3r/GCode/GCodeProcessor.cpp b/src/libslic3r/GCode/GCodeProcessor.cpp
index f1bae32eb..c32ee6857 100644
--- a/src/libslic3r/GCode/GCodeProcessor.cpp
+++ b/src/libslic3r/GCode/GCodeProcessor.cpp
@@ -5078,9 +5078,9 @@ void GCodeProcessor::run_post_process()
     const std::string result_filename = m_result.filename;
     export_lines.synchronize_moves(m_result);
 
-    if (rename_file(out_path, result_filename))
-        throw Slic3r::RuntimeError(std::string("Failed to rename the output G-code file from ") + out_path + " to " + result_filename + '\n' +
-            "Is " + out_path + " locked?" + '\n');
+    // if (rename_file(out_path, result_filename))
+    //     throw Slic3r::RuntimeError(std::string("Failed to rename the output G-code file from ") + out_path + " to " + result_filename + '\n' +
+    //         "Is " + out_path + " locked?" + '\n');
 }
 
 void GCodeProcessor::store_move_vertex(EMoveType type, EMovePathType path_type)
```

Unfortunately, I cant wrap my head around all the stuff going on there. But my gut feeling is that problem is around lines 5013-5059: it looks like line ends ignored on getting the input line, with some magic happening within `update_lines_ends_and_out_file_pos()` function (which is called by `ExportLines::write()`)

**Comment by discip** [comment]
@buzzhuzz
Thank you very much for your effort!

@Noisyfox
I know you're very busy fixing all these bugs, which I highly appreciate!
Could you please take a look at this issue if you happen to have a free minute? 😊

thanks in advance
kind regards

**Comment by discip** [comment]
@Rsoft1976
Thanks to @buzzhuzz it's back to its previous working state. 🎉

**Pull request merged**
