### PR TITLE
05-24 filenaming and some fixes

### PR DESCRIPTION
**Pull request by Bai825**
# Description

1. Removed the Generic in filament naming.
2. Add the "@FF" format in filament naming.
3. Updated the gcode start command： E-0.2. 
4. Fix the filament type for FusRock S-Multi and FusRock S-PAHT.

# Screenshots/Recordings/Graphs
See changed files in the commit.

## Tests
Worked on local OrcaSlicer portable package.

@SoftFever For your review.

### CODE REVIEW

**Comment by SoftFever** [comment]
Can you check and fix the errors reported by the "Check profiles"?

**Comment by Bai825** [comment]
> Can you check and fix the errors reported by the "Check profiles"?

Yes, this error occurred before. 

@RikshaDriver  I seemed not be able to locate the issues from the prompt. I also fixed the naming for AD3 machine profile. Can you help me check on the below prompt and is there any other method I can debug locally before making a PR?

**Comment by Bai825** [comment]
> Can you check and fix the errors reported by the "Check profiles"?

Yes, this error occurred before.

@RikshaDriver I seemed not be able to locate the issues from the prompt. I also fixed the naming for AD3 machine profile. Can you help me check on the below prompt and is there any other method I can debug locally before making a PR?
check_profile1

**Comment by RikshaDriver** [comment]
The test is referencing the old "Generic" filaments.

@SoftFever does the check script require manual updating if filaments have been removed/renamed?

**Comment by SoftFever** [comment]
It is not suppose to rename/delete existing profiles as it will invalidate users' custom profile based them.

**Comment by RikshaDriver** [comment]
> It is not suppose to rename/delete existing profiles as it will invalidate users' custom profile based them.

@SoftFever @Bai825 it may be worthwhile looking at developing a "profile migration" tool if filament/nozzle profile renaming is required.

**Comment by Bai825** [comment]
> > It is not suppose to rename/delete existing profiles as it will invalidate users' custom profile based them.
> 
> @SoftFever @Bai825 it may be worthwhile looking at developing a "profile migration" tool if filament/nozzle profile renaming is required.

Agree, that will help with situations when one wants to make things cleaner if there are too many profiles in different naming rules.

**Pull request closed without merging**
