### PR TITLE
Improved FLSUN S1 and T1 configurations

### PR DESCRIPTION
**Pull request by Guilouz**
- Improved buildplates and textures for S1 and T1:

  Capture d’écran 2024-08-05 à 10 59 35

- Improved printers settings.

- Added more filaments.

- Integrated the management of bed zones according to the location of the model for S1:

### CODE REVIEW

**Comment by Guilouz** [comment]
@SoftFever Can you check why checks return this:

```
Error: 8-05 09:05:28.897875] [0x00007fa858b0e740] [error]   can not find parent for config /home/runner/work/OrcaSlicer/OrcaSlicer/resources/profiles/user/default/process/FLSun_0.20mm PLA_HS_S1_FLSUN @FLSUN_orca_test.json!
Error: 8-05 09:05:29.141807] [0x00007fa858b0e740] [error]   can not find parent for config /home/runner/work/OrcaSlicer/OrcaSlicer/resources/profiles/user/default/process/FLSun_0.20mm PLA_HS_T1_FLSUN @FLSUN_orca_test.json!
Error: 8-05 09:05:29.443539] [0x00007fa858b0e740] [error]   can not find parent for config /home/runner/work/OrcaSlicer/OrcaSlicer/resources/profiles/user/default/filament/FLSun_FLSun Generic PLA-HS-T1_orca_test.json!
Error: 8-05 09:05:29.493201] [0x00007fa858b0e740] [error]   can not find parent for config /home/runner/work/OrcaSlicer/OrcaSlicer/resources/profiles/user/default/filament/FLSun_FLSun Generic PLA-HS-S1_orca_test.json!
Validation failed
Error: Process completed with exit code 1.
```

These files no longer exist in the new profile configuration

**Comment by SoftFever** [comment]
It is because it always compares with main branch. 
Any good reason why you want to delete these files?

**Comment by Guilouz** [comment]
> It is because it always compares with main branch. Any good reason why you want to delete these files?

Yes profiles was reorganized with new ones.

**Comment by Guilouz** [comment]
@SoftFever Can you merge it ?

**Review by SoftFever — APPROVED** [review]
Looks good
Thanks

**Pull request merged**
