### PR TITLE
Feature/measure tool port - NOT READY

### PR DESCRIPTION
**Pull request by SoftFever**
It's far from ready.
For discussion only.

Measure tool works, but other tools are broken.
@Noisyfox

### CODE REVIEW

**Comment by Eldenroot** [comment]
Wau! Good job, looking for a working version

**Comment by Ocraftyone** [comment]
@SoftFever wanted to pass along that I am currently not able to get it to build. Seems there are some conflicts with the array constructor for the ColorRGBA class. For some reason it seams that when passing one of the const colors (the error is specifically pointing to the color initis in the GLGizmoBase::,Grabber struct) it is trying to use the array constructor rather than the (const ColorRGBA& other) constructor. LMK if there is any more info/help I can provide.

**Comment by Noisyfox** [comment]
> @SoftFever wanted to pass along that I am currently not able to get it to build. Seems there are some conflicts with the array constructor for the ColorRGBA class. For some reason it seams that when passing one of the const colors (the error is specifically pointing to the color initis in the GLGizmoBase::,Grabber struct) it is trying to use the array constructor rather than the (const ColorRGBA& other) constructor. LMK if there is any more info/help I can provide.

I got it fixed on my branch: https://github.com/Noisyfox/OrcaSlicer/commit/048e4401f9f86673816da4acd0a592a1497f5d75

**Comment by SoftFever** [comment]
> @SoftFever wanted to pass along that I am currently not able to get it to build. Seems there are some conflicts with the array constructor for the ColorRGBA class. For some reason it seams that when passing one of the const colors (the error is specifically pointing to the color initis in the GLGizmoBase::,Grabber struct) it is trying to use the array constructor rather than the (const ColorRGBA& other) constructor. LMK if there is any more info/help I can provide.

Ah, a new ColorRGBA class has been introduced.
You can convert the array to ColorRGBA. I believe I've made the necessary changes in most places. If you search through the codebase, you should find how to address them for this error.
I haven't been working on Windows lately, so I might have overlooked some adjustments, especially if these errors are unique to Windows.

**Comment by SoftFever** [comment]
As for the remaining work, currently a lot of gizmo tools are broken as them need to migrate to the new grabber/picking approach. 
The build is working expect most gizmo tools.
Though I expect many bugs and quirks need to be addressed.

**Comment by SoftFever** [comment]
Please ref to #2603

**Pull request closed without merging**
