### PR TITLE
Use namespaces to link against libcereal >= 1.3.1

### PR DESCRIPTION
**Pull request by ovlach**
https://github.com/prusa3d/PrusaSlicer/commit/0ffcfd8393457fd035576436752267c9a1e6bbcc

### CODE REVIEW

**Comment by SoftFever** [comment]
@ovlach
Can you describle what problem is the PR trying to solve?

**Comment by ovlach** [comment]
On linux systems (for example NixOS, Gentoo...) which have libcereal >= 1.3.1 causes linking to libcereal error
```
[100%] Linking CXX executable orca-slicer
/nix/store/r5x7gyddzwml0h9g7gg7r6zlwpdzc10a-binutils-2.40/bin/ld: cannot find -lcereal: No such file or directory
collect2: error: ld returned 1 exit status
```
See https://bugs.gentoo.org/834005 and https://github.com/NixOS/nixpkgs/issues/239390#issuecomment-1646751521

**Comment by SoftFever** [comment]
> On linux systems (for example NixOS, Gentoo...) which have libcereal >= 1.3.1 causes linking to libcereal error
> 
> ```
> [100%] Linking CXX executable orca-slicer
> /nix/store/r5x7gyddzwml0h9g7gg7r6zlwpdzc10a-binutils-2.40/bin/ld: cannot find -lcereal: No such file or directory
> collect2: error: ld returned 1 exit status
> ```
> 
> See https://bugs.gentoo.org/834005 and [NixOS/nixpkgs#239390 (comment)](https://github.com/NixOS/nixpkgs/issues/239390#issuecomment-1646751521)

Thanks for the explaination. Make sense now :)
Will merge it once the CI/CD passed

**Review by SoftFever — APPROVED** [review]

**Comment by SoftFever** [comment]
Merged.
Appreciate your contribution 👍

**Pull request merged**
