### PR TITLE
Show used filament length and weight per line type

### LINKED ISSUE #2252: Calculation of filament use for every type of printing part
**Is your feature request related to a problem? Please describe.**
PS displays detailed info for used filament /weight, length, nicely visualized % of usage/

image

**Which printers will be beneficial to this feature**
All

**Describe the solution you'd like**
Add these info (including first layer time) into Orca Slicer

image

**Describe alternatives you've considered**
---

**Additional context**
----

### PR DESCRIPTION
**Pull request by Noisyfox**
image

Fixes #2252

### CODE REVIEW

**Comment by Eldenroot** [comment]
Nice!

First time layer time - is it possible?

I like visualization from PS - you can see it really fast without analysing the numbers... I know, not a lot space in gui but anyway ;)

Great work!

**Comment by discip** [comment]
## Nice!
Maybe you could put a PS-like bar-graph underneath the percentage value. 😊

**Comment by Noisyfox** [comment]
> Maybe you could put a PS-like bar-graph underneath the percentage value.

I personally don't think that's necessary. Let's leave that to another ticket maybe.

**Comment by discip** [comment]
Alright, no intention of pushing, just thought about saving space compared to the PS approach. 😀

**Comment by Eldenroot** [comment]
> > Maybe you could put a PS-like bar-graph underneath the percentage value.
> 
> I personally don't think that's necessary. Let's leave that to another ticket maybe.

I understand. Just my reply above - easier for comparison :)

**Review by SoftFever — APPROVED** [review]
Looks good

**Comment by SoftFever** [comment]
Looks safe changes.
Let's include it in the alpha release

**Pull request merged**
