### PR TITLE
Add Ellis' pattern method for pressure advance calibration

### LINKED ISSUE #640: Pressure Advance Pattern Method instead of line method
**Is your feature request related to a problem? Please describe.**

I've been reading the Ellis Print Tuning Guide and it seems that the line method used to calibrate the pressure advance is no longer a good method. It seems that it can cause inconsistencies.

**Describe the solution you'd like**

The new Pattern Method is far superior to dial the correct PA settings. Described here: [Pattern Method](https://ellis3dp.com/Print-Tuning-Guide/articles/pressure_linear_advance/pattern_method.html)
 It would be great that the Pattern Method could be implemented in the Calibration menu of Orca Slicer.

**Describe alternatives you've considered**
Generate the gcode using the Ellis tool here: [Pressure Advance Tool](https://ellis3dp.com/Pressure_Linear_Advance_Tool/)

### LINKED ISSUE #794: New PA/LA Tool
It would be awesome to see the newer Ellis3DP PA/LA tool incorporated into your calibration feature set. I really like this one and find I have great results with it. I have linked it below. Keep up the great work!

https://ellis3dp.com/Print-Tuning-Guide/articles/pressure_linear_advance/pattern_method.html

### PR DESCRIPTION
**Pull request by thewildmage**
~**WIP note:** I'm feeling good about where the code for this is at, ready to see how it does with the build checks, but I also want to do some actual print tests before moving it out of WIP status. Will update once those are done.~
Done! Bugs and optimization opportunities identified and incorporated.

---

Closes #640. Closes #794.
Also heads up to #373 and #761.

I was going to pull the instructions into `doc/Calibration.md`, but ran into a licensing issue with that. The [pattern generator](https://github.com/AndrewEllis93/Pressure_Linear_Advance_Tool) itself is licensed GPL-3.0, but the instructions are part of [Ellis' guide](https://github.com/AndrewEllis93/Print-Tuning-Guide), which doesn't have a license. So I linked out to the instructions instead. 

Tested via prints on a Frankensteined Monoprice Select Mini v1 (now running Klipper) and a Bambu X1C.

The pressure advance line method test was modified only as much as needed to share some functions with the pattern test (like number drawing).

### CODE REVIEW

**Comment by jeremytodd1** [comment]
I'm excited that this may finally be getting added. Thank you for the work you've put in on this. I've been watching the other issues for this for a while in hopes that I see some progress but they've stood still for a while now.

**Comment by SoftFever** [comment]
@thewildmage 
Very cool. thanks.
I'm testing the VS2022 CICD, once it's done, the CICD will kick off for this PR.

**Comment by thewildmage** [comment]
Running test prints turned up a few bugs and opportunities for optimization. These are now incorporated and I think this is PR is ready for review.

---

> I'm testing the VS2022 CICD, once it's done, the CICD will kick off for this PR.

@SoftFever, sounds good, thanks!

**Comment by thewildmage** [comment]
Almost forgot to include some photos from the test prints!

IMG_2260
IMG_2261

**Comment by FillPavS** [comment]
I found an error. When I create a temperature test, a PA test is added to it
image

Windows 10

**Comment by thewildmage** [comment]
> I've found a bug. When I create a temperature test, a PA test is added to it

Weird! Thanks for catching that, @FillPavS!

I don't have a Windows machine and am unable to reproduce this bug on my MacBook, but I've taken a shot at adjusting the bit of code I think may be the cause. Can you try again now please?

**Comment by SoftFever** [comment]
Hi @thewildmage 
Thanks for the PR, looks very promising!

I noticed some issues when trying it. Could you take a look?
1. The model is overlapping with the pattern.  It would be better to skip slicing the model like the PA line IMO.
image
2. The pattern is not centered and is generating outside of the bed for some printers.:
image

[ellis_pattern_out_of_bed_issue.zip](https://github.com/SoftFever/OrcaSlicer/files/12082987/ellis_pattern_out_of_bed_issue.zip)

**Comment by FillPavS** [comment]
> > I've found a bug. When I create a temperature test, a PA test is added to it
> 
> Weird! Thanks for catching that, @FillPavS!
> 
> I don't have a Windows machine and am unable to reproduce this bug on my MacBook, but I've taken a shot at adjusting the bit of code I think may be the cause. Can you try again now please?

I found out that the error appears after some actions. Here's what you need to do to reproduce-
1. Create a PA test and click the slice button.
2. Without closing the program, create a new project and do not save anything.
3. Create any test - temperature, flow, retract and others.

Now the PA test will appear with them until you restart the program.

**Comment by thewildmage** [comment]
> I found out that the error appears after some actions. Here's what you need to do to reproduce-
> 
>     1. Create a PA test and click the slice button.
> 
>     2. Without closing the program, create a new project and do not save anything.
> 
>     3. Create any test - temperature, flow, retract and others.
> 
> 
> Now the PA test will appear with them until you restart the program.

This is super helpful info, thanks @FillPavS! I added a commit that should fix this.

**Comment by thewildmage** [comment]
Thanks for taking a look at this PR, @SoftFever!

As for the issues you called out...

> 1. The model is overlapping with the pattern.  It would be better to skip slicing the model like the PA line IMO.

If we skip slicing the model, then it will also skip slicing the pattern. That's because the pattern is injected via `Model.plates_custom_gcodes`; the pattern's custom G-code is _part_ of the model. I chose this approach hoping to leverage as much of the preexisting pipeline as possible, so that any checks, safeties, and bug fixes that apply to adding in custom G-code will also automatically apply to the PA pattern G-code.

That said, I do recognize that the model overlapping the pattern is an issue, so I added in a gap to keep them apart from each other.

> 2. The pattern is not centered and is generating outside of the bed for some printers.

The pattern is actually movable! If you move the model around in the Prepare tab, the pattern will move with it.

I can see how it's annoying to always have to move the pattern around though, so I added another new commit that should start the pattern out centered.

**Comment by SoftFever** [comment]
> Thanks for taking a look at this PR, @SoftFever!
> 
> As for the issues you called out...
> 
> > 1. The model is overlapping with the pattern.  It would be better to skip slicing the model like the PA line IMO.
> 
> If we skip slicing the model, then it will also skip slicing the pattern. That's because the pattern is injected via `Model.plates_custom_gcodes`; the pattern's custom G-code is _part_ of the model. I chose this approach hoping to leverage as much of the preexisting pipeline as possible, so that any checks, safeties, and bug fixes that apply to adding in custom G-code will also automatically apply to the PA pattern G-code.
> 
> That said, I do recognize that the model overlapping the pattern is an issue, so I added in a gap to keep them apart from each other.
> 
> > 2. The pattern is not centered and is generating outside of the bed for some printers.
> 
> The pattern is actually movable! If you move the model around in the Prepare tab, the pattern will move with it.
> 
> I can see how it's annoying to always have to move the pattern around though, so I added another new commit that should start the pattern out centered.

Great!
I will do some tests this weekend.

**Comment by ThoughtfulDev** [comment]
I was curious and compiled this version and tried it with 3 different filaments on my X1C.
Works flawlessly without any issues

**Review by SoftFever — APPROVED** [review]
Fantastic!

**Comment by SoftFever** [comment]
@thewildmage 
I just tested it.
Works like a charm :)

**Comment by SoftFever** [comment]
merged

**Comment by SoftFever** [comment]
Oops, I merged a bit too fast.
I can repro the isuse that @FillPavS reported.

@thewildmage could you take a look? It's probably because we didn't clear the calib flag?

**Comment by thewildmage** [comment]
> Oops, I merged a bit too fast. I can repro the isuse that @FillPavS reported.
> 
> @thewildmage could you take a look? It's probably because we didn't clear the calib flag?

@SoftFever, looking into this now. I suspect I missed a spot in `Model.cpp`'s model copying. I'll dig into it and open a new PR for the fix.

**Comment by magic-happenz** [comment]
I am on version 1.6.3 but I am not seeing the method yet as shown.
image

**Comment by jeremytodd1** [comment]
@magic-happenz 

1.6.3 came out late May. The PA pattern calibration test wont be in until 1.6.4. It looks like 1.6.4-beta isn't too far off, according to the "actions' tab.

If you want to use it sooner, you can also download the latest nightly version in the "main" branch and it will have the pattern test included.

**Comment by iitsalex** [comment]
Haven't read through the code much at all, but it seems that this is using the default acceleration as a parameter instead of the outside wall accel?

**Comment by btlucas** [comment]
Hey guys, I'm having an issue when trying to use this method in my Creality K1. The small square piece is printed like a blob and it ruins everything. Here are some photos of what's happening. Also, when the blob is being spit out the printer does a really bad noise because the extruder is being forced to it's maximum. 

image
image

Screenshot from orcaslicer and 3mf (zipped because github doesn't accept 3mf format) file:

image

[Pressure Advance Test.zip](https://github.com/SoftFever/OrcaSlicer/files/12338453/Pressure.Advance.Test.zip)

**Pull request merged**
