### PR TITLE
Flatpak build

### PR DESCRIPTION
**Pull request by powpingdone**
This is here so that I can link #3949 and #1670, along with testing the CI. THIS IS NOT FINISHED, AT ALL.

(imho it's really hard to find external work to show what's going on in an issue so I'm linking it here)

### CODE REVIEW

**Comment by anarsoul** [comment]
@powpingdone it looks like github CI VM doesn't get enough free disk space to build a flatpak. Maybe it's time to ask help from flatpak experts?

**Comment by powpingdone** [comment]
I'm trying one last thing before that.

**Comment by Ocraftyone** [comment]
@powpingdone I set up the current CI that is being used and I want to see if I can help with fixing the flatpak building. I personally don't have much experience with building flatpaks, but here it goes :). It seems as when packing the flatpak, you are attempting to build all of the dependencies and the application. Are you not able to simply package the already compiled program from the ubuntu CI? As I understand it, that is how the AppImage is created, but I also understand that flatpak uses containerization and could be different.

**Comment by powpingdone** [comment]
@Ocraftyone the reason for this is debugging symbols and the flatpak's runtime bundled deps. I might be able to just build an appimage in distribute that, but it would be a waste of space. Currently, the amount of debugging symbols, even compressed, is the issue in CI because I am running out of space.

**Comment by Ocraftyone** [comment]
@powpingdone is there a reason for the debug symbols? I do remember always running out of space if I tried to do them on actions and I don't think there is a way around it.

**Comment by powpingdone** [comment]
@Ocraftyone Distributing a flatpak (or appimage) with debugging symbols would allow for, well, better debugging. Like for, say, a deep segfault, a backtrace and execution context would be immensely helpful for pinpointing how a bug could happen. `flatpak-builder` automatically strips and distributes symbols as a separate "package" that can be installed later for helping debugging issues.

**Comment by powpingdone** [comment]
@SoftFever Could you weigh in on debugging symbols here?

**Comment by cochcoder** [comment]
About how much space do you need to have the build successfully work? How much space should be available, so that we don't run into the issue of no available space in the near future?

**Comment by SoftFever** [comment]
It will be better to pack these debug symbols in a separate package. Like we did for the windows PDB files

**Comment by powpingdone** [comment]
@SoftFever that would automatically be the case here, as that's part of distributing the flatpak. The problem is that the CI is running out of space during building. 

@cochcoder unknown. I haven't actually fully measured it but if it's breaking past github's limit of 15gb then there's your (not accurate) minimum

**Comment by cochcoder** [comment]
> @cochcoder unknown. I haven't actually fully measured it but if it's breaking past github's limit of 15gb then there's your (not accurate) minimum

I've never seen a Flatpak for applications like this get so large! Considering that all the current builds take up ~500 MB. Is this to do with poor optimization or am I missing something?

**Comment by powpingdone** [comment]
@Ocraftyone no
```
❯ du -hd 1 .
1007M	./.git
8.0K	./.devcontainer
68K	./.github
28K	./.idea
3.8M	./SoftFever_doc
192K	./cmake
1.1G	./deps
7.4M	./doc
176K	./lib
8.1M	./localization
140M	./resources
164K	./sandboxes
4.0K	./scripts
49M	./src
240K	./t
3.3M	./tests
16K	./tools
480K	./xs
1.4G	./flatpak
20K	./.flatpak-builder
12G	./build
16G	.
```

**Comment by powpingdone** [comment]
It could be the amount of static linking that is done by default.

**Comment by powpingdone** [comment]
Oh, you're talking about flatpak size. Well, no, it's a normal size.
```
$ flatpak info io.github.softfever.OrcaSlicer

OrcaSlicer - Get even more perfect prints!

          ID: io.github.softfever.OrcaSlicer
         Ref: app/io.github.softfever.OrcaSlicer/x86_64/master
        Arch: x86_64
      Branch: master
     Version: 2.0.0-951fc8e
     License: AGPL-3.0-only
      Origin: orcaslicer-origin
  Collection: 
Installation: user
   Installed: 470.5 MB
     Runtime: org.gnome.Platform/x86_64/45
         Sdk: org.gnome.Sdk/x86_64/45

      Commit: 2d373df0923172e6cba45ffc23c29bb8dbdd6471a8acb90dc4c772d97ac4f282
      Parent: 0af880ef40c80f4f840f24251b5af468d297ed2591b7bbd7c4f220ea958a25fc
     Subject: Export io.github.softfever.OrcaSlicer
        Date: 2024-03-15 03:31:05 +0000
```

**Comment by ZeFoxii** [comment]
Would it be possible to exclude debug features on parts of orca you know currently work well/have less issues. Just to get the flatpak up then add them in as time goes on? That way people have a flatpak and you can slowly work more debug features in later on with more help from other developers?

**Comment by powpingdone** [comment]
@SoftFever debug symbols or no?

**Comment by SoftFever** [comment]
> @SoftFever debug symbols or no?

I prefer we don't include debug symbols in the flatpak file as 99.9999% percent people don't need this ;)

**Comment by powpingdone** [comment]
In the future, I would like to distribute debug symbols as (again) they're part of a separate package that is part of the build process but is not installed normally, just avail on the remote repository.

**Comment by campmeharder** [comment]
Hi there thanks for working on getting this flatpaked, any update on how its going?

**Comment by ZeFoxii** [comment]
So have you finished cleanup and review? I'm personally "very" excited for this feature.

**Comment by etrigan63** [comment]
Someone correct me if I am wrong, but I don't think flatpak applies to macos.

**Comment by ellisgl** [comment]
> Someone correct me if I am wrong, but I don't think flatpak applies to macos or windows.

As far as I know, FlatPak is only for Linux.

**Comment by etrigan63** [comment]
> > Someone correct me if I am wrong, but I don't think flatpak applies to macos or windows.
> 
> As far as I know, FlatPak is only for Linux.

I was curious to this because the failing checks in the pipeline below are related to macos and I was wondering why they are there at all.

**Comment by powpingdone** [comment]
@SoftFever could you please approve the workflow so I can continue testing?

**Comment by SoftFever** [comment]
> @SoftFever could you please approve the workflow so I can continue testing?

It should build automatically now. I temporarily disabled CI/CD this morning as I was fixing a build error. Let me know if it still has issues.

**Comment by powpingdone** [comment]
Alright, @SoftFever . It's ready. Took way too damn long but it's ready for review and merging. From here, because of the unique setup, after this is merged (and begins building bundles) I'll get in contact with the Flathub admins so that automated upload keys can be given. You'll be given a secret API key which will be used in the CI.

**Comment by buzzhuzz** [comment]
Looking at the changes within this PR I'd suggest to split it into several phases:
1. Compilation fixes: all the cpp and hpp files within src directory
2. *.cmake changes within deps
3. root CMakeLists.txt
4. actual Flatpak support

That'll make review of the changes and validation easier

**Comment by SoftFever** [comment]
@powpingdone 
Thank you so much for your incredible work.
I will start reviewing the changes!

**Comment by cochcoder** [comment]
Should the included images be updated for the redesign that yw4z made?

**Comment by powpingdone** [comment]
@cochcoder What updated design? The cube navigator?

**Comment by cochcoder** [comment]
> @cochcoder What updated design? The cube navigator?

The #4368 was a redesign of all of the icons in Orca Slicer while #5239 changed the color scheme in some areas (G-Code viewer, Bed plate, etc.).

**Comment by powpingdone** [comment]
Ah, I had not noticed. Oops. Anyways, up to Softfever.

**Comment by Alaric323** [comment]
I'm testing out the artifact generated above.  Can slice and send to a Bambu printer without issue!  A few issues exist that are probably unrelated to the Flatpak itself, such as being unable to preview an X1 camera feed due to the "system player missing", which I've seen as a general Linux issue.

**Comment by rehashedsalt** [comment]
> such as being unable to preview an X1 camera feed due to the "system player missing", which I've seen as a general Linux issue.

Just grabbed the flatpak myself to test and was able to replicate. My X1C camera works under Bambu Studio's flatpak but not under this one. Using x1plus 1.1 in LAN mode.

image

Everything else seems to work fine though. There a way for me to provide some helpful logs? STDOUT and the log dir in `config/OrcaSlicer/log` didn't have anything useful.

I wouldn't consider this a blocker for merging though. Could always iron out platform-specific bugs later.

**Comment by SoftFever** [comment]
@powpingdone 
I noticed you have modified the CMake files, especially for dependencies. Are these changes absolutely needed for the Flatpak? If they are not, can we revert them (and other unrelated CMake changes in the source as well)? It’s better to focus on one feature in one PR so it will be easier to troubleshoot in the future.

**Comment by powpingdone** [comment]
They are required to make the Flatpak (CI) work, mostly because of size constraints. Just reverted a few lines that were unnecessary.

**Comment by powpingdone** [comment]
@SoftFever The CMake changes can be put into a list:
* Boost dep resolution refactoring, because the previous method was causing resolution issues during building on CI.
* Compressing debug info in GCC, for the future.
* Unbinding `$DESTDIR` from `<dir>/usr/local`, because it's installing into `/app`. The path stays the same on non-flatpak builds (it appends `/usr/local`), but is changed for Flatpak builds. This is mostly the reason why I touched all the deps, because it effects *everything*.
* Removing files build files after the build. Github CI has a limit of about 15GB of disk space (I don't remember the exact amount), and was making builds just outright fail, so I put that hack in to reduce disk usage. 
* Using the bundled flatpak image deps, which comes provided by flathub for all applications. CI forced my hand.  While it does bundle a newer version of OpenSSL that is incompatible with 1.1, this is easily rectified by checking the version.
* Patching TBB to not build with LTO. I don't have an explanation for this one, but the Flatpak doesn't build without it. 
* Building wxwidgets in the flatpak manifest (not technically a cmake issue). CI forced my hand again, so I chucked it here so that it could be adequately cleaned up.
* Force linking slic3r GUI to webkit2gtk and X11, because somehow that linker flag got dropped.

**Comment by powpingdone** [comment]
@Alaric323 @rehashedsalt unfortunately I don't have any bambu lab printer to test with so once this is merged, I'll need some help debugging this particular dep issue

**Review by SoftFever — APPROVED** [review]
Looks good.

Thank you for you hard work! @powpingdone

**Comment by rehashedsalt** [comment]
Seriously awesome job! I spun off an issue for the X1 camera thing, but that was the only problem I encountered with the flatpak, and it surely won't stop me from switching to Orca as my daily driver from here on!

**Comment by Alaric323** [comment]
Yeah, definitely a huge improvement towards usability on Linux.  V2.0 appimage didn't work on my OpenSUSE install, but the flatpak works wonderfully aside from slight visual bugs and the x1 camera thing.

Thank you so much for your work everyone!  Next stop, Flathub? 😀

**Comment by etrigan63** [comment]
Where is the flatpakref so I can give this a try on NixOS and Bluefin?

**Comment by powpingdone** [comment]
@etrigan63 the bundle should be in the ci artifacts, but iirc there isn't a ref

**Comment by etrigan63** [comment]
> @etrigan63 the bundle should be in the ci artifacts, but iirc there isn't a ref

Guess I wait for flathub. Hopefully soon.

**Comment by cochcoder** [comment]
I just looked at the latest build and it seems that the flatpak is named orcaslicer-x86_64. Shouldn't the artifact be named something along the lines of OrcaSlicer_Flatpak_[version here]?

**Comment by hgelpke** [comment]
Can somebody give a rundown on how to build this? Tried on Fedora 40 and failed but it is also the first time I'm trying this.

**Comment by bleomycin** [comment]
Are there any updates on this? The Appimage has been unusable on bleeding edge distro's such as fedora and opensuse tumbleweed when used with the latest nvidia drivers.

**Comment by JaneSmith** [comment]
When can we expect this to be added to Flathub? It would be great to have this app be available on Linux with a modern Flatpak. Cura, PrusaSlicer, and Bambu Studio are all on Flathub.

**Comment by nokiomanz** [comment]
When will this be added to Flathub?

**Comment by TheOverpassArsonist** [comment]
In the meantime before an official flathub release, is there any way to install the flatpak manually? I'm on arch and the appimage nearly works, but there is no buildplate rendered at all so it's unusable. (native doesn't work either unfortunately, arch+nvidia ain't a good combination) I'm not sure what all goes into getting a flatpak officially pushed to flathub, but in the meantime I'd be perfectly fine having a manual working installation going. (currently I'm relying on a seperate windows laptop which, given it's windows, isn't exactly a fun experience) I tried to find some method of doing so but as a github noob I can't even figure out how to view (letalone download) the artifacts.

**Comment by anarsoul** [comment]
> In the meantime before an official flathub release, is there any way to install the flatpak manually? I'm on arch and the appimage nearly works, but there is no buildplate rendered at all so it's unusable. (native doesn't work either unfortunately, arch+nvidia ain't a good combination) I'm not sure what all goes into getting a flatpak officially pushed to flathub, but in the meantime I'd be perfectly fine having a manual working installation going. (currently I'm relying on a seperate windows laptop which, given it's windows, isn't exactly a fun experience) I tried to find some method of doing so but as a github noob I can't even figure out how to view (letalone download) the artifacts.

You can grab it either from here if you want the latest release: https://github.com/anarsoul/io.github.softfever.OrcaSlicer/releases/tag/v2.2.0-2

Or from https://github.com/SoftFever/OrcaSlicer/actions/runs/12070959597/artifacts/2250759692 if you prefer a nightly build

**Comment by TheOverpassArsonist** [comment]
> > In the meantime before an official flathub release, is there any way to install the flatpak manually? I'm on arch and the appimage nearly works, but there is no buildplate rendered at all so it's unusable. (native doesn't work either unfortunately, arch+nvidia ain't a good combination) I'm not sure what all goes into getting a flatpak officially pushed to flathub, but in the meantime I'd be perfectly fine having a manual working installation going. (currently I'm relying on a seperate windows laptop which, given it's windows, isn't exactly a fun experience) I tried to find some method of doing so but as a github noob I can't even figure out how to view (letalone download) the artifacts.
> 
> You can grab it either from here if you want the latest release: https://github.com/anarsoul/io.github.softfever.OrcaSlicer/releases/tag/v2.2.0-2
> 
> Or from https://github.com/SoftFever/OrcaSlicer/actions/runs/12070959597/artifacts/2250759692 if you prefer a nightly build

I downloaded and installed it and it seems to work fine, but there is still no buildplate rendering when I run it. Is this not a bug but some weird linux-specific configuration thing? I've had a few graphics issues in the past, but generally speaking using universal packaging formats like flatpak has solved them before because it pins down the dependencies exactly. The entire program seems to work, all the menus are fine, it's responsive, all the buttons work, etc. but the buildplate still isn't rendering so am I just missing something?

**Comment by ItsJupiter21** [comment]
@bleomycin, @Alaric323 
for opensuse, (OPI)[https://github.com/openSUSE/opi] has an OrcaSlicer plugin, just run
`sudo zypper install opi
opi orcaslicer`

**Comment by Kaympe20** [comment]
@powpingdone @anarsoul Is there any ETA for when a flatpak build will be released on flathub?

**Comment by anarsoul** [comment]
> @powpingdone @anarsoul Is there any ETA for when a flatpak build will be released on flathub?

No

**Comment by PervyJoker** [comment]
it crashes for everytime i Add my Creality K1 Max to work on LAN. i tried the nightly build and the v2.2.0-2. i run it on Arch

**Comment by Anthony-Bec** [comment]
following

**Comment by grooby** [comment]
following

**Comment by LuccoJ** [comment]
@Anthony-Bec @grooby can you folks possibly hit the Subscribe button and not actually write comments that reach everybody's email just to announce that you're following this?

**Pull request merged**
