### PR TITLE
[Feature] Introduced experimental option to fully disable solid infill against walls when ensure vertical thickness is turned off

### LINKED ISSUE #1887: Internal Solid Infill affected by Top & Bottom Shell Layers
**Describe the bug**
I was trying to get rid of the _purple_ `Internal Solid Infill` and noticed it being affected by the `Top` & `Bottom Shell Layers`:
IMG
IMG
Obviously, with its generation being tied to the Top & Bottom Shell Layers one cannot edit them out like that without it conflicting with the actual Top & Bottom Shell Layers elsewhere needed on the Model 😑

**To Reproduce**
Load a Model with a fairly steep overhang value at or nearing 45° and have it Sliced with like 3 `Wall Loops` and 5 `Top` & `Bottom Shell Layers`.

**Expected behavior**
For a way to disable the generation of the `Internal Solid Infill` on `Overhangs` causing more unnecessary heat to get pumped into the local area.

**Screenshots**
See above

**Printer model**
[Voron V2.4 350](https://imgur.com/a/peDnYxr)

**Desktop (please complete the following information):**
 - OS: Windows 11 Professional
 - Version: 22H2

### LINKED ISSUE #3016: Ensure vertical thickness setting inverted and not working as intended?
### OrcaSlicer Version

1.9.0-dev

### OS version

macOS Sonoma arm64

### Additional system information

_No response_

### Printer

X1C

### How to reproduce

This manifests on various objects, but can be replicated with a simple cylinder

Add primitive -> Cylinder
Then rotate it on its side
Compare with "Ensure vertical thickness" enabled and disabled
Disabling this setting seems to actually add 2 extra layers (not sure if on all models)

### Actual results

It looks like this setting is actually decreasing time and filament use on most models.
However, the settings for Top+Bottom shell thickness still takes effect (I don't think it should?), there's just 2 more infill layers with this setting **disabled**
e.g. with 0.2mm layer height and 2mm Top shell thickness setting, there are 10 layers on the top with this setting **enabled** but **12** with this setting **disabled** which is 2 more than I'd expect and asked for
I am fairly certain that it used to work as I expect in PrusaSlicer some time back, is there a different logic now?

### Expected results

I'd expect filament consumption and time to predictably decrease with "Ensure vertical shell thickness" unchecked and shell thickness settings to only take effect when it is enabled.

### Project file & Debug log uploads

[thicknessbug.zip](https://github.com/SoftFever/OrcaSlicer/files/13573006/thicknessbug.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

### LINKED ISSUE #3224: Orca is taking extra 2h with unnecessary solid infill/shell thickness
### OrcaSlicer Version

1.9.0-dev, 1.8.1, 1.7.0

### OS version

Linux Mint Cinnamon

### Additional system information

_No response_

### Printer

Voron Trident

### How to reproduce

1. Slice the STL attached
2. Check layer by layer to see the problem

### Actual results

**NOTE**: This has been happening for some time now, it just got worse.

~2h wasted with solid infill but shell thickness is disabled.
No explanation is good enough to explain that, I usually print with 3 walls, you do not need any extra support, that is why I keep shell thickness disabled.

image

If I enable shell thickness, it does the opposite, it partially disables those non necessary infill and takes less time to print.

image

I tried to slice again and from 6h22 it changed to 6h10 so something weird is going on.
As I tried to replicate things to get the log, it went to 6h39

image

The screenshots above were shared within Discord, now that I am replicating everything to open this bug report, shell thickness is finally showing what it should have done in the the first place and 30 minutes longer.
There is some logic bug going on

From 6h22 to 6h39 to 7h, this cannot be right.

image

### Expected results

I expect no extra shell/infill to be added on its own.
It is taking an extra 2-3h to print, wasting filament and energy for no reason.

### Project file & Debug log uploads

[debug_log.txt](https://github.com/SoftFever/OrcaSlicer/files/13741866/debug_log.txt)
[Clockspring3D Torture Toaster v24.stl.zip](https://github.com/SoftFever/OrcaSlicer/files/13741870/Clockspring3D.Torture.Toaster.v24.stl.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

### PR DESCRIPTION
**Pull request by igiannakas**
Introduced experimental option to fully disable solid infill printed against sloping walls even when ensure vertical thickness is turned off.

Fixes #3224
Fixes #3016
Fixes #1887

**Ensure vertical thickness ON:**
We can see solid infill against the walls even on pretty much flat surfaces. This is the most conservative option.
image

**Ensure vertical thickness OFF:**
Solid infill greatly reduced in mostly flat areas. 
image

However it is present on sharp sloping surfaces like the below. So **this resulted in the total volume of infill to be increased as also increasing the print time.** This is because of the more infill applied to high degree sloping surfaces compared to the new ensure vertical thickness algorithm.
image

**With the Further reduce solid infill on walls option ON:**
Sloping surfaces infill completely eliminated. Print time is lower now compared to the ensure vertical thickness on and with ensure vertical thickness off as is material use.
image

This PR respects the need for solid infill where features are printed over bridges so we dont end up with unsupported features when printing external wall features that require internal bridging:
image
image

It also doesnt affect the treatment of the first layer over an external bridge:
**Before:**
image
**After:**
image

**Implementation details:**
Turns out the discover horizontal shells function that was used when ensure vertical thickness was off allowed for significantly reduced wall solid infill when the infill density was set to 0. This was because it was assumed by the developers that the user would only want to print the hollow object. 

With this PR we are piggy backing on that code and enabling the calculation of a reduced solid wall infill even when infill density is >0. 

image
image

### CODE REVIEW

**Comment by igiannakas** [comment]
Pushed a minor parameter update to make this option somewhat safe for sloped top surfaces where the perimeters were close to overhanging.

Slight increase in print time but still very effective.

image

**Comment by Eldenroot** [comment]
Wow, thank you!

**Comment by igiannakas** [comment]
> Wow, thank you!

The code change is pretty simple but I am debating a few things:
1. Do we keep this as a separate option or replace the behaviour when the ensure vertical shell thickness is de-selected? Its pretty "safe" with the latest code submission and the legacy algorithm doesn't always behave as expected.
2. Is the name correctly reflecting what we are trying to do?
3. Is this even worth while?

The way it is with this PR now, is we have a spectrum of 3 options - 
1. ensure ticked - the most conservative option, the shells are always the right thickness 
2. unticked -> middle of the road, reduces solid infill in most cases
3. further reduce infill -> the most aggressive in reduction, always reduces solid infill

**Comment by Eldenroot** [comment]
It depends... there are many "conservative" users who does not like new things or prefer the old behaviour. For example arachne vs classic perimeter generator :) there are and there will be always two camps of these users.

Maybe we should use new "enhanced" code as a default option and behaviour BUT provide an "option" - switch to the old mode.

**Comment by ShryuKt** [comment]
Thanks for this PR, I've been waiting for it for a moment ^_^.
I haven't fully tested it but it looks good to me.

Just a small thing, it might be better not to add an option but rather to modify the "Ensure vertical hull thickness" option as a drop-down menu (with 3 options like Active, inactive and aggressive)

**Comment by HakunMatat4** [comment]
> It depends... there are many "conservative" users who does not like new things or prefer the old behaviour. For example arachne vs classic perimeter generator :) there are and there will be always two camps of these users.
> 
> Maybe we should use new "enhanced" code as a default option and behaviour BUT provide an "option" - switch to the old mode.

Yup, I agree with that in parts.
This awesome PR also covers a ticket I opened, to cover both "camps" I think this should not be added enabled by default.

Ensure vertical shell thickness was added back and enabled by default, that is wrong, many users won't even bother to change stuff, but those like us who do, the last thing you want is a feature added back messing things around.
I had it disabled only to find out printing time and filament was out of chart because of it.

This is a somewhat advanced/enhancement feature which users like us can very well enable/disabled it.
Unless of course, setting it enabled by default won't harm ordinary users.

**Comment by igiannakas** [comment]
The only problem with the drop down is that it may break I think the printer profiles. But not 100% sure so I’ll wait for softfever to chime in with a review

**Comment by igiannakas** [comment]
> > It depends... there are many "conservative" users who does not like new things or prefer the old behaviour. For example arachne vs classic perimeter generator :) there are and there will be always two camps of these users.
> > Maybe we should use new "enhanced" code as a default option and behaviour BUT provide an "option" - switch to the old mode.
> 
> Yup, I agree with that in parts. This awesome PR also covers a ticket I opened, to cover both "camps" I think this should not be added enabled by default.
> 
> Ensure vertical shell thickness was added back and enabled by default, that is wrong, many users won't even bother to change stuff, but those like us who do, the last thing you want is a feature added back messing things around. I had it disabled only to find out printing time and filament was out of chart because of it.
> 
> This is a somewhat advanced/enhancement feature which users like us can very well enable/disabled it. Unless of course, setting it enabled by default won't harm ordinary users.

I wouldn’t change the default behaviour or ensure vertical shell thickness being on to be honest. Not sure if that’s what you’re thinking here, but it’s the safest option hence the default. Users can mess it up in so many ways (1-2 perimeters with very sloped surfaces for example) that it would be best to keep it turned on

**Comment by igiannakas** [comment]
I’ve found a second way to achieve the same result - but this one may make internal bridging a bit more reliable - will post a separate PR after Christmas and welcome a review to pick which one of the two.

**Comment by igiannakas** [comment]
Found a bug but not necessarily related to this PR:

When ensure vertical thickness was off, the bridges over the letters were way too short, not expanding enough to allow good bridging. This resulted in the bridges collapsing and filling the letters with loose filament.

image

This did not happen with ensure vertical thickness on:
image

This was because the process external surfaces was called before the discover horizontal shells (the ensure vertical thickness disabled function) but after the discover vertical shells (that is the ensure vertical thickness enabled function).

Reordered the function so its after the discover horizontal shells. Results as below - beautiful bridging:
image

**Comment by Eldenroot** [comment]
Good catch!

**Comment by liftbag** [comment]
I find the function of further reducing solid infill on walls very interesting. However, there are cases where I cannot use it, because it prevails over the ability to generate a consistent number of top shell layers where the top surfaces are slightly inclined rather than flat.
Fortunately the parameter can be assigned to modifiers, but I wonder if it is possible to introduce a mediation in the algorithm, for example establishing from which angle the number of top shell layers should prevail.

Screenshot 2023-12-25 alle 13 06 15

Screenshot 2023-12-25 alle 13 07 22


In this example, 7 top shell layers are set, but further reduce solid infill on walls is enabled.
IMG_9478-edited

**Comment by igiannakas** [comment]
> I find the function of further reducing solid infill on walls very interesting. However, there are cases where I cannot use it, because it prevails over the ability to generate a consistent number of top shell layers where the top surfaces are slightly inclined rather than flat. Fortunately the parameter can be assigned to modifiers, but I wonder if it is possible to introduce a mediation in the algorithm, for example establishing from which angle the number of top shell layers should prevail.
> 
> Screenshot 2023-12-25 alle 13 06 15 Screenshot 2023-12-25 alle 13 07 22
> In this example, 7 top shell layers are set, but further reduce solid infill on walls is enabled. IMG_9478-edited

Is this with the latest build?

**Comment by igiannakas** [comment]
Also could you please attach your 3mf project file?

**Comment by liftbag** [comment]
> Also could you please attach your 3mf project file?

Yes, I'm on build #397.

Here the 3mf file.

[Hiby dock_base.3mf.zip](https://github.com/SoftFever/OrcaSlicer/files/13766155/Hiby.dock_base.3mf.zip)

**Comment by igiannakas** [comment]
> > Also could you please attach your 3mf project file?
> 
> Yes, I'm on build #397.
> 
> Here the 3mf file.
> 
> [Hiby dock_base.3mf.zip](https://github.com/SoftFever/OrcaSlicer/files/13766155/Hiby.dock_base.3mf.zip)

There is an interaction between this option and the single wall top perimeter. Set the top surface threshold to 200% or greater and the sloped surface now has partial supporting infill.

But in general a model like that with sloped surfaces really does need the ensure vertical shell thickness option turned on to print best - that is what this option is for :)

**Comment by igiannakas** [comment]
There is an alternative way to implement this - https://github.com/prusa3d/PrusaSlicer/pull/11950

Basically disable the combining of holes in the new ensure vertical shell thickness algorithm while retaining the combine surfaces. This removes most of the side wall infill but retains the top layers better. I'll open another PR tomorrow with this approach implemented and we just need to pick one of the two.

**Comment by Eldenroot** [comment]
Good catch, anyway quite difficult to say which way is the better one :(

**Comment by igiannakas** [comment]
> Good catch, anyway quite difficult to say which way is the better one :( I like both approaches

I’ve opened an alternative PR on this based on the work that vovodroid did for prusa slicer. Waiting for the build to finish in order to upload screenshots. 

Then we can test both and decide on which one

**Comment by igiannakas** [comment]
So I've found a major deficiency with the other approach. It stops top solid infill from being generated when the top surface is perfectly flat. That is a no-go. So reopening this one and tweaking the parameters a bit to cover edge cases like the above.

**Comment by igiannakas** [comment]
Latest parameters:

image


image


image

This should be a good balance between infill and sloped surfaces.

**Comment by igiannakas** [comment]
@SoftFever ready for review. Will also do a bit more parameter testing specifically this statement to see whether we can go even less with the filtering to make it more conservative.

```
                        // Orca: Also use the same strategy if the user has selected to reduce
                        // the amount of solid infill on walls. However reduce the margin to 20% overhang
                        // as we want to generate infill on sloped vertical surfaces but still keep a small amount of
                        // filtering. This is an arbitrary value to make this option safe
                        // by ensuring that top surfaces, especially slanted ones dont go **completely** unsupported
                        // especially when using single perimeter top layers.
                        float margin = region_config.reduce_wall_solid_infill? float(neighbor_layerm->flow(frExternalPerimeter).scaled_width()) * 0.2f : float(neighbor_layerm->flow(frExternalPerimeter).scaled_width());
```

**Comment by ShryuKt** [comment]
This last build looks good to me.
A little bit too much solid infill for my taste, but no problem on the top layers.

Like you I would prefer to always use this option but it seems that it is not possible, so best of both world I guess ^_^

**Comment by igiannakas** [comment]
So I've done some more testing with the above parameters. The currently submitted PR is where I'd say I'm happy to leave it for my personal preference. Any less and the slanted top surfaces become risky, any more and the reduction is not as significant as it can be. 

@SoftFever ready for your review and feedback

**Comment by Panacaguy** [comment]
@igiannakas Just curious if your proposed implementation would help for my use case. I print RC airplanes with single wall and some non-zero level of infill. These extra walls trying to enforce top/bottom thickness are driving the weight up ~10 or more percent depending on the file. To me, having an option to specify an angle threshold to determine where it does or does not ensure the vertical wall thickness would be ideal, but maybe that opens up too much potential trouble for the casual user to get into trouble, or maybe it would be too difficult to implement in the code. Anyway, I'd love to hear your take on if your proposed fix will reduce or eliminate extra material on sloped surfaces of ~35-45 degrees on up, specifically, single wall prints with ~5% infill.

This... (achieved using height range modifiers)
image
Not this... (note, ensure vertical wall thickness not enabled)
image

**Comment by igiannakas** [comment]
> @igiannakas Just curious if your proposed implementation would help for my use case. I print RC airplanes with single wall and some non-zero level of infill. These extra walls trying to enforce top/bottom thickness are driving the weight up ~10 or more percent depending on the file. To me, having an option to specify an angle threshold to determine where it does or does not ensure the vertical wall thickness would be ideal, but maybe that opens up too much potential trouble for the casual user to get into trouble, or maybe it would be too difficult to implement in the code. Anyway, I'd love to hear your take on if your proposed fix will reduce or eliminate extra material on sloped surfaces of ~35-45 degrees on up, specifically, single wall prints with ~5% infill.
> 
> This... (achieved using height range modifiers) image Not this... (note, ensure vertical wall thickness not enabled) image

Download the build above and let me know what you think. Enable the reduce solid infill and the further reduce option and see the results

**Comment by Panacaguy** [comment]
I'm not very familiar with Github. I don't know how to do that. I assume it
means I would need to compile it once downloaded too? Would it mess with my
current install? Sorry if these are dumb questions.v

**Comment by igiannakas** [comment]
Create a git hub account then download it from the bottom of the page here: https://github.com/SoftFever/OrcaSlicer/actions/runs/7552665935

you can download the portable version which won’t mess with your current install.

**Comment by Panacaguy** [comment]
> Download the build above and let me know what you think. Enable the reduce solid infill and the further reduce option and see the results

Works great! That will save me a lot of time (and weight) on my airplanes. Thanks a bunch!

**Comment by igiannakas** [comment]
> > Download the build above and let me know what you think. Enable the reduce solid infill and the further reduce option and see the results
> 
> Works great! That will save me a lot of time (and weight) on my airplanes. Thanks a bunch!

Welcome 😀

**Comment by HakunMatat4** [comment]
@igiannakas I am running this version that fixes the chaotic printing by layer order, finally: https://github.com/SoftFever/OrcaSlicer/actions/runs/7529929480?pr=3685
Are your changes merged to it, how does it work???

Atm, OrcaSlicer is incapable of printing by layer following the object list creating tons of headache, personally I judge that higher issue but I wanna keep your PR too haha
Please, tell me something positive.

**Comment by igiannakas** [comment]
> @igiannakas I am running this version that fixes the chaotic printing by layer order, finally: https://github.com/SoftFever/OrcaSlicer/actions/runs/7529929480?pr=3685 Are your changes merged to it, how does it work???
> 
> Atm, OrcaSlicer is incapable of printing by layer following the object list creating tons of headache, personally I judge that higher issue but I wanna keep your PR too haha Please, tell me something positive.

I've sent you a DM with a build that contains both, till they are reviewed and merged.

**Review by SoftFever — APPROVED** [review]
Looks good.
Thank you so much for your expceptional contribution!

**Pull request merged**
