### PR TITLE
Add elephant foot compensation over multiple layers

### PR DESCRIPTION
**Pull request by bitingsock**
#https://github.com/prusa3d/PrusaSlicer/pull/10976

### CODE REVIEW

**Comment by SoftFever** [comment]
@bitingsock 
First of all, thanks for the PR!

Do you mind to add more details about the problem the PR is trying to solve?
Some before and after photo for comparison will be helpful

**Comment by bitingsock** [comment]
The problem is basically detailed here:
https://github.com/prusa3d/PrusaSlicer/issues/6276

By definition elephant's foot is not just a single layer problem, albeit on most printers a single layer compensation fixes 90% or more of the problem. In CAD we can easily put a substantial chamfer to fix it but that is not always a possibility. 

[https://youtu.be/zlgR3rHg4p8?si=X3kndwDf-0lYNEcY&t=573](https://youtu.be/zlgR3rHg4p8?si=X3kndwDf-0lYNEcY&t=573) at around 9:30 explains it well.

**Comment by bitingsock** [comment]
Note that this feature actually already exists in SuperSlicer which, I believe, is what the original write up was back-ported from.
https://github.com/supermerill/SuperSlicer/blob/45d0532845b63cd5cefe7de7dc4ef0e0ed7e030a/src/libslic3r/PrintObjectSlice.cpp#L986

**Review by SoftFever — APPROVED** [review]
LGTM

**Comment by SoftFever** [comment]
@bitingsock Thanks for the PR and explainations.
Merged.

**Pull request merged**
