### PR TITLE
build on systems with libwebkit2gtk-4.1

### PR DESCRIPTION
**Pull request by buzzhuzz**
# Description

Linux distros started removing libwebkit2gtk-4.0 library from their repos. Ubuntu Noble (24.04) is one of them.

Modify Linux deps script to check which version of libwebkit2gtk is available.

This change addresses #5007

Requires https://github.com/SoftFever/Orca-deps-wxWidgets/pull/1 to be integrated first.

## Tests

Build on Ubuntu 24.04 Beta
Build on Ubuntu 20.04 (through github actions)

### CODE REVIEW

**Comment by schugabe** [comment]
I tried running the AppImage from this PR on Fedora 40 and get the error: libwebkit2gtk-4.0.so.37: cannot open shared object file: No such file or directory

**Comment by mathojojo** [comment]
Same for me on kubuntu 24.04. What is surprising is that the appimage doesn't work as well... I thought that Appimages were created to avoid dependancies problems (all are built in the appimage package, like snap or flatpack... but I might be wrong).

**Comment by buzzhuzz** [comment]
This PR only fixes compilation issue.

For the AppImage fixes please check test build from #4616. https://github.com/SoftFever/OrcaSlicer/issues/4616#issuecomment-2079487313

**Comment by SoftFever** [comment]
@buzzhuzz 
Thanks.
I can't imagine what kind of changes are in the new patch file that contains 53,627 lines of changes...

Anyway, please refer to #5184, for changes related to wxWidgets; let's submit PRs there.: https://github.com/SoftFever/Orca-deps-wxWidgets

**Comment by buzzhuzz** [comment]
@SoftFever 

Majority of that patch is configure script re-generated by autotools due to updated configure.am

I'll open PR fo Orca-deps-wxWidgets first.

**Comment by SoftFever** [comment]
> 
> I'll open PR fo Orca-deps-wxWidgets first.

Thanks.

> Majority of that patch is configure script re-generated by autotools due to updated configure.am
> 

I suggest we don't include these changes

**Review by SoftFever — APPROVED** [review]
LGTM
Thank you!

**Pull request merged**
