### PR TITLE
fix Language en de and make new features to pot

### PR DESCRIPTION
**Pull request by hliebscher**
fix some new features in master POT file and en and de
in PrintConfig.cpp fix def->tooltip = L("")

### CODE REVIEW

**Comment by hliebscher** [comment]
Can you add a script for you  after add new features ?

(add new keywords)
xgettext --keyword=L --keyword=_L --keyword=_u8L --keyword=L_CONTEXT:1,2c --keyword=_L_PLURAL:1,2 --add-comments=TRN --from-code=UTF-8 --no-location --debug --boost   -f "bbl/i18n/list.txt" -o "bbl/i18n/OrcaSlicer.pot"

(add new keywords to other language)
msgmerge bbl/i18n/de/OrcaSlicer_de.po bbl/i18n/OrcaSlicer.pot -o bbl/i18n/de/OrcaSlicer_de.po
msgmerge bbl/i18n/en/OrcaSlicer_en.po bbl/i18n/OrcaSlicer.pot -o bbl/i18n/en/OrcaSlicer_en.po

(generate lang mo files )
 msgfmt -o resources/i18n/de/Orcaslicer.mo bbl/i18n/de/OrcaSlicer_de.po
msgfmt -o resources/i18n/en/Orcaslicer.mo bbl/i18n/en/OrcaSlicer_en.po

**Comment by SoftFever** [comment]
Hi @hliebscher 

We have these already :)
Building "gettext_make_pot" project/target will add new keywords to OrcaSlicer.pot
Building "gettext_merge_po_with_pot" project/target will add new keywords to all other languages.
Building "gettext_po_to_mo" will generate .mo files for all languages.

**Comment by hliebscher** [comment]
@SoftFever but in the POT file not all from your new msgs
 the bug is in 

src/libslic3r/PrintConfig.cpp:2456: warning: Empty msgid.  It is reserved by GNU gettext:
                                             gettext("") returns the header entry with
                                             meta information, not the empty string.
if you fix this than make pot works

i close the PR

**Comment by SoftFever** [comment]
@hliebscher do you mind repurposing this PR for that fix?
The reason we don't build gettext_* projects is that it will update the timestamp of pot/po files, which will cause troubles in git.
If you have a good resolution for the issue, let me know.

**Comment by SoftFever** [comment]
Fixed.
Thanks

**Pull request closed without merging**
