### PR TITLE
Added additional filament vendors.

### PR DESCRIPTION
**Pull request by anselor**
Added Anker printers to filament presets dialog.
Added helper to generate formatted strings for dialog from profile JSON files.
Added PHA material type
Changed to allow all material types when creating custom filaments.

### CODE REVIEW

**Review by SoftFever — COMMENTED** [review]
Do you mind to add some details to this PR?

**Comment by anselor** [comment]
> Do you mind to add some details to this PR?

Sure, just let me know

**Comment by thijstriemstra** [comment]
Would be great to use https://docs.python.org/3/library/argparse.html#module-argparse for the script, providing a standarized way to create commandline scripts.

**Comment by anselor** [comment]
@thijstriemstra 

I would have were there parameters to gather. In this case the script is just a helper to generate the list of names alphabetized and formatted to more easily update the c++ code in the dialog. The python script has the names formatted for easy manual update and generates the list of strings that can be pasted into the dialog without interrupting the code style currently in that file.

Was there a specific thing you wanted to have parameterized?

**Comment by anselor** [comment]
@SoftFever What details did you want added for this? Thanks.

**Comment by SoftFever** [comment]
> @SoftFever What details did you want added for this? Thanks.

Sorry for the late response.

A little bit of context for the PR would be helpful, such as details about what problem the PR is aiming to solve or enhance.

Screenshots would also be extremely useful.

It's not immediately clear to me what a PR is trying to achieve if little background information is provided.

**Comment by SoftFever** [comment]
It seems the PR has gone stale. 
I'm closing it for now.
Feel free to reopen it in the future.

**Pull request closed without merging**
