### PR TITLE
Support larger printer (up to hundred meters)

### LINKED ISSUE #186: Extend Maximum Size Limitation
Currently, the bed limitation is 1200mm and our printer is 4000mm long. 
Is it possible to either remove the maximum value limit or set it at something like 6000mm?

### PR DESCRIPTION
**Pull request by SoftFever**
# Description

Orca Slicer currently only supports printer bed sizes smaller than 2147mm x 2147mm due to the limitations of the 32-bit data type.
This limitation also applies to the maximum number of platers you can create for a project.
The total width/length of all the plates cannot exceed this limit.

With this change, Orca can now support sizes as large as desired.
For convenience, the limit is currently set to 214m x 214m x 214m.

SuperSlicer is referenced for some changes.

closes #186 
# Screenshots/Recordings/Graphs

image

- [x] Fix the issue that Orca can't slice if the model is larger than 2147mm when Arachne generator is used. Classic engine works fine
- [x] Optimize grid size for large bed
- [ ] Optimize gcode window for large coords

### CODE REVIEW

**Comment by yw4z** [comment]
thanks for letting me building my next house with orca :)

**Comment by madeintaiwan** [comment]
Amazing, great news and great work as always @SoftFever

**Comment by madeintaiwan** [comment]
One aspect of big prints I've noticed is that especially for rectangular beds, the code might be adjusted to account for a print that is long (in my case in Y).  
image

Hard to see the blue line of the travel move there and Cura was particularly bad at it but it would be great if there was a 'big bed' option or something that sliced without having to do full bed travel moves back and forth to deposit small artifacts. 

_n

**Comment by SoftFever** [comment]
> One aspect of big prints I've noticed is that especially for rectangular beds, the code might be adjusted to account for a print that is long (in my case in Y). image
> 
> Hard to see the blue line of the travel move there and Cura was particularly bad at it but it would be great if there was a 'big bed' option or something that sliced without having to do full bed travel moves back and forth to deposit small artifacts.
> 
> _n

These are usually gap fillings.
I assume you are using large nozzle as well.
You probably can play around gap filling parameter 
image

Same as the Resolution parameter for large nozzles:
image

**Comment by SoftFever** [comment]
The PR should fully functional now.
If anyone interested, please give it a try and let me know how well it when slicing real models ;) @madeintaiwan 
large

**Comment by madeintaiwan** [comment]
Dude! Making it now and will print our next smart buoy body with it!  

WhatsApp Image 2024-05-10 at 21 15 56_76318d9e

**Comment by madeintaiwan** [comment]
Struggled to build this on Windows, assume I'm doing something wrong. 

Will this be part of Nightly Build?

**Comment by SoftFever** [comment]
> Struggled to build this on Windows, assume I'm doing something wrong.
> 
> Will this be part of Nightly Build?

It's not part of the nightly build yet.
But you can download it here: https://github.com/SoftFever/OrcaSlicer/actions/runs/9052512767?pr=5320
Screenshot 2024-05-13 at 6 52 17 AM

**Comment by LE1ED4523** [comment]
maybe support belt printer next step?

**Comment by madeintaiwan** [comment]
@SoftFever YES! Fantastic work man. Full 4-meter-long prints are now possible.

image


I am putting a print on now, I will see how it gets and report back.

**Comment by SoftFever** [comment]
> @SoftFever YES! Fantastic work man. Full 4-meter-long prints are now possible.
> 
> image
> 
> I am putting a print on now, I will see how it gets and report back.

Hey @madeintaiwan 
How's the print going on?

**Comment by madeintaiwan** [comment]
@SoftFever I did! 

Not the board yet because I've got to finish the buoy first. 

But four big prints later - 

image


image


image

Need to finish the data well and then it's going into the ocean...... TO MONITOR ORCAS.....

**Comment by madeintaiwan** [comment]
@SoftFever Next idea and I'm sure this applies to beds like the ones on the Elegoo Orangestorm too-

Multiple bed heater control depending on object placement on the bed. In my case if it's longer than 1.5 meters it would be great to have an option to automatically heat bed heater two as well. 

image

Don't know if that's better in slicer or via machine control.

**Pull request merged**
