### PR TITLE
Add TM3D Troodon 2.0

### PR DESCRIPTION
**Pull request by tinymachines3d**
Please consider adding our supercharged Troodon 2.0 profiles.

### CODE REVIEW

**Comment by hliebscher** [comment]
pls delete the desktop.ini 's  and why you have only one nozzle 0.4?
pls use the filenames like #1357

**Comment by tinymachines3d** [comment]
> pls delete the desktop.ini 's and why you have only one nozzle 0.4? pls use the filenames like #1357 Currently @fr3ak2402 is helping consolidate the printer profile names. Can you refer to this: [#1100 (comment)](https://github.com/SoftFever/OrcaSlicer/pull/1100#issuecomment-1556946352) to match the new name schema?

Thank you for the info. I've updated as far as I can tell.

**Comment by SoftFever** [comment]
@tinymachines3d 
Thanks for the PR.
Can you please check this PR #1041?
If I'm not wrong, they are the same printers?

**Comment by tinymachines3d** [comment]
> @tinymachines3d Thanks for the PR. Can you please check this PR #1041? If I'm not wrong, they are the same printers?

Sort of. We build customized versions of this maching running Klipper only and our profiles are faster.

**Comment by SoftFever** [comment]
> > @tinymachines3d Thanks for the PR. Can you please check this PR #1041? If I'm not wrong, they are the same printers?
> 
> Sort of. We build customized versions of this maching running Klipper only and our profiles are faster.

There is already a `Troodon 2.0 - Klipper` model.
If you believe you can optimised it, feel free to create another PR based on that profile.

**Comment by SoftFever** [comment]
Closing due to duplication.

**Pull request closed without merging**
