### PR TITLE
Add Textured PLU Plate (Sliceworx) for Bambu Lab printers

### PR DESCRIPTION
**Pull request by philltran**
# Description

Added new bed plate option for [Textured PLU Build Plate](https://amzn.to/4cU8nXn) such as the [Sliceworx plate](https://www.sliceworx.com/products/bambulab-compatible-pei-textured-spring-steel-sheet-257x257mm-for-x1c-x1e-p1p-p1s-a1-3d-printer?variant=44608210305181). 

# Screenshots/Recordings/Graphs

My screenshot A

My screenshot B

## Tests

This needs more testing and review as it is my first PR to this project

### CODE REVIEW

**Comment by SoftFever** [comment]
Hi @philltran 
What's difference between this and cool plate? I failed to see the necessarily to add a new bed type here TBH.
PS. You will need to clean up/sync your branch before creating PR.

**Comment by philltran** [comment]
@SoftFever Thanks for looking into this. The difference between the cool plate and textured plu plate is the textured plate would still need the z height offset that is added in g-code start. 

> ;===== for Textured PEI Plate , lower the nozzle as the nozzle was touching topmost of the texture when homing ==

Ideally the[ option to add custom plates](https://github.com/SoftFever/OrcaSlicer/issues/5989) would be great, but that would be considerable more effort to implement. 

I will clean up the PR and test some more.

**Comment by kylek29** [comment]
> Hi @philltran What's difference between this and cool plate? I failed to see the necessarily to add a new bed type here TBH. PS. You will need to clean up/sync your branch before creating PR.

Just to chime in, I find that BambuLab printers are not the best at determining a starting Z-Offset for many plate types and lack any ability to micro-adjust it (or see the value). They've patched this themselves for their official plates via custom G-Code in the startup sequence. Adding this additional plate will help users determine their own Z-Offset setting without needing in to remember to set the Z override in the printer setting.

Just for example, my X1C needs these adjustments:

- Official Bambu Textured PEI Plate: -0.04
- Textured PEI Plate: -0.08
- G10: -0.14
- WhamBam: +0.04

Having more options to target custom G-Code at is always a plus.

**Comment by johnny-bit** [comment]
IMHO custom plates with sane default ones are the way to go instead of having to do PR for each custom plate just to have proper Z-offset (or custom GCode for something like LiDaR adjustment for non-uniform surface)

**Comment by SoftFever** [comment]
Indeed, allowing user to add custom bed is more preferrable.

I'm afraid the proposed bed type is too specific to one vendor, but more importantly it's only used by very few people and causing confusion/bloating for rest of the users.
So I'm inclined to accept this PR.

**Pull request closed without merging**
