### PR TITLE
Add a new placehoder `is_extruder_used` for IDEX printers

### PR DESCRIPTION
**Pull request by macdylan**
for IDEX printers, It is necessary to check whether the extruder is used in the slice for preheating, nesting and other operations, like:
```
{if is_extruder_used[0]}M104 S{temperature[0]} T0 ;preheat T0{endif}
{if is_extruder_used[1]}M104 S{temperature[1]} T1 ;preheat T1{endif}
```

### CODE REVIEW

**Comment by SoftFever** [comment]
@macdylan, thanks. The `is_extruder_used` change looks good to me.

Can you explain more about the other two changes you made in the PR?

**Comment by macdylan** [comment]
[59035cb](https://github.com/SoftFever/OrcaSlicer/pull/951/commits/59035cb53fbaa3b92deb6fab3b3aa59c473834fe)
 - Just using a fixed-width font for the purpose of `is_code`

[29ad67a](https://github.com/SoftFever/OrcaSlicer/pull/951/commits/29ad67abd4758d3a630fb0ccc979e73b3f5bf624)
- cmd+shift+g will always bring up the BBS job window, but I'm using OctoPrint:
image

Please reject these 2 changes if they are causing confusion, I'm sorry i made multiple commits in one PR it is not easy to read.

**Review by SoftFever — APPROVED** [review]
LGTM

**Comment by KoenVanduffel** [comment]
Without opening a new pull request, maybe this one can be expanded:

Orca puts an M104 at every filament change. These should also contain the T0 and T1 statements for IDEX printers. as when different temperatures are used for both extruders all M104 commands will land on T0 (at least for RatOS 2.1 that is the case).

**Pull request merged**
