### PR TITLE
Enabling object skirt.

### PR DESCRIPTION
**Pull request by vovodroid**
Implements individual object skirts, as requested in  **Individual skirts when printing by object. #3486** and  **Skirt around each object when using "by object" sequence #2652**

Now skirt type could be
image

This PR based on several refactorings, including  **Configure skirt start point #6490** PR. To make review more easy each step was committed individually. Obviously them could be separated to different PRs or dropped.

I removed `prime_extruder && first_layer && extruder_id == first_extruder_id` as explicit object skirt is available.

Open question : do we need both common and object skirt together, probably with separate loop number?

All four combinations are possible.

Print by layer, common skirt:
image

Print by layer, object skirt:
image

Print by object , object skirt:
image

Print by object , common skirt (any meaning?):
image

### CODE REVIEW

**Comment by vovodroid** [comment]
@igiannakas , would you like to test it?

**Comment by igiannakas** [comment]
Will do, no problem! From Tuesday though as I’m away from home for a few days :)

**Comment by SoftFever** [comment]
Love the idea!
Will review and test it soon

**Comment by SoftFever** [comment]
Looks all good to me.
Just got a suggestion, can we name the skirt type to: `Combined` and `Per-object` for clarity?

**Comment by vovodroid** [comment]
Renamed:

image

**Review by SoftFever — APPROVED** [review]
Looks good
Thank you!

**Pull request merged**
