### PR TITLE
Enable skirt for Flashforge process profiles

### PR DESCRIPTION
**Pull request by mariuske**
I've now performed some testing with the skirt setting. I see that this setting has already saved my prints several times due to either not optimal filament flow when entering the print area or the nozzle dragging som flushed filament into the print area.

Also, most other Orca Slicer profiles have this setting enabled (for good reason I guess).

It might make sense to increase the number of loops to "2" later (after more testing) as I see this is more common in other profiles.

@FlashforgeOfficial - FYI. I believe "skirt" is equivalent to "pre-extrusion" in FlashPrint which is enabled by default.

@SoftFever - Please merge this PR when you have the opportunity. Thanks!

### CODE REVIEW

**Review by SoftFever — APPROVED** [review]
LGTM
Thanks

**Comment by FlashforgeOfficial** [comment]
Yes, in Flashprint the pre-extrusion function is the skirt function.  It's recommended to apply the pre-extrusion function for better flow of filament. Also, in my experience if filament loading is performed right before the printing starts, it's also printing smoothly without skirt setting.  Anyway, it's safer to be better prepared for the printing lol. @mariuske

**Comment by 3DThingy** [comment]
FYI there is a pre-extrusion already being executed without the skirt function being selected
IMG_5140
IMG_5139

**Comment by mariuske** [comment]
> FYI there is a pre-extrusion already being executed without the skirt function being selected IMG_5140 IMG_5139

That's true, I'm aware of the initial pre-extrusion around the edges of the bed. I still believe the additional skirt serves a purpose as I've had multiple cases over the past weeks where a loop (or two) of skirt is needed for a smooth flow of filament. It's also a "safety net" for bad adhesion of the first layer and has also saved my prints from flushed filament which is dragged into the print area (and stopped by the skirt).

**Pull request merged**
