### PR TITLE
Add the Polish language

### PR DESCRIPTION
**Pull request by KrisMorr**
Please add the Polish language

### CODE REVIEW

**Comment by SoftFever** [comment]
@KrisMorr 
I'm a bit confused.
Could you clarify the PR a bit more?
Did you add the Polish language option and translation in this PR?

**Comment by KrisMorr** [comment]
@SoftFever 
Unfortunately, I don't have much knowledge of GitHub. I've just PR here to download from my created branch on GitHub. I have prepared translations in .po and text.json formats for the Polish language. I'm also attaching them below.
[OrcaSlicer_pl.zip](https://github.com/SoftFever/OrcaSlicer/files/13941533/OrcaSlicer_pl.zip)

**Comment by SoftFever** [comment]
> @SoftFever Unfortunately, I don't have much knowledge of GitHub. I've just PR here to download from my created branch on GitHub. I have prepared translations in .po and text.json formats for the Polish language. I'm also attaching them below. [OrcaSlicer_pl.zip](https://github.com/SoftFever/OrcaSlicer/files/13941533/OrcaSlicer_pl.zip)

You actually have all the necessary changes in place :)
I fixed two small issues, looks we are good
image

**Review by SoftFever — APPROVED** [review]
Looks good

**Comment by SoftFever** [comment]
The nightly build including this change should be ready in about 1 hour from now.
Let me know if it looks good on your side.
Thank you for your work again 👍 
https://github.com/SoftFever/OrcaSlicer/releases/tag/nightly-builds

**Comment by KrisMorr** [comment]
👍
It's okay, I have sent another PR with many corrections

**Pull request merged**
