### PR TITLE
Fix building with GCC13 (required to build on Arch and Fedora)

### PR DESCRIPTION
**Pull request by c2h5oh**
Arch and Fedora switched to GCC 13.x as default making it impossible to build BambuStudio/OrcaSlicer on those distros.

Only minor cleanup was required to fix that.

### CODE REVIEW

**Comment by SoftFever** [comment]
Thanks.
I will create a CICD script for dependencies to ensure it won't break builds on other platforms.
Will merge this PR after that.

**Comment by SoftFever** [comment]
@c2h5oh 
It breaks ubuntu build, can you take a look?
https://github.com/SoftFever/OrcaSlicer/actions/runs/5206674509/jobs/9393476148

**Comment by c2h5oh** [comment]
At first glance it looks like it fails linking libcurl for some reason https://github.com/SoftFever/OrcaSlicer/actions/runs/5206674509/jobs/9393476148#step:7:23804 which is unrelated to the changes I've made.

I see you've reached the same conclusion - dummy PR is failing in the exact same way https://github.com/SoftFever/OrcaSlicer/actions/runs/5209254063/jobs/9398859063?pr=1295#step:7:24268

I'm currently on a PC without a dev env set up, but I'll try to help in about 2-3h.

**Comment by SoftFever** [comment]
@c2h5oh 
Agreed. There is an issue in the current CICD runner.

**Review by SoftFever — APPROVED** [review]

**Pull request merged**
