### PR TITLE
1025 Add Flashforge printers profile

### PR DESCRIPTION
**Pull request by FlashforgeOfficial**

### CODE REVIEW

**Comment by mariuske** [comment]
With the caveat that this is my first 3D printer and I have very limited experience:

I've tested these profiles with a portable installation on my Flashforge AD5M Pro with a 0.4 nozzle. Based on my initial (and limited) testing, it seems like the different profiles loads fine in OrcaSlicer and I'm successfully printing.

A few improvements (for a later PR?):

1. Nozzle type is undefinded, 
image

The machine profiles should include (based on the desciption on the [website](https://www.flashforgeshop.com/product/0-6-mm-nozzle-kit-for-adventurer-5m-series?cID=52)):
`"nozzle_type": "hardened_steel",`

2. For "Flashforge Generic HS PLA" filament, the "hot_plate_temp" parameter is used instead of "textured_plate_temp". I've manually changed the value for High Temp Plate from "45" to "60" as this improves the print, especially for the intial layer.
```
  "hot_plate_temp_initial_layer": [
    "45"
  ],
  "hot_plate_temp": [
    "45"
  ],
    "textured_plate_temp": [
    "60"
  ],
  "textured_plate_temp_initial_layer": [
    "60"
  ],
```
 
image

3. For "Flashforge Generic HS PLA" filament, the defined range (190-230) is not matching the range on the filament (190-220 and 220-240 for high speed):

```
  "nozzle_temperature_range_high": [
    "230"
  ],
  "nozzle_temperature_range_low": [
    "190"
  ],
```

**Comment by SoftFever** [comment]
@FlashforgeOfficial 
Let me know if you plan to address @mariuske 's feedback.
I plan to release a beta build by end of this week just FYI.
BTW, you can push new changes directly into the same branch instead of creating a new PR every time, so that we can track all things in one place.

**Comment by FlashforgeOfficial** [comment]
> With the caveat that this is my first 3D printer and I have very limited experience:
> 
> I've tested these profiles with a portable installation on my Flashforge AD5M Pro with a 0.4 nozzle. Based on my initial (and limited) testing, it seems like the different profiles loads fine in OrcaSlicer and I'm successfully printing.
> 
> A few improvements (for a later PR?):
> 
> 1. Nozzle type is undefinded,
>    image
> 
> The machine profiles should include (based on the description on the [website](https://www.flashforgeshop.com/product/0-6-mm-nozzle-kit-for-adventurer-5m-series?cID=52)): `"nozzle_type": "hardened_steel",`
> 
> 2. For "Flashforge Generic HS PLA" filament, the "hot_plate_temp" and "hot_plate_temp_initial_layer" parameters are used instead of the "textured_plate_temp"/"textured_plate_temp_initial_layer" parameters. As a workaround, I've manually changed the value for High Temp Plate from "45" to "60" as this improves the print, especially for the intial layer, but I guess the intention was to use the textured plate parameters.
> 
> ```
>   "hot_plate_temp_initial_layer": [
>     "45"
>   ],
>   "hot_plate_temp": [
>     "45"
>   ],
>     "textured_plate_temp": [
>     "60"
>   ],
>   "textured_plate_temp_initial_layer": [
>     "60"
>   ],
> ```
> 
> image
> 
> 3. For "Flashforge Generic HS PLA" filament, the defined range (190-230) is not matching the range on the filament (190-220 and 220-240 for high speed):
> 
> ```
>   "nozzle_temperature_range_high": [
>     "230"
>   ],
>   "nozzle_temperature_range_low": [
>     "190"
>   ],
> ```

@mariuske Hi,   thank you for your help in testing! 
Regarding the tips, here are the changes made or to make:
1. The AD5M series printers are with stainless nozzle by default. The hardened one is optional so the nozzle type is set to be stainless steel.
2. For the hot_plate_temp_initial_layer  and hot_plate_temp  setting, by our test 45℃ is a proper value as going higher could bring out some issues in printing. 60 could be a better choice and let's give more tests and hopefully update it in next commit.
3. For the nozzle range of temperature for HS PLA is what works fine in testing. So for now let's keep it and do more testing, similar to the hotplate setting in [2]. 
Looking forward to more feedback in the future and make improvements together.

**Comment by FlashforgeOfficial** [comment]
> @FlashforgeOfficial Let me know if you plan to address @mariuske 's feedback.
> 
> I plan to release a beta build by end of this week. Just FYI in case you want to squeeze the profiles into the beta release. BTW, you can push new changes directly into the same branch instead of creating a new PR every time, so that we can track all things in one place.

Hi SoftFever,
We are adopting part of the tips from @mariuske for now.  Thank you for your notice too, I am going to finish and manage update for the beta build. LOL I made many closed PR as trying to fix some issues and I will push new changes into the same branch later.

**Comment by FlashforgeOfficial** [comment]
@SoftFever @mariuske  I have updated the nozzle type setting in this PR directly as the screenshot below. For now, I guess this is the  version to be loaded in your beta build.  Thanks for all the patience!
image

**Review by SoftFever — APPROVED** [review]

**Comment by SoftFever** [comment]
Thanks all.
Merged.

**Comment by mariuske** [comment]
I can confirm that the nozzle type is now displayed correctly with the latest update.

image

**Comment by davidrq78** [comment]
Is there any change of connecting Adventurer 4 or Guider 3 with Orca? @FlashforgeOfficial

**Pull request merged**
