### PR TITLE
Creality Ender 3   and Prusa Mk3s   0,2;0,4,06 and 0,8 profiles

### PR DESCRIPTION
**Pull request by goyetus**
Prusa Mk3s Profiles for 0,2;0,4;0,6;0,8
Ender 3 Profiles for 0,2;0,4;0,6;0,8

5 Different and independent Quality profiles for each Nozzle.
Fine, Optimal, Standard, Draft and Superdraft
All working perfect in Orcaslicer last version. Profiles direct from Prusa.

### CODE REVIEW

**Comment by goyetus** [comment]
Now is fine.   The previous pull request was missing the Mk3s  Profiles.   Thanks!!

**Comment by SoftFever** [comment]
MK3 profile doesn't work properly.
Can you double check?

image

**Comment by goyetus** [comment]
Going to check,  sorry for the problem.

**Comment by goyetus** [comment]
Fixed.   

Added  resources / profiles / Prusa / machines / mk3s.json  and changed  
   
   "nozzle_diameter": "0.4",  
   
   TO
   
   "nozzle_diameter": "0.25;0.4;0.6;0.8",

**Review by SoftFever — APPROVED** [review]
Looks good
Thank you!

**Pull request merged**
