### PR TITLE
Italian translation

### PR DESCRIPTION
**Pull request by FabioForcina**
[https://github.com/Fabietto996/OrcaSlicer/blob/main/localization/i18n/it/OrcaSlicer_it.po](url)

### CODE REVIEW

**Comment by SoftFever** [comment]
@Fabietto996 can you take a look at the conflicts?

**Comment by FabioForcina** [comment]
> @Fabietto996 can you take a look at the conflicts?

I should have solved them

**Review by SoftFever — DISMISSED** [review]
Thanks

**Comment by SoftFever** [comment]
There are some errors in the translation.
Can you take a look?
Screenshot 2023-11-14 at 5 18 01 PM

**Review by SoftFever — APPROVED** [review]

**Comment by Pisuke74** [comment]
hi. how can I import in Mac version ? thanks

**Pull request merged**
