### PR TITLE
Initial port of organic tree support from PrusaSlicer

### PR DESCRIPTION
**Pull request by Noisyfox**
PS and BBL both got their ideal of tree support from Cura, but implemented differently, and PS implements the Organic support based on their tree support impl, which cannot be easily ported to BBL's tree support code base. Hens here I copied the entire tree/organic support code from PS and use it for Organic mode only, while still use the BBL's tree support impl otherwise.

The main motivation of adding the Organic support is that the Tree support has an annoying issue:
d31a7d4027d694026e6a54e7cdad8abe
aa427730474e01568d566c85b1d67188
Which does not present in Organic support:
image

#1436

### CODE REVIEW

**Comment by jeremytodd1** [comment]
Yesssss. Very excited for this as Organic Supports do work quite a bit better than Orca's current Tree Supports.

Nice work on all the stuff you've worked on for Orca, noisyfox!

**Comment by eugenmeltis3pg** [comment]
Yes, yes, and yes

**Comment by SoftFever** [comment]
I'm having difficulties to get the same result as in PS2.6
By checking the parameters, I found it uses different parameters than the slim trees e.g. branch angles
image

We can either adding more parameters, or simple get rid off the slim tree.
What's your opinion?
[rotated_3DBenchy.zip](https://github.com/SoftFever/OrcaSlicer/files/12454443/rotated_3DBenchy.zip)

**Comment by Noisyfox** [comment]
Yeah I noticed the same issue when modifying the https://github.com/SoftFever/OrcaSlicer/pull/1938/files#diff-7e7fd87409e62196ead25d347b0c2994c461d80d4b5d6a9abb5f371bfdc6eeb9 file, which I have to comment out some parameters (such as `support_tree_top_rate`) and share the same value for different parameters (such as the `support_tree_tip_diameter`) so it compiles.

PS has a lot more parameters for supports than Orca, however I don't want to add those extra complicity to Orca unless it's necessary. Since IMO one advantage of BBL (and Orca) is that it just work (even if it won't always gives you the best result possible), and PS just have too much parameters which makes it much harder to use.

**Comment by Noisyfox** [comment]
BTW I just found some mistakes when replacing PS's config with Orca's. Will update soon.

**Comment by Noisyfox** [comment]
I have an idea, I could add those missing parameters, but not showing them (for now) and use their default values. Then we could decide whether to let user tweaking them later.

**Comment by SoftFever** [comment]
> I have an idea, I could add those missing parameters, but not showing them (for now) and use their default values. Then we could decide whether to let user tweaking them later.

I agree.
I would say: just port all the parameters, but add a `_organic` suffix if there's name conflicts.
We can decide what parameter to display and hide depends on the selection of tree style.

**Comment by SoftFever** [comment]
> They share most of the parameters in common (though named differently), any particular reason of the duplication?

Sorry for the confusion caused by my previous comment.
I was referring to the organic tree related parameters. In case we already have that parameter name but it's used differently in the slim tree, we can add a new one with a suffix

**Comment by eugenmeltis3pg** [comment]
I'm all for getting rid of slim trees, if it means getting better organic supports

**Comment by Noisyfox** [comment]
> I'm all for getting rid of slim trees, if it means getting better organic supports

 What about the strong tree and hybrid tree then?

**Comment by eugenmeltis3pg** [comment]
> > I'm all for getting rid of slim trees, if it means getting better organic supports
> 
> What about the strong tree and hybrid tree then?

Hmm I've never really used them. But maybe paying around with the organic parameters we could have something like "organic strong"?

For me the use case for strong trees is when you need to make sure that the supports hold, and not fall down.

**Comment by Noisyfox** [comment]
I think for now I'd prefer to keep the existing tree supports, until we are confident enough that Organic support will always yield a better result.

**Comment by eugenmeltis3pg** [comment]
> 

Yes, doubling the support wall would be nice.

@Noisyfox @SoftFever what do you thing about having a Orca build only with some parameters exposed in the UI (am official one), and another Alpha/Beta/Experimental/whatever where you expose the rest of the parameters so users, like me, can play around with them and provide feedback on?

**Comment by Noisyfox** [comment]
> > 
> 
> Yes, doubling the support wall would be nice.
> 
> @Noisyfox @SoftFever what do you thing about having a Orca build only with some parameters exposed in the UI (am official one), and another Alpha/Beta/Experimental/whatever where you expose the rest of the parameters so users, like me, can play around with them and provide feedback on?

I think I could set those parameters as advanced so it will be hidden unless user turned on advance mode.

**Comment by eugenmeltis3pg** [comment]
> > > 
> > 
> > 
> > Yes, doubling the support wall would be nice.
> > @Noisyfox @SoftFever what do you thing about having a Orca build only with some parameters exposed in the UI (am official one), and another Alpha/Beta/Experimental/whatever where you expose the rest of the parameters so users, like me, can play around with them and provide feedback on?
> 
> I think I could set those parameters as advanced so it will be hidden unless user turned on advance mode.

Yes, sounds good to me

**Comment by YanceyA** [comment]
Agree with Eugen, for testing it would be good to have all the organic support parameters exposed for testing/tuning. It would also be good to have these parameters use the default values from PS. From my perspective, given the same default parameters PS and OS should produce the same supports.

I had a play last night and OS organic support with default values was producing way too much support interface (and placing this interface in free space) and several branches failed to complete (that is that abruptly stopped without continuing up to meet the support interface). I need to play a lot more and give some good feedback.

For me, the tough benchmark file will be the Cura dragon pencil cup and this will be what my initial evaluation will be using.
https://www.thingiverse.com/thing:6069926

Regardless I am very happy with the work!

**Comment by Noisyfox** [comment]
Currently the organic support shares 3 parameters with the existing tree support, which may/may not have the same default as PS, because I don't want to update the default value of those parameters at the moment because there might be user that does not use advance mode which have no knowledge of those parameters and suddenly the tree support works differently if those parameters are changed.

Also keep in mind the results are also affected by parameters such as your extruder/filament/layer height/etc. settings so make sure those parameters are all set to the same before comparing the result between Orca and PS.

**Comment by eugenmeltis3pg** [comment]
I also had some time to play with this, and my observations are also about the support interfaces. 

But then again, I never really liked the existing style of support, so if it is shared, that could be the case

**Comment by eugenmeltis3pg** [comment]
@Noisyfox Tried the latest build and I get this on mac (x86_64):
image

**Comment by Noisyfox** [comment]
> @Noisyfox Tried the latest build and I get this on mac (x86_64): image

Mac build seems to be broken recently...

**Comment by Noisyfox** [comment]
> In case we already have that parameter name but it's used differently in the slim tree, we can add a new one with a suffix

There is one such parameter actually, the `tree_support_branch_distance`. Going to fix that soon.

**Comment by Noisyfox** [comment]
I think the three shared parameters have the same meaning in PS and Orca. It should be good for another PR build now so more people can play around with it.

**Comment by YanceyA** [comment]
@Noisyfox  I've replicated your findings on the two test models (dragon cup and xeno). PS and OS organic supports are nearly identical with the same settings. 

The supports on the floating mobius strip are nice too:
image

Unfortunately i won't be able to do any test prints until next week but the support generation seems to be working well. with this build, i am also not getting weird interface generation as mentioned previously.

**Comment by eugenmeltis3pg** [comment]
@Noisyfox is it possible to have a setting to expand/make bigger the support brim for the organics? 

It's an issue I also saw in PS with some organic supports coming loose from the build plate due to not enough contact area.

So a setting to controll that would be really nice

**Comment by Noisyfox** [comment]
> @Noisyfox is it possible to have a setting to expand/make bigger the support brim for the organics?
> 
> It's an issue I also saw in PS with some organic supports coming loose from the build plate due to not enough contact area.
> 
> So a setting to controll that would be really nice

Will take a look at this soon.

**Comment by Noisyfox** [comment]
> @Noisyfox is it possible to have a setting to expand/make bigger the support brim for the organics?
> 
> It's an issue I also saw in PS with some organic supports coming loose from the build plate due to not enough contact area.
> 
> So a setting to controll that would be really nice

2a156f11f0114d5496ed3d78cdcc69c7
Got you covered :P

**Comment by eugenmeltis3pg** [comment]
> > @Noisyfox is it possible to have a setting to expand/make bigger the support brim for the organics?
> > It's an issue I also saw in PS with some organic supports coming loose from the build plate due to not enough contact area.
> > So a setting to controll that would be really nice
> 
> 2a156f11f0114d5496ed3d78cdcc69c7 Got you covered :P Turned out those settings were hidden under the Raft section which affect not only the raft but also the grid/snag supports (and also the organic support). Not sure why Bambu did this. Now they are moved to where they should be.

Dude, you're just amazing. Period

**Comment by YanceyA** [comment]
> Is it possible to change the default style of tree support to point to organic? Currently, it points to "Tree hybrid" I believe.

I think this decision should be made after the beta has been used for a while and there is wider feedback that the Organic is a better choice than Slim Trees as a general case for everyone. My opinion is that it should be, but I think the feedback should be gathered first. Changing defaults is always risky as it will strongly affect less sophisticated users with sudden errant behavior which they don't understand.

**Comment by Noisyfox** [comment]
> > Is it possible to change the default style of tree support to point to organic? Currently, it points to "Tree hybrid" I believe.
> 
> I think this decision should be made after the beta has been used for a while and there is wider feedback that the Organic is a better choice than Slim Trees as a general case for everyone. My opinion is that it should be, but I think the feedback should be gathered first. Changing defaults is always risky as it will strongly affect less sophisticated users with sudden errant behavior which they don't understand.

Agreed

**Comment by HahBikes** [comment]
> > Is it possible to change the default style of tree support to point to organic? Currently, it points to "Tree hybrid" I believe.
> 
> I think this decision should be made after the beta has been used for a while and there is wider feedback that the Organic is a better choice than Slim Trees as a general case for everyone. My opinion is that it should be, but I think the feedback should be gathered first. Changing defaults is always risky as it will strongly affect less sophisticated users with sudden errant behavior which they don't understand.

Yeah, that makes sense. Unless it's widely tested, we can hold off on the default settings for now I guess. 
The only reason I was asking for this change was that if you normally have the tree (auto) setting selected for your profile, and want to change it to tree (manual) for some specific prints, the moment you make that change the tree style now changes to "Default" automatically ( even though I had organic selected). It would be great if somehow it respects the changes I have already made and does not change to the "Default" tree style when I make the switch from tree (auto) to tree (manual).

I hadn't noticed that it automatically changed the tree style to "Default" and was getting the old tree supports instead of the organic ones and got confused. But anyway, this is a minor inconvenience at best.

**Comment by Noisyfox** [comment]
> It would be great if somehow it respects the changes I have already made and does not change to the "Default" tree style when I make the switch from tree (auto) to tree (manual).

That's a good point, I'll take a look soon.

**Comment by SoftFever** [comment]
@Noisyfox Nicely done!
I played it around for a while, and the tree generation behavior is consistent with what I got from PrusaSlicer.
It's good to merge on my side.
Do you have other things you plan to change?

PS, do you mind to add disclaimers in the beginning of those source code files?

**Comment by SoftFever** [comment]
Seems PrusaSlicer has just added copyright message in all the source code files a few hours ago [final copyright headers](https://github.com/prusa3d/PrusaSlicer/commit/f32859c302a5d8d00f557808d8d758ba63c1bbf3).
It would be great we include that message.

**Comment by Noisyfox** [comment]
> Seems PrusaSlicer has just added copyright message in all the source code files a few hours ago [final copyright headers](https://github.com/prusa3d/PrusaSlicer/commit/f32859c302a5d8d00f557808d8d758ba63c1bbf3). It would be great we include that message.

Done

**Review by SoftFever — APPROVED** [review]
Well done!

**Comment by SoftFever** [comment]
Awesome, merged!

**Pull request merged**
