### PR TITLE
AnkerMake profile updates

### PR DESCRIPTION
**Pull request by just-trey**
Resubmitting per request.

This update provides many more profile options and includes the new AnkerMake M5C printer. These profiles are based on some thoroughly tested and popular Prusa Slicer profiles I maintain for the community at https://github.com/Ankermgmt/prusaslicer-ankermake-ce-profiles. If you have any questions or see any improvements needed, please let me know.

### CODE REVIEW

**Comment by SoftFever** [comment]
@just-trey 

Can we keep the printer/profile/filament name and it's file names unchanged?
Otherwise existing user settings based on these profiles will not work anymore.

**Comment by just-trey** [comment]
@SoftFever, I have reverted back to the naming convention requested. Something for you to note. You will see new temperatures on some filaments and some filaments removed from the support of the M5. The Ankermake printer beds top out at 100°. The M5 is a PTFE-lined hotend with an all-metal hotend coming in the future, so I removed support for the hotter filaments as a safety measure. the M5C has an all-metal hotend already and supports up to 300°

**Comment by SoftFever** [comment]
Reopen it as it was accidently closed.

Thank you.
I will review it

**Comment by SoftFever** [comment]
Oops, it was automatically closed.
Looks like your repo is forked from BS instead of Orca, seem's GitHub don't allow PR because of this.

**Pull request closed without merging**
