### PR TITLE
Updated internal bridging flow change and reverted bridge PR

### PR DESCRIPTION
**Pull request by igiannakas**
As per feedback from @SoftFever - this PR fixes review comment on https://github.com/SoftFever/OrcaSlicer/pull/2859 and reverts unneeded code.

### CODE REVIEW

**Review by SoftFever — APPROVED** [review]
Looks good.
Thank you!

**Comment by igiannakas** [comment]
@SoftFever you may want to add this to the release 1.8 branch as that branch contains the old logic?

**Comment by SoftFever** [comment]
Let me know if you found anything wrong in the commit. 
I haven't got time to test 1.8 thoroughly yet.

**Comment by igiannakas** [comment]
Ah my bad, I just noticed. Apologies for the confusion… haven’t had much time either to test the 1.8.1 - using 1.9 at the moment :)

**Pull request merged**
