### PR TITLE
reordering and renaming certain menu items

### PR DESCRIPTION
**Pull request by discip**
# Description

With this PR I tried to unify the behavior and appearance of the menu structure so that the entry that controls others is above them.
I hope that makes sense. 😊

# Screenshots/Recordings/Graphs

before||after
-:|-|:-
image||image
||
image||image
||
image||image
||
image||image

The colored markings are only to indicate the different placement. 😊

### CODE REVIEW

**Comment by Noisyfox** [comment]
This makes a lot more sence to me, cool!

**Comment by discip** [comment]
Glad you see it that way too. 😊

**Comment by discip** [comment]
@Noisyfox
> This makes a lot more sence to me, cool!

Glad you see it that way too. 😊

**Comment by Ergonomicmike** [comment]
It's too late to add this idea now that all checks have passed. But perhaps for a next time? (I had posted this in early August, but it's gone now.)  There is one more item to "unify."

The Compare presets feature is not in the same visual order as the Presets to compare. In the Presets, it's Printer at the top, Filament in the middle, and Process at the bottom. Whereas in the Compare presets window, it's Process at the top and Printer at the bottom. (See screen shot.) I am guessing that two lines of code could be swapped to unify this?

Ergonomic improvement Orca compare feature

**Comment by discip** [comment]
@Ergonomicmike
I finally found the part of code that needed to be changed to meet your request. 😊

This is how it looks now:

image


@SoftFever
Since this is about unifying the order of entries, I hope it's OK to include that here as well.
Please let me know if this is ok.

**Comment by Ergonomicmike** [comment]
@discip Cool! Thanks!

I can see where the printer, filament, material entries were swapped and I could have hacked that part myself. (But I don't know how to do a PR.) But I would totally have missed changing the order of things at line 1845. Glad to have experts here.

**Comment by Hammerfest** [comment]
I know logic isn't everything, but it always broke my brain the out of order option hierarchy

As someone who prefers the tree style visual layout of old, at least this brings some order to the chaos and its much appreciated, always jarring to see options above others that if not set mean they don't actually do anything (hence the tree layout comment)

Experience: I actually fumbled over skirt loops and a few others when I first started a short time ago, wondering why they didn't work

**Comment by discip** [comment]
@Ergonomicmike

> Glad to have experts here.

# 🤣
I'm by no means an expert! I just searched for the specific term and tried changing what ever seemed to fit until it worked. 😊

> But I would totally have missed changing the order of things at line 1845.

This is the line that actually made the change.
And in the interest of uniformity, I left the changes in the other lines as they do not seem to be disruptive.

**Comment by discip** [comment]
@Ergonomicmike

> Glad to have experts here.

# 🤣
By no means I'm an expert! I just searched for the specific term and tried changing what ever seemed to fit until it worked. 😊

> But I would totally have missed changing the order of things at line 1845.

This is the line that actually made the change.
And in the interest of uniformity, I left the changes in the other lines as they do not seem to be disruptive.

**Review by Noisyfox — APPROVED** [review]
LGTM

**Pull request merged**
