### PR TITLE
Feature/merge 1.8.4

### PR DESCRIPTION
**Pull request by SoftFever**

### CODE REVIEW

**Comment by Eldenroot** [comment]
OK, this "Plate type" button is not working - should redirect you to the wiki

image

**Comment by Eldenroot** [comment]
Also I think the button should be next to the "OK" "Cancel", now it is reverted back to the top :(

image

**Comment by SoftFever** [comment]
> Also I think the button should be next to the "OK" "Cancel", now it is reverted back to the top :(
> 
> image

Hmm, I double-checked, and it's the same as 1.9.  
It would be better to put the button at the bottom, but I can live with the current layout. 😉

**Comment by SoftFever** [comment]
> OK, this "Plate type" button is not working - should redirect you to the wiki
> 
> image

I will add back the link once the WIKI is ready

**Comment by tsmith35** [comment]
This build causes the application to crash under Windows 10 x64. Details below...

May have something to do with the network plugin, since this build uses a different version than what was used with [PR3802](https://github.com/SoftFever/OrcaSlicer/pull/3802)

Details:
Just grabbed this build for Windows 10 x64 and got an unhandled unknown exception when I click the edit link for the first filament (the orange one) or any other. Event viewer for the crash (running PR3909, which also crashes) was this:

Faulting application name: orca-slicer.exe, version: 1.0.0.0, time stamp: 0x65ba279c
Faulting module name: OrcaSlicer.dll, version: 0.0.0.0, time stamp: 0x65ba2792
Exception code: 0xc000041d
Fault offset: 0x0000000002b735d0
Faulting process id: 0x765c
Faulting application start time: 0x01da569ee641fc48
Faulting application path: C:\Program Files\OrcaSlicer\orca-slicer.exe
Faulting module path: C:\Program Files\OrcaSlicer\OrcaSlicer.dll
Report Id: fadaa8ef-97ac-4500-b8de-c6999b751036
Faulting package full name: 
Faulting package-relative application ID: 

and from the appcrash .wer file:

Sig[0].Name=Application Name
Sig[0].Value=orca-slicer.exe
Sig[1].Name=Application Version
Sig[1].Value=1.0.0.0
Sig[2].Name=Application Timestamp
Sig[2].Value=65ba279c
Sig[3].Name=Fault Module Name
Sig[3].Value=OrcaSlicer.dll
Sig[4].Name=Fault Module Version
Sig[4].Value=0.0.0.0
Sig[5].Name=Fault Module Timestamp
Sig[5].Value=65ba2792
Sig[6].Name=Exception Code
Sig[6].Value=c000041d
Sig[7].Name=Exception Offset
Sig[7].Value=0000000002b735d0

image

This appears to affect earlier versions as well. I reinstalled the PR3802 build and it's back to normal. I did notice that when I rolled back, it downloaded the network plugin again. When I'd installed this build, it said it needed to update the network plugin. Perhaps that has something to do with it?

**Pull request merged**
