### PR TITLE
Fix regression in AnkerMake profiles

### PR DESCRIPTION
**Pull request by Patnnn**
Reverting the changes that got introduced with the merge request https://github.com/SoftFever/OrcaSlicer/pull/7117.

This should fix https://github.com/SoftFever/OrcaSlicer/issues/7633

In addition, this PR swaps the jerk setting from the machine limits tab and the print profile. These were accidentally swapped when @Xelinor initially created these profiles. This should remove the warning that the jerk settings exceed the printer limits.

### CODE REVIEW

**Comment by robertbaker** [comment]
The actual issue is the values between the M5 and M5C are different and so while this fixes the M5C, the M5 doesn't have this problem and is now limited by the M5C. Instead of a common profile, both printers need their own settings.

Compare the values yourself in anker's studio by adding a M5 and looking at the values compared to the M5C. You'll see that both printers have different values.

A proper solution would be introducing the proper values for both instead of just reverting and having the M5 use the M5C values which are not ideal for that printer.

**Comment by robertbaker** [comment]
also just an FYI. Instead of making a new commit for a revert, it's proper and much better just to do a git revert instead of changing the values in a new commit.

**Comment by robertbaker** [comment]
M5C  4 extruder
M5  4 extruder

M5c  2 extruder
m5  2 extruder

M5c  8 extruder
M5  8 extruder

M5c  6 extruder
M5  6 extruder

**Comment by robertbaker** [comment]
https://github.com/ankermake/AnkerMake-PrusaSlicer-Release/blob/main/AnkerStudio/resources/profiles/Anker-ini/AnkerMake%20base/base.ini

**Comment by Noisyfox** [comment]
How on earth does a 3mm retraction is ever needed for a DDE printer?

**Comment by Xelinor** [comment]
> How on earth does a 3mm retraction is ever needed for a DDE printer?

It isn't. Anker's values in their slicer are not a trustworthy source.

**Comment by robertbaker** [comment]
Thank you @Xelinor for the info. I submitted a PR to revert the change. It worked fine for the M5 and since the M5C has identical values, I had no idea it would cause such an issue for the M5C.

**Comment by Xelinor** [comment]
> @Xelinor in that case it's better for git purposes to revert the commit first and modify or make a new PR with that change. It's just better for git history and other reasons to do it that way.

Yep, no, I totally agree with you there

**Comment by robertbaker** [comment]
@Xelinor if you could tell me what to change I can do that PR now unless @Patnnn wants to do it. I don't mind either way.

**Comment by Xelinor** [comment]
> @Xelinor if you could tell me what to change I can do that PR now unless @Patnnn wants to do it. I don't mind either way.

It's fine, looking at the way @Patnnn submitted it, it's not quite correct either, I'll take some time tonight and get a submission done to finally get this off my to-do list. Jerk can probably be set a bit higher for fast mode then for the non-fast mode profiles, so that needs to be adjusted and validated too, and I have the files already set up to do the test prints so I'll just do that and make the changes.

**Comment by Patnnn** [comment]
> also just an FYI. Instead of making a new commit for a revert, it's proper and much better just to do a git revert instead of changing the values in a new commit.

Thanks for the info. It was my first GitHub commit ever. So I'm not really have any experience on how to do this correctly. I will close this PR for now

**Pull request closed without merging**
