### PR TITLE
Ender 3 V3 : Some improvements for supports and machines limits

### PR DESCRIPTION
**Pull request by bistory**
@Orel-A suggested in #4225 some improvements for Ender 3 V3 KE and SE
I don't have those machines anymore but I can trust him so I changed some parameters.

Thanks !

### CODE REVIEW

**Comment by Orel-A** [comment]
Why support_interface_top_layers has been set to 4? I'm not sure about this.
The other changes look okay.

**Comment by bistory** [comment]
> Why support_interface_top_layers has been set to 4? I'm not sure about this. The other changes look okay.

It depends on the layer height, for thin layers, interfaces can sag and give bad results, hence the increased number of layers :-)

**Comment by Orel-A** [comment]
I see.
BTW, why there is such disparity between the V3 SE's z-hop which shows a value of 0.4 and the V3 KE that gives 0.1 ?

**Comment by bistory** [comment]
> I see. BTW, why there is such disparity between the V3 SE's z-hop which shows a value of 0.4 and the V3 KE that gives 0.1 ?

It's Creality Print values :-)
I can increase that value to 0.2, this should avoig knocking parts when printing ;-)

**Comment by Orel-A** [comment]
Yes, but you know as well as I do that some settings in Creality Print don't make sense.

Okay, one last thing for the V3 KE is the Jerk settings.
In Orca there is a permanent "WARNING: Jerk settings exceeds the printer's maximum."
Indeed, a jerk of 30mm/s seems a bit too much.
Can you look into this?

**Comment by bistory** [comment]
> Yes, but you know as well as I do that some settings in Creality Print don't make sense.
> 
> Okay, one last thing for the V3 KE is the Jerk settings. In Orca there is a permanent "WARNING: Jerk settings exceeds the printer's maximum." Indeed, a jerk of 30mm/s seems a bit too much. Can you look into this?

Yes I know but I didn't check every settings one by one so good find ;-)
I changed jerk settings, if you are able to test, please do !

**Comment by Orel-A** [comment]
20mm/s???
Even the K1C only has a max of 12mm/s.
My bedslinger would fly off if I test this!

**Comment by Orel-A** [comment]
I'm currently testing the new settings. The z-hop of 0.2 has a bit of webbings on eSun PLA+, but my filament is a bit wet.
We need to find a balance, not too much jerk... I've reduced the z-hop to check the cause, there is a bit of scraping of the nozzle on the filament with 0.1 so it's too low.
I think the z-hop should be reduced to 0.16.
And the Jerk settings to these:
default: 9
outer wall: 7
inner wall: 7
infill: 9
top surface: 7
first layer: 8
Travel: 10

**Comment by Orel-A** [comment]
I'm still testing. Sorry for the late update.
7mm/s seems too low. Klipper uses the jerk for the Square Corner Velocity.

My print is still running, I'll do another with these settings soon:
default: 9
outer wall: 8
inner wall: 8
infill: 9
top surface: 8
first layer: 8
Travel: 9

The z-hop's new value of 0.16 seems to be fine for me.

**Review by Orel-A — CHANGES_REQUESTED** [review]
So I finished my tests, please change the jerk settings to these:
default: 9
outer wall: 8
inner wall: 8
infill: 9
top surface: 8
first layer: 8
Travel: 9

**Comment by bistory** [comment]
Generally, for travels, we seek the highest possible speed...

**Comment by Orel-A** [comment]
When I set it to 10mm/s it felt wrong.
The sweet spot is 9mm/s, that's the fastest without too much vibration, I think.
7mm/s is slowing the corners, too slow.
I guess we can roll with 10mm/s on travel since we upped the z-hop...
Yeah, if we want to not lose speed without reason then, these settings are more logical:
default: 9
outer wall: 9
inner wall: 9
infill: 9
top surface: 9
first layer: 9
Travel: 10
What do you think?

**Comment by bistory** [comment]
> When I set it to 10mm/s it felt wrong. The sweet spot is 9mm/s, that's the fastest without too much vibration, I think. 7mm/s is slowing the corners, too slow. I guess we can roll with 10mm/s on travel since we upped the z-hop... Yeah, if we want to not lose speed without reason then, these settings are more logical: default: 9 outer wall: 9 inner wall: 9 infill: 9 top surface: 9 first layer: 9 Travel: 10 What do you think?

I would reduce SQV for outer wall but increase it for infill (quality loss for infill is not important), so I would say :

default: 10
outer wall: 8
inner wall: 9
infill: 10
top surface: 9
first layer: 9
Travel: 10

What do you think ?

**Comment by Orel-A** [comment]
I'm sorry but there is a nasty vibration with these settings.
Maybe I damaged my printer, too much wobble on the bedslinger, with 7mm/s it's fine, no wobble.
I'll test again with 9-8mm/s again shortly...

**Comment by bistory** [comment]
> I'm sorry but there is a nasty vibration with these settings. Maybe I damaged my printer, too much wobble on the bedslinger, with 7mm/s it's fine, no wobble. I'll test again with 9-8mm/s again shortly...

Vibrations don't necessarily mean bad :-)
But it seems strange because with previous settings (jerk to 10), I had no vibrations problems at all :-)

**Comment by Orel-A** [comment]
No, I find it quite logical. You see, even with liner rails the bambu lab a1 has a limit of 9mm/s.
The creality Y-axis has liner rods which have a bit of tolerance, and should not be as good.
I tested again, 8mm/s has a bit of wobble.
I tried to disable the jerk settings with setting zero on the default jerk and putting 7mm/s on the Y-axis on the global printer settings.
But this gave me 5mm/s when I actually run the print on Mailsail...
Do you have any idea how to only limit the Y-axis safely?

**Comment by bistory** [comment]
> No, I find it quite logical. You see, even with liner rails the bambu lab a1 has a limit of 9mm/s. The creality Y-axis has liner rods which have a bit of tolerance, and should not be as good. I tested again, 8mm/s has a bit of wobble. I tried to disable the jerk settings with setting zero on the default jerk and putting 7mm/s on the Y-axis on the global printer settings. But this gave me 5mm/s when I actually run the print on Mailsail... Do you have any idea how to only limit the Y-axis safely?

I don't think it's possible without having a warning from Orca :-)

**Comment by Orel-A** [comment]
By the way, the V3 SE has the same frame and the same motors.
Jerk settings on Travel, first layer and default were set to 8mm/s.
But Marlin as a different approach to jerk settings, no?

**Comment by bistory** [comment]
> By the way, the V3 SE has the same frame and the same motors. Jerk settings on Travel, first layer and default were set to 8mm/s. But Marlin as a different approach to jerk settings, no?

Yes it has, "Jerk" setting for Klipper is used to set Square Corner Velocity with Orca.

https://www.reddit.com/r/klippers/comments/vse7ir/so_what_exactly_is_square_corner_velocity_and_how/

I don't remember if Creality has set that setting in the printer.cfg
Maybe they did so we can use it as the maximum value

**Comment by Orel-A** [comment]
I opened my printer.cfg, this is what I found:
```
[printer]
kinematics: cartesian
max_velocity: 500
max_accel: 8000
max_accel_to_decel: 2500
max_z_velocity: 30
square_corner_velocity: 5.0
max_z_accel: 300
```
I don't think the firmware uses this?

**Comment by bistory** [comment]
> I opened my printer.cfg, this is what I found:
> 
> ```
> [printer]
> kinematics: cartesian
> max_velocity: 500
> max_accel: 8000
> max_accel_to_decel: 2500
> max_z_velocity: 30
> square_corner_velocity: 5.0
> max_z_accel: 300
> ```
> 
> I don't think the firmware uses this?

Ok, they didn't change the default value.
Then we should maybe use more conservative values like you did.

default: 9
outer wall: 7
inner wall: 8
infill: 9
top surface: 9
first layer: 9
Travel: 9

**Comment by Orel-A** [comment]
No, let me test this a bit more.
I think the problem is with the states that have 5000mm/s acceleration
Which are default, inner wall, and top surface (?)
I'm checking...

**Comment by Orel-A** [comment]
So, I'm printing a cog, but without filament. That's my test bed.
And Inner Wall is problematic because of 300mm/s speed and 5000mm/s2 acceleration.
The Outer Wall isn't problematic because its settings are more tame.
I think this printer isn't tuned well enough...

**Comment by bistory** [comment]
> So, I'm printing a cog, but without filament. That's my test bed. And Inner Wall is problematic because of 300mm/s speed and 5000mm/s2 acceleration. The Outer Wall isn't problematic because its settings are more tame. I think this printer isn't tuned well enough...

What kind of problems do you see ?

**Comment by Orel-A** [comment]
When it finishes the first layer, during inner wall printing if I don't limit the jerk to 7mm/s, it will cause the bed to vibrate.

**Comment by Orel-A** [comment]
Let's do this, we will set a hard limit to all jerk settings to 7mm/s and speed up the Outer Wall a bit.
At first I thought the wall printing was slow due to the reduced jerk settings, this is not the case.
What do you think?

**Comment by bistory** [comment]
> Let's do this, we will set a hard limit to all jerk settings to 7mm/s and speed up the Outer Wall a bit. At first I thought the wall printing was slow due to the reduced jerk settings, this is not the case. What do you think?

It sounds good to me !

So

default: 7
outer wall: 8
inner wall: 7
infill: 8
top surface: 7
first layer: 7
Travel: 8

?

**Comment by Orel-A** [comment]
Yes, that's fine.
How should we speed up the Outer Wall's speed and acceleration?
I think we can safely increase the speed to 250mm/s
What about the acceleration though?

**Comment by bistory** [comment]
> Yes, that's fine. How should we speed up the Outer Wall's speed and acceleration? I think we can safely increase the speed to 250mm/s What about the acceleration though? 2500mm/s2?

It should be safe :-)

**Review by Orel-A — APPROVED** [review]
Looks good to me. There is a slight vibration on infill but that's fine.

**Comment by bistory** [comment]
> Looks good to me. There is a slight vibration on infill but that's fine.

Ok! Thanks for your help, we can consider this ready to merge ;-)

**Comment by SoftFever** [comment]
Awesome
@bistory @Orel-A  Thank you both 👍

**Review by SoftFever — APPROVED** [review]

**Pull request merged**
