### PR TITLE
Update Wiki

### PR DESCRIPTION
**Pull request by igiannakas**
# Description

Wiki updates - slowly populating the wiki with settings explanations, tips and tricks for how to set them.

### CODE REVIEW

**Comment by igiannakas** [comment]
@SoftFever whets the best way to contribute to the wiki? I’d love to do a bit of a cleanup and push some documentation pages drawing from the discord community interactions etc?

 Think it would make the project more complete and less reliant on other sources to figure out what the print settings mean and do :)

**Comment by SoftFever** [comment]
> @SoftFever whets the best way to contribute to the wiki? I’d love to do a bit of a cleanup and push some documentation pages drawing from the discord community interactions etc?
> 
> Think it would make the project more complete and less reliant on other sources to figure out what the print settings mean and do :)

That's fantastic!
I will start looking for an alternative option to host WIKI as I found the GitHub WIKI has very limited feature especially for the collaboration part. I'll give [miraheze](https://meta.miraheze.org/wiki/Miraheze_Meta) a try, it looks awesome and open source too, if you have other suggestions , please let me know!

Unit then, we can keep this way.

**Review by SoftFever — APPROVED** [review]
This looks much better!
Thank you!

**Comment by igiannakas** [comment]
Awesome thank you!

**Comment by igiannakas** [comment]
Ps. Links on the main wiki page don’t work eg the below. How would I fix them? Sorry complete newbie with the wiki component :(


**Quality Settings**

Layer Height Settings  
Line Width Settings  
Seam Settings  
Precise wall

**Speed Settings**

Extrusion rate smoothing

**Comment by SoftFever** [comment]
> Ps. Links on the main wiki page don’t work eg the below. How would I fix them? Sorry complete newbie with the wiki component :(
> 
> **Quality Settings**
> 
> Layer Height Settings Line Width Settings Seam Settings Precise wall
> 
> **Speed Settings**
> 
> Extrusion rate smoothing

The linked WIKI page file has to be in the same folder.
In short, GitHub WIKI doesn't support subdirectory...

**Comment by igiannakas** [comment]
Ok that is annoying!! Cool I’ll raise a pr to fix the links ;)

**Pull request merged**
