### PR TITLE
Deleted unused Hotend models & updated profiles

### PR DESCRIPTION
**Pull request by yw4z**
I tried all machines and none of them show hotend model on viewport on sliced object. orca always shows generic hotend
Deleted all hotend models and updated their profiles. Models took about 4MB> storage
Also there is a problem on wanhoo profile. its asking to add G92 E0 to layer change code

### CODE REVIEW

**Comment by SoftFever** [comment]
@yw4z 
Thanks, Orca should support custom hotend.
It might be a regression bug. I will take a look and fix it.

**Comment by yw4z** [comment]
no problems, just shared. i thought it was an abandoned feature

**Comment by SoftFever** [comment]
It's working fine.
image

**Comment by SoftFever** [comment]
> no problems, just shared. i thought it was an abandoned feature

Thanks.
I will close this PR hence

**Pull request closed without merging**
