### PR TITLE
Falashforge 5M network support

### PR DESCRIPTION
**Pull request by iherbak**
The build_orca.yml should not be merged as it is tailored to my repo, but the rest of the commits

Thanks

### CODE REVIEW

**Comment by iherbak** [comment]
Hi,
I reverted the files for easy merge.

Regards,
István

**Comment by Noisyfox** [comment]
LGTM

**Comment by SoftFever** [comment]
I have started the build.

Looking for testers who have this machine to test.

**Comment by jaimbo** [comment]
> I have started the build.
> 
> Looking for testers who have this machine to test.

I can give it a go

**Comment by jaimbo** [comment]
Adding printer works correctly, uploading sending gcode over the network also working correctly.

When specifying a directory for the uploaded gcode, this seems to be ignored by the printer and the file is put into the root of the onboard storage. The gcode still appears to be working but when a direcory is added, the printer won't show a working preview of the print on the screen.

Connection Success

**Comment by glizzyglizz69** [comment]
> I have started the build.
> 
> Looking for testers who have this machine to test.

I'm available to test - Just installed

**Comment by SoftFever** [comment]
> Adding printer works correctly, uploading sending gcode over the network also working correctly.
> 
> ~When specifying a directory for the uploaded gcode, this seems to be ignored by the printer and the file is put into the root of the onboard storage. The gcode still appears to be working but when a direcory is added, the printer won't show a working preview of the print on the screen.~
> 
> Connection Success
> 
> EDIT: Correction, when you specify slashes in the gcode to upload, if you choose to only upload (not print) the file will not appear in the printers onboard storage. If you choose upload and print, the printer will act like it is starting a print, it will say it's preheating but the nozzle/bed doesn't appear to be heating and if you go to the print info, there are no details there. As above, the file will also be missing from the onboard storage.Seems directories aren't currently working in any fashion.
> 
> image image

Does it work if you don't change the upload folder?
Many klipper system don't support uploading g-code to a subfolder.

I don't have this machine. 
So I leave @iherbak @FlashforgeOfficial to answer.

**Comment by jaimbo** [comment]
> Does it work if you don't change the upload folder? Many klipper system don't support uploading g-code to a subfolder.
> 
> I don't have this machine. So I leave @iherbak @FlashforgeOfficial to answer.

Yes, it works correctly if you don't specify a subfolder.

There doesn't seem to be any manual way to create a folder on the internal storage either, though the UI on the screen for starting a print will show/print from directories on a connected usb storage device.

@iherbak @FlashforgeOfficial If it's not possible to create a folder on the onboard storage, can we change filename window that appears to not suggest it? Would it also be possible to sanitize any slashes in the filenames so that the print will upload and start successfully if someone does try it?

Also, this might not be the correct place for this, but it would be handy if you could choose to level the bed before starting the print on OrcaSlicer, just like you can when starting print from the screen.

**Comment by iherbak** [comment]
Based on the experience with Flashprint.
On file upload it is disabled to input backslash in the file upload dialog,
so I guess this is not supported at all on the Flashforge's firmware

**Review by SoftFever — APPROVED** [review]
Looks good
Thank you

**Comment by SoftFever** [comment]
> > Does it work if you don't change the upload folder? Many klipper system don't support uploading g-code to a subfolder.
> > I don't have this machine. So I leave @iherbak @FlashforgeOfficial to answer.
> 
> Yes, it works correctly if you don't specify a subfolder.

Thanks

**Pull request merged**
