### PR TITLE
Elegoo cfg pr

### PR DESCRIPTION
**Pull request by ELEGOOTechSupport**
[Build all](https://github.com/ELEGOO-Slicer/OrcaSlicer_PR/actions/workflows/build_all.yml)
# Description

>1. This PR removes the Orcaslicer's original ELEGOO model configuration and its print parameters.
>2. The PR adds all the current ELEGOO manufacturer's model configurations and their print parameters.
>3. This PR version of Orcaslicer has been tested for installation slice printing.

# Screenshots/Recordings/Graphs

>The main changes were made to all Elegoo models, as shown below:
>企业微信截图_6e03e15b-b957-450c-a61a-0d018aaaa78c
>企业微信截图_51b8bc82-ac59-486e-992a-6b0f2f12bd62
>企业微信截图_ef621bf2-1e40-4564-bdaa-6da03303e52e
>企业微信截图_5eaac8d1-8c49-4a76-85d3-0077c26f7e93
>企业微信截图_4d1fbc90-eb32-4c61-9230-fd8dc45a9123

## Tests

>This PR has made a big change to the Elegoo model configuration and has completely replaced the previous Elegoo model configuration, meaning that if the PR is merged and the user installs this version of Orcaslicer, they will lose the previous project files saved after using Elegoo model slicing (only for Elegoo models).

### CODE REVIEW

**Comment by ELEGOOTechSupport** [comment]
@SoftFever 
Dear OrcaSlicer writer, hello!
I'm a tech support. I love using Orcaslicer, it gives us a lot of useful features. This time PR has made a lot of changes to the Elegoo machine configuration, and also introduced more printing configurations. I hope that this PR can be merged. If there is any problem with this PR, please contact me for further modification. Thank you very much!

**Comment by SoftFever** [comment]
@ELEGOOTechSupport 
Thanks :)

There is an error in the profile, can you take a look?

```
Run ./OrcaSlicer_profile_validator -p /home/runner/work/OrcaSlicer/OrcaSlicer/resources/profiles -l 2
[202[4](https://github.com/SoftFever/OrcaSlicer/actions/runs/11426755306/job/32019704291?pr=7170#step:4:5)-10-24 16:05:16.363609] [0x00007f43631a2740] [trace]   Initializing StaticPrintConfigs
Error: 0-24 16:0[5](https://github.com/SoftFever/OrcaSlicer/actions/runs/11426755306/job/32019704291?pr=7170#step:4:6):17.227182] [0x00007f43631a2740] [error]   load_from_json: parse /home/runner/work/OrcaSlicer/OrcaSlicer/resources/profiles/Elegoo/process/EN4SERIES/0.40mm Standard @Elegoo N4Pro 0.8 nozzle.json got a nlohmann::detail::parse_error, reason = [json.exception.parse_error.101] parse error at line 1, column 1: syntax error while parsing value - unexpected end of input; expected '[', '{', or a literal
Error: 0-24 16:05:17.22720[6](https://github.com/SoftFever/OrcaSlicer/actions/runs/11426755306/job/32019704291?pr=7170#step:4:7)] [0x00007f43631a2740] [error]   operator(): load config file /home/runner/work/OrcaSlicer/OrcaSlicer/resources/profiles/Elegoo/process/EN4SERIES/0.40mm Standard @Elegoo N4Pro 0.8 nozzle.json Failed!
Error: 0-24 16:05:17.227216] [0x0000[7](https://github.com/SoftFever/OrcaSlicer/actions/runs/11426755306/job/32019704291?pr=7170#step:4:8)f43631a2740] [error]   load_vendor_configs_from_json, got error when parse process setting from /home/runner/work/OrcaSlicer/OrcaSlicer/resources/profiles/Elegoo/process/EN4SERIES/0.40mm Standard @Elegoo N4Pro 0.8 nozzle.json
Error: 0-24 16:05:17.229227] [0x00007f43631a2740] [error]   Failed loading configuration file /home/runner/work/OrcaSlicer/OrcaSlicer/resources/profiles/Elegoo/process/EN4SERIES/0.40mm Standard @Elegoo N4Pro 0.[8](https://github.com/SoftFever/OrcaSlicer/actions/runs/11426755306/job/32019704291?pr=7170#step:4:9) nozzle.json
Suggest cleaning the directory /home/runner/work/OrcaSlicer/OrcaSlicer/resources/profiles firstly
Validation failed
Error: Process completed with exit code 1.
```

**Comment by ELEGOOTechSupport** [comment]
@SoftFever I found a few letter capitalization issues, and they've been fixed. If there are any other mistakes, please let me know. Thank you.

**Comment by ELEGOOTechSupport** [comment]
@SoftFever 
Thank you for your reply!
I noticed that the current version of the software already includes all ELEGOO models and configurations, which is really great.
At present, our team is also further optimizing and testing the printing configuration of the machine.  I want to close this PR first.  Consider submitting the updated configuration after completing all configurations.
Thank you very much for your attention to this issue.

**Pull request closed without merging**
