### PR TITLE
Russian translation update

### PR DESCRIPTION
**Pull request by AndylgTom**
The next russian translation update OrcaSlicer V2.2.0-beta2 + 3 lines in text.js.
The work done to improve translation, corrected errors.
Thx.

### CODE REVIEW

**Comment by AndylgTom** [comment]
Up
+ Updated three lines in text.js

**Review by SoftFever — APPROVED** [review]
Thank you

**Comment by Strefford** [comment]
String #5073 - msgstr "Проект больше не доступен."    
Misspelling of word "не доступен"! 
Correct - "недоступен" (this is ONE word!) 

String #6123  - "Твердость сопла, установленного по умолчанию, не достаточна для печати "
Misspelling of word "не достаточна"!
Correct - "недостаточна" (this id ONE word!)

(source of knowledge - "Spelling Dictionary of the Russian Language" )

**Comment by AndylgTom** [comment]
[Strefford](https://github.com/Strefford) Thanks, I'll fix the spelling in the next version.

**Pull request merged**
