### PR TITLE
Fix painting Gizmo rendering on AMD Vega GPUs

### LINKED ISSUE #3395: Model Not Visible When Painting Seams or Supports
### OrcaSlicer Version

Issue first presented in 1.9.0 Beta but is still present in 1.9.0 Official Release. 

### OS version

Windows 10

### Additional system information

AMD Ryzen 4800HS, 16 GB memory, NVidia GTX 1660 Ti Max-Q

### Printer

Voron Trident, Ratrig V-Core 3, Bambu P1S, Creality K1

### How to reproduce

1. Place an stl model onto the bed.
2. Select either support painting or seam painting.

### Actual results

Model disappears. The mouse will still change to the painting tool when it is over where the model is supposed to be.

Note: I have used more than few versions of OrcaSlicer on this computer and this has never been an issue. Also, I reinstalled version 1.8.1 Release and it works fine.

### Expected results

The model should stay so it can be painted.

### Project file & Debug log uploads

[desk_tool_holder-prject-file.zip](https://github.com/SoftFever/OrcaSlicer/files/13802213/desk_tool_holder-prject-file.zip)
[log.zip](https://github.com/SoftFever/OrcaSlicer/files/13802215/log.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

### LINKED ISSUE #3487: Support painting and seam painting
### OrcaSlicer Version

1.9.0

### OS version

Windows 10

### Additional system information

_No response_

### Printer

Sovol SV01

### How to reproduce

Import file
choose an object
click Support painting or Seam painting

the object disappears

### Actual results

no possibility to manipulate both paintings

### Expected results

see the object

### Project file & Debug log uploads

[clearance-test.zip](https://github.com/SoftFever/OrcaSlicer/files/13845971/clearance-test.zip)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### PR DESCRIPTION
**Pull request by Noisyfox**
Fixes #3395
Fixes #3487

Also fixes an issue that seam & support painting gizmo render improperly when wireframe is enabled:
The wireframe is displayed properly in MMU gizmo:
image
But looks like this when switching to seam/support gizmo:
image

### CODE REVIEW

**Review by SoftFever — APPROVED** [review]
Cool
Thank you for your efforts in troubleshooting this tricky issue :)

**Comment by cherub-i** [comment]
Happy to see this is fixed - thank you!

**Comment by Anubis-Scale** [comment]
is this fixed? I just did a fresh download of orca and it still isn't working.

**Comment by cherub-i** [comment]
@Anubis-Scale sorry if my use of words confused you. From what I understand, the team behind orca has changed the programming, so that this issues is fixed. 
But they have not yet made this new code available to the public in the form of a download.

As they are most probably working on quite a lot of changes to the progamming in parallel, it would not be doable to create a new download after every single change. 
Keep an eye on the releases, it is probable, that the next release (with a version number greater than the current 1.9.0) will include this change.

**Pull request merged**
