### PR TITLE
Show dialog when opening 3mf files to choose whether to import settings.

### PR DESCRIPTION
**Pull request by markleaf131313**
It is a bit annoying, the only time I use 3mf files is from online where the individual only uploaded the 3mf file. Which means all the settings are incorrect for my use and I never want to import them. It's a simple change that just opens a dialog to allow you to choose whether to import settings or not instead of always importing settings.

### CODE REVIEW

**Comment by Eldenroot** [comment]
Cool, I know this feature from prusa slicer

**Comment by jeremytodd1** [comment]
The weird thing is that Orca currently has this feature already... but only if you first add an stl file and _then_ a 3mf.

If you open up Orca and immediately open a 3MF, it'll just import without asking.
If you open up Orca and open up an STL, and then add a 3MF, it'll ask if you want to import using the 3mf settings or just the geometry.

**Comment by markleaf131313** [comment]
Yah the dialog was already there, this change just makes it always show up instead of only sometimes.

**Review by SoftFever — APPROVED** [review]

**Review by SoftFever — APPROVED** [review]
The change makes sense to me.
Thank you

**Comment by nashchelsy** [comment]
Didn't know if I should open a fresh one, or just add to this one. But:
Can a "Remember my choice" box be added to this new popup like the one on the "unsaved changes" window? And then an option added in the Preferences menu to clear my choice like the one for the the "unsaved changes" window.

**Pull request merged**
