### PR TITLE
Better 3D navigator

### PR DESCRIPTION
**Pull request by Noisyfox**
image
image
nav_light
nav_dark

- Add text to faces
- Better color scheme

### CODE REVIEW

**Comment by yw4z** [comment]
i was planing to make color changes on this
• can you remove background color. its already has too much transparency and it look way more modern without it
src/slic3r/GUI/GLCanvas3D.cpp > 5697 > last argument is color. you need to change it to 0x00101010
• this colors will fit better imo. Text color #2d2d31, Cube color #939396

Untitled-1

Great work btw

**Comment by Noisyfox** [comment]
> i was planing to make color changes on this • can you remove background color. its already has too much transparency and it look way more modern without it src/slic3r/GUI/GLCanvas3D.cpp > 5697 > last argument is color. you need to change it to 0x00101010 • this colors will fit better imo. Text color #2d2d31, Cube color #939396
> 
> Untitled-1
> 
> Great work btw

Great idea, it does look better without the background. Though I still prefer the current color.

**Comment by yw4z** [comment]
look great. here is few optional features generally used on other apps.
different usages and unique features for navigation cube you might interested

I really like how FreeCAD implemented axis arrows. no text and arrow head. just colored straight line. looks much more modern

• Home button > Look selected plate from front-right-top
• Zoom button > Zooms all objects / zoom selected objects if selection is not empty
• Isometric / perspective toggle
• Dropdown menu for more options

**Autodesk fusion 360 web UI**
Screenshot-20240531000234
Screenshot-20240531000213

**Autodesk 3ds Max / Revit / AutoCAD**
image_221
• You can use bottom circle for rotation on this one
• Big arrows turns cubes to neighbor face

**FreeCAD** [docs](https://wiki.freecad.org/Navigation_Cube)
Navigation_Cube_Example
• Interesting shape

**Comment by SoftFever** [comment]
> > i was planing to make color changes on this • can you remove background color. its already has too much transparency and it look way more modern without it src/slic3r/GUI/GLCanvas3D.cpp > 5697 > last argument is color. you need to change it to 0x00101010 • this colors will fit better imo. Text color #2d2d31, Cube color #939396
> > Untitled-1
> > Great work btw
> 
> Great idea, it does look better without the background. Though I still prefer the current color.
> 
> nav_dark_2 [ nav_dark_2 ](https://private-user-images.githubusercontent.com/1537155/337826612-a2d9e534-f3de-4907-ae69-8b6fe06c2537.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc4NDM4MzEsIm5iZiI6MTcxNzg0MzUzMSwicGF0aCI6Ii8xNTM3MTU1LzMzNzgyNjYxMi1hMmQ5ZTUzNC1mM2RlLTQ5MDctYWU2OS04YjZmZTA2YzI1MzcuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDhUMTA0NTMxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjllODgyM2RhM2VjZWEwYWI1Mjc4NjM0ZmU4Yzk1NTVhMTJlYjEyODMzZmMwOWMzNDgzOThlOTBmYjFhZWJhMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.GQSj8aMKlS9McKAkXLqTq85Gzq09e1fTo5cOtg3UxGQ) [ ](https://private-user-images.githubusercontent.com/1537155/337826612-a2d9e534-f3de-4907-ae69-8b6fe06c2537.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc4NDM4MzEsIm5iZiI6MTcxNzg0MzUzMSwicGF0aCI6Ii8xNTM3MTU1LzMzNzgyNjYxMi1hMmQ5ZTUzNC1mM2RlLTQ5MDctYWU2OS04YjZmZTA2YzI1MzcuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDhUMTA0NTMxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjllODgyM2RhM2VjZWEwYWI1Mjc4NjM0ZmU4Yzk1NTVhMTJlYjEyODMzZmMwOWMzNDgzOThlOTBmYjFhZWJhMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.GQSj8aMKlS9McKAkXLqTq85Gzq09e1fTo5cOtg3UxGQ) nav_light_2 [ nav_light_2 ](https://private-user-images.githubusercontent.com/1537155/337826616-a15c1e33-9b71-4bbe-a1d1-2517b7303ac0.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc4NDM4MzEsIm5iZiI6MTcxNzg0MzUzMSwicGF0aCI6Ii8xNTM3MTU1LzMzNzgyNjYxNi1hMTVjMWUzMy05YjcxLTRiYmUtYTFkMS0yNTE3YjczMDNhYzAuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDhUMTA0NTMxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODIzMjQ0ODU4ODRhMzVmZjlkNmYyNjY1NjA5MWNkNTdkMDU5NTZhYzU1OGJkNDBlNjhmOWRiOGNjYjBjMTEzOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ea28quXnlyTtsEBQhpJua11XwrYSVnhU9tFNUZa8uKs) [ ](https://private-user-images.githubusercontent.com/1537155/337826616-a15c1e33-9b71-4bbe-a1d1-2517b7303ac0.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc4NDM4MzEsIm5iZiI6MTcxNzg0MzUzMSwicGF0aCI6Ii8xNTM3MTU1LzMzNzgyNjYxNi1hMTVjMWUzMy05YjcxLTRiYmUtYTFkMS0yNTE3YjczMDNhYzAuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDhUMTA0NTMxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODIzMjQ0ODU4ODRhMzVmZjlkNmYyNjY1NjA5MWNkNTdkMDU5NTZhYzU1OGJkNDBlNjhmOWRiOGNjYjBjMTEzOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ea28quXnlyTtsEBQhpJua11XwrYSVnhU9tFNUZa8uKs)

Awesome!
Though I think the while color is a bit too bright.
Maybe make it light gray?

**Comment by netweaver1970** [comment]
> look great. here is few optional features generally used on other apps. different usages and unique features for navigation cube you might interested
> 
> I really like how FreeCAD implemented axis arrows. no text and arrow head. just colored straight line. looks much more modern
> 
> • Home button > Look selected plate from front-right-top • Zoom button > Zooms all objects / zoom selected objects if selection is not empty • Isometric / perspective toggle • Dropdown menu for more options
> 
> **Autodesk fusion 360 web UI** Screenshot-20240531000234 Screenshot-20240531000213
> 
> **Autodesk 3ds Max / Revit / AutoCAD** image_221 • You can use bottom circle for rotation on this one • Big arrows turns cubes to neighbor face
> 
> **FreeCAD** [docs](https://wiki.freecad.org/Navigation_Cube) Navigation_Cube_Example • Interesting shape but seems logical because angled surfaces represents direction of view angle

First of all, I love your work to give OrcaSlicer a nicer look and feel. Functionality of course rules but UI/UX is also important.

FWIW, I'm using Fusion 360 often but now I see the FreeCAD viewcube, I think it's pretty neat! Very intuitive. If we could get that one... :)
often I'm scrolling and panning around too much to my liking in Orca, just to get the correct view, to see some details or so. 

I personally like harder edge lines (can be non-contiguous, like Fusion but in a FreeCAD style cube it would soon become too busy as a picture), I feel the current proposal is too 'non-edgy' ...

**Comment by Noisyfox** [comment]
Don't expect too much from current impl. It's fully rendered in 2d so any complicated shapes will be nearly impossible.

**Comment by yw4z** [comment]
just shared :) these ones easy to implement compared to changing shape

• removing arrow heads and axis texts to make it more modern
• home button
• menu for additional options

ofc this ones a bit further steps

**Review by SoftFever — APPROVED** [review]

**Pull request merged**
