### PR TITLE
Turkish Language Support

### PR DESCRIPTION
**Pull request by sadriercan**
Added Turkish Language Support

### CODE REVIEW

**Review by SoftFever — APPROVED** [review]
Thank you 👍

**Comment by SoftFever** [comment]
@sadriercan thank you for the translation.

Let me know if you will add the language option in the UI.

**Comment by sadriercan** [comment]
> @sadriercan thank you for the translation.
> 
> Let me know if you will add the language option in the UI.

I want to add the option to UI. But i guess you will do that:) Otherwise I dont know how to.

**Review by SoftFever — APPROVED** [review]
Thanks 👍

**Pull request merged**
