### PR TITLE
show splash screen on Linux

### PR DESCRIPTION
**Pull request by jamincollins**
# Description

Actually show the splash screen on Linux

## Tests

Built and tested on Arch Linux

### CODE REVIEW

**Comment by discip** [comment]
## This one works as intended.
# Thank you! 😃👍

**Comment by Ocraftyone** [comment]
Stuff like this makes me want to bang my head on a wall. Good catch!

**Comment by jamincollins** [comment]
That's what I'm here for

**Review by discip — APPROVED** [review]

**Review by SoftFever — APPROVED** [review]
LGTM

**Pull request merged**
