### PR TITLE
Updated po files

### PR DESCRIPTION
**Pull request by bistory**
Updated po files for newly added Scarf joint seams 🥳
French files are up to date indeed !

### CODE REVIEW

**Comment by KrisMorr** [comment]
Accidentally, you deleted all the strings for the tip of the day.

**Comment by bistory** [comment]
> Accidentally, you deleted all the strings for the tip of the day.

I just ran the update gettext script so there is probably a bug in that script, I will manually add them, thanks for your feedback 🙂

**Comment by KrisMorr** [comment]
> EDIT : Got it, "HintsToPot" is called during full refresh of translations files, it was never compiled on my machine.

Sure thing. In a moment, I will upload a pull request with corrections to the list.txt file that will complete the strings in the 'Edit Custom G-code' section.

**Comment by bistory** [comment]
> > EDIT : Got it, "HintsToPot" is called during full refresh of translations files, it was never compiled on my machine.
> 
> Sure thing. In a moment, I will upload a pull request with corrections to the list.txt file that will complete the strings in the 'Edit Custom G-code' section.

Thanks for the hint, I added the missing translations without modifying POT file, pl translations and list.txt, so our commit will not conflict ;-)

**Comment by SoftFever** [comment]
You're quick!

I've updated the POT and PO files so that all translation-related PRs have the same base. This should help avoid conflicts after each PR merge. Unfortunately, it has caused conflicts in this PR. Could you take a look?

**Comment by bistory** [comment]
> You're quick!
> 
> I've updated the POT and PO files so that all translation-related PRs have the same base. This should help avoid conflicts after each PR merge. Unfortunately, it has caused conflicts in this PR. Could you take a look?

Thanks, it's done ;-)
I reverted changes on pot and other files than French .po file ;-)

**Comment by SoftFever** [comment]
> > You're quick!
> > I've updated the POT and PO files so that all translation-related PRs have the same base. This should help avoid conflicts after each PR merge. Unfortunately, it has caused conflicts in this PR. Could you take a look?
> 
> Thanks, it's done ;-) I reverted changes on pot and other files than French .po file ;-)

Thank you.
Could you include only the FR po file(the French translation updates you made) in this PR?
Otherwise it will cause conflicts with other translation PRs.

**Comment by bistory** [comment]
> > > You're quick!
> > > I've updated the POT and PO files so that all translation-related PRs have the same base. This should help avoid conflicts after each PR merge. Unfortunately, it has caused conflicts in this PR. Could you take a look?
> > 
> > 
> > Thanks, it's done ;-) I reverted changes on pot and other files than French .po file ;-)
> 
> Thank you. Could you include only the FR po file(the French translation updates you made) in this PR? Otherwise it will cause conflicts with other translation PRs.

PR opened : #4319

**Comment by 5axes** [comment]
OrcaSlicer 2.0 Beta 

Scarf joint seam  -> Couture en Echarpe ... J'ai mal à mon français !

Couture en biseau !

**Comment by bistory** [comment]
> OrcaSlicer 2.0 Beta
> 
> Scarf joint seam -> Couture en Echarpe ... J'ai mal à mon français !
> 
> Couture en biseau ! à la limite en sifflet mais ... Non en Biseau https://fr.wikipedia.org/wiki/Assemblage_en_sifflet#:~:text=Assemblage%20(marine).-,Assemblage%20en%20sifflet%20en%20bois,des%20pi%C3%A8ces.

Ah merci ! Je ne connaissais pas la traduction exacte, je vais ajuster ça ;)

**Comment by 5axes** [comment]
Par la même occasion , dans de nombreux slicer les traductions de Solid Infill  sont traduit par "Remplissage Solide"  alors que la traduction la plus appropriée serait **Remplissage plein** 

Et petite remarque sur la traduction "Tour de nettoyage" dans les autres slicers et ce qui est plus logique on utilise la traduction "**Tour de purge**" ce qui serait plus appropriée d'autant qu'après on retrouve les **Options de purge**.

**Comment by bistory** [comment]
> C est bien le problème 😁

Mais ça n'a pas de sens "remplissage plein" dans la plupart des descriptions 🤔

**Comment by 5axes** [comment]
Question d'appréciation.. pour moi la traduction de Solid à Solide c est la facilité et le résultat d'un Google Translate. Solid à pour traduction plein, complet, rempli...  Après je suis d'accord "Remplissage plein" ça sonne pas top .. mais dans les autres slicer on parle aussi de "Couche solide" qui sont des "Couches pleines"

**Comment by bistory** [comment]
> Question d'appréciation.. pour moi la traduction de Solid à Solide c est la facilité et le résultat d'un Google Translate. Solid à pour traduction plein, complet, rempli... Après je suis d'accord "Remplissage plein" ça sonne pas top .. mais dans les autres slicer on parle aussi de "Couche solide" qui sont des "Couches pleines"

Ou on pourrait dire "remplissage complet" ou intégral mais ça fait aussi bizzare...

**Comment by 5axes** [comment]
Internal solid infill - Remplissage solide interne
Internal solid infill pattern - Motif de remplissage solide interne
Top Solid Layers - Couches solides supérieures
All solid layer - Toutes les couches solides
Bottom Solid Layers -  Couches solides inférieures
Detect narrow internal solid infill - Détecter un remplissage solide interne étroit

**Comment by bistory** [comment]
> **OrcaSlicer**
> 
> Internal solid infill - Remplissage solide interne Internal solid infill pattern - Motif de remplissage solide interne Top Solid Layers - Couches solides supérieures All solid layer - Toutes les couches solides Bottom Solid Layers - Couches solides inférieures Detect narrow internal solid infill - Détecter un remplissage solide interne étroit
> 
> **SuperSlicer** All solid surfaces - Toutes les surfaces pleines Anchor solid infill by X mm - Ancrage des remplissages pleins Bottom solid layers - Couches pleines du dessous Connection of solid infill lines - Raccordement des lignes de remplissage pleines No solid infill over - Pas de remplissage plein si plus de No solid infill over perimeters - Pas de remplissage plein sur les périmètres Solid - Couche pleine Solid acceleration - Accélération pour remplissage plein Solid fill overlap - Chevauchement de remplissage plein Solid fill pattern - Motif de remplissage plein Solid infill - Remplissage plein Solid infill every - Remplissage plein toutes les Solid infill extruder - Extrudeuse pour le remplissage plein Solid infill spacing - Espacement des remplissages plein Solid infill speed - Vitesse des remplissages plein Solid infill threshold area - Surface de seuil pour le remplissage plein Solid infill width - Largeur des remplissages plein Solid layers - Couches pleines Solid spacing - Espacement plein Top solid - Plein du dessus Top solid acceleration - Accélération pour le dessus plein Top solid infill - Remplissage plein du dessus Top solid layers - Couches pleines du dessus Top solid spacing - Espacement des couches pleines du dessus Top solid speed - Vitesse de remplissage du dessus
> 
> Donc oui dans PrusaSlicer on a peut être du "Solid" mais bon au niveau Français je pense que SuperMerill à plus de légitimité que Google Translate ou DeepL

Ok tu m'as convaincu, #4472

**Pull request closed without merging**
