### PR TITLE
Profiles for Kingroon KLP1 and KP3S V1

### PR DESCRIPTION
**Pull request by kennethjiang**
# Description

This PR is to add the profiles for Kingroon KLP1 and KP3S V1 printers.

# Screenshots/Recordings/Graphs

Screenshot 2024-08-20 at 4 54 43 PM

## Tests

Rebuild the project. And add the new printer models to verify the associated filaments and process files are correctly loaded.

### CODE REVIEW

**Review by SoftFever — COMMENTED** [review]
Hi Kenneth

Can you check the errors reported by the CICD validation tool?

**Comment by Gudzonskiy** [comment]
Add KP5L-klipper! Where should I put the profile folder?

**Comment by kennethjiang** [comment]
> Hi Kenneth
> 
> Can you check the errors reported by the CICD validation tool?

Sorry for the delay. will do soon.

**Review by SoftFever — APPROVED** [review]
LGTM
Thank you

**Comment by Gudzonskiy** [comment]
[KP5L.zip](https://github.com/user-attachments/files/16843878/KP5L.zip)

**Comment by 2greatsecret** [comment]
The specified profile is the KLP1 (230) version, which is why the printable_area does not match. There should definitely be two distinct profiles for the KLP1: KLP1 (210) and KLP1 (230), as clearly designated by the manufacturer.

**Pull request merged**
