### PR TITLE
FlasForge Adventurer 3 machine start gcode fix #6282

### LINKED ISSUE #6282: FlashForge Adventurer 3 Custom line out of printing area for every file and calibration
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.1.1

### Operating System (OS)

Linux

### OS Version

22.04.4 LTS

### Additional system information

CPU: 13th Gen Intel® Core™ i9-13900H × 20
Memory: 96 GB
Graphic: NVIDIA Corporation / NVIDIA RTX 2000 Ada Generation Laptop GPU/PCIe/SSE2

### Printer

FlashForge Adventurer 3, 0.4 nozzle

### How to reproduce

1. Create new project
2. Calibration
3. Flow rate > Pass 1
4. Slice plate with default or any other presets
5. Export G-code file (That printer doesn't have network plugin in OrcaSlicer)
6. Try to print file using manufacturer app or USB stick

### Actual results

Got an error: "The printing file is out of the print range. The printer cannot print it".
In OrcaSlicer preview after slicing I can see thick straight line in start of printing. It appear always and for any file, not only in calibration. Line type shows it as "Custom".

### Expected results

No custom line or no nozzle travel outside the printing area
Screenshot from 2024-07-29 11-18-55

### Project file & Debug log uploads

[debug_Mon_Jul_29_11_08_43_579660.log.zip](https://github.com/user-attachments/files/16410514/debug_Mon_Jul_29_11_08_43_579660.log.zip)
[Flowrate Test - Pass1.zip](https://github.com/user-attachments/files/16410520/Flowrate.Test.-.Pass1.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by GabrielJanucik**
# Description

For every project in FlashForge Adventurer 3 printer custom line was created on the edge of print field making sliced project impossible to print (line was out of plate). Default gcode for machine has been changed around 3 months ago. I have removed new code and now default start gcode is the same as provided in offical Adv3 manual. Code has been tested on my machine before push.

# Screenshots/Recordings/Graphs

Screenshot from 2024-07-29 11-18-55

## Tests

Tested with calibration and custom files on linux (Ubuntu 22.04) and printed.

### CODE REVIEW

**Review by SoftFever — APPROVED** [review]
LGTM
Thanks

**Comment by RikshaDriver** [comment]
@GabrielJanucik I am the author of ALL the Adventurer 3 parameters added into OrcaSlicer thus far. This change was added to allow a pre-extrusion as the printer needs it.

FYI, the print is not actually out of plate as the printable area is larger than the quoted 150x150mm dimensions, but Flashprint will complain it is. This is likely what you're seeing.

If you wish to change anything, adjust the Y -75 values to something like Y -74.5

@SoftFever please revert this change

**Comment by GabrielJanucik** [comment]
@RikshaDriver but pre-extrusion is always added anyway on any custom objects. I agree that it doesn't appear on calibration prints and understand that is needed.

**Comment by SoftFever** [comment]
> @RikshaDriver but pre-extrusion is always added anyway on any custom objects. I agree that it doesn't appear on calibration prints and understand that is needed.
> 
> EDIT: I also saw people complaining about this bug few times on FlashForge users Fb groups. Sometimes there were other people giving them advice to edit that start code but sometimes I was the first one.
> 

Yeah, some people prefer skirt others prefer custom prime line.

Back to the original issue.
By right, `Y-75` should be a valid coordinate per machine's definition.
It's might be a bug in their firmware.

I agree with @RikshaDriver here that changing it to Y-74.5 is a good idea.
@GabrielJanucik What do you think?

**Comment by GabrielJanucik** [comment]
@SoftFever  I think that now I understand it, at least more so I agree with that. Do you want me to create new PR with revert and value change?

**Comment by SoftFever** [comment]
> @SoftFever I think that now I understand it, at least more so I agree with that. Do you want me to create new PR with revert and value change?

Yes, a new PR is appreciated!

**Comment by GabrielJanucik** [comment]
New PR created [#6744](https://github.com/SoftFever/OrcaSlicer/pull/6744)

**Pull request merged**
