### PR TITLE
Added 0.2mm, 0.6mm, 0.8mm nozzle support for Voron 2.4

### PR DESCRIPTION
**Pull request by lukicsl**
For the new nozzle sizes I have taken the basic width and heights from the definitions of BambuLab printers. The existing 0.4 nozzle definition left as is.

### CODE REVIEW

**Comment by netweaver1970** [comment]
I've got a 0.5mm, 1.0mm and a 1.8mm nozzle as well ... While you're at it ... ??? ;)
Thanks.

**Comment by lukicsl** [comment]
> I've got a 0.5mm, 1.0mm and a 1.8mm nozzle as well ... While you're at it ... ??? ;) Thanks.

I have searched through the repo and did not find any printer to get hits for setting the different parameters in
fdm_process_voron_common_0_5.json
fdm_process_voron_common_1_0.json
fdm_process_voron_common_1_8.json

Additionally to get hints for the reasonable layer height presets (extra fine,..., extra draft)
Get me this info and I can create an additional pull request.

**Review by SoftFever — APPROVED** [review]
Looks good

**Comment by SoftFever** [comment]
@lukicsl 
Thank you very much.
The profiles work well.

I will merge this PR now.
In case there are new profiles you plan to work on, feel free to create a new PR.
Cheers!

**Pull request merged**
