### PR TITLE
compilation errors fixed of Ukrainian localizalion

### PR DESCRIPTION
**Pull request by djperya**
many bugs have been fixed, (*.mo) can be compiles.

### CODE REVIEW

**Comment by SoftFever** [comment]
@djperya 
Did you delete the previous branch already?
I pushed a code change to display Ukrainian language option in that branch.
Seems I can't find that commit anymore.

**Comment by djperya** [comment]
it seems that I accidentally canceled previous changes during
synchronization, new changes take into account the previous ones

пт, 28 лип. 2023 р., 14:44 користувач SoftFever ***@***.***>
пише:

**Comment by djperya** [comment]
but only those that were open

**Comment by djperya** [comment]
my mistake please excuse me, I can re-add the language

**Comment by SoftFever** [comment]
@djperya 
Awesome, I have add them back.
Looks working well.
You can download the nightly build to try on your machine once the build is ready.
If all going well, we can merge this PR.
Thanks for the translation 👍 
image

**Comment by djperya** [comment]
Great!  Thanks a lot!

пт, 28 лип. 2023 р., 16:35 користувач SoftFever ***@***.***>
пише:

**Comment by SoftFever** [comment]
merged.

**Review by SoftFever — APPROVED** [review]

**Pull request merged**
