### PR TITLE
Auto arrange plate after cloning

### PR DESCRIPTION
**Pull request by vovodroid**
Add option to arrange plate after cloning:

image

image

### CODE REVIEW

**Review by SoftFever — APPROVED** [review]
Thank you.
I like this QoL improvement :)

**Comment by vovodroid** [comment]
Adding instances like Prusa has will improve QoL even better))

**Comment by yw4z** [comment]
This feature is nice but need few improvements
Screenshot-20240723163412
this also arranges objects that outside of plate
result unpredictable
Screenshot-20240723163545
Might be solve with adding "only arrange this plate" or "exclude outside objects"
also adding this option to clone window instead global settings would be better because its sometimes useful sometimes reverse. switching setting before use will be very helpful
Screenshot-20240723163800

**Comment by vovodroid** [comment]
I just added call to existing arranging method without learning its algorithm.

**Comment by yw4z** [comment]
np. just sharing some ideas for improvements

**Comment by vovodroid** [comment]
> just sharing some ideas for improvements

Open new FR, may be it will be implemented.

**Pull request merged**
