### PR TITLE
Add Lift Z only Above/Below, On Surface (e.g. Only on Top)

### PR DESCRIPTION
**Pull request by iFallUpHill**
Loosely ported from SuperSlicer + PrusaSlicer

Resolves: https://github.com/SoftFever/OrcaSlicer/issues/892, https://github.com/SoftFever/OrcaSlicer/issues/1015

Lift Z Only Above/Below apply to the On Surfaces options

On Surfaces supports 
- All Surfaces (i.e. All Layer)
- Top Only (i.e. Visible Top Layers)
- Bottom Only (i.e. First Layer)
- Top and Bottom (i.e. First and Top Layers)

image

**overrides work now!**

### CODE REVIEW

**Review by SoftFever — APPROVED** [review]
LGTM

**Comment by Nukle0n** [comment]
I find the naming here confusing. What's the difference between Z-Hopping and Lift-Z?

**Comment by jonferreira** [comment]
This is great but is it possible to add yet another option to make it Hop only when the nozzle will travel between external walls?

I don't care if it hops or not when it's printing supports or internal infill for example but I do want it to hop when going over an external wall.

Makes sense?

**Comment by ramosglauco** [comment]
How difficult will it be to implement this improvement? Jesus Christ...

**Comment by jeremytodd1** [comment]
> How difficult will it be to implement this improvement? Jesus Christ...

1. Why such a rude response? These people take time out of their own day to work on this program. Features will get added when they feel they are ready. Get out of here with that stupid entitled attitude.
2. If you bothered to do even a bit of research on this you'd realize that this feature has literally been in Orca since August 3, 2023.  This thread is even labeled as "Merged" which means it's in the software already. You're replying to an old thread but that is understandable as you were too focused on being rude to notice.

**Pull request merged**
