### PR TITLE
Fix Compile Warnings

### PR DESCRIPTION
**Pull request by Ocraftyone**
# Description

This PR clears up almost all of the compile warnings generated when building the slicer on Windows. There are still a few signed/unsigned issues, but fixing those would require larger codebase changes. I tried to keep these changes pretty simple.

## Tests

Tested on Windows 11

### CODE REVIEW

**Comment by vovodroid** [comment]
With warnings you can at least to see build progress)))

**Review by SoftFever — APPROVED** [review]
Thank you so much for your effort!

**Comment by SoftFever** [comment]
@Ocraftyone 

I wanted to give a heads-up that I reverted this PR due to some issues I found. 
It's a bit costly to test and go through all the changes so I decided to revert the change instead.

Issues I found in case you're curious:
* Auto orientation is no longer working as expected.
* There are unintended consequences in `src/libslic3r/Arrange.cpp`.
* A function call was removed due to a warning about unused return values, but it's still necessary for the code to function correctly.

**Comment by Ocraftyone** [comment]
No problem! I wasn't entirely done with development on this anyway, so I'll continue to work on it when I can 😁

**Comment by vovodroid** [comment]
Probably let's split the task - for instance I guess it's harmless to resolve `unreferenced local variable` warning.

**Pull request merged**
