### PR TITLE
General improvments to RatRig V-Core 4 & V-Core 4 HYBRID

### LINKED ISSUE #5932: RatRig V-Core 4 Profiles
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

Hi! I'm here submitting the new V-Core 4 Profiles by RatRig! This is the first iteration of the profiles so all the feedback from the users is welcomed and will be taken into consideration for future updates!
I've attached the RatRig.Json file as well as the RatRig Folder, everything was tested and in proper working condition!

[RatRig Profiles 29July2024.zip](https://github.com/user-attachments/files/16042258/RatRig.Profiles.29July2024.zip)

### Which printers will be beneficial to this feature?

Klipper

### Describe the solution you'd like

RatRig V-Core 4 profiles! This might not be the right place to submit them. If so, sorry in advance and I will publish them in the right place.

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by cochcoder**
Resolves #5932

**The following changes made are made to all V-Core 4 versions** 

- Improved cover's quality 
after
- Added RatRig's PunkFil ABS, PETG, and PETG CF filaments
- Added PETG-CF10 filament type & RatRig to filament vendors
- Increased max z speed to 200 from 50 and max acceleration travel to 10,000 from 9,000
- Enabled wipe and z hop, as well as, increased retract before wipe to 70% from 0%
- Improved layer change G-Code
- Fixed pause G-Code
- Added extruder clearance parameters 

*Almost all of these changes come from @nameisCruzCruz in #5932

### CODE REVIEW

**Comment by SoftFever** [comment]
Thanks @cochcoder 
Since Curz and his team has been printing and testing these machines extensively, I'm thinking it probably make sense to use the parameters he provide(Cruz is from RatRig team).
Please let me know if you have any concerns.

**Comment by cochcoder** [comment]
I am currently going through the profiles and finding what differences have been made and implementing them into the current profiles so that custom profiles shouldn't be broken. 

I'll make this PR as a draft as its probably best to include all the changes in one PR.

**Comment by SoftFever** [comment]
> I am currently going through the profiles and finding what differences have been made and implementing them into the current profiles so that custom profiles shouldn't be broken.
> 
> I'll make this PR as a draft as its probably best to include all the changes in one PR.

haha, it's probably not many v core 4 users there :)

**Review by SoftFever — COMMENTED** [review]
Hi @cochcoder
I'm not sure if they are still interested to submit their profiles.
What do you prefer to proceed?

**Review by SoftFever — COMMENTED** [review]
FYI #6838

**Comment by cochcoder** [comment]
> Hi @cochcoder I'm not sure if they are still interested to submit their profiles. What do you prefer to proceed?

I've opted to use a few parts of @nameisCruzCruz's profiles and merge them into the current profiles, instead of completely replacing the current ones.

**Review by SoftFever — APPROVED** [review]
LGTM
Thank you very much!

**Pull request merged**
