### PR TITLE
Adds and corrects printer profiles for Qidi printers

### PR DESCRIPTION
**Pull request by fr3ak2402**
These files contain the default QIDI profiles released for the QIDI printers

**Changes:**
The start & end codes of the Qidi X-Smart3, Qidi X-Plus3 & Qidi X-Max3 printers have been revised again, so that the parameters in codes have been replaced by those of OrcaSlicer.

The printing plate texture of the printers X-Smart3, X-Plus3 & X-Max3 has been revised.

The Qidi filaments have been adapted so that the X-Max & X-CF Pro printers can work with them.

**New printers:**

Qidi X-Max:
Printer image (180x180)
Custom Printing Plate Texture (512x512)(SVG) - the manufacturer plate imitated
Hotend Model (STL) - the manufacturer plate imitated
0.4 Nozzle Profile
0.12 Process Profile (Fine)
0.16 Process Profile (Optimal)
0.20 Process Profile (Standard)
0.25 Process Profile (Draft)
0.30 Process Profile (Extra Draft)

Qidi X-CF Pro:
Printer image (180x180)
Custom Printing Plate Texture (512x512)(SVG) - the manufacturer plate imitated
Hotend Model (STL) - the manufacturer plate imitated
0.4 Nozzle Profile
0.12 Process Profile (Fine)
0.16 Process Profile (Optimal)
0.20 Process Profile (Standard)
0.25 Process Profile (Draft)
0.30 Process Profile (Extra Draft)

### CODE REVIEW

**Review by SoftFever — APPROVED** [review]

**Comment by SoftFever** [comment]
Thank you @fr3ak2402 
LGTM

**Comment by fr3ak2402** [comment]
@SoftFever, why does the signing of macOS applications always fail? I synchronised my fork with the main earlier and saw again under the actions that the signing of the macOS application fails.

I observed the same behaviour yesterday.
In addition, why did you actually bookmark the main of my fork?

I'm a little confused right now....

**Comment by SoftFever** [comment]
@fr3ak2402 The signing failed on all Pull Request CICD.
I haven't got time to check what caused that.

I don't know what you mean by "bookmark" the main of your fork. Can you elaborate it a bit more?

**Comment by fr3ak2402** [comment]
@SoftFever, I just saw another error, when you add a BambuLab X1Carbon it also shows me the filaments from the SecKit / other vendors.

image

In addition, Qidi or SecKit is not displayed as a manufacturer in the filter of the selection of the filters.

**Comment by SoftFever** [comment]
Do you mean this?
That's your PR.
image

**Comment by fr3ak2402** [comment]
@SoftFever, I am aware of that

Earlier, the commit with a red X was in the list, followed by the Bambi Lab commit and then my PR. 

That confused me a bit at first, but no matter.

**Pull request merged**
