### PR TITLE
Bug Repaired

### PR DESCRIPTION
**Pull request by HYzd766**
Solve a litte bug and make some changes

### CODE REVIEW

**Comment by Ocraftyone** [comment]
Can your provide move of a description on the fixed bug?

**Comment by HYzd766** [comment]
There is a code in the fdm_qidi_x3_common.json file called "thumnails_format": "ColPic", which is not compatible with this version. After deleting it, I fixed the bug and found that it is not compatible with this version

**Review by SoftFever — APPROVED** [review]
LGTM
Thanks

**Comment by SoftFever** [comment]
> There is a code in the fdm_qidi_x3_common.json file called "thumnails_format": "ColPic", which is not compatible with this version. After deleting it, I fixed the bug and found that it is not compatible with this version

hehehe, there was a typo there before. it should be `thumbnails_format`.
Anyway, with the new thumbnail revamp, this parameter is not required anymore.

**Comment by M-B-work** [comment]
Let me start by saying that I have an Xplus3 and always used 2.0 and switched directly to 2.1.1
The miniatures thing never worked. I found this post and would like clarification or help if possible, I tried to add _format to thumbmail, I tried to replace png and alternate hits, also varying many formats, but nothing, nothing works. Have you solved this thing? Could I try it too thanks to your suggestions? Thank you

**Comment by M-B-work** [comment]
> > There is a code in the fdm_qidi_x3_common.json file called "thumnails_format": "ColPic", which is not compatible with this version. After deleting it, I fixed the bug and found that it is not compatible with this version
> 
> hehehe, there was a typo there before. it should be `thumbnails_format`. Anyway, with the new thumbnail revamp, this parameter is not required anymore.

**Comment by HYzd766** [comment]
I have submitted the modifications regarding the issue you mentioned

**Comment by M-B-work** [comment]
> Ho inviato le modifiche relative al problema da te menzionato

So there is no solution at the right time? We are a few users in a qidi group who have encountered this, we will have to wait for a new version right? Anyway we momentarily continue to use the 2.0, we trust the orca team for a solution, thank you

**Comment by HYzd766** [comment]
> > Ho inviato le modifiche relative al problema da te menzionato
> 
> 所以在正确的时间没有解决方案吗？我们是奇地群中的几个用户遇到过这种情况，我们将不得不等待新版本吧？无论如何，我们暂时继续使用 2.0，我们相信 orca 团队的解决方案，谢谢

image

Thank you for your support. You can modify this to an illustration so that the thumbnail can be displayed, which can be used first. Alternatively, after the modifications we submitted are approved, the next version can be restored to normal use

**Pull request merged**
