### PR TITLE
Rework Github Build Actions

### PR DESCRIPTION
**Pull request by Ocraftyone**
Each build task is moved to its own workflow file to improve organization
Allows the build tasks to be run manually via Actions tab in GH
Build deps are now cached using actions/cache and are only build when deps are updated or if a deps only build is requested via GH
Build orca is run after deps are done building
Each OS can move on to the next step independently (don't have to wait for each OS to finish step to move on)

### CODE REVIEW

**Comment by Ocraftyone** [comment]
Also, this PR does go with #2541 which should fix the build issues that are showing up on workflow runs.

**Comment by SoftFever** [comment]
@Ocraftyone 
Awesome, this is so much better 👍

**Review by SoftFever — APPROVED** [review]
perfect!

**Comment by Ocraftyone** [comment]
Glad to help!

**Pull request merged**
