### PR TITLE
Fixed all filaments and added a new filament named pla_Hyper 

### PR DESCRIPTION
**Pull request by FlyingbearOfficial**
Hi, If any conflicts here, please let me know the detail, I will fix it, thank you sir

### CODE REVIEW

**Comment by FlyingbearOfficial** [comment]
Hi,When will the new version be released?

**Review by SoftFever — APPROVED** [review]
Looks good.

**Comment by SoftFever** [comment]
Looks good.
Please also give it test once it's available in nightly build.

**Comment by SoftFever** [comment]
> Hi,When will the new version be released?

Hopefully in 2 weeks

**Pull request merged**
