### PR TITLE
Add Snapmaker J1

### PR DESCRIPTION
**Pull request by hliebscher**
0.4 Nozzle
0.6 Nozzle

### CODE REVIEW

**Review by SoftFever — APPROVED** [review]
👍

**Comment by theplanekid** [comment]
could a section be made in future release notes on how to use mirror/copy/multiple colors/the IDEX features of the J1 @hliebscher? or at least a link to a page where it is discussed?
I'm uncertain on how to actually enable mirroring or copying of prints through Orcaslicer
thank you!

**Comment by Learoy1** [comment]
> could a section be made in future release notes on how to use mirror/copy/multiple colors/the IDEX features of the J1 @hliebscher? or at least a link to a page where it is discussed? I'm uncertain on how to actually enable mirroring or copying of prints through Orcaslicer thank you!

I believe mirror and copy mode is only activated on the PRINTER touchscreen, although I could be wrong. As long as the model you have sliced is less than half the size of the bed you can mirror and copy on the printer. When you select the model on the touchscreen, before you hit print, bottom left will be a tab to select between modes > copy, mirror,backup. Works well for me. 

VideoCapture_20230417-213453

**Comment by hliebscher** [comment]
@theplanekid @Learoy1 we can make a discussion  
i open this
mirror and copy mode can activated in gcode
As long as the model you have sliced is less than half the size of the bed you can mirror and copy on the printer. 
on print bed left side behind the blue or red line
/Users/hliebscher/smfix_bs-darwin-arm64;
/Users/hliebscher/j1x2;
i use my own software to send the gcode to the j1 and fix the code for display the values

**Comment by theplanekid** [comment]
thank you both!

**Comment by arciarc** [comment]
@hliebscher
Great work! Thank you.
How do I get the files sent/ G-code-generating?
I get the error-message "The configured post-processing script does not exist: /Users/hliebscher/smfix_bs-darwin-arm64"

Thanks for helping out.  Dankeschön.
:-)

**Comment by projectsaturnstudios** [comment]
> /Users/hliebscher/smfix_bs-darwin-arm64;
> /Users/hliebscher/j1x2;
> i use my own software to send the gcode to the j1 and fix the cod

@hliebscher This J1 profile does not work without the postprocessing script(s) you say it needs. 
Please provide a download or link to the smfix_bs-darwin-arm64.

**Comment by projectsaturnstudios** [comment]
> > /Users/hliebscher/smfix_bs-darwin-arm64;
> > /Users/hliebscher/j1x2;
> > i use my own software to send the gcode to the j1 and fix the cod
> 
> @hliebscher This J1 profile does not work without the postprocessing script(s) you say it needs. Please provide a download or link to the smfix_bs-darwin-arm64.

I actually figured it out since I didn't want to wait.
If you travel to @hliebscher 's github 
https://github.com/hliebscher/Snapmaker2Slic3rPostProcessor
Just download the zip, fork or clone the repo.
In your terminal type "make", and when it's done the dist folder will get generated and you'll have your file.

If yo uhave a mac you'll need homebrew to install go.

**Comment by DrunkScienceMan** [comment]
> > > /Users/hliebscher/smfix_bs-darwin-arm64;
> > > /Users/hliebscher/j1x2;
> > > i use my own software to send the gcode to the j1 and fix the cod
> > 
> > 
> > @hliebscher This J1 profile does not work without the postprocessing script(s) you say it needs. Please provide a download or link to the smfix_bs-darwin-arm64.
> 
> I actually figured it out since I didn't want to wait. If you travel to @hliebscher 's github https://github.com/hliebscher/Snapmaker2Slic3rPostProcessor Just download the zip, fork or clone the repo. In your terminal type "make", and when it's done the dist folder will get generated and you'll have your file.
> 
> If yo uhave a mac you'll need homebrew to install go.

Can you elaborate on that "make" part a bit? It seems I am too smooth brained to figure this out. Am the wrong kind of engineer for this.

**Comment by projectsaturnstudios** [comment]
"make" is a terminal command that you run to build source code like the code in this branch.
Download the source, unzip it, open a terminal and cd into the unzipped folder and type make.
When it's done you should have an smfix file generated ion the unzipped folder's dist folder.
It should work unless you are missing a dependancy. At that point, google will be able to help ya out!

Hope that helps!

**Comment by hliebscher** [comment]
https://github.com/hliebscher/Snapmaker2Slic3rPostProcessor.git
and select OrcaSlicer Branch

witch version do yo need?

see at discussion Board in OrcaSlicer

@projectsaturnstudios @theplanekid @Learoy1 @arciarc

**Comment by projectsaturnstudios** [comment]
@hliebscher You should tag a release and publish it on the channels.
I was able to build it for M1 Pro but I can't get it running on on Intel.
Do you have Intel?

**Comment by DrunkScienceMan** [comment]
> @DrunkScienceMan "make" is a terminal command that you run to build source code like the code in this branch. Download the source, unzip it, open a terminal and cd into the unzipped folder and type make. When it's done you should have an smfix file generated ion the unzipped folder's dist folder. It should work unless you are missing a dependancy. At that point, google will be able to help ya out!
> 
> Hope that helps!

I see the problem now. Since I am no IT guy I was under the assumption that this works on windows. Am I seeing this right, that this is only for Mac and Linux? Specifically I would need it for and AMD processor on windows. I don't know if that makes a difference.

**Comment by hliebscher** [comment]
> > @DrunkScienceMan "make" is a terminal command that you run to build source code like the code in this branch. Download the source, unzip it, open a terminal and cd into the unzipped folder and type make. When it's done you should have an smfix file generated ion the unzipped folder's dist folder. It should work unless you are missing a dependancy. At that point, google will be able to help ya out!
> > Hope that helps!
> 
> I see the problem now. Since I am no IT guy I was under the assumption that this works on windows. Am I seeing this right, that this is only for Mac and Linux? Specifically I would need it for and AMD processor on windows. I don't know if that makes a difference.

[Releases 1](https://github.com/hliebscher/Snapmaker2Slic3rPostProcessor/releases)
here is my release

**Comment by DrunkScienceMan** [comment]
Thank you very much for the help so far. I have put the file into the folder orcaslicer says where it is missing. I am now getting a different error message when trying to export:  " Failed starting the script /Users/hliebscher/smfix_bs-darwin-arm64 C:\Users\[my name]\AppData\Local\Temp/orcaslicer_model/Sun_Apr_23/09_38_00#16448#32/Metadata\.16448.0.gcode.pp, Win32 error: 193 "
It still generates a .gcode file . Can this error message be ignored?

**Comment by hliebscher** [comment]
> Thank you very much for the help so far. I have put the file into the folder orcaslicer says where it is missing. I am now getting a different error message when trying to export: " Failed starting the script /Users/hliebscher/smfix_bs-darwin-arm64 C:\Users[my name]\AppData\Local\Temp/orcaslicer_model/Sun_Apr_23/09_38_00#16448#32/Metadata.16448.0.gcode.pp, Win32 error: 193 " It still generates a .gcode file . Can this error message be ignored?

you have to select the smfix_bs-win64 in any directory that you have and change the name in the script windows

**Comment by DrunkScienceMan** [comment]
Not sure I understoof this correctly. I have to rename "smfix_bs-win64" to "smfix_bs-darwin-arm64" in both folders? I did that. 
I still get an error. error: 193 changed to error: 5

**Comment by projectsaturnstudios** [comment]
@DrunkScienceMan 
What's being said is that the default value in the Post-processing Scripts field ~/Users/hliebscher/smfix_bs-darwin-arm64
is the path to the file on hliebscher's computer. You need to erase that value and replace it with the path to the file on your computer.

So wherever you stored the file, for example like C:\Users[my name]\MyDocuments\smfix_bs-win64 , you need to set the value of the Post-processing Scripts field with the path to the file on your computer.

Make for sense?

**Comment by DrunkScienceMan** [comment]
> @DrunkScienceMan What's being said is that the default value in the Post-processing Scripts field ~/Users/hliebscher/smfix_bs-darwin-arm64 is the path to the file on hliebscher's computer. You need to erase that value and replace it with the path to the file on your computer.
> 
> So wherever you stored the file, for example like C:\Users[my name]\MyDocuments\smfix_bs-win64 , you need to set the value of the Post-processing Scripts field with the path to the file on your computer.
> 
> Make more sense?

That does make sense. I did it the other way around. I created the folder orcaslicer references in the error. I guess that doesn't work then. What program can I edit the file with? Text editor doesn't seem to work.

**Comment by projectsaturnstudios** [comment]
@DrunkScienceMan 
There's no editing, just download the file here that pertains to your system
https://github.com/hliebscher/Snapmaker2Slic3rPostProcessor/releases

Put the file somewhere on your computer and copy the location (called  a path) of the file.
Delete everything inside the Post-processing scripts field  Paste that path in there.
Slice.
Screen Shot 2023-04-23 at 8 40 40 AM

**Comment by DrunkScienceMan** [comment]
> @DrunkScienceMan There's no editing, just download the file here that pertains to your system https://github.com/hliebscher/Snapmaker2Slic3rPostProcessor/releases
> 
> Put the file somewhere on your computer and copy the location (called a path) of the file. Delete everything inside the Post-processing scripts field that you see below. Forget that it was there. Screen Shot 2023-04-23 at 8 40 40 AM
> 
> Paste that path you copied in there. Slice.

so I did that but I am still getting the same "error: 5". And i can tell orcaslicer can find the file, because when I misstype the path or something it tells me it can't find the file. The slicing part works fine btw. The error occurs when trying to export the gcode.

**Comment by TylonHH** [comment]
> 0.4 Nozzle
> 0.6 Nozzle

Can pleas 0,8 also added 😎

**Comment by hliebscher** [comment]
> > @DrunkScienceMan There's no editing, just download the file here that pertains to your system https://github.com/hliebscher/Snapmaker2Slic3rPostProcessor/releases
> > Put the file somewhere on your computer and copy the location (called a path) of the file. Delete everything inside the Post-processing scripts field that you see below. Forget that it was there. Screen Shot 2023-04-23 at 8 40 40 AM
> > Paste that path you copied in there. Slice.
> 
> so I did that but I am still getting the same "error: 5". And i can tell orcaslicer can find the file, because when I misstype the path or something it tells me it can't find the file. The slicing part works fine btw. The error occurs when trying to export the gcode.

i think you have win 32 bit

**Comment by DrunkScienceMan** [comment]
> > > @DrunkScienceMan There's no editing, just download the file here that pertains to your system https://github.com/hliebscher/Snapmaker2Slic3rPostProcessor/releases
> > > Put the file somewhere on your computer and copy the location (called a path) of the file. Delete everything inside the Post-processing scripts field that you see below. Forget that it was there. Screen Shot 2023-04-23 at 8 40 40 AM
> > > Paste that path you copied in there. Slice.
> > 
> > 
> > so I did that but I am still getting the same "error: 5". And i can tell orcaslicer can find the file, because when I misstype the path or something it tells me it can't find the file. The slicing part works fine btw. The error occurs when trying to export the gcode.
> 
> i think you have win 32 bit

No I definitely have Windows 10 pro 64 bit (I don't think I could run hyper-v otherwise). But even still I tried the 32 bit version and I get the same error. Btw my Antivirus (avast) is throwing a fit at the .exe files. I deactivated it and redownload the files. But just so you know

**Comment by arciarc** [comment]
Call me stupid, but I don´t find the field "Post-processing Scripts"
 There is "Machine G-Code" 
 - Machine Start g-code
 - Machine End-g-code
 - Before Layer Change
 - Layer Change
 - ...
 but no Post-processing Scrips
 Am I looking at the wrong place?
 
 2nd question:
 is it possible to connect the printer using the printer ID-Adress?

**Comment by DrunkScienceMan** [comment]
> Call me stupid, but I don´t find the field "Post-processing Scripts" There is "Machine G-Code"
> 
> * Machine Start g-code
> * Machine End-g-code
> * Before Layer Change
> * Layer Change
> * ...
>   but no Post-processing Scrips
>   Am I looking at the wrong place?
> 
> 2nd question: is it possible to connect the printer using the printer ID-Adress?

Click on the "advanced" slider and then below on "others" (one of the settings next to quality, speed, etc). Then scroll down

**Comment by TylonHH** [comment]
> 0.4 Nozzle 0.6 Nozzle

is adding 0,8 a big deal?

**Comment by digitalsolutiontop** [comment]
hi,

I'm trying to print with orcaslicer 1.7.0/snapmaker j1 an object with PETG set on the first extruder and PLA support and the gcode compiler (latest smfix version), everything works correctly but when I save the gcode and insert the file on the printer with the latest firmware available, when print start the R extruder does not go into pre-heating.
I tried to insert an object to print on the plate of the usual support material but the second extruder still doesn't go into pre-heating and when it's its turn to print it stops because obviously the filament isn't extruded.

help me pls

**Pull request merged**
