### PR TITLE
Updated inner outer inner algorithm to cater for edge case where an internal island with two perimeters on both sides of an external wall was causing a secondary island to not reorder the walls correctly

### PR DESCRIPTION
**Pull request by igiannakas**
Updated inner outer inner algorithm to cater for edge case where an internal island with two perimeters on both sides of an external wall was causing a secondary island to not reorder the walls correctly

Bellow shows incorrect ordering of perimeters for the external wall - falls back incorrectly to printing outer to inner when it can print inner-outer-inner as two internal perimeters are present in the outer wall island.

This was happening because the current algorithm was considering the internal island perimeters to be part of the external island.

**Before:**
Incorrect ordering used for the external island
Incorrect ordering

**After:** 
Correct wall order is observed for the external wall island.
Correct ordering

### CODE REVIEW

**Comment by igiannakas** [comment]
My apologies for closing and re opening - renamed the branch by accident.

**Comment by SoftFever** [comment]
@igiannakas 
I'll check it tomorrow.
Is it possbile to share the testing model?

**Comment by igiannakas** [comment]
> @igiannakas I'll check it tomorrow. Is it possbile to share the testing model?

Yeap it’s this one: 

https://files.printables.com/media/prints/56731/stls/563074_47d87a59-8f93-4d9d-a13b-4b8dc5438822/wheel_x4.stl

nothing special in the slicing - 0.16 layer height, 3 perimeters, sandwich mode wall ordering

**Comment by igiannakas** [comment]
Please find attached 3MF. Layer 25.
[wheel.3mf.zip](https://github.com/SoftFever/OrcaSlicer/files/12505535/wheel.3mf.zip)

**Comment by SoftFever** [comment]
Hi @igiannakas 
Thanks for you patience.
I found an regression that is not directly related this PR, it probably cause the previous PR.
The walls are not printed at desired order as I described in previous PR.
Maybe need to revisit it when I got time.

https://github.com/SoftFever/OrcaSlicer/assets/103989404/d5036c96-3af7-4280-8451-52564b213255

**Comment by igiannakas** [comment]
> Hi @igiannakas Thanks for you patience. I found a regression which is not directly related this PR, it probably caused by the previous PR. The walls are not printed at desired order as I described in previous PR. Maybe need to revisit it when I got time.
> 
>  aa.mp4

That is the expected order I would think - it prints the second internal, then external, then the middle (first) internal, then carries on with the rest in an outer to inner sequence (as we are using the outer to inner ordering as the basis).

Would you expect all the internals to be printed first, then the external and then the final internal? 

Or something different?

**Comment by igiannakas** [comment]
> > > Hi @igiannakas Thanks for you patience. I found a regression which is not directly related this PR, it probably caused by the previous PR. The walls are not printed at desired order as I described in previous PR. Maybe need to revisit it when I got time.
> > > aa.mp4
> > 
> > 
> > That is the expected order I would think - it prints the second internal, then external, then the middle (first) internal, then carries on with the rest in an outer to inner sequence (as we are using the outer to inner ordering as the basis).
> > Would you expect all the internals to be printed first, then the external and then the final internal?
> > Or something different?
> 
> Following: all the internals to be printed first(inside to outside), then the external and then the final internal

Understood - let me have a go at it and I’ll revert back.

**Comment by igiannakas** [comment]
> 

I've pushed a new commit that takes a different approach. It scans all the perimeters in a layer to identify islands and the perimeters that need re-ordering. 

Then for any perimeter not involved in the sandwich re ordering (i.e perimeter 2+) it treats them as internal first, by reordering them to print first. It then prints the remaining perimeters that are involved in the sandwich mode (1 & 2) in an external to internal direction.

I am 50-50 whether this is a better approach or not - it is more computationally intensive as it scans the perimeters twice to perform that re-ordering and also uses a temporary array to facilitate that re-ordering which is then replacing the ordered extrusions array, as this approach is now much more extensive and dynamic, because it depends on the number of perimeters selected now by the user.

On the other hand this one may provide slightly better quality as it is slightly more biased towards printing as many internal perimeters as possible before doing the sandwich mode, hence priming the nozzle more and also minimising traveling over the internal lines that you pointed out above. The previous algorithm would do the bare minimum internal perimeters before doing sandwich and then continuing with the remaining internal perimeters.

It still solves the edge case issue from my original PR (where the outer perimeter would be printed last) and solves the issue this present PR was intending to solve.

What do you think?

PS. this is my favourite area of Orca slicer - its a truly unique feature that improves print quality immensely so I'm personally keen to get it working the best as possible :) So please do excuse my eagerness to contribute to this area :)

**Comment by igiannakas** [comment]
Further improvements pushed:
1. Disabled inner outer inner algorithm on first layer as it cause on occasion bed adherence issues due to the lines being separated (the outer and the second interior perimeter).

**Review by SoftFever — APPROVED** [review]

**Comment by SoftFever** [comment]
@igiannakas 
Thank you so much.
This is indeed one of the unique features introduced by OrcaSlicer.
While I've wanted to refine it further since its initial implementation, the responsibilities of managing the project have been consuming most of my free time outside of my day job.

That said, I'm immensely grateful for our supportive community. It's heartening to see more developers and contributors stepping up to help improve OrcaSlicer. Contributors like you, and many others, are the driving force behind this project's rapid progress. Thank you for being a part of it!

**Comment by igiannakas** [comment]
> @igiannakas Thank you so much. This is indeed one of the unique features introduced by OrcaSlicer. While I've wanted to refine it further since its initial implementation, the responsibilities of managing the project have been consuming most of my free time outside of my day job.
> 
> That said, I'm immensely grateful for our supportive community. It's heartening to see more developers and contributors stepping up to help improve OrcaSlicer. Contributors like you, and many others, are the driving force behind this project's rapid progress. Thank you for being a part of it!

Your welcome! It’s a pleasure to contribute even in my small way to this fantastic project!

**Pull request merged**
