### PR TITLE
Add Folgertech Printers

### PR DESCRIPTION
**Pull request by Musicdad12**
Fixed a Typo in one of the filament files, rendering it inoperative
Fixed filaments with a unique filament ID number
Uploaded cover images for printer models
Fixed typo in machine definition where texture and/or model was not correct

### CODE REVIEW

**Comment by SoftFever** [comment]
@Musicdad12 
There are a lot of conflicts
Can you take a look?

**Comment by fr3ak2402** [comment]
@SoftFever @Musicdad12 

Folgertech filaments have not been named correctly.
In the filament file the filaments were always named Folgertech Generic etc. The files themselves, however, only Generic etc.

I don't think this will work and would cause problems with other printers.

Bildschirmfoto 2023-05-14 um 13 01 54

In addition, images have already been created for the BIQU printers in OrcaSlicer.

**Comment by Musicdad12** [comment]
> @SoftFever @Musicdad12
> 
> Folgertech filaments have not been named correctly. In the filament file the filaments were always named Folgertech Generic etc. The files themselves, however, only Generic etc.
> 
> I don't think this will work and would cause problems with other printers.

I will make the changes. 
> 
> Bildschirmfoto 2023-05-14 um 13 01 54
> In addition, images have already been created for the BIQU printers in OrcaSlicer. The profiles from the BIQU have already been included.
> 
There were a few errors in the original BIQU files, these were corrected. 


> Moreover, the images Folgertech printer are also not in 180x180 pixels

I  will change

**Comment by fr3ak2402** [comment]
@Musicdad12 

The Folgertech filaments are now in order. In addition, the Folgertech printer images are now also okay.

The BIQU printer images still need to be removed, as there are already images of these models.

**Comment by Musicdad12** [comment]
> @Musicdad12
> 
> The Folgertech filaments are now in order. In addition, the Folgertech printer images are now also okay.
> 
> The BIQU printer images still need to be removed, as there are already images of these models.
> 
> Why did you give the BIQU filaments a new ID?
> 
> @SoftFever Is it at all possible to assign an own ID to filaments?
> 
> Doesn't that lead to a problem with the Bambulab Cloud synchronization if you use an ID that has not been released by BambuLab?

I am not aware. It seemed to work on my test version locally. Should I change them back?

**Comment by fr3ak2402** [comment]
@Musicdad12 
I have already fixed the problem with the SecKit printers, you won't have that in the next version. This has nothing to do with your profiles, but had something to do with the SecKit profile.

But you can ignore the filaments from SecKit.

Have you also installed the plugin from Bambulab and are logged in? Just change that for safety back to the original IDs

**Review by SoftFever — APPROVED** [review]

**Comment by SoftFever** [comment]
LGTM.
Thanks, @Musicdad12 👍 
Also, thank @fr3ak2402 for the code reviewing.

**Pull request merged**
