### PR TITLE
Update OrcaSlicer_es.po

### PR DESCRIPTION
**Pull request by gatosardina**
This pull request is not ready to merge.

I need confirmation on character limit per line.

This was a quick overview of the changes in the previous spanish translation update, plus some quick changes in related strings

### CODE REVIEW

**Comment by gatosardina** [comment]
msgid "Object coordinates"

Is this the object coordinates expressed in the world coordinates, or the coordinates of "something" expressed in the object's coordinates?


msgid "Frustum"

What is that? Where is it used (in orcaslicer? frustrum is a portion of a pyramid or cone, without the 'tip'


msgid "Set Mirror"
Where is this used?


msgid "Click to change text into object part."
Where is this used?


msgid "First Add style to list."
Where is this used?


msgid "Undefined stroke type"
Where is this used?


msgid "Open filled path"
Where is this used?


msgid "Select settings"
Where is this used?


msgid "Delete connector from object which is a part of cut"
Where is this used?

**Comment by hliebscher** [comment]
Where is this used? 

All msgids are inserted and used by a script; you can search for them in the code afterwards.

The term “Frustum” refers to a geometric shape that is typically used in 3D graphics and computer vision. It is formed by slicing the top off a cone or pyramid, creating a shape that has two parallel faces: a smaller top and a larger base. In 3D graphics, the view frustum is particularly important, as it represents the field of view of a camera. Objects within this frustum are visible in the rendered scene, while those outside are clipped and not displayed. The shape is crucial in determining what parts of a scene should be rendered on the screen.

pls translate all msgid's

**Comment by gatosardina** [comment]
I know what a frustrum is, i'm asking where is it used because the current translation does not seem to fit its meaning

I am reviweing and correcting all msgid in the already existing spanish localization

I can imagine that msgids are placed by a script, I'm asking where contextually in the app some msgstr are used to know what exactly is the meaning behind the message

I will commit new changes to this pull request branch as I cmmit them to my fork

**Comment by gatosardina** [comment]
I've reviewed around half of the file, up to line 10024
I would like confirmation on my previous comment plus some comments i've left in the code (you can find them starting with 
`#. ?` )

**Comment by gatosardina** [comment]
Aight, I think it's done.

Sorry for the delay, I was on vacation.

I assumme all lines starting with #~ are commented out?

I reckon they are a lot of changes to review one by one.
If anything, I would like for my comments (starting with "#. ?') are reviewed, but otherwise it's ready.

**Comment by gatosardina** [comment]
Btw, don't merge it yet, i'll add trnaslations for the new msgids, check if more updates to existing msgids were introduced

**Comment by gatosardina** [comment]
Added new translations for the new msgids and updated the existing translations for some updated msgids
Ready once again for review and merge

**Comment by gatosardina** [comment]
Fixed the strings breaking the check

**Comment by gatosardina** [comment]
Idk what that means?

I checked a few other translation files and the referenced msgids and msgstr look the same, including the `#, c-format` bits and stuff

I did change the string legths of the last error, which seemed like a different error and a bit too long

**Comment by gatosardina** [comment]
Aight it should be all good now, the msgfmt format check throws no errors to me:
image

**Review by SoftFever — APPROVED** [review]
Looks good
Thank you!

**Pull request merged**
