### PR TITLE
Fix flatpak build

### PR DESCRIPTION
**Pull request by anarsoul**
* Patch wxWidgets to automatically select dark theme variant (taken from Bambu slicer flatpak manifest)
* Drop python script that selected dark theme
* Add a patch to fix libslic3r build

# Description

# Screenshots/Recordings/Graphs

### CODE REVIEW

**Comment by danielcherubini** [comment]
Any chance that this can also include a deployment stage to flathub?

https://github.com/flatpak/flatpak-github-actions?tab=readme-ov-file#deployment-stage

**Comment by anarsoul** [comment]
> Any chance that this can also include a deployment stage to flathub?
> 
> https://github.com/flatpak/flatpak-github-actions?tab=readme-ov-file#deployment-stage

I don't think that flathub accepts external uploads. See https://github.com/SoftFever/OrcaSlicer/issues/3949 for details

**Comment by AMstuff** [comment]
I built a flatpak using this PR successfully, thanks! However, I noticed that  you missed deleting this line: "install -Dm755 set-dark-theme-variant.py /app/bin" from the post-install section.

**Comment by anarsoul** [comment]
> However, I noticed that you missed deleting this line:

Thanks, fixed now.

**Review by SoftFever — APPROVED** [review]

**Comment by SoftFever** [comment]
Awesome!
Thank you very much.

**Pull request merged**
