### PR TITLE
Creality K1 series improvements

### PR DESCRIPTION
**Pull request by bistory**
# Description

This new PR aims to fix some issues on Creality K1's : 

- Less stringing by removing retract before wipe and setting wipe distance
- Better overhangs with better default settings
- Better default configuration for scarf joint seams
- Disable always on fan to reduce noise when printing
- Prettified processes and machines JSON

### CODE REVIEW

**Comment by SoftFever** [comment]
Any chance to record the bug?
It saves and loads fine here
Screenshot 2024-04-22 at 7 32 53 PM

**Comment by bistory** [comment]
> Any chance to record a video about how to reproduce the bug? It saves and loads fine here Screenshot 2024-04-22 at 7 32 53 PM

Here is the video : https://streamable.com/jp6exe
Steps to reproduce the bug : 

1. Use the profiles of this PR ( [Archive.zip](https://github.com/SoftFever/OrcaSlicer/files/15062281/Archive.zip) )
2. Start OrcaSlicer
3. Choose K1 in the printers
4. Choose the filament and profile of your choice
5. Change the value of Scarf joint seams
6. seam_slope_conditional and other options don't have the values set in the profile

**Comment by SoftFever** [comment]
It's working fine here.
I guess I know why. 
Can you delete `/Users/<your_user_name>/Library/Application Support/OrcaSlicer/system` folder and try again?

**Review by SoftFever — APPROVED** [review]
Looks good.
Thank you very much!

**Comment by YoshimitsuGaiden** [comment]
Is anyone else getting the same if not longer estimated print times with the 0.6 or 0.8mm compared to the 0.4mm nozzle? and has anyone tried them to see if they print faster I'm looking in to getting the nozzles and I'm wondering if ill need to make a custom profile to get the speeds up.

**Comment by YoshimitsuGaiden** [comment]
@bistory  Hey, I've been tweaking my own custom 0.8mm nozzle profile and have had good results with it. It might still need a little more tinkering, but I've managed to reduce the print times while maintaining great results. Let me know of anyway to get it to you if you would like it, I'll start work on a 0.6mm profile soon.

**Comment by DCEngineerMax** [comment]
I apologize in advance if this is the wrong place to ask, but how were these profiles developed? I'm pretty new at this. We've got 2 K1 Max and 1 K1C here. I started in creality slicer and moved to Orca, but I noticed that the printer profiles and process are significantly different between Creality and Orca

**Pull request merged**
