### PR TITLE
Add plate name edit btn

### LINKED ISSUE #3367: Easy plate naming
**Is your feature request related to a problem? Please describe.**
Naming all the different plates of a big project is a pain. It's just unnecessarily complicated.

**Which printers will be beneficial to this feature**
This would make using and naming multiple build plates for projects in Orca Slicer easier.

**Describe the solution you'd like**
Just a simple click on the "Untitled" (or on a symbol next to it) would allow the title to being edited. It could be confirmed with Enter or just by clicking somewhere else. There would be no extra window opening. The title should be edited in the standart "Prepare" view.

### PR DESCRIPTION
**Pull request by Noisyfox**
Fix #3367

image

### CODE REVIEW

**Comment by Eldenroot** [comment]
Thank you very much!!!

**Review by SoftFever — APPROVED** [review]
You'da man!

**Comment by Nevio024** [comment]
Awesome!

**Comment by Nevio024** [comment]
How do I get this to work in Orcaslicer? 😅 
Do I need to wait until the newest version comes out?

**Comment by Noisyfox** [comment]
> How do I get this to work in Orcaslicer? 😅 Do I need to wait until the newest version comes out?

You can always download the latest nightly build from GitHub action tab.

**Comment by Nevio024** [comment]
> > How do I get this to work in Orcaslicer? 😅 Do I need to wait until the newest version comes out?
> 
> ~You can always download the latest nightly build from GitHub action tab.~
> 
> Edit: Seems @SoftFever just added the nightly build in the release page: https://github.com/SoftFever/OrcaSlicer/releases/tag/nightly-builds Nice one!

Don‘t the nightly builds have bugs in them? Are they stable to use?

**Pull request merged**
