### PR TITLE
Fix Dark Mode issues on Linux(via LAB)

### PR DESCRIPTION
**Pull request by jamincollins**
# Description

This should address _most_ (if not _all_) dark mode issues.

I've added routines based on LAB color space in an effort to ensure that foreground colors are not the same (or similar) to background colors.

https://en.wikipedia.org/wiki/CIELAB_color_space

I'm sure there are other areas and dialogs these changes fix.  While there are some targeted changes that were needed, the core is a generalized solution that should _just work_ for most areas.

# Screenshots/Recordings/Graphs

## Tabs

**Before**
image
image
image

**After**
image
image
image

## Custom Gcode Editor

**Before**
image

**After**
image

## Export Configs

**Before**
image

**After**
image

## Network Tests

**Before**
image

**After**
image

## Printer Settings X/Y Fields

**Before**
image
image

**After**
image
image

## Rename Plate

**Before**
image

**After**
image

## Send G-Code

**Before**
image

**After**
image

## Unsaved changes

**Before**
image

**After**
image

## Tests

Built and tested locally on Arch Linux.  I did need to revert commit  1bb8fad63fa4f4bcaeb039aec030b1247055c88a due to instability it introduced, see #5030.

### CODE REVIEW

**Comment by jamincollins** [comment]
Found another area that is improved.

Before:
image

After:
image

**Comment by jamincollins** [comment]
This also fixes a light mode issue #3936, and possibly others.

image

**Comment by discip** [comment]
@jamincollins
## First of all, thank you for your effort in fixing this issue once and for all! 😃👍
Unfortunately not all the fixes you mentioned above work for me on my machine, with the current build: https://github.com/SoftFever/OrcaSlicer/actions/runs/8708611679?pr=5044

Not working:
* Custom Gcode Editor
* Printer Settings X/Y Fields

Could not test:
* Network Tests
* Send G-Code

Everything else you mentioned above works. 👍

<details>
  <summary>
    <b>setup</b>
  </summary>
<br>

OS | CPU | GPU | RAM | SSD
-|-|-|-|-
Manjaro (Gnome) | Ryzen 9 7950X3D | XFX 7900 XTX | G.Skill Flare X5 32 GB | Samsung 990 Pro 2 TB

</details>

**Comment by discip** [comment]
@jamincollins
## First of all, thank you for your effort in fixing this issue once and for all! 😃👍
Unfortunately, not all of the fixes mentioned above work for me on my machine with the current build: https://github.com/SoftFever/OrcaSlicer/actions/runs/8708611679?pr=5044

Not working:
* Custom Gcode Editor
* Printer Settings X/Y Fields

Could not test:
* Network Tests
* Send G-Code

Everything else you mentioned above works. 👍

<details>
  <summary>
    <b>setup</b>
  </summary>
<br>

OS | CPU | GPU | RAM | SSD
-|-|-|-|-
Manjaro (Gnome) | Ryzen 9 7950X3D | XFX 7900 XTX | G.Skill Flare X5 32 GB | Samsung 990 Pro 2 TB

</details>

**Comment by jamincollins** [comment]
@discip what theme are you running?

I'll try this under Gnome here on Arch, and if it works I'll see about building a Manjaro test system.

Also, as indicated on this PR, I can't successfully run a build that includes commit https://github.com/SoftFever/OrcaSlicer/commit/1bb8fad63fa4f4bcaeb039aec030b1247055c88a to run.  Any build including it segfaults for me.

**Comment by discip** [comment]
Sorry, but I'm currently not near my machine, so will let you know later.

**Comment by discip** [comment]
@jamincollins
Thank you for fixing this! 👍
Now the colors are correct, but unfortunately now there is another strange issue:

In **`Printer settings`**, if for example the **`Basic Information`** tab is open and I click in any text box to change a value, but then switch to another tab e.g.: **`Extruder`**, I'm not able to change any values ​​except those that were previously unreadable (e.g.: **`Extruder`** > **`Extruder offset`** > **`x:`** )!
##
Off-topic:
There is another annoyance that's not directly related, but makes using the neat custom G-Code editing feature useless, as due to the size of the **`Edit Custom G-Code`** window, which can't be changed, the “save” button is hidden at the bottom of the screen.
##
😅 Absolutely off-topic:
Sorry, since the following is kind of abandoned I dare to ask: Could you by any chance have a look at this as well?:
```
https://github.com/SoftFever/OrcaSlicer/pull/2405
```

thanks in advance
kind regards

**Comment by discip** [comment]
@jamincollins
Thank you for fixing this! 👍
Now the colors are correct, but unfortunately now there is another strange issue:

In **`Printer settings`**, if for example the **`Basic Information`** tab is open and I click in any text box to change a value, but then switch to another tab e.g.: **`Extruder`**, I'm not able to change any values ​​except those that were previously unreadable (e.g.: **`Extruder`** > **`Extruder offset`** > **`x:`** )!

However I'm not sure if that was present prior to your latest changes.
##
Off-topic:
There is another annoyance that's not directly related, but makes using the neat custom G-Code editing feature useless, as due to the size of the **`Edit Custom G-Code`** window, which can't be changed, the “save” button is hidden at the bottom of the screen.
##
😅 Absolutely off-topic:
Sorry, since the following is kind of abandoned I dare to ask: Could you by any chance have a look at this as well?:
```
https://github.com/SoftFever/OrcaSlicer/pull/2405
```

thanks in advance
kind regards

**Comment by jamincollins** [comment]
> In **`Printer settings`**, if for example the **`Basic Information`** tab is open and I click in any text box to change a value, but then switch to another tab e.g.: **`Extruder`**, I'm not able to change any values ​​except those that were previously unreadable (e.g.: **`Extruder`** > **`Extruder offset`** > **`x:`** )!
> 
> However I'm not sure if that was present prior to your latest changes.

I am not able to reproduce this on Arch or Manjaro.

> Off-topic: There is another annoyance that's not directly related, but makes using the neat custom G-Code editing feature useless, as due to the size of the **`Edit Custom G-Code`** window, which can't be changed, the “save” button is hidden at the bottom of the screen.

Please create a separate enhancement request for this.

 
> 😅 Absolutely off-topic: Sorry, since the following is kind of abandoned I dare to ask: Could you by any chance have a look at this as well?:
> 
> ```
> https://github.com/SoftFever/OrcaSlicer/pull/2405
> ```

Please create a separate enhancement request for this.

**Review by SoftFever — APPROVED** [review]
LGTM

**Pull request merged**
