### PR TITLE
Fixing high GPU usage when color scheme is set to "Filament" or "Speed"

### LINKED ISSUE #3594: High GPU usage when color scheme is set to "Filament" or "Speed"
### OrcaSlicer Version

1.9.0

### OS version

Windows 10

### Additional system information

CPU: AMD Ryzen 7 3700X
RAM: 32GB
GPU: Nvidia RTX 3060

### Printer

Bambu Lab A1

### How to reproduce

1. Slice a print
2. Change color scheme to "Filament" or "Speed"

### Actual results

The GPU usage should be relatively low when viewing the sliced print with the default color scheme "Line Type" or any of the other schemes apart from filament or speed.
However, when filament or speed is selected, the GPU usage increases from about 1% max to around 48% max when not interacting with OrcaSlicer.
This occurs even when the window is not focussed and is not moused over/being interacted with, and also occurs when the window is minimised.
The high usage does not occur if a tab other than "Preview" is selected, even if filament or speed remains selected on the preview tab.

### Expected results

The GPU usage should remain at the same level as when using all the other color schemes.
If this is not possible then the filament or speed color schemes should at least not have high GPU usage when OrcaSlicer is minimised or the window is not focussed.

### Project file & Debug log uploads

[cube gpu usage bug.zip](https://github.com/SoftFever/OrcaSlicer/files/13880884/cube.gpu.usage.bug.zip)
[debug_Tue_Jan_09_22_43_35_26484.log.zip](https://github.com/SoftFever/OrcaSlicer/files/13880885/debug_Tue_Jan_09_22_43_35_26484.log.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

### PR DESCRIPTION
**Pull request by Azio-Pantheon**
First time contributing, I hope I'm doing this correctly.

# Description
Removed `imgui.set_requires_extra_frame()`, this line causes Slic3r::GUI::GLCanvas3D::render() to be called repeatedly when 'Filament' or 'Speed' is selected in the preview panel (even when OrcaSlicer is minimized)

This should fix #3594 

I see that this line was added in #3363. I don't fully understand the intention behind it, but removing this line does not seem to affect the legend window fix

# Screenshots/Recordings/Graphs
Now in "Filament" or "Speed" preview, GPU usage is 0% when OrcaSlicer is minimized or idle.

Before:
Screenshot 2024-07-22 183641

After:
Screenshot 2024-07-22 183917

### CODE REVIEW

**Comment by vovodroid** [comment]
Great finding! It also reduce CPU usage, not only GPU. Merging it into my fork, thanks!

**Comment by discip** [comment]
@azio25134 
# Thank you SIR! 😃👍

Am I right to assume that the flow-scheme is also affected?

**Comment by vovodroid** [comment]
> Am I right to assume that the flow-scheme is also affected?

I don't see such problem in Orca 2.1.1, so your fix affects only Filament and Speed.

**Review by SoftFever — APPROVED** [review]
Fantastic!
Thank you

**Comment by birdoplo** [comment]
In which file is the string imgui.set_requires_extra_frame() ?

**Comment by vovodroid** [comment]
See changes https://github.com/SoftFever/OrcaSlicer/pull/6223/files

**Pull request merged**
