### PR TITLE
Restructured Flashforge process profiles

### PR DESCRIPTION
**Pull request by mariuske**
After tweaking several parameters for the Flashforge profiles the past weeks, I found that the existing structure was very cumbersome to work with. Therefore, I have now restructured the Flashforge process profiles with inspiration from the BBL profiles.

**Highlights:**
- Added a structure for inheritance
- Distributed the parameters across the new structure to avoid duplicate values.
- Most of the parameter values are unchanged compared with the old profile structure, but has been given a new "home"
- As a result of the new structure, the AD5M Pro 0.6 profile has been cleaned up as this was not in sync with the other profiles
- The new structures makes it easier to both tweak existing and expand with new profiles

There is definitely more work to be done to further optimize the profile structure, but I believe this is a good start with minimal impact.

The new profile structure has been successfully loaded and verified with my setup, but it would be great if someone can review the end result.

@FlashforgeOfficial - FYI

@SoftFever - Please review the end result before merging. Thank you!

### CODE REVIEW

**Review by FlashforgeOfficial — APPROVED** [review]

**Review by FlashforgeOfficial — APPROVED** [review]
@mariuske We are grateful for the significant efforts made towards improvement. Sorry for the delay, I had been kind of occupied with other testing lately. 

This new structure looks a lot better than the original construction; I just realized the 'fdm_process_flashforge_common.json' file was never inherited in the old version lol.

**Comment by mariuske** [comment]
Great, thank you for the review and approval @FlashforgeOfficial 👍

**Comment by mariuske** [comment]
@SoftFever - This PR is now ready to be merged.

**Comment by SoftFever** [comment]
@mariuske Thank you.
Can you take a look at the conflicts?

**Comment by mariuske** [comment]
@SoftFever  - The conflicts were related to this [commit](https://github.com/SoftFever/OrcaSlicer/commit/5213fbfa86938f3fe62c856b5246514a7e246289), should be solved now and ready to be merged.

**Comment by mariuske** [comment]
A few more conflicts after this [commit](https://github.com/SoftFever/OrcaSlicer/commit/565732a0278c2b463fb6252a87d6e4662ae7c33f).

These have now been sorted out and we are ready for a merge @SoftFever ;)

**Review by SoftFever — APPROVED** [review]
Looks good

**Comment by SoftFever** [comment]
Merged.
Thanks

**Pull request merged**
