### PR TITLE
Use one loop for draft shield

### PR DESCRIPTION
**Pull request by vovodroid**
Currently draft shield loops number is set by skirt loops option. If it's set to one

image

there is a high chance it will be disconnected because of shield warping. If it's set to several loops

image

there is a lot of time and material waste (and probably adhesion is also affecting by thick wall warping).

This PR sets draft shield to one loop:

image

thus combining good bed adhesion and draft protection.

Actually draft shield loops number could be configurable, but from my extensive usage of  draft shield with materials like ABS/ASA it's not necessary. Three-five first layer loops and one loop shield works very good.

### CODE REVIEW

**Comment by igiannakas** [comment]
THANK YOU!! I was busting my head on how to do the same when I enabled the feature and could not figure it out no matter what I tried! That is a nice and simple fix! Well done on this!

**Review by SoftFever — APPROVED** [review]
Looks good.
Thank you!

**Comment by vovodroid** [comment]
Actually **Draft Shield** parameter also becomes excessive, one may just set skirt height to big enough value.

**Comment by igiannakas** [comment]
> Actually **Draft Shield** parameter also becomes excessive, one may just set skirt height to big enough value.

I’d keep the draft shield as not all users relate to this as a work around. Plus it’s automatic in its height vs trying to calculate it manually. Prusa has this available so for consistency between slicers I’d suggest it’s retained. 

For draft shield you don’t need many loops to be honest. One can make the argument that a one wall draft shield is weaker and may crack, but so will a multi wall one, so I’d say just just keep one option - enable draft shield and you’re done. I think 😀

**Comment by vovodroid** [comment]
> one wall draft shield is weaker and may crack

It warps, not cracks. but still glued to the base. Multiple wall produce stronger detaching force.

> I’d say just just keep one option - enable draft shield

So just OFF and ON. I agree.

**Comment by locki-cz** [comment]
this function destroyed our standard skirt 3 loops and 3 layer height for easy remove??? :( It is verhy hard remove from some sheets just on layer, this is why we user 3x3 for skirts .... for tune first layer and easy remove, can it be somehow revertec back and implemented skirt some loop count on high object better way?

**Pull request merged**
