### PR TITLE
Printer profile checker and updater

### PR DESCRIPTION
**Pull request by anselor**
Generates a vendor profile definition by parsing all of the specific profiles in the directory.
Reduces the amount of manual copy/paste required to maintain all of the redundant duplicated information

Ran the script on a selection of vendors (Anker, Creality, Sovol, and Ultimaker) to demonstrate the result.

### CODE REVIEW

**Comment by SoftFever** [comment]
@anselor, This is a sweet idea. However, I have some concerns about how to use it.

The first issue is that it creates conflicts with the handmade changes. I don't expect people to use this script exclusively to create the vendor.json file, hence this could be a real issue.

The second concern is that rebuilding the vendor.json file from the folder somewhat defeats the purpose of having the vendor.json file serve as a manifest file. The software is designed to find profiles listed in the vendor.json, not the other way around.

This script, however, could be a perfect validation tool if we modify it slightly so that it checks whether all the files listed in the vendor.json exist in the folder.

I'd like to hear your thoughts.

**Comment by SoftFever** [comment]
> @anselor, This is a sweet idea. However, I have some concerns about how to use it.
> 
> The first issue is that it creates conflicts with the handmade changes. I don't expect people to use this script exclusively to create the vendor.json file, hence this could be a real issue.
> 
> The second concern is that rebuilding the vendor.json file from the folder somewhat defeats the purpose of having the vendor.json file serve as a manifest file. The software is designed to find profiles listed in the vendor.json, not the other way around.
> 
> This script, however, could be a perfect validation tool if we modify it slightly so that it checks whether all the files listed in the vendor.json exist in the folder.
> 
> I'd like to hear your thoughts.

Some updates regarding to the validator idea.
I have implemented one with existing c++ codes #4249 #4251

**Comment by anselor** [comment]
I'm not sure what happened to my previous reply. Github seems to have deleted it?

In any case, I've updated the script a bit to support both validation and auto-update use cases. @SoftFever 

```
$ python ./profile_helper.py Test
Validating /home/anselor/source/OrcaSlicer/resources/profiles/Test.json...
[machine_model_list] Manifest entries with missing files:
 - Bogus machine: machine/Non-existent.json
[filament_list] Manifest entries with missing files:
 - Bogus Filament: filament/Not Present.json
 - Anker Generic PA: filament/Anker Generic PA.json
[filament_list] Profiles found but missing in manifest:
 - Anker Generic PAAA: filament/Anker Generic PA.json
Type SYNC to synchronize manifest to match profiles /home/anselor/source/OrcaSlicer/resources/profiles/Test.json
```

**Comment by anselor** [comment]
@SoftFever I re-ran the generator based on the latest updates in the main branch and pushed up the results.

**Comment by anselor** [comment]
@SoftFever Is there anything else you want to see here?

**Comment by anselor** [comment]
> > @anselor, This is a sweet idea. However, I have some concerns about how to use it.
> > The first issue is that it creates conflicts with the handmade changes. I don't expect people to use this script exclusively to create the vendor.json file, hence this could be a real issue.
> > The second concern is that rebuilding the vendor.json file from the folder somewhat defeats the purpose of having the vendor.json file serve as a manifest file. The software is designed to find profiles listed in the vendor.json, not the other way around.
> > This script, however, could be a perfect validation tool if we modify it slightly so that it checks whether all the files listed in the vendor.json exist in the folder.
> > I'd like to hear your thoughts.
> 
> Some updates regarding to the validator idea. I have implemented one with existing c++ codes #4249 #4251

I reviewed the c++ validator you added and it only checks for the existence of files which is insufficient for properly validating manifest files. Profile names and inheritance tree all must match. 

While it's may technically be true that the manifest identifies what profiles to load. Looking through all of the profiles, in practice it is just an additional burden of text strings that must be manually copied and synced across numerous files. This is error prone and a source of days of frustrating blind debugging when updating printer profiles.

**Comment by SoftFever** [comment]
> @SoftFever Is there anything else you want to see here?

Thank you for your patience.

I gave the script's validation a try. Here are some of my high-level feedback and thoughts:

Use explicit mode for validation and sync features. In validation mode, it would be better to stay away from user input and return 0 if validation passes, or 1 if an error is found.
It would be better to have both errors and warnings. Profiles listed in the vendor.json but not in the subfolder should be treated as errors. Warnings should be generated if vice versa.
A profile's name can be different from the file name. Currently, the script assumes that they are always the same, hence false positives may be reported.

**Comment by SoftFever** [comment]
It seems the PR has gone stale. 
I'm closing it for now. 
Feel free to reopen it in the future.

**Pull request closed without merging**
