### PR TITLE
Resolves #5808: Fix missing K1C processes

### LINKED ISSUE #5808: k1c nozzle profile dont show up.
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.1.0

### Operating System (OS)

Windows

### OS Version

10

### Additional system information

_No response_

### Printer

k1c

### How to reproduce

add printer k1c
nozzle 0.6,0.8

### Actual results

no printig profile . default more not
Screenshot 2024-06-22 154010

### Expected results

by the k1 ist comming

### Project file & Debug log uploads

[log.zip](https://github.com/user-attachments/files/15936929/log.zip)

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Anything else?

i had crashes but dont no why . its chainese for me

### PR DESCRIPTION
**Pull request by BruffyT**
Resolves #5808

Screenshots of evidance that they are now showing attatched below

Before not showing layer height profiles: 

image

After now showing the profiles:

**0.6mm Nozzle:**

Screenshot 2024-06-23 at 14 07 16

**0.8mm Nozzle:**

Screenshot 2024-06-23 at 14 07 06

Update after [ee52ec3]:

**0.6mm Nozzle:**

Screenshot 2024-06-26 at 01 13 00

**0.8mm Nozzle:**

Screenshot 2024-06-26 at 01 13 14

### CODE REVIEW

**Comment by Ocraftyone** [comment]
Hello! Could you provide more if a description of what is being fixed? It is not very clear with only the after screenshots.

Also, when creating a PR that resolves an issue, please use a supported keyword followed by the issue number. This links the issue the the PR and automatically closes the issue when the PR is merged. Here are some details on that: https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests

**Comment by BruffyT** [comment]
Hi, I have updated the details for you. Hope this is okay.

**Comment by Ocraftyone** [comment]
Oh, I'm sorry. The keyword for linking the issue should be done in the body of the PR, not the title 😁

**Review by Ocraftyone — APPROVED** [review]
Looks good to me 👍

**Comment by Noisyfox** [comment]
I wonder if we should rename the machine profile to include the "()" so it's consistent with K1 profiles instead? Though I guess that could cause compatibility issue for existing user.

**Review by Noisyfox — APPROVED** [review]

**Comment by BruffyT** [comment]
That was my thought @Noisyfox i wanted to cause the least chance of disruption to users

**Review by SoftFever — APPROVED** [review]
LGTM
Thanks

**Pull request merged**
