### PR TITLE
Revamp time cost feature 

### PR DESCRIPTION
**Pull request by cochcoder**
I revamped the time cost feature, so that it would be easier and more accessible for beginners to pros. Besides having to estimate the cost per hour, now you'll need to give your wattage per hour and price per kWh instead. I am open to having this as a separate feature from the current time cost system, however, I don't currently know how to do this as I am new to C++.  

Any feedback would be appreciated! 

To Do:

- [x] Add electric consumption & electric price to system options
- [x] Add electric cost calculation 
- [x] Rename total_cost to total_filament_cost for easier to understand code
- [x] Add electric cost & filament cost to Line Type sub-menu in legend
- [x] Add filament cost to Filament sub-menu in legend
- [x] Add total cost to Line Type sub-menu in legend
- [x] Add electric cost, filament cost, and total cost in All Plates menu
- [x] Add a button/other costs field for a substitute of the current cost per hour field

### CODE REVIEW

**Comment by Eldenroot** [comment]
I need to split the cost - to see coat for filament amd cost for others (electricity etc)

**Comment by cochcoder** [comment]
Do you mean that the standard time cost feature is the best for you? Or do you mean that you'd like to see the cost of filament and electricity separately in the statistics?

**Comment by Eldenroot** [comment]
Separately, because sometimes I need to know the proce for filament, electricity and time stabdalone

**Comment by cochcoder** [comment]
Do you have any idea where the file for the Total Estimation menu would be?

**Comment by Eldenroot** [comment]
In the legend (where you can see filament used etc.)

**Comment by cochcoder** [comment]
> In the legend (where you can see filament used etc.)

I was wondering what the file that controls the legend would be located (I haven't dealt with GitHub repos this complex). I think I found the file under src/slic3r/GUI/GCodeViewer.cpp?

**Comment by SoftFever** [comment]
@cochcoder 
do you mind to share some screenshots?

**Comment by cochcoder** [comment]
> @cochcoder do you mind to share some screenshots?

Sure!

In the printer settings I replaced time cost with electric consumption and electric cost:
Screenshot_electric_cost
I am currently trying to change the cost value in the legend to instead be two separate values, filament cost & energy cost:
Screenshot_wanttochange

**Comment by Eldenroot** [comment]
Anyway, just a note. I know that my buddy use time cost feature in a different way.

He just set some value (includes electricity cost, maintance cost, cost of his work). So all is cobered by one value.

With thia PR this ability is lost. It could be solve with another field and settings.

**Comment by cochcoder** [comment]
> Anyway, just a note. I know that my buddy use time cost feature in a different way.
> 
> He just set some value (includes electricity cost, maintance cost, cost of his work). So all is cobered by one value.
> 
> With thia PR this ability is lost. It could be solve with another field and settings.

I was thinking about having a button so that the user could choose between either the current system or the system I am currently making for this exact reason. However, I'm not sure how I would do this, I'll start looking into it after I get this system working, any pointers on how I would do this would be great! Also, I am marking this PR as a Draft as I didn't realize there would be this many changes. Thank you for all the great feedback!

**Comment by cochcoder** [comment]
@Eldenroot @SoftFever 
Should I have a button so that the user can swap between the two calculations, or should I have a other costs field that can be used with the new fields?

**Comment by Eldenroot** [comment]
> @Eldenroot @SoftFever Should I have a button so that the user can swap between the two calculations, or should I have a other costs field that can be used with the new fields?

Well, not sure.

I would like to see all:

- time cost - electricity - set value per W?
- time cost - filament - set value per g
- time cost - time (others - maintanance, person cost) - set value per 1 hour

Then TOTAL of all these three

**Comment by cochcoder** [comment]
> > @Eldenroot @SoftFever Should I have a button so that the user can swap between the two calculations, or should I have a other costs field that can be used with the new fields?
> 
> Well, not sure.
> 
> I would like to see all:
> 
>     * time cost - electricity - set value per W?
> 
>     * time cost - filament - set value per g
> 
>     * time cost - time (others - maintanance, person cost) - set value per 1 hour
> 
> 
> Then TOTAL of all these three

Do you think that it should be called time cost or other costs?

**Comment by Eldenroot** [comment]
Others I think ?

**Comment by cochcoder** [comment]
Ok, I think it is all good now, as long as there are not any bugs I missed. 

Here are some screen shots: 
Screenshot_1
Screenshot_2
Screenshot_3
Screenshot_4
If you don't enter a value for any of the cost fields, they won't be shown in the total estimation; if no cost can be calculated, then even the total cost estimation won't be shown. 
Screenshot_demo
Screenshot_demo_2

**Comment by Eldenroot** [comment]
Sweet.

One more request - add a custom option to display currency in [$] brackets maybe after the value.

Currency - text input box.

**Comment by cochcoder** [comment]
I'll definitely add this as a field instead of adding it in the config wizard, as I don't currently know how to do this (even though I would love setting it up that way)

**Comment by cochcoder** [comment]
Everything should be good now

**Comment by cochcoder** [comment]
Yes, I'll add try to add currency later, once I understand more of C++. Thank you for your feedback!

**Comment by EdwardChamberlain** [comment]
Would it be preferable to simply reduce this to a "running cost / hr" metric and allow the user to roll in their energy costs / depreciation themselves. While it offer less specific functionality and detail it does reduce the complexity for the user while still providing the same benefit of exposing them to more accurate cost data in the slicer.

**Comment by cochcoder** [comment]
If the user wants to, they can only fill out the other costs field, and it will work the same as the current time cost system.

**Comment by cochcoder** [comment]
@SoftFever Are there any changes you think need to be implemented?

**Comment by bwstandard** [comment]
This would be cool to have in the main program. Hopefully it gets approved.

**Comment by Eldenroot** [comment]
I hope so

**Comment by pedrohbraga** [comment]
Thank you so much for making this feature! What is missing for it to be incorporated into a future build? I am looking forward to using it!

**Comment by cochcoder** [comment]
> Thank you so much for making this feature! What is missing for it to be incorporated into a future build? I am looking forward to using it!

Nothing should be missing for this to be merged. It is all up to timing now and when it would be best implement a new feature that could have unforeseen bugs. I'm sure that SoftFever has it all planned out. 

Thank you all for the support, I would have never thought that one of my first PRs would be so liked!

**Comment by vgdh** [comment]
But the printer consumption is not a static thing. You need to measure it average consumption and with that you can already  know the cost: electricity_cost_watt_per_hour * printer_average_consumption_in_hour

**Comment by cochcoder** [comment]
> But the printer consumption is not a static thing. 

Yes, that is true, the system that is from this PR aims to make it easier for others to get a more detailed cost breakdown if they so wish, even though it could be wildly inaccurate, it depends on the print. However, this PR does open the pathway for someone to make an accurate electric consumption calculator and only have to edit one value in this PR while getting all the other features it adds. 

> You need to measure it average consumption and with that you can already know the cost per hour: electricity_price_per_watt * printer_average_consumption_watt_in_hour

That is true, however, most people won't want to go to that extent to get an estimation of their electric cost. Again, this PR is meant to be more of a stepping stone to open the current time cost feature to either being more complex & accurate or just getting the job done (even if it comes at the cost of accuracy)

**Comment by cochcoder** [comment]
For whatever reason this PR was closed by GitHub, I reopened it at #4840

**Pull request closed without merging**
