### PR TITLE
05-14 [Flashforge] fix 5M gcode and consolidate the filenaming

### PR DESCRIPTION
**Pull request by Bai825**
# Description

1. Fix the 5M series gcode
2. Fix the compatible printers for G3U filaments
3. Improve the filenaming

# Screenshots/Recordings/Graphs

## Tests

Profiles running normally on local portable version.

### CODE REVIEW

**Comment by Bai825** [comment]
Hi,  @SoftFever ,for your review!

**Comment by RikshaDriver** [comment]
@Bai825 remove the additional "flashfoge" STL files as they are not required.

**Comment by SoftFever** [comment]
There are errors, please check

**Comment by RikshaDriver** [comment]
@FlashforgeOfficial @Bai825 @Flashforge what about removal of legacy filament files?

Regarding the errors,

either rename:

```
resources\profiles\Flashforge\machine\Flashforge Adventurer 3 Series 0.4 nozzle.json
resources\profiles\Flashforge\machine\Flashforge Adventurer 3 Series 0.6 nozzle.json
```

to 

```
resources\profiles\Flashforge\machine\Flashforge Adventurer 3 Series 0.4 Nozzle.json
resources\profiles\Flashforge\machine\Flashforge Adventurer 3 Series 0.6 Nozzle.json
```


or update `resources\profiles\Flashforge.json` by changing the following lines:



```
	{
      "name": "Flashforge Adventurer 3 Series 0.4 Nozzle",
      "sub_path": "machine/Flashforge Adventurer 3 Series 0.4 Nozzle.json"
    },
    {
      "name": "Flashforge Adventurer 3 Series 0.6 Nozzle",
      "sub_path": "machine/Flashforge Adventurer 3 Series 0.6 Nozzle.json"
    },
```


to



```
	{
      "name": "Flashforge Adventurer 3 Series 0.4 Nozzle",
      "sub_path": "machine/Flashforge Adventurer 3 Series 0.4 nozzle.json"
    },
    {
      "name": "Flashforge Adventurer 3 Series 0.6 Nozzle",
      "sub_path": "machine/Flashforge Adventurer 3 Series 0.6 nozzle.json"
    },
```

**Comment by Bai825** [comment]
> @FlashforgeOfficial @Bai825 @FlashForge what about removal of legacy filament files?
> 
> Regarding the errors,
> 
> either rename:
> 
> ```
> resources\profiles\Flashforge\machine\Flashforge Adventurer 3 Series 0.4 nozzle.json
> resources\profiles\Flashforge\machine\Flashforge Adventurer 3 Series 0.6 nozzle.json
> ```
> 
> to
> 
> ```
> resources\profiles\Flashforge\machine\Flashforge Adventurer 3 Series 0.4 Nozzle.json
> resources\profiles\Flashforge\machine\Flashforge Adventurer 3 Series 0.6 Nozzle.json
> ```
> 
> or update `resources\profiles\Flashforge.json` by changing the following lines:
> 
> ```
> 	{
>       "name": "Flashforge Adventurer 3 Series 0.4 Nozzle",
>       "sub_path": "machine/Flashforge Adventurer 3 Series 0.4 Nozzle.json"
>     },
>     {
>       "name": "Flashforge Adventurer 3 Series 0.6 Nozzle",
>       "sub_path": "machine/Flashforge Adventurer 3 Series 0.6 Nozzle.json"
>     },
> ```
> 
> to
> 
> ```
> 	{
>       "name": "Flashforge Adventurer 3 Series 0.4 Nozzle",
>       "sub_path": "machine/Flashforge Adventurer 3 Series 0.4 nozzle.json"
>     },
>     {
>       "name": "Flashforge Adventurer 3 Series 0.6 Nozzle",
>       "sub_path": "machine/Flashforge Adventurer 3 Series 0.6 nozzle.json"
>     },
> ```

Thanks!
Yes, I was intended to keep all the naming uniform with first letter being capital letter. Somehow I submit the commit, the machine profile name for ad3 were still like Flashforge Adventurer 3 Series 0.4 nozzle.json and Flashforge Adventurer 3 Series 0.6 nozzle.json. I am gonna rewind this part change submit change for other parts.

**Pull request closed without merging**
