### PR TITLE
Adds printer profiles for Qidi printers

### PR DESCRIPTION
**Pull request by fr3ak2402**
These files contain the default QIDI profiles released for the QIDI printers

Note: this PR also holds the PR #846 (add QIDI X Plus 3 Printer Profile) of @Musicdad12 with minor changes!!!

The files include the following....
Qidi Filaments:

Qidi Generic ASA, Qidi Generic ABS, Qidi Generic PA-CF, Qidi Generic PA, Qidi Generic PC, Qidi Generic PETG-CF, Qidi Generic PETG, Qidi Generic PLA-Silk, Qidi Generic PLA-CF, Qidi Generic PLA, Qidi Generic PVA, Qidi Generic TPU.

Qidi X-Smart 3:
Printer image (180x180)
Custom Printing Plate Texture (512x512)(SVG) - the manufacturer plate imitated
Hotend Model (STL) - the manufacturer plate imitated
0.4 Nozzle Profile
0.12 Process Profile (Fine)
0.16 Process Profile (Optimal)
0.20 Process Profile (Standard)
0.25 Process Profile (Draft)
0.30 Process Profile (Extra Draft)

Qidi X-Plus 3:
Printer image (180x180)
Custom Printing Plate Texture (512x512)(SVG) - the manufacturer plate imitated
Hotend Model (STL) - the manufacturer plate imitated
0.4 Nozzle Profile
0.12 Process Profile (Fine)
0.16 Process Profile (Optimal)
0.20 Process Profile (Standard)
0.25 Process Profile (Draft)
0.30 Process Profile (Extra Draft)

Qidi X-Max 3:
Printer image (180x180)
Custom Printing Plate Texture (512x512)(SVG) - the manufacturer plate imitated
Hotend Model (STL) - the manufacturer plate imitated
0.4 Nozzle Profile
0.12 Process Profile (Fine)
0.16 Process Profile (Optimal)
0.20 Process Profile (Standard)
0.25 Process Profile (Draft)
0.30 Process Profile (Extra Draft)

@SoftFever, you need to look at the settings_id & filament_id again, I don't know if I have set them correctly.

### CODE REVIEW

**Review by SoftFever — APPROVED** [review]
LGTM

**Comment by SoftFever** [comment]
Thank both of you.

**Comment by fr3ak2402** [comment]
Hello @SoftFever, unfortunately I can't test the profile like this as I don't own a Windows computer and have a Mac.

How far did the profile not work?

**Comment by fr3ak2402** [comment]
@SoftFever, I am setting up a Windows11 machine with Parallels on my Mac. Then I can test the problem better

**Comment by scottmudge** [comment]
Why are there so many commits of images/files being deleted then added again? Why delete, commit, add, then commit again? Rather than just changing the file and committing the change?

Adding, deleting, then adding again a bunch of binary data is going to inflate the repo size way larger than it needs to be. Every time the an image file is added or deleted, git is going to have to keep track of every changed byte, which means cloning the repo isn't just going to be the size of the current image(s) (or other binary data) at the tip, but will include all of the images ever added or deleted in all past commits.

It's very inefficient, and is another reason to squash all of these single-file commits down to a single commit before creating a PR. It will erase all of the unneeded and unnecessary add/remove/etc commits, and all of the binary data changes in between. 

If it were me, I would squash/erase all of the unnecessarily granular commits, then use BFG to clean up all of the unnecessary history.

**Pull request merged**
