### PR TITLE
Consolidate 3rd party printer profiles (V1.x -> V2.x)

### PR DESCRIPTION
**Pull request by fr3ak2402**
@SoftFever 

I closed the old PR that led to your main branch. Now I have created a new PR that follows the branch you suggested.

I am a little confused right now. By profile folder, do you mean the folder in which all profiles are stored, where I have selected a printer from the printer selection ? and not the profile folder with all profiles. So I have understood that, based on the changes in this branch....

Yes, I can add to the JSON file, but I'm not quite sure how that works... because not everything has been adjusted in this branch so that the old file names are compared with the new file names.

One problem we will have is that some profiles have been completely rebuilt and have not only received a renaming of the file name, as it was not possible to carry out the new naming scheme for these profiles.

Each printer has now received its own processes and no longer shares these with another printer, so one file has subsequently become two files, for example...

### CODE REVIEW

**Comment by SoftFever** [comment]
By profile folder, I meant the data folder. The one in Application support folder or Roaming folder. e.g. ~/Library/Application Support/OrcaSlicer-profile_work

> One problem we will have is that some profiles have been completely rebuilt and have not only received a renaming of the file name, as it was not possible to carry out the new naming scheme for these profiles.

> Each printer has now received its own processes and no longer shares these with another printer, so one file has subsequently become two files, for example...

Hmmm... This is not good. Let's see if we can work out a solution for it. Otherwise, we can't make such changes.
Also, `Each printer has now received its own processes and no longer shares these with another printer` is not always preferable. For example, Voron 2.5/Trident 250/300/350 printers are better to share one process profile.

**Comment by scottmudge** [comment]
Maybe I'm not necessarily interpreting the PR correctly, but this seems like a nightmare to maintain. I thought the point of having shared JSON/configs was that you have an easy to maintain tree of inheritance, rather than now hundreds/thousands of new JSON files to maintain when you want to update a printer config. And having a separate stock config for every conceivable nozzle diameter for every printer... what's the intention behind that? Isn't it easier just to make a small change to a local config when you have a non-standard diameter (I think I've read somewhere that over 90% of 3D printer owners just stick with 0.40mm).

**Comment by fr3ak2402** [comment]
@scottmudge 

The basic idea was that we agree on a uniform naming of the files for the printer profiles and then apply this to the existing profiles. We have agreed on the following naming:

**Printer family filenames:**
Printer family -> `{Printer manufacturer}.json`

**Filament filenames:**
Generic filament -> `{Printer manufacturer} Generic {filament type}.json`
Vendor filament -> `{Filament vendor} {filament type}.json`

**Printer machine filenames:**
Printer machine -> `{Printer manufacturer} {machine name}.json`

Note: The Model_ID in the machine file is set as follows -> {Printer manufacturer}-{machine name}
A few things have to be considered here, which I will show in examples

Printer machine nozzle -> `{Printer manufacturer} {machine name} ({nozzle diameter} nozzle).json`

**Printer process filenames:**
Printer process -> `{layer height}mm {quality} @{Printer manufacturer} {machine name} ({nozzle diameter} nozzle).json`

**Printer assets filenames:**
Printer thumbnail -> `{Printer manufacturer} {machine name}_cover.png (180x180) pixels`
Buildplate model -> `{Printer manufacturer}_{machine name}_buildplate_model.stl`
Buildplate texture -> `{Printer manufacturer}_{machine name}_buildplate_texture.png` or `{Printer manufacturer}_{machine name}_buildplate_texture.svg`
Hotend model -> `{Printer manufacturer}_{machine name}_hotend.stl`

If the printer is from a series or generation, the file will be named as follows:

Hotend model -> `{Printer manufacturer}_{series name}_{gen number}_hotend.stl`

Note: This is only valid if the complete series and generation used the same hortend. Otherwise a separate hotend is created for each printer.

I have created an examples of how this looks with the new scheme.
`Example Qidi:`
**Printer family filenames:**
`Qidi.json`

**Filament filenames:**
`Qidi Generic PLA.json`
`AddNorth ePLA.json`

**Printer machine filenames:**
`Qidi X-Max 3.json`
`Qidi X-Max 3 (0.4 nozzle).json`
`Qidi X-Max 3 (0.6 nozzle).json`

**Printer process filenames:**
`0.20mm Standard @Qidi Xmax3 (0.4 nozzle)`
`0.20mm Standard @Qidi Xmax3 (0.6 nozzle)`

**Printer assets filenames:**
`Qidi X-Max 3_cover.png`
`qidi_xmax3_buildplate_model.stl`
`qidi_xmax3_buildplate_texture.png`
`qidi_xseries_gen3_hotend.stl`

`Example Snapmaker:`
**Printer family filenames:**
`Snapmaker.json`

**Filament filenames:**
`Snapmaker Generic PLA.json`
`AddNorth ePLA.json`

**Printer machine filenames:**
`Snapmaker J1.json`
`Snapmaker J1 (0.4 nozzle).json`
`Snapmaker J1 (0.6 nozzle).json`

**Printer process filenames:**
`0.20mm Standard @Snapmaker J1 (0.4 nozzle)`
`0.20mm Standard @Snapmaker J1 (0.6 nozzle)`

**Printer assets filenames:**
`Snapmaker J1_cover.png`
`snapmaker_j1_buildplate_model.stl`
`snapmaker_j1_buildplate_texture.png`
`snapmaker_j1_hotend.stl`

**Model_ID:**
`Example Qidi:`

Qidi X-Max 3 -> `Qidi-XMax-3`
Qidi X-Max -> `Qidi-XMax`
Qidi X-CF Pro -> `Qidi-XCF-Pro`

`Example Snapmaker:`

Snapmaker J1-> `Snapmaker-J1`
Snapmaker A250-> `Snapmaker-A250`
Snapmaker A350-> `Snapmaker-A350`

`Example Creality:`

Creality Ender-3 S1 Pro-> `Creality-Ender3-S1-Pro`


Before this definition, the profiles were all a nightmare, since everyone built their profiles so that their printer would work. That's what they looked like, the main thing is that my printer works and I don't care about the addition of other printers. Which is very difficult for me when someone wants another printer and I can then completely rebuild an existing profile of a printer family in order to add a printer. Which has often given me a headache. Because then I first have to understand how the profile is structured. Now all profiles are uniform and it is also clear which file belongs to which printer and to which nozzle.

-------------------------------------------------------------

Later I thought to myself, if I'm already revising all the profiles. Then I can also directly unify the images of all printer models so that they are similar (perspective, background, etc.). Since they were all very different...

After that I noticed that not all printers had a model for a buildplate or not even a texture. I changed this in this step by creating files for all printers that did not have them before.

-------------------------------------------------------------

I also always thought that most people use a 0.4 nozzle on their printer, which apparently isn't always the case.

How this came to the care of the other nozzle diameters: 

Many users of the slicer have seen that I have created many profiles and have written to me directly via Discord... Most of them asked if I could create a profile for a printer, but many also asked if I could add more nozzle diameters to existing profiles. 

It quickly became apparent that many users take a machine for a 0.4 nozzle and then create a process for a 0.6 nozzle. Which is not really the intention... They also complained that the selection of processes was very long, which is also logical. Since everything is bound to the 0.4 nozzle.

There were also others who simply wanted to use the slicer and not create profiles for another nozzle size.

As a result, I created additional nozzle diameters (0.2,0.5,0.6,0.8) for all printers, so that the user can simply select the additional nozzle diameter in the printer selection as usual.

To solve the problem with the long lists, I had already thought about and is also part filename naming of the profiles.
This way, each printer can have different nozzles and each nozzle has its own processes without having to rename or rebuild the profiles. 

If you now select a printer with a 0.4 nozzle, only all files for this nozzle of the printer are shown. Likewise if you select a different Nozzle diameter. In addition, the user can also create processes that are large for a specific nozzle directly at the correct nozzle. 

This ensures that the inheritance tree remains small and does not become a huge inheritance tree. Due to the fact that there are many small inheritance trees instead of one, which is getting bigger and bigger, for example with further processes for a different nozzle size.

And not all other files etc. It is also easier for me to create more profiles for new printers in the background, as I no longer have to rename other files, since all printer profiles are now structured in a uniform way and provide an easy overview.

-------------------------------------------------------------

I am also aware that not everyone will create a profile with different nozzles and create the appropriate buildplate files. Since not everyone has the right software for this.

Therefore, I will always collect all added profiles at regular intervals and supplement them in such a way that they also have all nozzle diameters, provided these nozzles are possible with this printer model. I also create the appropriate buildplate files if they are missing.

**Comment by scottmudge** [comment]
Perhaps the better solution here is to instead of having a bunch of static files that are going to be a major pain to maintain in the repo (and update by hand), have a smaller set of primary descriptors/templates and then programmatically generate the default files for each printer type when the application first launches (creates a new default config). With python or or something.

I get the point behind standardizing, but this just seems like a big headache long-term. At least to me. But I generally subscribe to the "the best part is no part", or "keep it simple" philosophy.

**Comment by fr3ak2402** [comment]
I am currently working on writing a profile manager for all the profiles of the Orcaslicer, which will manage the profiles etc.

So I will soon take the profiles out of the slicers and you can then only set the printers you really need with the nozzles etc. for yourself, so that everyone can configure the profiles themselves in the selection.

You can also convert PrusaSlicer profiles / SuperSlicer profiles via the Manager so that they work with OrcaSlicer. It should also be possible to create new printer profiles via the manager, etc.

So that it is easier for the user to create a profile etc. for the slicer....

I think my idea with the Profile Manager follows your suggestion with the Script....

**Comment by scottmudge** [comment]
A Profile Manager would be a nice addition!

**Comment by fr3ak2402** [comment]
Yes, I think so too... I have already created a profile library for the Profile Manager. Therefore, I have already started to implement such a manager.

This library should be used to synchronise the local status with a kind of cloud (Github repository). So you can also use profiles in every version of the slicer and drag them into the slicer yourself and don't always have to wait for the next version.

In addition, you should also be able to compare the profiles of other printers via the library or even use them as the basis for a new profile.

So if you want to have a process of a profile, for example, you can simply take it over into the new profile etc.

**Comment by fr3ak2402** [comment]
@SoftFever , @scottmudge 

Maybe someone can help me compile a version of OrcaSlicer myself to test the changes for this PR. I've been trying to solve this problem for hours, but I'm getting desperate....

I am using a Windows 11 Pro (22H2), downloaded and installed VS 2022, cmake, git and Starberry Perl.

In the `build_release.bat` I also changed the generator from `Visual Studio 16 2019` to `Visual Studio 17 2022`.

When I open the Developer Powershell of VS 2022 and change to the folder of my OrcaSlicer project. I run the batch file with the following command: `.\build_release.bat`

A lot of stuff is downloaded, copied and installed. But in the end I always get errors when I build the slicer.

-------------------------------------------------------------

Screenshot 2023-06-19 110433

**Comment by fr3ak2402** [comment]
@SoftFever

I tried this again with VS2019 and also get an error that this fails. I do not know now further, I have now alleys tried what I can think of. Everything that is required to install software I have installed and the batch file I have also run in Developer Powershell from VS2019.

Screenshot 2023-06-19 211053

**Comment by scottmudge** [comment]
Don't use `build_release.bat`, I never got it to work.

Just use cmake directly and follow the general instructions outlined by the PrusaSlicer Windows Build guide. Build the deps first, then use cmake to configure the OrcaSlicer build files (be sure to pass the deps build output path to cmake), and build normally.

I've had no issues with VS2019 and VS2022.

**Comment by fr3ak2402** [comment]
@scottmudge 

Ah okay. I will try that... Thanks for the info. 

Can I then also use oneTBB instead of TBB?

**Comment by scottmudge** [comment]
Just use the TBB produced by building the deps. Newer versions of TBB aren't compatible.

**Comment by fr3ak2402** [comment]
With me he complains that he can not find a TBB installation.

This TBB is not compiled if I understand correctly....

**Comment by scottmudge** [comment]
It's compiled when you build the deps. It's two different cmake steps. Follow the PrusaSlicer build guide.

Go into the <repo>/deps folder, make a new "build" folder here, run cmake from <repo>/deps/build, pointing to the <repo>/deps folder, and build all the deps.

This will install all the dependencies (including building TBB), along with everything else required.

If you look in <repo>/deps, you'll see a TBB folder.

**Comment by fr3ak2402** [comment]
So you use the manual way and not the automatic way via build_win.bat?

**Comment by scottmudge** [comment]
Yes do not use the batch files. They don't work correctly. Plus it makes it very difficult to use tools like VS Code. If you use cmake manually, you can open the cmake project in VS Code for debugging, etc.

**Comment by fr3ak2402** [comment]
okay... so VS code I could also use instead of VS2019 / VS2022?

**Comment by scottmudge** [comment]
No VS Code is just an editor, not a compiler. You still need to install VS 2019/2022 to install the compiler + Windows SDK. I just prefer editing in VS Code over Visual Studio, because visual studio is pretty bloated/slow.

You could also in theory just invoke MSBuild.exe directly to build the solution/project files.

**Comment by fr3ak2402** [comment]
I actually prefer to use VS Code as well, for the reasons mentioned. 

Okay.... and where can I find the MSBuild.exe?

**Comment by fr3ak2402** [comment]
I have now reinstalled VS2022, Git, Cmake and Strawberry Perl and pulled my repository locally....

Now in the Developer Powershell I change to the folder of my local repository and enter run cmake/msbuild ?

**Comment by scottmudge** [comment]
You can use powershell or the native tools command prompt (in Start Menu). But that's the idea. Make sure you build the deps first, don't try building OrcaSlicer first.

**Comment by fr3ak2402** [comment]
cd c:\Users\Fr3ak\Desktop\OrcaSlicer\deps
mkdir build
cd build
cmake .. -G "Visual Studio 17 2022" -DDESTDIR="c:\Users\Fr3ak\Desktop\OrcaSlicer\deps"

msbuild /m ALL_BUILD.vcxproj


I hope I have done everything right so far....

**Comment by scottmudge** [comment]
Try uninstalling any versions of TBB you installed on your system. I can't reproduce, it works fine for me. Building the deps should download TBB:

### TBB.cmake

```
prusaslicer_add_cmake_project(
    TBB
    URL "https://github.com/oneapi-src/oneTBB/archive/refs/tags/v2021.5.0.zip"
    URL_HASH SHA256=83ea786c964a384dd72534f9854b419716f412f9d43c0be88d41874763e7bb47
    CMAKE_ARGS          
        -DTBB_BUILD_SHARED=OFF
        -DTBB_TEST=OFF
        -DCMAKE_POSITION_INDEPENDENT_CODE=ON
        -DCMAKE_DEBUG_POSTFIX=_debug
)

if (MSVC)
    add_debug_dep(dep_TBB)
endif ()
```

**Comment by fr3ak2402** [comment]
I did this on another computer, on this one I never had TBB installed etc....

Yes I know, I saw that too in the deps....

is that maybe because I use a very new Windows 11 or have an AMD processor?

**Comment by scottmudge** [comment]
Shouldn't matter, I have Windows 11 and and AMD

**Comment by fr3ak2402** [comment]
Okay, then it shouldn't matter.

Have the commands been correct that I have entered into the Powershell?

**Comment by fr3ak2402** [comment]
I'll try this again and run it all as admin, maybe that will help

**Comment by fr3ak2402** [comment]
@SoftFever 

I tried this again in a virtual machine and keep the same errors again when I build the deps

Screenshot 2023-06-20 000300

Screenshot 2023-06-20 000318

Maybe the error message will help us...

The virtual machine I have just created for the test...

**Comment by fr3ak2402** [comment]
@scottmudge 

I was able to solve the problems with the TBB, so these no longer appear.... But now I get another problem with the OCCT apparently.

Screenshot 2023-06-20 103222

Funny thing is that the file dep_OCCT.vexproj is also present in this folder.... But according to this log it is not.

Do you maybe know how to fix this?

**Comment by fr3ak2402** [comment]
@SoftFever 

Currently, a problem has arisen that causes the user's custom profiles to disappear after the slicer is restarted. During my test, I noticed the same error, I am currently checking and fixing this error.

So for now I will concentrate on this problem and then continue the JSON list....

**Comment by SoftFever** [comment]
@fr3ak2402 Let me know if you still have compiling issues.

**Comment by SoftFever** [comment]
I'm having difficulties to review and comment in the GitHub review interface due to excessive file changes in in PR.
Here is my comments from my initial code review:
1. Let's spilt the PR into small PRs so that it's easy to test and review. I suggest to create one PR for one vendor.
2. I suggest you focus on one vendor at a time. Once all the changes and challenges have been discussed/agreed/solved in this one, then apply the same changes to the next vendor.
3. I see you created process files for each machine model. This creates too many files and is not desirable. For example, Voron 2.5/Trident 250/300/350 printers should share one process profile.
4. All name changes proposed in this PR should follow the rule of 1 to 1 mapping relation between old and new names. I think it shouldn't be an issue if you follow the comment 3

**Comment by fr3ak2402** [comment]
@SoftFever 

Yes I still have problems with compiling, the one time option I had was to compile it via github....

Unfortunately I couldn't encapsulate this from the main branch either and was forced to put everything in main, which also means that unfortunately it all ends up here in this PR. As Github then gives me an error saying it's not my repository and it can't be done if I change it from main to a branch.

I have tried compiling on the following system:
Mac mini M2 Pro (macOS 13.4.1)
Mac Studio M2 Ultra (macOS 13.4.1)
Mac Book Pro 16" M2 Max (macOS 13.4.1)
iMac 24" M1 (macOS 13.4.1)
Mac Book Pro i7 16" (macOS 13.4.1)
Mac Book Pro i7 16" (Bootcamp Windows 11)
and on all Macs with Parallels under Windows 11

I also tested under my desktop PS with Windows 11 and an AMD Lyzeen 9 5950X.

I always get the error message that the Xcode or Visual Studio project file is not found, whether on Xcode, VS2019 or VS2022.

Meanwhile, I have all the possibilities that occurred to me and all the errors that happened I could fix something like that, but in the end it always led to an error. 

I have installed as described, on the Macs Xcode, about brew all programs and on Windows VS2019, Git, Cmake, Strawberry Perl... additionally VS2022 on windows...

When I run the scripts I always get error messages. In the beginning I already got errors when building the deps, I was able to fix that.... but at the end always the project file is missing or not completely configured

**Comment by SoftFever** [comment]
Your dependencies are not built successfully.
Please ref to this: https://github.com/SoftFever/OrcaSlicer/discussions/1425
Let's move any future compilation related discussion there.

**Comment by fr3ak2402** [comment]
@SoftFever 

I have made the following changes:

1. I have adapted the file names to my suggested naming scheme as discussed. Which you also agreed to...

I have invested several weeks and time of my free time in this change to implement it... so I wanted to have your approval first... and now I should turn everything around again because it is too much?

2. after I had adapted all the profiles, I created several nozzle profiles for all printers, which are also possible for the respective printers.

3. I created and added these files for all printers that did not have a buildplate model and texture.

4. I changed the location of the assets file of a profile so that the current solution and the BBL solution still work independently. So in the new profiles there is an Assets folder that still has subfolders for the Cover, Buildplate and Hotend. I have adjusted this so that everything still works as before, in addition to this solution.

5. I have then set the versions of the profiles to 2.0.0.0, as this is a conclusion from the 1.x version, as the profiles are also managed somewhat differently in the structure. This change is already preparing something I am working on of a Profile Manager with a Profile Library. I have already completed the library in a repository and also documented how the new profiles are structured and what needs to be taken into account, etc. 

During the changeover to the 2.x version, a tester noticed that due profiles worked but no user-defined presets were available after restarting the slicer. Unfortunately, BBL has made the version of the profiles dependent on the slicer version and does not allow any profiles that have a higher version than 1.x, as these are set as incompatible. Therefore, I have set the version back to 1.9.9.9 for the time being, as I have not yet had time to solve the problem...

The goal of the Profile Manager and the Profile Library is to make the profiles independent of release cycles, so that you don't have to wait for a release because of a profile, that offers advantages. In addition, the user can also convert his PrusaSlicer profiles for the OrcaSlicer... Or they can configure only the profiles they need in the slicer.

6. all my changes are always tested by users from the OrcaSlicer community and @hliebischer... Because I can't push something in a PR that doesn't work, I know that other people might see it differently than I do, but this is very important to me. I have also set up a Discord server on which over 140 people have joined by now, this server offers the users and us another contract to the user to clarify certain things or to find out the opinion of the users or their needs. All the changes I have made or plan to make have been well received by the users.

But you can also have a different opinion than me and find my idea bad, which is also okay. 
Yes, there is a lot in this PR, but I couldn't compile it or I still can't...

That I can only do this via Github using an action... But yes I can also split everything into separate PRs if you want...

**Comment by SoftFever** [comment]
> @SoftFever
> 
> I have made the following changes:
> 
> 1. I have adapted the file names to my suggested naming scheme as discussed. Which you also agreed to...
> 
> I have invested several weeks and time of my free time in this change to implement it... so I wanted to have your approval first... and now I should turn everything around again because it is too much?
> 
> 2. after I had adapted all the profiles, I created several nozzle profiles for all printers, which are also possible for the respective printers.
> 3. I created and added these files for all printers that did not have a buildplate model and texture.
> 4. I changed the location of the assets file of a profile so that the current solution and the BBL solution still work independently. So in the new profiles there is an Assets folder that still has subfolders for the Cover, Buildplate and Hotend. I have adjusted this so that everything still works as before, in addition to this solution.
> 5. I have then set the versions of the profiles to 2.0.0.0, as this is a conclusion from the 1.x version, as the profiles are also managed somewhat differently in the structure. This change is already preparing something I am working on of a Profile Manager with a Profile Library. I have already completed the library in a repository and also documented how the new profiles are structured and what needs to be taken into account, etc.
> 
> During the changeover to the 2.x version, a tester noticed that due profiles worked but no user-defined presets were available after restarting the slicer. Unfortunately, BBL has made the version of the profiles dependent on the slicer version and does not allow any profiles that have a higher version than 1.x, as these are set as incompatible. Therefore, I have set the version back to 1.9.9.9 for the time being, as I have not yet had time to solve the problem...
> 
> The goal of the Profile Manager and the Profile Library is to make the profiles independent of release cycles, so that you don't have to wait for a release because of a profile, that offers advantages. In addition, the user can also convert his PrusaSlicer profiles for the OrcaSlicer... Or they can configure only the profiles they need in the slicer.
> 
> 6. all my changes are always tested by users from the OrcaSlicer community and @hliebischer... Because I can't push something in a PR that doesn't work, I know that other people might see it differently than I do, but this is very important to me. I have also set up a Discord server on which over 140 people have joined by now, this server offers the users and us another contract to the user to clarify certain things or to find out the opinion of the users or their needs. All the changes I have made or plan to make have been well received by the users.
> 
> But you can also have a different opinion than me and find my idea bad, which is also okay. Yes, there is a lot in this PR, but I couldn't compile it or I still can't...
> 
> That I can only do this via Github using an action... But yes I can also split everything into separate PRs if you want...

1. As far as I recall, you mentioned renaming existing profile names and creating new profiles for missing nozzle sizes. I agree with that part. There might have been some miscommunication, but it's common to discover new problems and previously overlooked issues during development, code review, and testing. Unfortunately, we have to make changes to fix them. That's exactly why I suggest working on one vendor/profile first to ensure everything works before moving on to other files. This will help avoid wasted effort.

2. I'm yet to review them
3. Good
4. I'm not clear about the purpose or benefit of this change.
5. The version of profiles should be equal to or less than the application version.
6. Sorry, but I'm not sure what you are trying to express here. If anyone wants to have a discussion with me about the feature development of Orca Slicer, the only place to do so is on the Orca Slicer GitHub Discussions page (https://github.com/SoftFever/OrcaSlicer/discussions). Social platforms like Discord are generally not suitable for technical or serious discussions. GitHub Discussions is currently the only official platform for Orca Slicer.

**Pull request closed without merging**
