### PR TITLE
Improve overhang slowdown granularity & line segmentation handling

### LINKED ISSUE #4553: Slow Down For Overhangs - Artifacts induced by unwanted slowdowns.
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.0.0-beta

### Operating System (OS)

Windows

### OS Version

Windows 10

### Additional system information

_No response_

### Printer

LH Stinger

### How to reproduce

Load the file
Switch preview to Flow and observe unwanted slowdowns continuing out of the overhang areas.
Switch to Classic and observe they are gone.

### Actual results

image

### Expected results

No slowdowns on perimeters with no overhang
More like Classic mode
2024_03_18_4820_orca-slicer

### Project file & Debug log uploads

[cube overhang.zip](https://github.com/SoftFever/OrcaSlicer/files/14638331/cube.overhang.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by igiannakas**
When encountering an overhanging region in non-classic mode, the slicer checks if the extrusion segment leading to the overhang is greater than 4mm. If it is, it splits the extrusion path to smaller segments, irrespective of if the segment will actually get slowed down. It then evaluates and applies the slowdown speeds to the resulting smaller paths depending on their overlap with the perimeter underneath.

However, there are two issues with this approach:
1. if the length of the last path segment from the overhang is less than 4mm, the entire 4mm path is slowed down, even if this is not in an overhanging region (as its last point ends in an overhang). 

This can lead to large visible areas with external wall artefacts, as the entire 4mm area is slowed down, while layers above or below may or may not be, depending on the model geometry, and specifically the length of the extrusion from a corner or sharp edge.

2. because there is no check whether the overhanging lines will be affected by the slowdown for overhangs, it generates unnecessary segmentations if the speeds actually don’t change. This is particularly important for tiny overhangs, like the sides of the benchy hull.

**For example on issue 1 above:**
image
image

Example of the visual impact seen below:
IMG_4031

This PR reduces the artificial 4mm limit to 0.8mm, as it is visually small enough to not cause a significant artefact, hence the visual impact should be diminished to the eye.

image
image

**Same for the curled perimeter speed segmentation here:**
**Before:**
image

Notice the extended slowdown above the "S" and "r"

**After:**
image
Removed unnecessary slowdown while preserving the benchy hull slowdown completely intact in the background (which is really what the curled edges is intended to solve).

**print shots with combined changes**
Before left, after right, taken with top down lighting to illustrate the extrusion variations
IMG_4033

From a distance
IMG_4034

PS. this has been one of my biggest bugbears on visual fidelity, as till now I could not figure out why arbitrarily some lines have large areas where they are slowed down, resulting in external wall artefacts. Finally managed to find the cause :D 

fixes #4553

**edit:**

this PR has been expanded to better handle segmentation of lines on overhangs when applying slowdown.

**Perimeter segmentation / splitting based on overhang degree whether there is an impact on speed:**
The current Orca and Prusa code when it detects a perimeter has even one overhang, it commences segmenting that contiguous extrusion into smaller "chunks" in order to apply the slowdown algorithm. 

However it doesnt check whether the newly generated point needs to be created. For example if the overhanging region doesnt need to change in speed, because it is only slightly overhanging and the user has elected to only slow down after the 20% overhang mark, then this segmentation is not needed, and it just creates more perimeter points and inflates the gcode. Hence why it always doesnt segment below 8mm in line length.

The new approach here checks if the overhang is material enough to change speeds first - if it is, then it proceeds to segment the perimeter into smaller chunks. If not, it leaves the original points untouched, hence saving on gcode volume (and accuracy as artificial points are not created via extrapolation).

**Quantise speed transitions to 1mm/sec**
The currently calculated speed change at an overhang is currently calculated as a float - meaning any arbitrary value is allowed. However from a practical perspective, this is not needed - and may result in a large number of speed changes being emitted to the printer with small deviation from each other. I have currently rounded and quantised the speed changes to 1mm/sec so any speed change that is less than this from the current speed will not be emitted, hopefully making gcode slightly less big and also reduce the overhead on the firmware. 

This may be unnecessary, but feel like it may be a good practice.

**Screenshots:**
image

**Print tests.**
Print test completed successfully. 

Test 1: increased segmentation without consideration on the overhangs and with a 0.8 mm split distance. Can see even with klipper some rounding issues / micro extrusion issues causing spots.

IMG_4098

test 2: this PR now, with segmentation in overhangs only.
IMG_4099

and a comparison
IMG_4100

benefits from improving segmentation remain against the current release:
IMG_4033
IMG_4034

also the current release does create some minor artefacts like the below on occasion, which are eliminated with this PR.

IMG_4102

### CODE REVIEW

**Comment by Ataraxia-Mechanica** [comment]
How about using 2x nozzle size instead of 0.8mm? Hardcoded value might cause some problems with larger nozzles.

**Comment by igiannakas** [comment]
> How about using 2x nozzle size instead of 0.8mm? Hardcoded value might cause some problems with larger nozzles. Or would this cause some problems because the code surrounding it also uses hardcoded values

I don’t think a larger nozzle will have an issue with this - there are plenty of times where a single extrusion is composed of smaller line segments than 0.8 size in a print. The nozzle just prints them as normal as it’s a continuation of the existing line.

**Comment by Ataraxia-Mechanica** [comment]
Yeah, now I think about it, it probably shouldn't matter, didn't read through the description thoroughly, sorry about that. Can you run the build action for your dev branch by the way? A build with both this and dynamic PA within roles would be cool.

**Comment by igiannakas** [comment]
Done, it should be ready in an hour or so

**Comment by igiannakas** [comment]
Edit: I've pushed a tweak to the curled perimeters segmentation too. Dev build restarted.

**Comment by ramorimdias** [comment]
This is awesome, incredible results! Thanks you!

**Comment by igiannakas** [comment]
Turns out 0.8mm segmentation was way too small and it ended up segmenting the path too short for overhangs over smooth surfaces, causing slight extrusion variations.

Re-tuned the variable to 2mm (instead of 4mm default) and the issue is gone and it should also be manageable from a motion system perspective. 

Original use case is still unaffected.

**Comment by igiannakas** [comment]
While this works there is scope for improvement. Marking it as draft and will come back with further commits.

for example the estimate point properties function splits the path even though there may be no slowdown due to an overhang resulting in unnecessary segments.

**Comment by igiannakas** [comment]
So I've made some changes to the approach for overhang speed handling.

**Perimeter segmentation / splitting based on overhang degree whether there is an impact on speed:**
The current Orca and Prusa code when it detects a perimeter has even one overhang, it commences segmenting that contiguous extrusion into smaller "chunks" in order to apply the slowdown algorithm. 

However it doesnt check whether the newly generated point needs to be created. For example if the overhanging region doesnt need to change in speed, because it is only slightly overhanging and the user has elected to only slow down after the 20% overhang mark, then this segmentation is not needed, and it just creates more perimeter points and inflates the gcode. Hence why it always doesnt segment below 8mm in line length.

The new approach here checks if the overhang is material enough to change speeds first - if it is, then it proceeds to segment the perimeter into smaller chunks. If not, it leaves the original points untouched, hence saving on gcode volume (and accuracy as artificial points are not created via extrapolation).

**Quantise speed transitions to 1mm/sec**
The currently calculated speed change at an overhang is currently calculated as a float - meaning any arbitrary value is allowed. However from a practical perspective, this is not needed - and may result in a large number of speed changes being emitted to the printer with small deviation from each other. I have currently rounded and quantised the speed changes to 1mm/sec so any speed change that is less than this from the current speed will not be emitted, hopefully making gcode slightly less big and also reduce the overhead on the firmware. 

This may be unnecessary, but feel like it may be a good practice.

**Screenshots:**
image

**Print tests to follow.**

**Comment by igiannakas** [comment]
As I'm not 100% familiar with the code in that area I've made some assumptions:
1. In the estimate_points_properties method, I've assumed that we need to use the absolute value of the distances - as I am not 100% sure what the negative or positive distance value here means. I'm assuming its offset internally from the line below (negative) or externally (positive) but would be good to confirm this

Eg: (std::abs(curr.distance) > min_distance) || (std::abs(next.distance) > min_distance)) 
EG: (std::abs(p0_dist) > min_distance 

2. I've clamped the minimum segment length to 2mm when in an overhang, instead of 4mm that was in the past. This is an arbitrary value, as was the previous one, but from what I see this seems to be the right value as you really dont want to be creating more segments unecessarily

**Ideas for the future:**
Currently the existing split algorithm and the changes in this PR creates at most 2 new points, i.e. subdivides the line in consideration to 3 segments **irrespective if the overhang angle** (i.e. distance from the line underneath) being similar to each other. 

This is unnecessary in some cases, i.e. a bridge, as the overhang angle doesnt really change, so why bother splitting this line either. Another change that could be implemented is to check whether the overhang angle of the produced points is similar to each other (within some tolerance). If it is, skip creating them as we are probably just printing a straight overhang line instead of a complex curve that would benefit from different speeds per segment.

**Comment by igiannakas** [comment]
Print test completed successfully. 

Test 1: increased segmentation without consideration on the overhangs. Can see even with klipper some rounding issues / micro extrusion issues causing spots.

IMG_4098

test 2: this PR now, with segmentation in overhangs only.
IMG_4099

and a comparison





benefits from improving segmentation remain against the current release:

**Comment by celtare21** [comment]
Would love to see this merged!

**Comment by igiannakas** [comment]
It needs more testing - both from the community and myself. It’s a pretty radical change in an important area of the slicer so any consequences need to be evaluated. 
Personally I’d love some real world feedback on the feature as I’m currently only testing it on a Voron and X1C with both being high speed printers with reasonably capable MCUs

**Review by SoftFever — APPROVED** [review]
Look good!
I noticed this artefacts too, this improvement is fantastic!

**Review by SoftFever — APPROVED** [review]

**Comment by SoftFever** [comment]
Could you take a look at the conflicts?

**Comment by igiannakas** [comment]
Of course no problem. I’ll get them sorted in the next couple of days

**Review by SoftFever — APPROVED** [review]
Fantastic!
Thank you

**Comment by igiannakas** [comment]
Think its done :)

**Review by SoftFever — APPROVED** [review]

**Comment by Rickthebig** [comment]
I was investigating how bridge settings work and found some inconsistencies using the current Orca v. 2.1.1, which apparently are corrected using a version with this feature #5996 implemented (thanks to igiannakas who provided me with that version).

I have a number of bridges, for which I changed settings per-object wise:
Namely, bridge speed (external bridge):

image

Speeds are in the range 10-70 mm/s in the row. What do I see then?
The 1st layer of all bridges have the same speed! See this:

image

Bridge speed settings affect only the topmost layer, as one can see here:

image

Obviously, the crucial speed for a bridge is the one of the 1st layer. This seems a bit wrong to me. In all of these cases, "Slow down for curled perimeters" was set and then the speed of bridge lines (between the outer perimeter lines of the bridge) should change accordingly. The speed of the overhang walls (the perimeter walls of the bridge) should be controlled by overhang settings - that is not the case in Orca 2.1.1. In the following picture the overhang speed was deliberately set to 70% just to make a difference. 
image

This is the result:
image
So the overhang speed affects not only the border lines of the bridge, but also the bridge lines (which are internal in the bridge).  In order to control the bridge perimeter speed, I have to disable "Slow down for curled perimeters" and then the bridge speed settings are applied to the bridge perimeters, but may not always be desirable.

Just to illustrate the bug, pay attention at the different bridge speed settings in the following pictures.
100 mm/s:
image
1 mm/s:
image
The speed does not change as commanded.

OK, all this misbehaviour is corrected using the Orca version with the change in this Pull Request (https://github.com/igiannakas/OrcaSlicer/actions/runs/10008381271), as I was able to verify.

@SoftFever 
I strongly recommend it, in case it is not yet approved for next release, since it not only improves subtle extrusion defects in the indicated cases, but also fixes bugs related to bridge/overhang speed settings.

**Comment by igiannakas** [comment]
So does the version from the run works, right?

This feature has already been merged in the latest nightly and will be present in the upcoming 2.2 release: https://github.com/SoftFever/OrcaSlicer/pull/5996

**Pull request merged**
