### PR TITLE
fix: ambiguous call _check_convertible_to_path_source(const wxCStrData&)

### PR DESCRIPTION
**Pull request by ovlach**

### CODE REVIEW

**Comment by SoftFever** [comment]
@ovlach 
Can you describle what problem is the PR trying to solve?
As far as I see the changes in this PR, I'm afraid it will cause issues for languages using unicode(wchar)

**Comment by ovlach** [comment]
I'am not C/C++ developer, but problem is 
> ```
> In file included from include/boost/filesystem.hpp:16,
>                  ...
>                  from <command-line>:
> include/boost/filesystem/path.hpp:1029: note: declared here
> In file included from include/boost/filesystem/path.hpp:21:
> include/boost/filesystem/detail/path_traits.hpp: In instantiation of ‘constexpr const bool boost::filesystem::detail::path_traits::is_convertible_to_path_source<wxCStrData>::value’:
> include/boost/type_traits/conjunction.hpp:31:0:   required from ‘struct boost::conjunction<boost::disjunction<boost::filesystem::detail::path_traits::is_path_source<wxCStrData>, boost::filesystem::detail::path_traits::is_convertible_to_path_source<wxCStrData> >, boost::negation<boost::filesystem::detail::path_traits::is_native_path_source<wxCStrData> > >’
> include/boost/filesystem/path.hpp:256:0:   required by substitution of ‘template<class Source, class> boost::filesystem::path::path(const Source&) [with Source = wxCStrData; <template-parameter-1-2> = <missing>]’
> /home/ovlach/Devel/Nanobyte/orca-slicer/source/src/slic3r/GUI/Auxiliary.cpp:352:0:   required from here
> include/boost/filesystem/detail/path_traits.hpp:495: error: call of overloaded ‘_check_convertible_to_path_source(const wxCStrData&)’ is ambiguous
> ```

wxString.c_str() -> returns wxCStrData (in documentation told "implicitly convertible to both const char* and to const wchar_t*."). I expect compiler can't determinate which function exactly call because functions is defined for booth... So, solution will be use wxString::ToStdWstring or explictly cast to wchar_t*?

**Comment by SoftFever** [comment]
@ovlach 
> So, solution will be use wxString::ToStdWstring or explictly cast to wchar_t*?

I agree!

**Comment by SoftFever** [comment]
@ovlach
I have submitted a commit with the changes per our discussion. 
Let me know if it looks good to you.

**Comment by SoftFever** [comment]
merged.

**Review by SoftFever — APPROVED** [review]

**Pull request merged**
