### PR TITLE
Changed default infill pattern to crosshatch for Creality printers

### PR DESCRIPTION
**Pull request by bistory**
# Description

Following new default settings for printers

### CODE REVIEW

**Comment by SoftFever** [comment]
Hi @bistory 

The "Support Style" currently only support the grid and snug options(it's different than then sparse infill). 
The crosshatch is for sparse infill patten.

**Comment by bistory** [comment]
> Hi @bistory
> 
> The "Support Style" currently only support the grid and snug options(it's different than then sparse infill). The crosshatch is for sparse infill patten.

Whoops sorry, I didn't double check this, I'll have to check why I still see grid as default infill for the K1 ;-)

**Comment by SoftFever** [comment]
> 
> EDIT : Cleaned "user" folder in app support fixed my issue (as usually)

Delete "%appdata%/OrcaSlicer/system" instead would make our life easier, it will force Orca to copy built-in profiles while user profiles are not affected.

**Comment by bistory** [comment]
> > EDIT : Cleaned "user" folder in app support fixed my issue (as usually)
> 
> Delete "%appdata%/OrcaSlicer/system" instead would make our life easier, it will force Orca to copy built-in profiles while user profiles are not affected.

Yes, it's the system profile I purged, not user, my bad ;-)

**Pull request closed without merging**
