### PR TITLE
Feature/move plate to the front

### LINKED ISSUE #3508: Ability to re-organize plate order
It would be of tremendous help to be able to re-order the plates of a job.

- Sometimes its nice to move similar objects in sequence
- Move completed plates to the end so you know what's next or where you left off printing
- - Or maybe just a clickable check box on the right-side tools to show `[x] Done`.  I feel silly using the `Lock` tool right now for this indicator.
- Re-organize once you slice and know the print time.  For example: Two 4hrs jobs making up one 8hr shift of work, followed by a 12-16hr job to run overnight.  Putting the jobs in workflow order would do a lot for job sequence planning.

image

### PR DESCRIPTION
**Pull request by Azio-Pantheon**
# Description
Added a button on the plates to move the plate to the front. Gives users the ability to re-order the plate to some extent. It resolves #3508 

# Screenshots/Recordings/Graphs
image

## Tests
Tested locally on Windows 11 system.

### CODE REVIEW

**Review by SoftFever — APPROVED** [review]
LGTM
Thank you!

**Comment by SoftFever** [comment]
> @SoftFever @Azio-Pantheon Sorry I'm a bit late, but I think the Icon could be something like: **`#1`**, **`1.`** or **`1st`** instead of the arrow, which could cause confusion on what exactly it means. 😃

I actually like the icon NGL
The UP allow with a line on top of it is a common icon to indicate "top"

**Comment by discip** [comment]
Ok, just my two cents. 😊

**Comment by MKloberg** [comment]
Awesome, thank you so much for adding this!

**Comment by ShaneDelmore** [comment]
I was just wanting this functionality today, thank you.

**Comment by tblake84** [comment]
This is a bit of a half solution.  Being able to drag and drop plates where you want them would be way more helpful rather than having to sort them in reverse order by using a button that forces them to the front.  Hiding the button behind the plate number also frustrates the use of this feature.
image

**Pull request merged**
