### PR TITLE
Adds overview for custom gcodes like pause, change filament, custom #2191

### PR DESCRIPTION
**Pull request by niklasb22**
This inserts an overview of all inserted user-specified gcodes, such as the filament change, pause and custom gcodes.
The layer on which the gcode is located is displayed, as well as a time estimate.
If there is no user-specified gcode in the print, nothing is displayed.

image

Closes: #2191

### CODE REVIEW

**Comment by Eldenroot** [comment]
Please, check alsonthe issue / request for the First Layer Times and adding filament used for every type of part of model. Like IT is in Prusa

**Comment by Eldenroot** [comment]
https://github.com/SoftFever/OrcaSlicer/issues/2252 this oné, including icons

**Comment by discip** [comment]
@niklasb22
# Thank you! 👍🏻

Unfortunately there is an issue regarding the time, as the current approach shows the time of the layer after it is finished but unfortunately we need the time before the layer starts.

Please see the conversation here https://github.com/SoftFever/OrcaSlicer/pull/2312.

**Comment by discip** [comment]
@niklasb22
# Thank you! 👍🏻
<br>

Unfortunately there is an issue regarding the **time** as the current approach shows the **time** of the layer **_after it is finished_**.

But unfortunately we need the time before the layer starts.

Please see the conversation here https://github.com/SoftFever/OrcaSlicer/pull/2312.

**Review by Noisyfox — CHANGES_REQUESTED** [review]
Should show the previous layer time as mentioned in the comment.

**Comment by niklasb22** [comment]
@discip  The time display should now be correct.

**Review by Noisyfox — APPROVED** [review]
Looking good to me.

**Comment by discip** [comment]
@niklasb22
As Noisyfox stated, this is good to go. 😀
## Thank you! 👍🏻

**Comment by discip** [comment]
@niklasb22
## Thank you very much! 😀👍🏻
As Noisyfox stated, this is good to go.

**Review by SoftFever — APPROVED** [review]

**Comment by SoftFever** [comment]
Very handy feature.
Thank you very much 👍

**Pull request merged**
