### PR TITLE
ESP3D printer connection for wireless printing

### PR DESCRIPTION
**Pull request by PreyK**
# Description
Added [ESP3D ](https://github.com/luc-github/ESP3D) support for wireless printer connection to be able to send gcode & start printing directly from the slicer on printers with ESP3D module.

# Screenshots/Recordings/Graphs
image
image
image
image

## Tests
Sent and printed files on my printer from orca slicer sent via the upload & print commands

### CODE REVIEW

**Review by SoftFever — APPROVED** [review]
LGTM
Thanks

**Comment by KristiyanHristov** [comment]
@PreyK Every time I send a file directly to the printer it reaches 100% and gets an ERROR response. Is there something specific in the ESP3D config that I'm missing?

Screenshot 2024-06-07 172713
Screenshot 2024-06-07 173102

**Comment by SoftFever** [comment]
Not sure if this helps: #857

**Comment by KristiyanHristov** [comment]
Thanks for the response. 
It's definitely not a timeout. Happens with all prints (event within 4 seconds). 
Is there a dev console or verbose mode to see what is sent?

**Comment by KristiyanHristov** [comment]
Is this feature built with ESP3D v3.0 in mind?

The new API doesn't have /upload_serial
http://esp3d.io/esp3d/v3.x/documentation/api/webhandlers/index.html

**Comment by PreyK** [comment]
> Is this feature built with ESP3D v3.0 in mind?
> 
> The new API doesn't have /upload_serial
> http://esp3d.io/esp3d/v3.x/documentation/api/webhandlers/index.html

This was written with V2.X in mind as this is the version considered "stable" by the author.
V3 is still considered experimental afaik

**Comment by PreyK** [comment]
Have to look into this, don't have my printer at hand right now

**Comment by kleffa** [comment]
I'm  a ES3D user from CURA, since I noted this option I'm trying to change to Orcaslicer, but I some troubles, like 
M118 P0 [ESP600]finished\\ print;
that line I use at end of my printings to get notified, but when try to set on OrcaSlicer, doesn't slice because it shows as a error

**Comment by phanex** [comment]
> Have to look into this, don't have my printer at hand right now

Nothing has changed for ESP3d 3.0 yet. 
Any chance?

**Comment by Ozzzone** [comment]
Is ESP3D v3.0.1 not supported? Should I roll back to version 2.x, or will there be an update with ESP3D 3.0.1 support soon?

**Pull request merged**
