### PR TITLE
Allow specifying print order within each layer

### LINKED ISSUE #3555: Unable to change printing order
### OrcaSlicer Version

Any

### OS version

Linux Mint Cinnamon

### Additional system information

_No response_

### Printer

Voron Trident

### How to reproduce

1. Add multiple objects to the plate
2. Try to have them printed the order you need

### Actual results

As much I love OrcaSlicer, this has to be worst object management ever.
We have talked about this on Discord a bunch of time but nothing was done about it.

As you are looking at it, any 3D printer I am aware of, will move the head from the left to right where is usually the purge line is printed.
With that being said, it should start printing like so, from the left to the right, from the front towards the back. 
Basic logic right?!?

Here you have the normal behaviour

A slightly change and there goes the toolhead traveling across the bed to start the print.

And again.

That data isn't helpful enough???
Sure...
What logic is this???

It is so frustrating because this is such a basic must have logic but doesn't seem to be relevant.
Nobody is talking about print by object, save that nonsense.
You have to waste minutes trying to move things around to get a somewhat decent sequence.

The object list and nothing is the same, it does not work, you cannot interact with it, not like PrusaSlicer does.
You don't have to have print by object enabled on PrusaSlicer to allow the order to be changed.

I cannot get the sequence right with a full plate like this no matter what I try.

### Expected results

Follow the common logic sequence, from the left to the right, from the front towards the back.
You avoid a 260c nozzle traveling all the way to the back to start a print which usually ends up with curling line at the start and messed up first layer.

Users with the "print by object nonsense", please, press "Alt + F4"
Thank you

### Project file & Debug log uploads

This can be simulated with anything, it does not require user log.

### Checklist of files to include

- [X] Log file
- [ ] Project file

### PR DESCRIPTION
**Pull request by Noisyfox**
Fixes #3555

Now you can drag the object list to reorder the object in "by layer" mode. And if you choose "as object list" option in the layer order drop down, then for each layer, the objects will be printed in that order.

Currently this only applies to object, not their parts. So it currently won't print the object parts use the order as in object list. Will try to improve this later.

Also, the tool change order has higher priority than object list order, and the object list order will be used within each color. For example, if you have object A, B, C, and color 1, 2, and the object list is C, A, B, then the actual print order will be (assume color 2 is the initial color): 
layer 1: C2, A2, B2, tool change, C1, A1, B1
layer 2: C1, A1, B1, tool change, C2, A2, B2
layer 3: C2, A2, B2, tool change, C1, A1, B1
layer 4: C1, A1, B1, tool change, C2, A2, B2
etc...
This was by design to minimize tool changes.

Also, when "As object list" is selected, the object labels will show their print order, just like when "print by object" is used:
image

### CODE REVIEW

**Comment by tlhintoq** [comment]
By Layer
Sequence as imported - good
Sequence as re-ordered - good

By object
Sequence as imported - good
Sequence as re-ordered - good

image

image

image

**Comment by Eldenroot** [comment]
Coooool! Thx

**Comment by Noisyfox** [comment]
> By Layer Sequence as imported - good Sequence as re-ordered - good
> 
> By object Sequence as imported - good Sequence as re-ordered - good
> 
> image
> 
> image
> 
> image

Awesome! Thanks for your test.

**Comment by discip** [comment]
@Noisyfox
> This was by design to minimize tool changes.

Just remembered having an issue, were I had imprinted text on the first layer in a different color than the main body.
Instead of printing the text first, to save 1 color change, it started with the main color, changed to the text color and after that back to main color.

Is this also by design?
Maybe this could also be fixed with this PR in one go, or do we need to open a separate one?

Please rename:
[distance-check.3mf.txt](https://github.com/SoftFever/OrcaSlicer/files/13959637/distance-check.3mf.txt)

**Comment by discip** [comment]
Thanks you very much!

However, I consider this only a temporary solution as there is at least one case where it would not completely solve the issue.

Is it possible to make the auto setting smarter?

e.g. If you need text at both the bottom and the top, the order would have to be exactly reversed in one of the cases.

**Comment by Noisyfox** [comment]
> Thank you very much!
> 
> However, I consider this only a temporary solution as there is at least one case where it would not completely solve the issue.
> 
> Is it possible to make the auto setting smarter?
> 
> e.g. If you need text at both the bottom and the top, the order would have to be exactly reversed in one of the cases.

You could raise another ticket for this.

**Review by SoftFever — APPROVED** [review]
Looks good.
Thanks!

**Comment by Primus007** [comment]
where can i find the new options like "as object list option in the layer order drop down"? i use the latest dev version and can't find it.

**Pull request merged**
