### PR TITLE
updates for PR #6638 - typos and grammar

### PR DESCRIPTION
**Pull request by henrivdr**
Including a marathon of resolving merge conflicts due to PRs today.
We should abolish multi-line msgids :-)

# Description
This looks like a huge PR, but it is only fixes for typos and grammar.
On the previous PR #6638 I mistakenly used _en.po as the reference instead of the .pot.
It caused missed strings in the source and other .po files.
This around I triple checked again to make sure the msgids are in sync with the L"" strings in the code.

Comments, variable names and non-English translation strings were excluded.

I learnt that typos were "fixed" before by using translations. After this PR, those translations are no longer relevant and can be cleaned up.
Hopefully this sets a new baseline which will last us a while. :-)

# Screenshots/Recordings/Graphs

## Tests
The code compiled and ran successfully.
The translation files were verified with ./run_gettext.sh

I did not se any issues when running ./run_gettext.sh --full
Please confirm it again, before the merge.

### CODE REVIEW

**Comment by SoftFever** [comment]
Thank you!
There is one last string missed, we need to add a , and space there:
image

Rests look all good.

For the multi-line message, don't worry about the link break positions. It won't cause problem as gettext handles it

**Comment by henrivdr** [comment]
How do you detect those missed ones?

The "gripe" I have with the (inconsistent) line breaks is that it makes it tricky to search across files for the substring/phrase of words which contains the typo word.
If I search for the affected word **only** it finds them in comments as well, which I chose to exclude from the first phase.
It's just makes it tedious and risky.

**Comment by SoftFever** [comment]
> How do you detect those missed ones?
> 
> The "gripe" I have with the (inconsistent) line breaks is that it makes it tricky to search across files for the substring/phrase of words which contains the typo word. If I search for the affected word **only** it finds them in comments as well, which I chose to exclude from the first phase. It's just makes it tedious and risky.

I can't figure out how to make gettext to generate consistent line breaks on different machines.
So my trick is:
1. Before make any editing, run "run_gettext.bat --full" once
2. Git stage the changes, this will be your new baseline
3. Correct strings
4. Run "run_gettext.bat --full" again
5. Diff the changes against staged file, this will only show changes caused by your changes.
6. repeat step 3-5 until everything is corrected.

**Review by SoftFever — APPROVED** [review]
LGTM
Thanks

**Comment by henrivdr** [comment]
I was actually still busy keeping gettexty happy.   It moved a bunch of translations to the comment section.
The last commit , just now , fixes that.
Do I have to make a seperate PR for that?

I've been running it al along with '-full', one '-'.  :tired_face: 
Seems like I'll be doing some gettext docs reading. :nerd_face:

**Pull request merged**
