### PR TITLE
Consolidate printer profile names

### PR DESCRIPTION
**Pull request by fr3ak2402**
@hliebscher and me exchanged ideas yesterday and have the following improvements planned for the printer profiles.

In addition, we want to develop a configurator for the creation of the printer profiles. In consequence of this we have also defined some things to enable a uniform structure of the profiles.

For certain printer profiles, I have already started the transition to the new Unified Profile Scheme.
I had to make the following changes to convert them to the new scheme.

The printer processes are no longer called "0.20mm Standard (@)Manufacturer Printer Name" but "0.20mm Standard (nozzle diameter) (@)Manufacturer Printer Name".

This change makes it easy to add more nozzle diameters.

The following printer families were already adapted by me:
Anycubic
Artillery
Creality
Elegoo
FLSun
Qidi
Raise3D
Snapmaker
Sovol
Ultimaker
Voxelab

I will also transition the other printer families to the new printer profile scheme in the next few days. So that all printer profiles show a uniform structure and the supplement of further printers facilitates.

### CODE REVIEW

**Comment by SoftFever** [comment]
@fr3ak2402 
Thanks for bringing up this discussion.

In the current schema design, the process name is "0.20mm Standard @ MachineName," where the MachineName should include the nozzle size. For example, "Orca Arena X1 Carbon 0.8 nozzle." You can refer to the [OrcaArena](https://github.com/SoftFever/OrcaSlicer/tree/main/resources/profiles/OrcaArena) profile as an example.
I would suggest we keep this schema.

In the future, I'm planning to add support for using the percentage of the nozzle diameter to specify the line width. This would allow us to consolidate process profiles for different nozzle sizes of the same printer model.
However, the current schema will still be supported to accommodate profile creators and maintainers who want to optimize for different nozzle sizes.

**Comment by fishercraigj** [comment]
> @fr3ak2402 Thanks for bringing up this discussion.
> 
> In the current schema design, the process name is `0.20mm Standard @MachineName`, where the MachineName should include the nozzle size. For example, `Orca Arena X1 Carbon 0.8 nozzle` and `0.24mm Standard @Arena X1C 0.8 nozzle.json`. You can refer to the [OrcaArena](https://github.com/SoftFever/OrcaSlicer/tree/main/resources/profiles/OrcaArena) profile as an example. I would suggest we keep this schema. Let me know what you think.
> 
> In the future, I'm planning to add support for using the percentage of the nozzle diameter to specify the line width. This would allow us to consolidate process profiles for different nozzle sizes of the same printer model. However, the current schema will still be supported to accommodate profile creators and maintainers who want to optimize for different nozzle sizes.

FWIW from the mac side of the house - I'm having a ton of organization troubles managing all the printers profiles, with all the filaments, and all the process that also have to be adjusted while also managing all the nozzle sizes (like for us E3 Revo owners).  It's pure pain but gets even worse when using the ender 3 v2 profile and all it comes with one nozzle setting 0.4 so EVERYTHING is mapped to one big fat drop down box for each individual Printer/Filament/Process.

I'd really like to use my smaller and larger nozzles without having to be worried about managing 50 different profiles across the board.  And for the record, this is not an OrcaSlicer only issue.  This is an issue that goes across all slicers.  But the juice is not worth the squeeze to manage all this, and for me personally, my other nozzles will sit in a box while I sit here hating myself for buying a E3 Revo solely for the purpose to change nozzles while I watch my 0.4 nozzle do it's thing.  :)

**Comment by SoftFever** [comment]
> > @fr3ak2402 Thanks for bringing up this discussion.
> > In the current schema design, the process name is `0.20mm Standard @MachineName`, where the MachineName should include the nozzle size. For example, `Orca Arena X1 Carbon 0.8 nozzle` and `0.24mm Standard @Arena X1C 0.8 nozzle.json`. You can refer to the [OrcaArena](https://github.com/SoftFever/OrcaSlicer/tree/main/resources/profiles/OrcaArena) profile as an example. I would suggest we keep this schema. Let me know what you think.
> > In the future, I'm planning to add support for using the percentage of the nozzle diameter to specify the line width. This would allow us to consolidate process profiles for different nozzle sizes of the same printer model. However, the current schema will still be supported to accommodate profile creators and maintainers who want to optimize for different nozzle sizes.
> 
> FWIW from the mac side of the house - I'm having a ton of organization troubles managing all the printers profiles, with all the filaments, and all the process that also have to be adjusted while also managing all the nozzle sizes (like for us E3 Revo owners). It's pure pain but gets even worse when using the ender 3 v2 profile and all it comes with one nozzle setting 0.4 so EVERYTHING is mapped to one big fat drop down box for each individual Printer/Filament/Process.
> 
> I'd really like to use my smaller and larger nozzles without having to be worried about managing 50 different profiles across the board. And for the record, this is not an OrcaSlicer only issue. This is an issue that goes across all slicers. But the juice is not worth the squeeze to manage all this, and for me personally, my other nozzles will sit in a box while I sit here hating myself for buying a E3 Revo solely for the purpose to change nozzles while I watch my 0.4 nozzle do it's thing. :)

It's a tedious work to manage so many profiles for sure :(

**Comment by fr3ak2402** [comment]
@SoftFever 

It's not about enforcing my profile scheme, rather that we use a consistent scheme for all printer profiles.

Me and @hliebscher noticed that many profiles were created only for one printer and the addition of other printers of the same manufacturer are very need. Because then all profiles of the manufacturer must be adapted first.
In addition, many different schemas are used in the slicer for the creation of the profiles, which is also not very helpful.

Personally, I don't care if we set it up like this:

`(layer height)mm (quality) (nozzle diameter) @(machine name) `
or 
`(layer height)mm (quality) @(machine name) (nozzle diameter) nozzle`
or
`(layer height)mm (quality) @(machine name) ((nozzle diameter) nozzle)`

would look like this:

`0.20mm Standard (0.4) @Snapmaker A250`
or
`0.20mm Standard @Snapmaker A250 0.4 nozzle`
or
`0.20mm Standard @Snapmaker A250 (0.4 nozzle)`

I can also agree to change that as follows for all profiles:

(layer height)mm (quality) @(machine name) (nozzle diameter) nozzle
or
(layer height)mm (quality) @(machine name) ((nozzle diameter) nozzle)

For example, that it is then like this:

`0.20mm Standard @Snapmaker A250 0.4 nozzle`
`0.20mm Standard @Snapmaker A250 0.6 nozzle`
`0.20mm Standard @Snapmaker A250 0.8 nozzle`
or
`0.20mm Standard @Snapmaker A250 (0.4 nozzle)`
`0.20mm Standard @Snapmaker A250 (0.6 nozzle)`
`0.20mm Standard @Snapmaker A250 (0.8 nozzle)`

I would rather prefer this form of writing, because I find it easier to read when the nozzle diameter is in brackets:
`0.20mm Standard @Snapmaker A250 (0.4 nozzle)`

I just want to have a uniform scheme for the profiles, which makes it easier to expand and create. I have now brought 43 printer profiles into the OrcaSlicer and often had to change or adapt other profiles because they used a different scheme. In the worst case, they were created for only one printer.

--------------------------------------------------------------
In addition, I and @hliebscher have also planned a configurator for the printer profiles. We would also implement this.
This should then offer the possibility to maintain all parameter values in a window or to take over the values from an existing profile. At the end the program should write all JSON files for the profile. If the printer manufacturer already exists, then manufacturer.json should be adapted to the new printer.

This would also make it much easier to create new printer profiles.

--------------------------------------------------------------
In addition, I have already started to integrate the post-processor scripts into the OrcaSlicer, these can be maintained soon also directly in the order of the printer family.

**Comment by julie777** [comment]
Is there a discussion about this?

I have been thinking about profiles, dependencies, and support for multiple printers, nozzle sizes and plate types for months. I have also been thinking about how to improve diffs, including diffing the G code, and have a better management interface.

@SoftFever 
This is one of the things I was going to bring up after you clarified the goal of the Orca project. 

Some of what you mention above, I do not think is the best solution, and **I would welcome the opportunity to contribute.**

I have already started working on a profile library that records system profiles and when they change and how they are different, including extracting and managing the G code as separate files so they can actually be diffed.

**Comment by fr3ak2402** [comment]
@julie777 

There is no discussion about it, but you could consider this chat in PR as a discussion.

I think first of all it would be best if we have a uniform scheme for the profiles. So that they all have the same structure and are easier to manage. 

I think it makes sense to use a uniform scheme for the profiles of the printers.
In the same way, I also find it useful to build a configurator that provides the creation of the required JSON files for a printer profile. This also offers the possibility to create a new printer profile based on an existing profile. Because there are also printers that are a clone of another printer and usually differ only very slightly. Then you can simply take this as a template, adjust the values and then create the JSON files. It also reduces the error rate that can occur when creating the profile.

I don't think it makes sense to manage the codes in a single file, because each G-code belongs only to a specific printer. Therefore, the splitting does not make sense of the G-code. If you want to compare the G-codes, you have to save the old profiles first, then you can simply read in the files and then compare them. 
The Configurator has a database for this, in which all JSON contents of the files are administered. And automatically synchronized with the files as the slicer or on command of the user.

**If you want, feel free to contribute to the Configurator.**

Currently I am also working on the possibility to maintain a display name for the processes of a profile in the profile itself. This will allow the same name to be displayed in the slicer for a process for all Nozzle diameters. Then only the file names background have to differ.
Then also the description in the slicer itself are no longer so long.

**Comment by fr3ak2402** [comment]
@SoftFever 
I propose the following scheme for printer profiles:

**Printer family filenames:**
Printer family -> `{Printer manufacturer}.json`

**Filament filenames:**
Generic filament -> `{Printer manufacturer} Generic {filament type}.json`
Vendor filament -> `{Filament vendor} {filament type}.json`

**Printer machine filenames:**
Printer machine -> `{Printer manufacturer} {machine name}.json`

Note: The Model_ID in the machine file is set as follows -> {Printer manufacturer}-{machine name}
A few things have to be considered here, which I will show in examples

Printer machine nozzle -> `{Printer manufacturer} {machine name} ({nozzle diameter} nozzle).json`

**Printer process filenames:**
Printer process -> `{layer height}mm {quality} @{Printer manufacturer} {machine name} ({nozzle diameter} nozzle).json`

**Printer assets filenames:**
Printer thumbnail -> `{Printer manufacturer} {machine name}_cover.png (180x180) pixels`
Buildplate model -> `{Printer manufacturer}_{machine name}_buildplate_model.stl`
Buildplate texture -> `{Printer manufacturer}_{machine name}_buildplate_texture.png` or `{Printer manufacturer}_{machine name}_buildplate_texture.svg`
Hotend model -> `{Printer manufacturer}_{machine name}_hotend.stl`

If the printer is from a series or generation, the file will be named as follows:

Hotend model -> `{Printer manufacturer}_{series name}_{gen number}_hotend.stl`

Note: This is only valid if the complete series and generation used the same hortend. Otherwise a separate hotend is created for each printer.

I have created an examples of how this looks with the new scheme.
`Example Qidi:`
**Printer family filenames:**
`Qidi.json`

**Filament filenames:**
`Qidi Generic PLA.json`
`AddNorth ePLA.json`

**Printer machine filenames:**
`Qidi X-Max 3.json`
`Qidi X-Max 3 (0.4 nozzle).json`
`Qidi X-Max 3 (0.6 nozzle).json`

**Printer process filenames:**
`0.20mm Standard @Qidi Xmax3 (0.4 nozzle)`
`0.20mm Standard @Qidi Xmax3 (0.6 nozzle)`

**Printer assets filenames:**
`Qidi X-Max 3_cover.png`
`qidi_xmax3_buildplate_model.stl`
`qidi_xmax3_buildplate_texture.png`
`qidi_xseries_gen3_hotend.stl`

`Example Snapmaker:`
**Printer family filenames:**
`Snapmaker.json`

**Filament filenames:**
`Snapmaker Generic PLA.json`
`AddNorth ePLA.json`

**Printer machine filenames:**
`Snapmaker J1.json`
`Snapmaker J1 (0.4 nozzle).json`
`Snapmaker J1 (0.6 nozzle).json`

**Printer process filenames:**
`0.20mm Standard @Snapmaker J1 (0.4 nozzle)`
`0.20mm Standard @Snapmaker J1 (0.6 nozzle)`

**Printer assets filenames:**
`Snapmaker J1_cover.png`
`snapmaker_j1_buildplate_model.stl`
`snapmaker_j1_buildplate_texture.png`
`snapmaker_j1_hotend.stl`

**Model_ID:**
`Example Qidi:`

Qidi X-Max 3 -> `Qidi-XMax-3`
Qidi X-Max -> `Qidi-XMax`
Qidi X-CF Pro -> `Qidi-XCF-Pro`

`Example Snapmaker:`

Snapmaker J1-> `Snapmaker-J1`
Snapmaker A250-> `Snapmaker-A250`
Snapmaker A350-> `Snapmaker-A350`

`Example Creality:`

Creality Ender-3 S1 Pro-> `Creality-Ender3-S1-Pro`

-------------------------------------------------------------
Once I have implemented this with the display names, only the printer family files need to be adjusted.

Bildschirmfoto 2023-05-22 um 11 52 57

At the moment, the following would still be available for a 0.6 nozzle process:

Bildschirmfoto 2023-05-22 um 11 47 31

After the adjustment, a display name can be defined, which is then named as follows:
`0.20mm Standard @BBL X1C`

Then the following would be displayed in the slicer:

Bildschirmfoto 2023-05-22 um 11 47 46

-------------------------------------------------------------
In addition, it will soon be possible to maintain the post-processors of the printers directly in the printer family folder.

Bildschirmfoto 2023-05-22 um 11 55 39

------------------------------------------------------------
@SoftFever 

Can we agree on the proposed scheme?
I would then start directly with the conversion of the profiles

**Comment by SoftFever** [comment]
> @SoftFever I propose the following scheme for printer profiles:
> 
> **Printer family filenames:** Printer family -> `{Printer manufacturer}.json`
> 
> **Filament filenames:** Generic filament -> `{Printer manufacturer} Generic {filament type}.json` Vendor filament -> `{Filament vendor} {filament type}.json`
> 
> **Printer machine filenames:** Printer machine -> `{Printer manufacturer} {machine name}.json`
> 
> Note: The Model_ID in the machine file is set as follows -> {Printer manufacturer}-{machine name} A few things have to be considered here, which I will show in examples
> 
> Printer machine nozzle -> `{Printer manufacturer} {machine name} ({nozzle diameter} nozzle).json`
> 
> **Printer process filenames:** Printer process -> `{layer height}mm {quality} @{Printer manufacturer} {machine name} ({nozzle diameter} nozzle).json`
> 
> **Printer assets filenames:** Printer thumbnail -> `{Printer manufacturer} {machine name}_cover.png (180x180) pixels` Buildplate model -> `{Printer manufacturer}_{machine name}_buildplate_model.stl` Buildplate texture -> `{Printer manufacturer}_{machine name}_buildplate_texture.png` or `{Printer manufacturer}_{machine name}_buildplate_texture.svg` Hotend model -> `{Printer manufacturer}_{machine name}_hotend.stl`
> 
> If the printer is from a series or generation, the file will be named as follows:
> 
> Hotend model -> `{Printer manufacturer}_{series name}_{gen number}_hotend.stl`
> 
> Note: This is only valid if the complete series and generation used the same hortend. Otherwise a separate hotend is created for each printer.
> 
> I have created an examples of how this looks with the new scheme. `Example Qidi:` **Printer family filenames:** `Qidi.json`
> 
> **Filament filenames:** `Qidi Generic PLA.json` `AddNorth ePLA.json`
> 
> **Printer machine filenames:** `Qidi X-Max 3.json` `Qidi X-Max 3 (0.4 nozzle).json` `Qidi X-Max 3 (0.6 nozzle).json`
> 
> **Printer process filenames:** `0.20mm Standard @Qidi Xmax3 (0.4 nozzle)` `0.20mm Standard @Qidi Xmax3 (0.6 nozzle)`
> 
> **Printer assets filenames:** `Qidi X-Max 3_cover.png` `qidi_xmax3_buildplate_model.stl` `qidi_xmax3_buildplate_texture.png` `qidi_xseries_gen3_hotend.stl`
> 
> `Example Snapmaker:` **Printer family filenames:** `Snapmaker.json`
> 
> **Filament filenames:** `Snapmaker Generic PLA.json` `AddNorth ePLA.json`
> 
> **Printer machine filenames:** `Snapmaker J1.json` `Snapmaker J1 (0.4 nozzle).json` `Snapmaker J1 (0.6 nozzle).json`
> 
> **Printer process filenames:** `0.20mm Standard @Snapmaker J1 (0.4 nozzle)` `0.20mm Standard @Snapmaker J1 (0.6 nozzle)`
> 
> **Printer assets filenames:** `Snapmaker J1_cover.png` `snapmaker_j1_buildplate_model.stl` `snapmaker_j1_buildplate_texture.png` `snapmaker_j1_hotend.stl`
> 
> **Model_ID:** `Example Qidi:`
> 
> Qidi X-Max 3 -> `Qidi-XMax-3` Qidi X-Max -> `Qidi-XMax` Qidi X-CF Pro -> `Qidi-XCF-Pro`
> 
> `Example Snapmaker:`
> 
> Snapmaker J1-> `Snapmaker-J1` Snapmaker A250-> `Snapmaker-A250` Snapmaker A350-> `Snapmaker-A350`
> 
> `Example Creality:`
> 
> Creality Ender-3 S1 Pro-> `Creality-Ender3-S1-Pro`
> 
> Once I have implemented this with the display names, only the printer family files need to be adjusted.
> 
> Bildschirmfoto 2023-05-22 um 11 52 57
> At the moment, the following would still be available for a 0.6 nozzle process:
> 
> Bildschirmfoto 2023-05-22 um 11 47 31
> After the adjustment, a display name can be defined, which is then named as follows: `0.20mm Standard @BBL X1C`
> 
> Then the following would be displayed in the slicer:
> 
> Bildschirmfoto 2023-05-22 um 11 47 46
> In addition, it will soon be possible to maintain the post-processors of the printers directly in the printer family folder.
> 
> Bildschirmfoto 2023-05-22 um 11 55 39
> @SoftFever
> 
> Can we agree on the proposed scheme? I would then start directly with the conversion of the profiles
@fr3ak2402 
I say let's don't use the `display` name, so that users see the same names in the UI as the corresponding .json file names in the file explorer.
Everything else looks good👍, let's do it!

**Comment by fr3ak2402** [comment]
Brief feedback:

I have already transferred the following profiles to the new scheme:
Anke
Anycubic
Artillery
Creality
Elegoo
FLSun
Prusa
Qidi
Raise3D
SecKit
Snapmaker
Sovol

**The others I now transfer to the new scheme.**

In addition, profiles have already been introduced at Snapmaker.

**Comment by fr3ak2402** [comment]
I have already transferred the following profiles to the new scheme:
Custom
Tronxy
TwoTrees
UltiMaker
Voxelab
Vzbot

**I will transfer the others to the new system tomorrow.**

**Comment by julie777** [comment]
I am sorry to be late to the party. This is something that I have wanted to bring up for a long time, but I was waiting to see what @SoftFever had for the goals of the project first.

**A general comment: we should not take this lightly as it breaks compatibility with Bambu Studio. I am fine with that. However, we should really take our time, discuss it at length, and try to get it right. It will be harder if it needs to be changed again. BBL printer users are going to struggle with it already, because they will not be able to go back and forth as easily.**

Instead of responding to each of the above comments, I am going to try and add my thoughts as one comment. Hopefully I can organize it to be understandable.

### Profile Files

Although the name of the file should be usable to identify the file, it should not be use by the slicer for anything else. 
   - all profile information should be stored in the file, including printer brand, model, firmware type (and supporting version?)
   - all information should be stored in a single file. BBL's two files per profile is not good because files can get out of sync or change independently
   - if files are going to have some sort of checksum to detect corruption, it should only issue a warning if it fails. It should be possible to hand edit profile files
   - dependencies should be specified using the identifying information in the parent file and not the name.

Because file names are not used to manage dependencies, the slicer will need to create its own index of existing profiles, which it already does I believe. The slicer should check the profile directory contents when started to update the index based on new or changed files.

The user should be notified when the slicer detects changed or new files.

Files should not be duplicated. I do not understand why BBL copies system profiles from the install directory into the appdata directory.

If the system files are going to be updated automatically, independent from updating the slicer, then 
  1. the user must be notified when this happens
  2. the previous system profiles should be moved to a backup/old directory in case the user has issues with the new versions
  3. it would be nice if the user had the option of 
      4. seeing a list of files that changed
      5. being able to see diffs of the changes
      6. being able to see which of their custom profiles depend on the changed system profiles and how their custom profiles are affected.

### Profile Directory

BBL has an overly complicated directory structure, including using a printer directory as a sibling directory of the profile directory to hold information about AMS profiles. 

I just realized why Bambu Studio is copying system profiles from the install directory to AppData. It only copies profiles for printers that you have selected during setup. I guess that makes sense. 

I am looking at the appdata system directory for Orca and there is a BBL and a Custom. I do not think custom makes sense under system.

It does not make sense to me that OrcaSlicer/user has subdirectories, as if there are multiple users, when the AppData directory is for a specific user on Windows. 

I would suggest that in AppData/Roaming/OrcaSlicer this directory structure is used.
- profiles
    - system
        - base  (this makes sense for filament and process, but maybe not machine)
            - machine
            - filament
            - process
        - printer model
          - machine
          - filament
          - process
          - assets
        - printer model
    - user
        - base
        - printer model
        - printer model

For the individual files each should have a name that includes brand, model, nozzle size. Each model should have a base profile that includes all information for that model of printer, and then derived profiles for each nozzle size. This allows a printer to be defined once, and different nozzles to be added with minimal extra information.

I would really like to see the printer model have a profile and nozzle profiles to be a separate type of profile, or at least a machine profile without any of the settings specific to the machine specified.

In addition, there can be multiple profiles for a single brand/model, for example someone might have two Prusa MK3S printers, but have klipper on one of them. The printer profile/definition specifies the extruder area, the bed size and shape, but then there are two derived profiles that specify the machine limits because running klipper can change those so they are different than when running prusa firmware.

### UI

I posted a long issue for Bambu Studio about scoping #1838 and how Project should be included in the scope hierarchy along with all the plates and objects. The most important part of that was to allow plates to also have a printer, nozzle, filament, and process profile selected. This makes plates much more useful.

Given that Orca is supporting so many other printers, I think one of my suggestions is even more important. If a user has multiple printers and they are different brands and models, the current selection of "printer" is not manageable. The user does get to use the setup wizard and restrict the set of printers that they have so that only those profiles will be shown. That could still leave a list in the drop-down showing dozens of options. Just because profiles are stored with separate file for each printer nozzle combination, and have file names like that, does not mean that the user should have it presented that way.

A better user experience would be to select the printer model to be used for this project (and also for each plate if desired). Change from two drop-downs to three.
  - Printer Model: after the user makes a selection the other two drop-downs have their lists constrained to compatible choices. Because the use will have chosen available printers during setup, this will be a short list, possibly only a single entry
  - Nozzle Profile: with only the nozzle profiles available for the selected printer model this should be a short list. Having already selected the printer model, the nozzle profile choices do not need to show brand and model for the printer again and will be shorter and easier to distinguish. 
  - Plate Type: this is only the plates allowed for the printer/nozzle profile (Note: The label for the drop-down should be "Plate Type" and not "bed type". The bed is the heated part that is under the plate.

So an example for my currently printing job:
    Printer: BBL P1P
    Nozzle Profile: .4mm - fast start
    Plate Type: Textured PEI

Note: that adding nozzle into the nozzle profile name is not required, neither is adding plate into the plate type.

Showing how this fits into the browser:
```
Project  Printer: BBL P1P  Nozzle: .4 - fast start  Plate: Textured PEI  Filament: Hatchbox PLA
  - Plate 1  Printer: BBL P1P  Nozzle: .4 - standard  Plate: Textured PEI
    - Object 1
  - Plate: Optional Parts  Printer: Prusa MK3S  Nozzle: .8 Plate: Smooth PEI  Filament: Generic CF
    - hanger
    - post
```

That should be enough to present the general idea and start a discussion. (We should have the UI discussion in a separate issue or discussion.) 


### Profile Management

I think that profiles should be moved to a separate GitHub repo under the Orca project. I am going to create a separate issue for this and explain.

**I really think we should break this down into several focused discussions so that each part can be clarified before moving forward. Changing profiles is very significant and completely breaks compatibility with Bambu Studio.

**Comment by fr3ak2402** [comment]
@julie777 

**All BBL printer profiles are never touched and are not affected by this change. They are explicitly managed and modified only by Bamnbilab!!!!**
**If Bambulab makes a change, we can simply pull this over from the Bambulab Studio repo.**

Yes I know myself that this is not so simple, so I also thought about it. All changes I make to the slicer also take into account that all profiles of Bambulab Studio still work.

**The new scheme will only be applied to third party printers and we have set it that way now.**
**All third party printers we have to obsolete and maintain and not bambulab!**

The scheme we are introducing now is also the scheme now and the change affects the users only once.

Moreover, the users also get a possibility to convert their profiles etc. to the new schema. 

**I have already considered this with @hliebscher.**

**Comment by fr3ak2402** [comment]
I have already transferred the following profiles to the new scheme:
BIQU
Folgertech
RatRig
Voron

Now the profiles are still missing:
OrcaArena
Vivedino

**Comment by SoftFever** [comment]
I created a discussion thread here: https://github.com/SoftFever/OrcaSlicer/discussions/1132
@julie777 @fr3ak2402 and anyone interested can move there for further discussions.

I've also renamed the PR title to avoid confusion.

**Comment by SoftFever** [comment]
@julie777 

I would like to address the compatibility concern regarding this PR. Rest assured, the changes made here will not break any existing user-created profiles. Furthermore, it will not affect the compatibility with Bambu Studio as this PR does not modify BL profiles.

The changes made by @fr3ak2402 aim to consolidate the naming convention of third-party printer profiles, as explained in detail in his comment here: #1100 (comment).

Process name and file name changes won't affect existing profiles per my understanding. But we need to test it to make sure this is the case. @fr3ak2402 Have you got a chance to verify the assumption on your machine?

**Comment by fr3ak2402** [comment]
@SoftFever 

I have now adjusted all printer profiles.

All printer profiles now have a uniform scheme, like the one discussed.

**Comment by fr3ak2402** [comment]
@SoftFever 

Me and @hliebscher have already started testing this.

We have already noticed a few things that must be taken into account by the users in order to enable a smooth changeover.

Our tests are not yet completely finished. But we will report these when completed.

**Comment by SoftFever** [comment]
> @SoftFever
> 
> Yes I also have the possibility to test this on my computers
> 
> Me and @hliebscher have already started testing this.
> 
> We have already identified a few things that users need to be aware of to ensure a smooth transition.
> 
> Our tests are not yet completely finished. But we will report these when completed.

Oh no, what kind of issues are you referring to?
We should avoid changes that will break the user's existing profiles. Meaning they shouldn't be required to do anything for the changes.

**Comment by fr3ak2402** [comment]
@SoftFever 

So the existing profiles of the users are not destroyed, that I can already say.

Only these are no longer displayed in the slicer, since the reference on which these profiles are based no longer exists as of the name.

To fix this you only need to change the name and version in the file of the self-generated files to the new name of the reference

Otherwise, nothing else happens, so the profiles of the users already remain.

furthermore, we also noticed that when we load the older .3mf into the slicer after the change, it does not work. Since all file names have been changed and these can no longer be referenced. 

But this can be fixed by first deleting the printer and loading the .3mf file and setting up the printer again, then the .3mf can be used and saved normally again and so on.

**Comment by SoftFever** [comment]
> @SoftFever
> 
> So the existing profiles of the users are not destroyed, that I can already say.
> 
> Only these are no longer displayed in the slicer, since the reference on which these profiles are based no longer exists as of the name.
> 
> To fix this you only need to change the name and version in the file of the self-generated files to the new name of the reference
> 
> Otherwise, nothing else happens, so the profiles of the users already remain.
> 
> furthermore, we also noticed that when we load the older .3mf into the slicer after the change, it does not work. Since all file names have been changed and these can no longer be referenced.
> 
> But this can be fixed by first deleting the printer and loading the .3mf file and setting up the printer again, then the .3mf can be used and saved normally again and so on.
> 
> We are also in the process of writing a converter that will automatically adjust users' profiles to the new names, so they don't actually have to do anything. Except run a script.
> 
> After that all users can use everything as normal again, that script I'm just testing.
> 
> I have already thought about which things occur during the change and have already found a solution. How I can make it as unique as possible for the users.
> 
> The script I could also build in the slicer, then this would simply happen at the start of the slicer, then the user would not have to do anything and would not really come along the change.
> 
> The same would then happen when the user opens an older .3mf file, then Slicer would automatically adjust this to the new names etc.
> 
> Don't worry, if I change something that brings such a big change, then I implement everything so that it is also for the benefit of the users. So that they do not have to make big problems or things. As I have met @hliebscher, he sees the same as I do and would do so.
> 
> So we decided to work together as a team and continue to improve the maintenance of the post-processor scripts.
> 
> Besides, we both won't let you down and leave you with a chaos to clean up. We are happy to develop things for the OrcaSlicer, as well as support you.

I have an idea. We can address the file name changes in OrcaSlicer's profile loading logic. OrcaSlicer can check the filename map for the new file if it cannot find the requested file. 

Once all the changes are made, could you please provide a list of file name changes in the following format:
`old-file-name.json` -> `new-file-name.json`

I can then incorporate the necessary code changes in OrcaSlicer to handle this. This way, users won't need to take any additional steps, and even .3mf projects will be handled seamlessly.

**Comment by fr3ak2402** [comment]
@SoftFever 

I had also thought of something similar. Let's do it like this 👍

I've already finished all the profiles, so now I'll finish you the as you described the two JSON files.
old-file-name.json -> new-file-name.json

I will now start directly with the creation of the two lists.

**Comment by SoftFever** [comment]
> @SoftFever
> 
> I had also thought of something similar. Let's do it like this 👍
> 
> I've already finished all the profiles, so now I'll finish you the as you described the two JSON files. old-file-name.json -> new-file-name.json
> 
> I will now start directly with the creation of the two lists.
> 
> Where should I put the following JSON files in the slicer?

Posting here as a comment is fine.
I can copy it into the source code directly to make things simple. I don't expect many changes to the list in the future so storing them in a JSON file is not necessary.

**Comment by fr3ak2402** [comment]
@SoftFever 

I have already finished the list of old file names.

I have omitted the file names of the BIQU printers because the profiles are currently not functional. Therefore, no one can use them at the moment. I have already fixed the error and it has been implemented together with the adjustment of the file names.

I have also not included the file names for the custom profiles in the list, if I have understood correctly, they are only intended as an example for the creation of a custom profile and are not used by the user as a printer.

If the printers are to be included in the list after all, I would submit this later.

I have attached the list for you as a txt file:
[old_names.txt](https://github.com/SoftFever/OrcaSlicer/files/11569296/old_names.txt)

**Comment by SoftFever** [comment]
> @SoftFever
> 
> I have already finished the list of old file names.
> 
> I have omitted the file names of the BIQU printers because the profiles are currently not functional. Therefore, no one can use them at the moment. I have already fixed the error and it has been implemented together with the adjustment of the file names.
> 
> I have also not included the file names for the custom profiles in the list, if I have understood correctly, they are only intended as an example for the creation of a custom profile and are not used by the user as a printer.
> 
> If the printers are to be included in the list after all, I would submit this later.
> 
> I have attached the list for you as a txt file: [old_names.txt](https://github.com/SoftFever/OrcaSlicer/files/11569296/old_names.txt)
> 
> I will now also start the list for the new file names.

Thanks @fr3ak2402 
The custom profiles are used by users whose printer don't have built-in profiles. We will need to include them.

>  I have already fixed the error and it has been implemented together with the adjustment of the file names.

Do you mind to create a PR for this fix first? For 1.6.3 official release. 

For the changes in this PR, I plan to include them into the next version (1.6.4)
Also, I wanted to give you a heads up that I'll be traveling for the majority of June, so I may not be very responsive during that time. Just wanted to let you know in advance.

**Comment by fr3ak2402** [comment]
@SoftFever 

No problem, I'll push the BIQU printer fix and the changes to the Snapmaker profiles in a separate PR. So I will remove them from this PR. We still have the Snmapmaker Artisan installed and I will just create buildplate model and textures.

Okay, thanks for info and I hope your travels go well too.

We will then hold the fort during these times and try to help the users of the slicer as much as possible.

If there are any bugs during this time we will try to fix them and put them in this PR.

**Comment by fr3ak2402** [comment]
@SoftFever 

Why did you activate arc fitting on the Qidi printers of the third X series? As far as I know, the Qidi printers still have a problem with this as it has a negative effect on the print quality.

-------------------------------------------------
In the future, can you always assign me all PRs that contain profiles for printers so that I can always audit them and then release them if they are OK?

Since I am currently investing a lot of time in the profiles and will continue to do so in the future. 
Wouldn't it then perhaps be useful if I could edit this PR for new profiles to ensure consistency of profiles.

-------------------------------------------------
I have also started to create plate models and textures for all printers that don't have one. Also the matching nozzle models.
I have also been able to increase the quality of the existing plate textures of all my created profiles so that they are no longer blurry.

I will also change all the printer images so that they have a similar perspective. I had to do a lot with Photoshop for many of them. Which is time-consuming.
Unfortunately, I won't be able to finish this before the release of V 1.6.3.

I would then want to deliver this together with this PR.

**Comment by SoftFever** [comment]
> As far as I know, the Qidi printers still have a problem with this as it has a negative effect on the print quality.

Can you provide more details about the problem?
The X3 serial run on Klipper as far as I know. I was told their klipper configures have arc support on by default.
So with have arc fitting on should be fine.

**Comment by fr3ak2402** [comment]
@SoftFever 

Yes, klipper also supports arc fitting etc. by default.

So the Qidi third-gen X-series printers all use Klipper is correct, but Qidi unfortunately doesn't use everything from Klipper and much is replaced by in-house developments etc. In addition, the problem with the printer quality is related to the firmware of the printers, which does not work properly when processing arc fitting, which means that the print quality is degraded. 

This had also been found out when testing the profile with arc fitting activated, that the printer printed worse than with arc fitting deactivated.

My knowledge is also 2 weeks old, so it may have changed in the meantime, but I don't want to deny that.

So I thought you might have a different level of knowledge than me. I'm not angry that you activated it or anything. 
I just hadn't activated that because there were problems with it at the time of creating the profile, but still good if we just activate that.

**Comment by fr3ak2402** [comment]
@SoftFever 

I'm about to open a new PR, I closed this PR to resolve the conflicts more easily.

I will then add the file for the old names in the commentary of the new PR again, like the one for the new names

**Pull request closed without merging**
