### PR TITLE
Fixed a bug that caused curled edge detection not to work as expected for left facing edges when using Arachne. Enabled fan speed control for curled overhangs

### PR DESCRIPTION
**Pull request by igiannakas**
Found bug where the curled logic would not apply on the left most side of the prints and its amount of slow down would change based on model orientation. Also fixed a bug/introduced feature where the filament variable fan speed logic for overhangs would not be run on curled edges, even though they would benefit from it.

**Facing left**
image

**Facing right**
image

**Fixed:**

(ignore the changes in speed in the upper part of the model - I am testing it with 0 minimum layer time)
**Facing left:**
image

**Facing right:**
image

Also the factors I used needed updating post the above fix to match Prusa's. 

**Filament fan speed logic for overhangs enabled for curled edges:**

image

Finally introduced const variable in the SupportSpotsGenerator.hpp to adjust the area & magnitude over which the slowdown is performed for potential future use. Left to default 1.0 in the code.

### CODE REVIEW

**Comment by igiannakas** [comment]
Ready for review, test and merge.

Please test with a benchy facing left and then right on the plate. Slowdown should be visible on both directions.

**Comment by SoftFever** [comment]
@igiannakas 
Curious, what is causing the orientation of the model affect the curled logic?

**Comment by igiannakas** [comment]
> @igiannakas Curious, what is causing the orientation of the model affect the curled logic?

I’ll tell you, this was a pain to debug. What I noticed is that the individual layer curls where calculating correctly at the points however they were not accumulating properly across layers - they were varying by the degree of rotation of the benchy.

So I discovered that when I ported the feature I had used the estimate_points_properties of the current Bambu legacy/ orca source which was missing the curvature accumulation logic in the above function (in the end of the function block). I thought it was ok at the time (as it appeared working) but was wrong :) So I upgraded that function from the latest prusa code porting over the missing code and fixes etc they had done since.

**Comment by igiannakas** [comment]
I’ve also noticed that the aabb tree class has been upgraded for improved performance compared to the one orca currently uses - I’ll submit a new PR for this at some point as it affects more features than just this one.

**Comment by igiannakas** [comment]
Take a look here:https://github.com/prusa3d/PrusaSlicer/commits/c54c4d0a1f893dc97160fb2a33fe6213a24e86a7/src/libslic3r/GCode/ExtrusionProcessor.hpp

8th of aug commit,
21st April commits

**Comment by SoftFever** [comment]
> > @igiannakas Curious, what is causing the orientation of the model affect the curled logic?
> 
> I’ll tell you, this was a pain to debug. What I noticed is that the individual layer curls where calculating correctly at the points however they were not accumulating properly across layers - the accumulation was varying by the degree of rotation of the benchy. This led me to triage it down to the estimate points properties function as this one does the addition of curvature against the previous layer neighbouring curves.
> 
> So I discovered that when I ported the feature I had used the estimate_points_properties of the current Bambu legacy/ orca source which was missing the curvature accumulation logic in the above function (in the end of the function block). I thought it was ok at the time (as it appeared working) but was wrong :) So I upgraded that function from the latest prusa code porting over the missing code and fixes etc they had done since.

Haha, I can feel your pain.
Thank you so much!

**Review by SoftFever — APPROVED** [review]
Looks good

**Comment by igiannakas** [comment]
> > > @igiannakas Curious, what is causing the orientation of the model affect the curled logic?
> > 
> > 
> > I’ll tell you, this was a pain to debug. What I noticed is that the individual layer curls where calculating correctly at the points however they were not accumulating properly across layers - the accumulation was varying by the degree of rotation of the benchy. This led me to triage it down to the estimate points properties function as this one does the addition of curvature against the previous layer neighbouring curves.
> > So I discovered that when I ported the feature I had used the estimate_points_properties of the current Bambu legacy/ orca source which was missing the curvature accumulation logic in the above function (in the end of the function block). I thought it was ok at the time (as it appeared working) but was wrong :) So I upgraded that function from the latest prusa code porting over the missing code and fixes etc they had done since.
> 
> Haha, I can feel your pain. Thank you so much!

Welcome :D

**Pull request merged**
