### PR TITLE
Update QIDI profiles

### PR DESCRIPTION
**Pull request by HYzd766**
We have mainly made modifications to printing consumables. Through testing, some parameters of consumables have been modified and new consumables have been added for everyone to choose from. The selection of consumables has also become more neat and regular. In addition, minor changes have been made to the machine configuration parameters.

### CODE REVIEW

**Comment by vgdh** [comment]
Please write some description.

**Comment by bistory** [comment]
It seems that this PR includes changed suggested in your previous PR #4939
You can only keep the current one ;-)

**Comment by HYzd766** [comment]
The branch submitted three days ago has been deleted and the branch currently named as the newfeature has been retained

**Comment by bistory** [comment]
Great ;-)
Change filament gcode is missing, maybe adding PAUSE could be an improvement over the current profile ?

**Comment by SoftFever** [comment]
@HYzd766 
Thanks. I noticed that you have renamed some profile names. 
As a principle, we should avoid renaming profiles because this prevents existing user profiles based on them from loading in Orca. I suggest you add new profiles without touching existing ones
image

**Pull request closed without merging**
