### PR TITLE
QOL improvments to Ender 3 V3 KE G-Code

### LINKED ISSUE #4420: Creality Ender 3 V3 SE/KE Incorrect start of G-Code
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

Creality Ender 3 V3 SE and V3 KE are using a CR-Touch sensor by default and create a mesh of the bed by themself.
By default, Marlin turns off using the bed mesh in the G28 command, so an additional M420 S1 command is needed at the start of the g-code, to re-enable it.
In the default profile for these printers, the M420 S1 command is missing.

### Which printers will be beneficial to this feature?

Marlin

### Describe the solution you'd like

After "_G28; Home_", a "_M420 S1; Enable mesh leveling_" command is needed in the default profile for these printers.

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by cochcoder**
Closes #4420 after #4653 is merged

### CODE REVIEW

**Comment by bistory** [comment]
This is strange, that gcode is not added by Creality Print, did they added some "magic" detection to enable it ?

**Comment by SoftFever** [comment]
This is a Marlin g-code command.
Need some volunteers who own the machine to test

**Comment by Orel-A** [comment]
I own the machine. This PR should be rejected.
The G28 already has a homing override with `BED_MESH_PROFILE LOAD="default"`

image

What do needs to be changed though is this line:
`G1 X-1.7 Y20 Z0.28 F1500.0 E30 ;Draw the second line`
It's outputing too much filament for TPU, causing pressure build up on the nozzle when it's starting the print.
Furthermore, since it's returning to the same place where it started the first line and was waiting there to heat up, it will often pick up the residue filament from the last print.
Let's change it to:
`G1 X-1.7 Y25 Z0.28 F1250.0 E15 ;Draw the second line`

And in the machine g-code we should raize the Z a bit more so we can take off the plate more easily on low prints. so:
`G1 Z5 ;Raise Z more`
change to:
`G1 Z20 ;Raise Z more`

What do you think?

**Comment by cochcoder** [comment]
I'll implement these changes so this PR has a use, as the issue, this was initially trying to close, had a modified machine.

**Comment by Orel-A** [comment]
So I've tested this, we'll return the F1500.0 speed to that line, and end the second pass a bit shorter.
Here is the full gcode without all the annoying whitespaces at the end of each line:

`"machine_start_gcode": "M220 S100 ;Reset Feedrate\nM221 S100 ;Reset Flowrate\n\nM140 S[bed_temperature_initial_layer_single] ;Set final bed temp\nG28 ;Home\n\nG92 E0 ;Reset Extruder\nG1 Z2.0 F3000 ;Move Z Axis up\nM104 S[nozzle_temperature_initial_layer] ;Set final nozzle temp\nG1 X-2.0 Y20 Z0.28 F5000.0 ;Move to start position\nM190 S[bed_temperature_initial_layer_single] ;Wait for bed temp to stabilize\nM109 S[nozzle_temperature_initial_layer] ;Wait for nozzle temp to stabilize\nG1 X-2.0 Y145.0 Z0.28 F1500.0 E15 ;Draw the first line\nG1 X-1.7 Y145.0 Z0.28 F5000.0 ;Move to side a little\nG1 X-1.7 Y30 Z0.28 F1500.0 E15 ;Draw the second line\nG92 E0 ;Reset Extruder\nG1 E-1.0000 F1800 ;Retract a bit\nG1 Z2.0 F3000 ;Move Z Axis up\nG1 E0.0000 F1800"`

`"machine_end_gcode": "G91 ;Relative positionning\nG1 E-2 F2700 ;Retract a bit\nG1 E-2 Z0.2 F2400 ;Retract and raise Z\nG1 X5 Y5 F3000 ;Wipe out\nG1 Z20 ;Raise Z more\nG90 ;Absolute positionning\n\nG1 X2 Y218 F3000 ;Present print\nM106 S0 ;Turn-off fan\nM104 S0 ;Turn-off hotend\nM140 S0 ;Turn-off bed\n\nM84 X Y E ;Disable all steppers but Z"`

**Comment by cochcoder** [comment]
@Orel-A implemented the changes

**Comment by Orel-A** [comment]
I think so...
At the end of the machine start gcode, it's retracting 1mm, moving the nozzle up and then immediately deretracting.
Shouldn't we deretract only after we travel to the first print object?
I exported the generated gcode file and saw that the software is also adding its own retraction.
Can you look into this?

**Comment by Orel-A** [comment]
I just tested the gcode without the last 3 lines, this helps eliminate the underextrusion I was having on the skirts since now it uses the correct retraction length.
Remove these:
`\nG1 E-1.0000 F1800 ;Retract a bit\nG1 Z2.0 F3000 ;Move Z Axis up\nG1 E0.0000 F1800`
And if people are complaining about the nozzle oozing it means their retraction is incorrect.
I use 0.3mm for PLA and 1.2mm for TPU.

Another issue is the 0.38mm line width for support is causing weak layer adhesion.
The best line width is the nozzle diameter * 1.05 which should be 0.42mm.
Can you set the default line width for the V3 KE to these?
image

**Comment by cochcoder** [comment]
> enable Arc Fitting by default

Does the stock Klipper installation support this?

**Comment by Orel-A** [comment]
> Does the stock Klipper installation support this?

Yes it's on by default.

image

Also, I missed that the machine gcode start up code is printing at 0.28mm layer height. Do you think we should change it to 0.2mm?

**Comment by cochcoder** [comment]
> Yes it's on by default.

Ok, I'll enable it once I get the chance

> Also, I missed that the machine gcode start up code is printing at 0.28mm layer height. Do you think we should change it to 0.2mm?

I don't think I'll change it in this PR as I haven't seen anyone complaining about it.

**Review by Orel-A — APPROVED** [review]
Okay, the latest changes look good to me.

**Comment by cochcoder** [comment]
> I use 0.3mm for PLA and 1.2mm for TPU.

One concern I do have for this is that the profiles the KE uses for PLA & TPUs also apply to the SE and could cause some issues. What do you think?

**Comment by cochcoder** [comment]
Apart from that I applied your other suggestions, let me know if everything works for you and once everything is ready to go, I'll mark the PR ready for review. The latest build with the changes [here](https://github.com/cochcoder/OrcaSlicer/actions/runs/8510658706).

**Comment by Orel-A** [comment]
I'm reviewing the changes.
Regarding line width, also set default, outer wall, and top surface to 0.42mm.
This help to prevent layer separation between layers.

Last time we increased outer wall speed to 250mm/s, I think we should revert this change and set it back to 200mm/s. It's causing some kind of wave pattern to manifest on PETG.
Outer wall acceleration should be bumped to 5000mm/s2.
And Jerk(XY) should all be set to 7mm/s, last time we left outer wall, infill and travel on 8mm/s. The firmware itself uses 5mm/s but this can cause blobs on the corners as it's slowing down.
On 8mm/s it's beginning to resonance the bedslinger with the 5000mm/s2 acceleration.

Internal solid infill should be downed to 250mm/s and gap infill increased to 200mm/s.
Intial layer acceleration can be increased to 1000mm/s2 from the 500mm/s2 it's set to.

**Comment by Orel-A** [comment]
> One concern I do have for this is that the profiles the KE uses for PLA & TPUs also apply to the SE and could cause some issues. What do you think?
As I understand it, they have different extruder. So it's not the same.

**Comment by Orel-A** [comment]
Inner wall line width should be 0.45mm. I missed this.
Basically set everything as in this image:
image

**Comment by cochcoder** [comment]
I have applied the given settings to all of the profiles and the new build is located [here](https://github.com/cochcoder/OrcaSlicer/actions/runs/8511398337)

**Comment by cochcoder** [comment]
Should we enable infill combination?

**Comment by Orel-A** [comment]
> Should we enable infill combination?

Yes, enable it.

The elephant foot compensation value was too big. I'm checking for the correct value.

**Comment by Orel-A** [comment]
Wipe distance should be 2mm instead of 1mm (`"wipe_distance": ["2"]`). This reduces some spiderwebs on eSun PLA+.
Reduce infill retraction should be unchecked (`"reduce_infill_retraction": "0"`).

**Comment by Orel-A** [comment]
> How come?

To prevent nozzle scraping on infill the crosses itself.

> Should Z-hop also be disabled by defualt?

No, I'm using Z-hop even on TPU. Why disable it?

**Comment by cochcoder** [comment]
> No, I'm using Z-hop even on TPU. Why disable it?

I was thinking of maybe disabling it due to the stringing it tends to cuase.

**Comment by bistory** [comment]
> > How come?
> 
> To prevent nozzle scraping on infill that crosses itself.
> 
> > Should Z-hop also be disabled by defualt?
> 
> No, I'm using Z-hop even on TPU. Why disable it?

reduce_infill_retraction permits faster prints, users can select infills like gyroid if they want to avoid scraping on infill :-)

**Comment by Orel-A** [comment]
> I was thinking of maybe disabling it due to the stringing it tends to cuase.

That would mean you will need to set 20-30mm/s speed on everything, without slowing down or accelerating too much to prevent it from leaking and oozing (on TPU). But with the correct retraction settings and slowing down the volumetric speed you don't have to worry about that.
Regarding PLA, it depends on the type. With eSun PLA+, when it gets wet it tends to have spiderwebs. It's more resistant to humidity than other filaments that I know, like Creality's Hyper PLA which gets sticky and have micro bubbles when wet.

> reduce_infill_retraction permits faster prints, users can select infills like gyroid if they want to avoid scraping on infill :-)

Yeah, gyroid defintelly helps...

**Comment by Orel-A** [comment]
Okay, set gyroid as the default infill.
Elephant foot compensation should be reduced, my printer is still printing but I think 0.1mm should work.

**Comment by bistory** [comment]
> Okay, set gyroid as the default infill. Elephant foot compensation should be reduced, my printer is still printing but I think 0.1mm should work.

Gyroid infill causes slower printers and makes the machine shake more, let just grid and let user choose what they want :-)

**Comment by cochcoder** [comment]
> Gyroid infill causes slower printers and makes the machine shake more, let just grid and let user choose what they want :-)

Grid would be a good default option, however, the revamped 3D Honeycome does seem promising: same benifits of gyroid, while doing very well for high speed printing.

**Comment by bistory** [comment]
> > Gyroid infill causes slower printers and makes the machine shake more, let just grid and let user choose what they want :-)
> 
> Grid would be a good default option, however, the revamped 3D Honeycome does seem promising: same benifits of gyroid, while doing very well for high speed printing.

But prints are weaker ;-)
It's always a trade-off...

**Comment by cochcoder** [comment]
> But prints are weaker ;-)
It's always a trade-off...

True, I'll leave it to grid

**Comment by Orel-A** [comment]
> Gyroid infill causes slower prints

Exactly.
That's why I recently printed with Cubic infill at 35% density to speed up the print.
But the nozzle scraping is horrible with the V3 KE.

**Comment by cochcoder** [comment]
> > Gyroid infill causes slower prints
> 
> 
> 
> Exactly.
> 
> That's why I recently printed with Cubic infill at 35% density to speed up the print.
> 
> But the nozzle scraping is horrible with the V3 KE.

I think that it should be enabled by default and let people disable it themselves if they choose to. Unless having it enabled is a significant issue (ie significant quality issues, possible damage to the printer, etc)

**Comment by Orel-A** [comment]
> I think that it should be enabled by default

What should be enabled by default?

**Comment by cochcoder** [comment]
> > I think that it should be enabled by default
> 
> 
> 
> What should be enabled by default?

Reduce infill retraction, sorry

**Comment by Orel-A** [comment]
It's fine for it to be on with gyroid.
Anyway, reduce the elephant foot compensation to 0.1mm. With 0.15mm the model won't connect to the brim (excluding the brim-object gap).

**Comment by cochcoder** [comment]
Ok, everything should be applied [here](https://github.com/cochcoder/OrcaSlicer/actions/runs/8513795665)

**Comment by Orel-A** [comment]
Thank you.

Let's disable retract before wipe, it's causing clogs on TPU.
It was introduced by Prusa for the Bowden extruder on the Original Prusa MINI/MINI+.
A gradual retract on wipe is better from my testing:
`"retract_before_wipe": ["0%"]`

We'll speed up the 25-50% and 50-75% overhang speeds and lower the bridging speed to 65mm/s to allow more time on cooling:
```
"overhang_2_4_speed": "50"
"overhang_3_4_speed": "30"
"bridge_speed": "65"
```

**Comment by cochcoder** [comment]
> Thank you.
> 
> 
> 
> Let's disable retract before wipe, it's causing clogs on TPU.
> 
> It was introduced by Prusa for the Bowden extruder on the Original Prusa MINI/MINI+.
> 
> A gradual retract on wipe is better from my testing:
> 
> `"retract_before_wipe": ["0%"]`


And this doesn't negatively affect PLA?

**Comment by cochcoder** [comment]
Done! Anything else?

**Comment by Orel-A** [comment]
I'm doing some VFA tests.
Also checking if we can safely increase the travel speed, must likely yes.

**Comment by Orel-A** [comment]
`machine_max_acceleration_z` should be 300mm/s2 the same as it's set in printer.cfg `max_z_accel: 300`
`machine_max_jerk_x` and `machine_max_jerk_y` should be set to 7mm/s
Outer wall speed return to 250mm/s, sorry about that. `"outer_wall_speed": "250"`
`machine_max_speed_e` should be 40mm/s

**Comment by cochcoder** [comment]
Thanks for finding that! I started a new build, with the new values, [here](https://github.com/cochcoder/OrcaSlicer/actions/runs/8527957635) if you want :)

**Comment by Orel-A** [comment]
By the way, the print percentage on the screen isn't working. It's showing 0% all the time.
I've looked into the gcode that Creality Print exports, it has `;TIME_ELAPSED: HERE_SECONDS_SINCE_START`
I've tried to mimic this behaviour in Orca but the gcode variable for second isn't since the print started...
I'm not sure if it's even related...

**Comment by Orel-A** [comment]
PLA bed temperature needs to be 60C not 55C.
The support top Z distance preferably be in increments of 0.04mm so change it from 0.15mm to 0.16mm.
The minimum layer height is 0.08mm, I think the minimum should be 0.12mm...

**Comment by bistory** [comment]
Pla bed temp has been set to 55°C because it is sufficient for PLA on PEI.
It allows to save a bit of power 🙂

**Comment by Orel-A** [comment]
I'm investigating this.
The upload command is fairly simple. It's a HTTP POST with the file name in the URL.
http://LAN_IP_ADDRESS/upload/Cube_PLA_29s.gcode
But other commands seem to go through a WebSocket connection.
I'll try to sniff the packets of Creality Print and see if it's any simpler.

**Comment by cochcoder** [comment]
> The support top Z distance preferably be in increments of 0.04mm so change it from 0.15mm to 0.16mm. The minimum layer height is 0.08mm, I think the minimum should be 0.12mm...

Let me know if the support z distance is too much at 0.16, I doubt this. I also decided to not change the minimum layer height to 0.12 as I don't see a valid reason for doing this and I don't want to potentially cause any potential issues with someone's profile.

**Review by Orel-A — APPROVED** [review]
Looks good.

**Review by SoftFever — APPROVED** [review]
Looks good.

**Comment by SoftFever** [comment]
@cochcoder @Orel-A @bistory 
Thank you all！
Merged.

**Comment by Orel-A** [comment]
@cochcoder I noticed that the tolerances of screw holes in prints are too tight and nuts can't fit at all. I've done the Orca Tolerances Test, and we need to set 0.1mm in compensation.
`"xy_hole_compensation": "0.1"`

I also think we should reduce the default threshold angle of supports to 30 degrees:
`"support_threshold_angle": "30"`

Furthermore, retraction speed is too high for TPU and to reduce bite marks on PLA I suggest we lower it and match it to Creality Print's own settings. `deretraction_speed` is set to zero to mirror the retraction speed in case people change it in filament override settings.
```
"retraction_speed": ["30"],
"deretraction_speed": ["0"]
```

Thanks for your help.

**Comment by cochcoder** [comment]
> @cochcoder I noticed that the tolerances of screw holes in prints are too tight and nuts can't fit at all. I've done the Orca Tolerances Test, and we need to set 0.1mm in compensation. `"xy_hole_compensation": "0.1"`
> 
> I also think we should reduce the default threshold angle of supports to 30 degrees: `"support_threshold_angle": "30"`
> 
> Furthermore, retraction speed is too high for TPU and to reduce bite marks on PLA I suggest we lower it and match it to Creality Print's own settings. `deretraction_speed` is set to zero to mirror the retraction speed in case people change it in filament override settings.
> 
> ```
> "retraction_speed": ["30"],
> "deretraction_speed": ["0"]
> ```
> 
> Thanks for your help.

I'll look into implementing these changes if @Orel-A can verify these changes as I don't personally own this printer.

**Comment by Orel-A** [comment]
> I'll look into implementing these changes if @Orel-A can verify these changes as I don't personally own this printer.

That's me, sir.

**Comment by cochcoder** [comment]
> > I'll look into implementing these changes if @Orel-A can verify these changes as I don't personally own this printer.
> 
> That's me, sir.

Lol, I need some sleep, I'll try to add these changes before the weekend.

**Comment by cochcoder** [comment]
> I also think we should reduce the default threshold angle of supports to 30 degrees: "support_threshold_angle": "30"

Should this only be applied to the Standard & Draft settings, rather than also the Fine settings?

**Comment by cochcoder** [comment]
I have implemented the changes, please let me know if this [build](https://github.com/cochcoder/OrcaSlicer/actions/runs/8655093065) looks good once it's done compiling.

**Review by esn814 — COMMENTED** [review]
Well played hoppfully im upp and printing soon

**Comment by cochcoder** [comment]
> @cochcoder There is a problem sometimes when the BL-Touch homes the Z axis on cold bed, it affects the z-offset. I had it today when the nozzle scratched the bed due to it.
> 
> 
> 
> I purpose a new change to to the machine start gcode:
> 
> ```
> 
> M220 S100 ;Reset Feedrate
> 
> M221 S100 ;Reset Flowrate
> 
> 
> 
> M140 S[bed_temperature_initial_layer_single] ;Set bed temp
> 
> G28 X Y ;Home XY axes
> 
> M190 S[bed_temperature_initial_layer_single] ;Wait for bed temp to stabilize
> 
> M104 S[nozzle_temperature_initial_layer] ;Set nozzle temp
> 
> G28 Z ;Home Z axis & load bed mesh
> 
> 
> 
> G92 E0 ;Reset Extruder
> 
> G1 X-2.0 Y20 Z0.28 F5000.0 ;Move to start position
> 
> M109 S[nozzle_temperature_initial_layer] ;Wait for nozzle temp to stabilize
> 
> G1 X-2.0 Y145.0 Z0.2 F1500.0 E15 ;Draw the first line
> 
> G1 X-1.7 Y145.0 Z0.2 F5000.0 ;Move to side a little
> 
> G1 X-1.7 Y30 Z0.2 F1500.0 E15 ;Draw the second line
> 
> G92 E0 ;Reset Extruder
> 
> ```
> 
> 
> 
> In JSON:
> 
> `"machine_start_gcode": "M220 S100 ;Reset Feedrate\nM221 S100 ;Reset Flowrate\n\nM140 S[bed_temperature_initial_layer_single] ;Set bed temp\nG28 X Y ;Home XY axes\nM190 S[bed_temperature_initial_layer_single] ;Wait for bed temp to stabilize\nM104 S[nozzle_temperature_initial_layer] ;Set nozzle temp\nG28 Z ;Home Z axis & load bed mesh\n\nG92 E0 ;Reset Extruder\nG1 X-2.0 Y20 Z0.28 F5000.0 ;Move to start position\nM109 S[nozzle_temperature_initial_layer] ;Wait for nozzle temp to stabilize\nG1 X-2.0 Y145.0 Z0.2 F1500.0 E15 ;Draw the first line\nG1 X-1.7 Y145.0 Z0.2 F5000.0 ;Move to side a little\nG1 X-1.7 Y30 Z0.2 F1500.0 E15 ;Draw the second line\nG92 E0 ;Reset Extruder"`
> 
> 
> 
> The new changes are; the printer will first home the X & Y axes, then will wait for the bed temperature to stabilize, then will start to heat the nozzle and at the same time will home the Z axis.

If you can confirm that this fixes the issue, then I'll add it to the profile fixes PR.

**Comment by Orel-A** [comment]
> If you can confirm that this fixes the issue, then I'll add it to the profile fixes PR.

Yes, it's working beautifully.

**Comment by cochcoder** [comment]
It's added! Thank you for your help again, let me know if you notice anything else!

**Comment by arosovic** [comment]
> > If you can confirm that this fixes the issue, then I'll add it to the profile fixes PR.
> 
> Yes, it's working beautifully.



> > @cochcoder There is a problem sometimes when the BL-Touch homes the Z axis on cold bed, it affects the z-offset. I had it today when the nozzle scratched the bed due to it.
> > I purpose a new change to to the machine start gcode:
> > ```
> > 
> > M220 S100 ;Reset Feedrate
> > 
> > M221 S100 ;Reset Flowrate
> > 
> > 
> > 
> > M140 S[bed_temperature_initial_layer_single] ;Set bed temp
> > 
> > G28 X Y ;Home XY axes
> > 
> > M190 S[bed_temperature_initial_layer_single] ;Wait for bed temp to stabilize
> > 
> > M104 S[nozzle_temperature_initial_layer] ;Set nozzle temp
> > 
> > G28 Z ;Home Z axis & load bed mesh
> > 
> > 
> > 
> > G92 E0 ;Reset Extruder
> > 
> > G1 X-2.0 Y20 Z0.28 F5000.0 ;Move to start position
> > 
> > M109 S[nozzle_temperature_initial_layer] ;Wait for nozzle temp to stabilize
> > 
> > G1 X-2.0 Y145.0 Z0.2 F1500.0 E15 ;Draw the first line
> > 
> > G1 X-1.7 Y145.0 Z0.2 F5000.0 ;Move to side a little
> > 
> > G1 X-1.7 Y30 Z0.2 F1500.0 E15 ;Draw the second line
> > 
> > G92 E0 ;Reset Extruder
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > In JSON:
> > `"machine_start_gcode": "M220 S100 ;Reset Feedrate\nM221 S100 ;Reset Flowrate\n\nM140 S[bed_temperature_initial_layer_single] ;Set bed temp\nG28 X Y ;Home XY axes\nM190 S[bed_temperature_initial_layer_single] ;Wait for bed temp to stabilize\nM104 S[nozzle_temperature_initial_layer] ;Set nozzle temp\nG28 Z ;Home Z axis & load bed mesh\n\nG92 E0 ;Reset Extruder\nG1 X-2.0 Y20 Z0.28 F5000.0 ;Move to start position\nM109 S[nozzle_temperature_initial_layer] ;Wait for nozzle temp to stabilize\nG1 X-2.0 Y145.0 Z0.2 F1500.0 E15 ;Draw the first line\nG1 X-1.7 Y145.0 Z0.2 F5000.0 ;Move to side a little\nG1 X-1.7 Y30 Z0.2 F1500.0 E15 ;Draw the second line\nG92 E0 ;Reset Extruder"`
> > The new changes are; the printer will first home the X & Y axes, then will wait for the bed temperature to stabilize, then will start to heat the nozzle and at the same time will home the Z axis.
> 
> If you can confirm that this fixes the issue, then I'll add it to the profile fixes PR.

Sorry for this hard core newbie question, but where to find the fixed profile and how to apply it/upload it to Orca?

**Comment by cochcoder** [comment]
> Thx for your reply. I can wait for the updated version of Orca. So, the printer (V3 KE) will be updated, too?

Yep, it'll even include the improvements Orel-A mentioned in #4793

**Comment by Piettro-Laurindo** [comment]
this profile is making a bed mesh calibration on every print, how can i disable that?

**Comment by Rhrod-5** [comment]
will this work for the se

**Comment by cochcoder** [comment]
> will this work for the se 

These changes were made specifically for the KE, but if you want to try them in the SE, feel free to do so

**Pull request merged**
