### PR TITLE
Add Artillery Genius Pro Profile

### PR DESCRIPTION
**Pull request by Mr-PBH**
Added the Artillery Genius Pro Profile. The changes allow the user to add the printer in the wizard and a photo to differ from the regular Genius model. Additionally some temperature changes to the base filament for the Artillery printers, mainly raising the bed temp to 60c rather than 45c.

### CODE REVIEW

**Review by SoftFever — CHANGES_REQUESTED** [review]
Thanks for the PR.
Did you forget to include the changes in Artillery.json?

**Review by Mr-PBH — COMMENTED** [review]
Add genius pro paths to Artillery.json

**Comment by Mr-PBH** [comment]
> Thanks for the PR. Did you forget to include the changes in Artillery.json?

I had the changes locally but i guess it didn't reflect my fork or PR.
Thank you for pointing that out.

**Review by SoftFever — APPROVED** [review]
Looks good.
Thank you very much 👍

**Pull request merged**
