### PR TITLE
Port "Extend sparse infill" from Prusa

### PR DESCRIPTION
**Pull request by Noisyfox**
#1165

image
image

This also removes the "internal_bridge_support_thickness" option as it's replaced by the extend sparse infill feature and no longer needed.

### CODE REVIEW

**Comment by Noisyfox** [comment]
Also this PR includes changes from #2132.

**Comment by igiannakas** [comment]
Hi Noisyfox, does this also contain the code for the vertical shell thickness? Would love to test that out compared to Bambus implementation.

**Comment by Noisyfox** [comment]
> Hi Noisyfox, excellent work!! Ps. does this also contain the code for the vertical shell thickness? Would love to test that out compared to Bambus implementation.

Nope.

**Comment by SoftFever** [comment]
@Noisyfox 
Fantastic!

I noticed some area is not achored properly.
Any idea what could be the cause?

image
[extended_sparse_infill_layer_188_issue.zip](https://github.com/SoftFever/OrcaSlicer/files/12706423/extended_sparse_infill_layer_188_issue.zip)

**Comment by Noisyfox** [comment]
> @Noisyfox Fantastic!
> 
> I noticed some area is not achored properly. Any idea what could be the cause?
> 
> image [extended_sparse_infill_layer_188_issue.zip](https://github.com/SoftFever/OrcaSlicer/files/12706423/extended_sparse_infill_layer_188_issue.zip)

image
Fixed

**Comment by Noisyfox** [comment]
I've further improved the algorithm so it finds the optimal bridge direction under extreme conditions (0% infill):
Prusa:
image

Our improved version:
image

**Review by SoftFever — APPROVED** [review]
LGTM

**Comment by SoftFever** [comment]
Awesome!

**Comment by Creo2005** [comment]
Screenshot 2023-10-30 090337
in latest beta I don't see these options.

**Comment by Noisyfox** [comment]
> Screenshot 2023-10-30 090337 in latest beta I don't see these options.

There is no options for this. It's on permanently.

**Pull request merged**
