### PR TITLE
Fix issue that print host and webui settings are not properly reset

### PR DESCRIPTION
**Pull request by Noisyfox**
after switching from certain host type

### CODE REVIEW

**Comment by SoftFever** [comment]
@Noisyfox 
How to reproduce the bug?

**Comment by Noisyfox** [comment]
1. Switch the print host to obico/prusa connect/simplyprint, leave the default api url option and save
2. Go to device tab to make sure the target web page has been loaded
3. Switch the print host to octo etc. that does not come with a default url, and the url & webui field shoud appears to be cleared, then save
4. Go to device tab, and you will notice that the obico/prusa connect/simplyprint web page is still loaded, even after restarting the app

**Comment by Noisyfox** [comment]
print_host_url

**Comment by SoftFever** [comment]
Thanks!

**Pull request merged**
