### PR TITLE
just fixing a typo

### PR DESCRIPTION
**Pull request by discip**
_in_ the bottom => **on** the bottom

### CODE REVIEW

**Comment by SoftFever** [comment]
Thanks
I think "in the bottom" is not wrong here though

**Comment by discip** [comment]
I think that's actually wrong, as by definition it would mean that there is something _**in**_ the bottom of the enclosure, not **on** the bottom.

Isn't that the descriptive text for the process of lowering the print bed, which involves reducing the current of the Z motor to avoid damaging the underside of it?


Just to be clear:
image

**Comment by discip** [comment]
@SoftFever
I think that's actually wrong, as by definition it would mean that there is something _**in**_ the bottom of the enclosure, not **on** the bottom.

Isn't that the descriptive text for the process of lowering the print bed, which involves reducing the current of the Z motor to avoid damaging the underside of it?


Just to be clear:

image

**Comment by discip** [comment]
@SoftFever
Could you please elaborate what am I missing here?

**Pull request closed without merging**
