### PR TITLE
Reverse draft shield direction on even layers to reduce thermal stress.

### PR DESCRIPTION
**Pull request by vovodroid**
This PR will increase draft shield stability.

N.B. `layer_id % 2 == 1` is odd mathematically, but from user POV layer number starts from one, not zero.

### CODE REVIEW

**Review by SoftFever — COMMENTED** [review]
Thanks @vovodroid
I'm a bit confused why you claim reverse dir will increase stability. It has no overhangs
Care to explain?

**Comment by vovodroid** [comment]
That's what is `reverse_internal` option for:

>This setting greatly reduces part stresses as they are now distributed in alternating directions. This should reduce part warping while also maintaining external wall quality. This feature can be very useful for warp prone material, like ABS/ASA, and also for elastic filaments, like TPU and Silk PLA. It can also help reduce warping on floating regions over supports.

There is also  **Add option to "Reverse only internal perimeters" under the reverse on odd feature to reduce part warping #2722** 

So I guess it's also correct for draft shield.

**Comment by SoftFever** [comment]
That's designed for overhangs.
Which I think doesn't really applies to draft shield

**Comment by vovodroid** [comment]
Actually reverse internals with threshold 0 reverses all walls, disregarding overhangs. And warping is common problem, not overhangs only.

**Comment by SoftFever** [comment]
I'm not 100% convinced but then I can't think of any harm with this change.
One last thing, can you double check if draft shield is affected by `wall_direction`?
If it does, the proposed change won't always work

**Comment by vovodroid** [comment]
Skirt direction is not affected by walls. 
image
image

Nevertheless to make code more transparent I'm replacing `make_clockwise `with `reverse`.

**Review by SoftFever — APPROVED** [review]

**Comment by SoftFever** [comment]
Looks good
Thank you!

**Pull request merged**
