### PR TITLE
Wrong bridge detection result (FOR TESTING ONLY)

### PR DESCRIPTION
**Pull request by SoftFever**
Quick and dirty.
Haven't got time to dive deep to the original code logic yet.
Initial testing result seems fine.
image

@igiannakas 
[OrcaCube.zip](https://github.com/SoftFever/OrcaSlicer/files/14735411/OrcaCube.zip)

### CODE REVIEW

**Comment by igiannakas** [comment]
Makes sense, subtract top area from the bridging area, good one! The only thing I can think off is whether we need to add an expansion margin to the top area unless that is covered elsewhere? To ensure there is enough expansion basically underneath the solid infill lines above the Z. 

Will also need to regression test it with the sloped models to make sure bridging is still performed properly there. 

Will test a bit when back home.

**Comment by SoftFever** [comment]
Yeah, bridge margin is usually handled in perimeter generator
image

**Comment by igiannakas** [comment]
Initial tests show no regressions. Sloped surfaces look good, no impact there. Standard models look also OK. 

To contain potential impact for defects in the 2.0 release, maybe push this in 2.1 after more testing by the community?

**Comment by SoftFever** [comment]
> Initial tests show no regressions. Sloped surfaces look good, no impact there. Standard models look also OK.
> 
> To contain potential impact for defects in the 2.0 release, maybe push this in 2.1 after more testing by the community?
> 
> I've merged it in my dev branch and use it as my daily just in case any issues pop up :)

I think so, too

**Comment by vgdh** [comment]
something maybe wrong


[Cube.zip](https://github.com/SoftFever/OrcaSlicer/files/14897901/Cube.zip)

**Comment by igiannakas** [comment]
> something maybe wrong sudden flow change in the bridge   [Cube.zip](https://github.com/SoftFever/OrcaSlicer/files/14897901/Cube.zip)

Is this also happening with the 2.0 release or not?

**Comment by vgdh** [comment]
in version 1.9.1 it's fine though

**Comment by igiannakas** [comment]
So it’s not this PR then, right?

**Comment by vgdh** [comment]
> So it’s not this PR then, right?

yeah

**Pull request merged**
