### PR TITLE
Creality K1 Profiles improvements (and K1C addition)

### PR DESCRIPTION
**Pull request by bistory**
This PR aims to improve K1 profiles by : 

- Adding new filament types (PLA-CF, PA-CF)
- Improving default settings (for example, retraction length goes from 0.6 to 0.5mm to reduce oozing)
- Adding K1C profile
- For K1C, I have made specific filament profiles so "Generic PLA" doesn't have a low volumetric speed by default
- For K1C, processes names are more concise : I removed "0.x nozzle" indication as it is useless and handled by the slicer
- For K1C, files have been prettified with JSON Prettifier
- For K1/K1 Max : using Creality Generic HF PLA by default to avoid users to use Creality Generic PLA
- For K1/K1 Max : Porting special PLA (silk, matte, high speed) from K1C
- Changing thumbnail default size to optimize pixels density
- Enabling multi bed types
- Changing slow down layer time and slow down min speed in order to improve overall speed on details
- Optimized ASA profile
- _More to come..._

_I decided to make a draft PR in order to lock PR for K1C addition, to be sure to have a cleaner base than K1/K1 Max. Don't hesitate to test them and make feedbacks !_

If you want to test, you can download Creality profiles here : 
[Archive.zip](https://github.com/SoftFever/OrcaSlicer/files/13976520/Archive.zip) and put them in your **application folder** (depends on your system) then resources/profiles, replace Creality.json file and Creality folder with the ones in the zip file.

### CODE REVIEW

**Comment by Brockas** [comment]
Can you make some profiles to use 0.6 and 0.8 nozzle for the K1. Thanks

**Comment by bistory** [comment]
> Can you make some profiles to use 0.6 and 0.8 nozzle for the K1. Thanks

They are already there ;-)

Capture d’écran 2024-01-18 à 15 46 58

**Comment by Georgelou35** [comment]
Cant wait to test them.And i will upload photos and more information.

**Comment by dwaite** [comment]
Does a textured plate need G-Code to adjust the Z Offset?

**Comment by bistory** [comment]
> Does a textured plate need G-Code to adjust the Z Offset?

Not idea, but it shouldn't be the case as Creality does nothing on their slicer whatever plate you use

**Comment by Georgelou35** [comment]
I start print a rtown part from Blastoise pokemonSo far so good from the first layer

**Comment by Georgelou35** [comment]
IMG_20240123_161254
IMG_20240123_161249

**Comment by Georgelou35** [comment]
So far so good.I want to say that your Profile is magnificent 🤌
Its so clean the printing 
IMG_20240123_204639
IMG_20240123_204633

IMG_20240123_204622
IMG_20240123_204618

**Comment by bistory** [comment]
@Georgelou35 great ! Good to know the profile works great for you ! I will probably undraft this PR soon to get it merged to the main branch :-)
Thanks for your valuable feedback !

**Comment by Georgelou35** [comment]
I must thank you because you spend a loy of time and effort to make this great profile 😊😊.

**Review by SoftFever — APPROVED** [review]
Looks good

**Comment by SaturnsVoid** [comment]
How about a few slower profiles for more high-detail/cleaner prints?

**Comment by PIPIAJT** [comment]
Hello, I found a problem. The exhaust fan of k1max is m106 p1, not m106 p3 (sorry for my poor English)

**Comment by bistory** [comment]
> Hello, I found a problem. The exhaust fan of k1max is m106 p1, not m106 p3 (sorry for my poor English)

It's 100% Creality's fault, they are not using the standard command : https://github.com/SoftFever/OrcaSlicer/issues/3373

**Pull request merged**
