### PR TITLE
Duplicate Current Plate with objects

### PR DESCRIPTION
**Pull request by eoyilmaz**
# Description

- Addressed #2025 
- Added "Duplicate Plate" for the plate and the main toolbar

# Screenshots/Recordings/Graphs

[Video demo](https://github.com/SoftFever/OrcaSlicer/assets/1786804/0b14ba9e-8683-4712-82ad-37108eaab3be)

## Tests

Run manual tests only...

### CODE REVIEW

**Comment by eoyilmaz** [comment]
Yes, I didn't think about the local transformations, need to do the transformation in global space.

**Comment by eoyilmaz** [comment]
Okay the local vs global transformation issue has been fixed now:

https://github.com/SoftFever/OrcaSlicer/assets/1786804/6f2e6081-800e-4cba-a62a-819f8c8d8f5d

And this is ready to be reviewed.

**Comment by eoyilmaz** [comment]
Any progress with this PR?

**Comment by eoyilmaz** [comment]
Tagging @SoftFever

**Comment by eoyilmaz** [comment]
@SoftFever do you need any changes or any review comments?

**Comment by SoftFever** [comment]
Hi @eoyilmaz 

Thank you for your time and effort.
After reviewing the use case, I feel it serves a very specific purpose that is unlikely to benefit other users. Therefore, I believe it's not a strong fit for the mainstream.

**Comment by techman83** [comment]
Interestingly, googling for this very use case led me to subscribing to this PR for updates. :slightly_smiling_face:

**Comment by eoyilmaz** [comment]
> Hi @eoyilmaz
> 
> Thank you for your time and effort. After reviewing the use case, I feel it serves a very specific purpose that is unlikely to benefit other users. Therefore, I believe it's not a strong fit for the mainstream.

Oh, okay, I used this functionality a lot in one of my last projects, where I had to print the same items in differnt color combinations, and because they were barely fitting to the built plate, placing them was not easy, duplicating the plate was much much easier.

Do you think that we can at least supply this functionality in the edit menu or somewhere else? Instead of placing it into the main toolbar and on the plate actions.

**Comment by PalyCGman** [comment]
I would very much appreciate if this "copy build plate" feature were implemented. Thanks

**Comment by SoftFever** [comment]
> > Hi @eoyilmaz
> > Thank you for your time and effort. After reviewing the use case, I feel it serves a very specific purpose that is unlikely to benefit other users. Therefore, I believe it's not a strong fit for the mainstream.
> 
> Oh, okay, I used this functionality a lot in one of my last projects, where I had to print the same items in different color combinations, and because they were barely fitting to the built plate, placing them was not easy, duplicating the plate was much much easier.
> 
> Do you think that we can at least supply this functionality in the edit menu or in right-click context menu or somewhere else? Instead of placing it into the main toolbar and on the plate actions.

Put it into `Edit` menu sounds feasible.

**Comment by SoftFever** [comment]
Seems this PR is currently inactive.
I'm closing it for now.
Please feel free to re-open it whenever you feel ready.
Thank you for your contribution!

**Comment by TylonHH** [comment]
Please implement thsi feature

**Comment by eoyilmaz** [comment]
I updated my branch, so that the "Duplicate Current Plate" functionality now lives in the Edit menu, and removed the previously created actions in the plate actions and in the toolbar. I opted to keep the icons for future use.

https://github.com/user-attachments/assets/d6f8f37e-8fad-44b5-b5ab-7c12b75b372b

@SoftFever, I can't re-open this PR, can help me with this?

**Comment by SoftFever** [comment]
> I updated my branch, so that the "Duplicate Current Plate" functionality now lives in the Edit menu, and removed the previously created actions in the plate actions and in the toolbar. I opted to keep the icons for future use.
> 
> @SoftFever, I can't re-open this PR, can help me with this?
> 
>  Orca_Slicer_Duplicate_Plate_Preview_3_1.mp4

That's strange.
I can't reopen it either.
Looks like there is a forced pushing in this feature branch.
image

Can you create another PR instead?

**Comment by eoyilmaz** [comment]
Create #6710

**Pull request closed without merging**
