### PR TITLE
Various Emboss improvements from PS

### PR DESCRIPTION
**Pull request by Noisyfox**
Sync latest emboss/svg code from PS 2.7.2-alpha2, which fixes https://github.com/SoftFever/OrcaSlicer/pull/2819#issuecomment-1846791320
and some other improvements.

### CODE REVIEW

**Comment by discip** [comment]
Just noticed the folollowing:

image

Is this a typo or a reference to you? 😁😃😊😄

Nice! 👍

**Comment by discip** [comment]
Just noticed the folollowing:

image

Is this a typo or a reference to you? 😁😃😊😄

Nice! 👍

**Comment by discip** [comment]
Just noticed the following:

image

Is this a typo or a reference to you? 😁😃😊😄

Nice! 👍

**Comment by SoftFever** [comment]
> Just noticed the following:
> 
> image
> 
> Is this a typo or a reference to you? 😁😃😊😄
> 
> Nice! 👍

hahaha

**Pull request merged**
