### PR TITLE
Обновление перевода на русский язык, при поддержке AndylgTom

### PR DESCRIPTION
**Pull request by stasyan68**
Обновление перевода на русский язык, при поддержке AndylgTom

### CODE REVIEW

**Comment by SoftFever** [comment]
Not sure if I understand it.
But I assume this is duplicated with @AndylgTom's PR #1994 ?

**Comment by stasyan68** [comment]
You got it right! I thought he would appreciate the help!

**Comment by AndylgTom** [comment]
> You got it right! I thought he would appreciate the help! From now on I will update my translation, regardless of @AndylgTom, he acted ugly, replacing my translation with his own!

And why is that necessary? I'm not going to stop supporting translation.
"With my support"? Are you kidding me? It's my translation from start to finish (90% of which comes from Prusa), not one line of yours. And now you're gonna tell me it's ugly? I didn't take anything from you, unlike you. 
I told you in private why I replaced it. You have seen the quality of your lousy translation, I told you about it and video specially recorded for you with comments, not just blabbering and beating your chest, like if you are the first, then you are right. You should not have been initially shameful with such a translation. I wrote about it here https://github.com/bambulab/BambuStudio/issues/1960#issuecomment-1640657506. You do not understand the terminology of printing, 3D modeling terminology. So you'd be correcting your translation for years. Put your pride away. And you don't have to answer me anything.

@SoftFever He just decided that if he is the first, he is right about everything, but I think the quality of translation comes first. He originally had a purely machine translation and why he's making this circus now by writing that "with my support", I don't know. I didn't give him any right to use it and say so. I'm not going to stop my translation support (for both Prusa, Bambu and OrcaSlicer). I think you get what I meant by that - just ignore @stasyan68.

**Comment by Makismax2020** [comment]
где можно скачать руссификатор ваш?

**Pull request closed without merging**
