### PR TITLE
Fix btt tft thumbnail regression

### PR DESCRIPTION
**Pull request by SoftFever**

### CODE REVIEW

**Comment by SoftFever** [comment]
@discip @Rsoft1976
Thanks for reporting the issue.
When you have time, could you please test if this resolves the issue for the BTT TFT? 
I don't have this monitor, so I'm unable to verify it myself.

**Comment by discip** [comment]
## Thank you for taking care of this! 👍🏻

Unfortunately this did not solve the issue:

image

**Comment by discip** [comment]
# Thank you for taking care of this! 👍🏻 ❤️

This fixed it for me!

**Comment by SoftFever** [comment]
> # Thank you for taking care of this! 👍🏻 ❤️
> This fixed it for me!

thanks for testing it

**Pull request merged**
