### PR TITLE
Add Chocolatey info for Windows installations

### PR DESCRIPTION
**Pull request by strausmann**
This PR adds the Chocolatey OrcaSlicer Package Info to the readme file.

### CODE REVIEW

**Comment by SoftFever** [comment]
Hi @strausmann 

Thanks for the PR.
May I check if this Choco package is built and maintained by you?

**Comment by strausmann** [comment]
Yes, the package is managed by myself

**Comment by SoftFever** [comment]
Closing inactive PRs.
Feel free to reopen it if you are still working on it and it's ready to be reviewed/merged again.

-SoftFever

**Comment by strausmann** [comment]
Please merge my PR

**Comment by strausmann** [comment]
Hi @SoftFever, please merge my changes...

**Pull request closed without merging**
