### PR TITLE
Update and correct Vz configs

### PR DESCRIPTION
**Pull request by HumbleDeer**
- Family changed from Vzbot to VzBoT
- Added printable height to the root machine file
- Moved the values previously in klipper common to vzbot common
- Added new klipper common from the Voron directory as reference/parent
  - Purged redundant values from vzbot common that were now already defined in the new klipper common
- Removed DSLR/Snapshot/timelapse picture from the default vzbot layer change gcode (1)

Feedback from OrcaSlicer team welcome; the standards of how these configs are written are a little unclear to me 

(1) These changed include some which were requested by the VzBoT3D team (of which I'm member on GitHub)

### CODE REVIEW

**Comment by HumbleDeer** [comment]
@pbsuper @staticfx

**Comment by SoftFever** [comment]
Seems this PR has gone stale.
I will temporarily close it as I'm trying to keep the pending PR list short. 
Feel free to reopen it when you think it's ready

**Comment by HumbleDeer** [comment]
> Seems this PR has gone stale. I will temporarily close it as I'm trying to keep the pending PR list short. Feel free to reopen it when you think it's ready

It'll be up to the Vz team to pick this back up if they wish to. I'm no longer in any position to speak on this.

**Comment by SoftFever** [comment]
> > Seems this PR has gone stale. I will temporarily close it as I'm trying to keep the pending PR list short. Feel free to reopen it when you think it's ready
> 
> It'll be up to the Vz team to pick this back up if they wish to. I'm no longer in any position to speak on this.

Thank you for submitting the PR, and I apologize for my delayed response. I've attempted to comment on it multiple times, but I've been consistently distracted. The questions from the Discord part is also a bit overwhelming for me, as I lack experience with this particular machine.

**Comment by HumbleDeer** [comment]
No worries. If there's demand I can pick up the finished parts and put them
in a new PR.

There's one thing that bothered people quite severely that may be worth my
time.

**Pull request closed without merging**
