### PR TITLE
Creality textures and covers tweaks

### PR DESCRIPTION
**Pull request by bistory**
- Fix for textures of K1 series and V3 KE/SE (see screenshots, the issue has been introduces recently)
- Images optimisations using ImageOptim (files size reduction)

Before :
Capture d’écran 2024-02-29 à 20 53 34

After : 
Capture d’écran 2024-03-01 à 10 27 29

### CODE REVIEW

**Comment by SoftFever** [comment]
Thank you 👍

**Review by SoftFever — APPROVED** [review]
Looks good

**Comment by yw4z** [comment]
i recommend pinga ([Link](https://css-ig.net/pinga)) for png compression it does wonders
```
Original>>>Pinga>>>>imageOptim
24,6>>>>>18,6>>>>>24,4
```
here is used setting, it can compress a bit more but i prefer light compression
Screenshot-20240301223607

**Comment by bistory** [comment]
> i recommend pinga ([Link](https://css-ig.net/pinga)) for png compression it does wonders
> 
> ```
> Original>>>Pinga>>>>imageOptim
> 24,6>>>>>18,6>>>>>24,4
> ```
> 
> here is used setting, it can compress a bit more but i prefer light compression Screenshot-20240301223607

Thanks but this app is only for Windows that I don't have and it seems to be a lossy compressor while ImageOptim uses lossless algorithms for PNG compression.

**Comment by yw4z** [comment]
I have a texture collection and compressed all images with that and i cant see a big difference. i checked all folders on orca slicer. with compressed images size can be reduced up to 15+MB

**Pull request merged**
