### PR TITLE
Potential fix for other layers bed temperature not applied

### LINKED ISSUE #1853: Temps in filament settings not being inserted into sliced file
**Describe the bug**
User values entered in Print Temperatures in Filament Settings are not being automatically inserted into code of the sliced file. 

**3mf File for This Bug**
N/A

**To Reproduce**
Go to Filament Settings > Nozzle or High Temp Plate settings and change values. 
Slice file and view generated code under filament start G-code.
Notice no code is generated for the nozzle or bed temps inputted by the user.
Should have set bed and set extruder temp G-code commands
Only way to get code to appear is to enter manual commands in Advanced > Filament Start G-code 

**Expected behavior**
Filament start G-code should have nozzle and bed temperature commands auto created from user entered values in the UI instead of requiring manual G-code entries.

**Screenshots**

**Printer model**
N/A

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 1.6.4 Beta 3

### LINKED ISSUE #3015: "Other layers" bed temperature not working after changing settings
### OrcaSlicer Version

1.8.0

### OS version

Windows 11

### Additional system information

_No response_

### Printer

Klipper Generic

### How to reproduce

1. Slice something (M140 is present)
2. Change e.g. brim settings
3. Slice (M140 is missing)
4. Revert the brim settings
5. Slice (M140 is still missing)
6. Change profile
7. Slice (M140 is present again)

### Actual results

See the video:

https://github.com/SoftFever/OrcaSlicer/assets/13891066/90334718-4f9c-4c2d-b5a2-e76e64c55218

### Expected results

M140 should be present every time

### Project file & Debug log uploads

[after-issue.zip](https://github.com/SoftFever/OrcaSlicer/files/13572825/after-issue.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

### LINKED ISSUE #4676: Slicer doesn't change bed temperature for upper layers
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.1 dev

### Operating System (OS)

Windows

### OS Version

win 10

### Additional system information

_No response_

### Printer

kingroon kp3s

### How to reproduce

make two objects with different colors
slice

### Actual results

in the gcode absent change bed temperature gcode after the first layer done.

### Expected results

change bed temp for other layers

### Project file & Debug log uploads

[project.zip](https://github.com/SoftFever/OrcaSlicer/files/14735136/Tmp.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Anything else?

_No response_

### LINKED ISSUE #5485: "other layers" bed temperature don't apply when disabling supports or disabling brims
### Is there an existing issue for this problem?

- [ ] I have searched the existing issues

### OrcaSlicer Version

2.0.0

### Operating System (OS)

Windows

### OS Version

11 Pro

### Additional system information

CPU: Ryzen 3 3300x
GPU: Asus Rog Strix 1070ti

### Printer

Neptune 4 Max

### How to reproduce

1. Go to filament settings, set first layer bed temperature to 70 degree, set other layers to 60 degree
2. In process, turn turn off supports/disable auto brim
3. Slice
4. Check gcode preview at the start of layer 2/end of layer 1

### Actual results

M104 is present (Nozzle temp), but M140 is not (Bed temp)
Printer does not lower temps after first layer because the gcode is not present

### Expected results

M140 S60 should be present
Printer should lower bed temperature to 60 after first layer

### Project file & Debug log uploads

[No bed temp change bug report.zip](https://github.com/SoftFever/OrcaSlicer/files/15467252/No.bed.temp.change.bug.report.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Anything else?

image

### PR DESCRIPTION
**Pull request by igiannakas**
# Description

On occasion the second layer bed temperature was not set according to the filament preferences. This PR aims to introduce a fix for this. This issue seems to have been present since v1.6.4 or earlier.

This is a particularly difficult one to reproduce as it doesn't happen repeatably.

Requesting community testers to validate the fix. 

**Test needed:**
1. Slice a model with a filament that needs a different temperature for the second layer
2. Change the brim setting to auto and slice - confirm that the second layer bed temperature is being emitted
3. Change the brim setting back to none and confirm that the second layer bed temperature is emitted 

To see the Gcode window press key "C" on your keyboard. Navigate using the sliders to the second layer and at the start of it as shown in the screenshots below.

Asking for testers as its been particularly difficult to a) replicate that the issue is happening as its sporadic and b) validate that the fix is working. 

When testing please confirm with your existing installation that the issue is happening first before trying the PR build. Please comment back below on whether a) it happened to you in the current build you're using alongside the version number you're running and b) if this PR fixed it or not.

**When it works it should look like the below (line 774)**
image

**If it doesn't work it will look like this (line 773 only, no set bed temperature present)**
image

**Tests performed**
As above.
I think that this PR also causes the bed temperature to always be set on the second layer but this also needs testing... Whether this is an issue or not remains open for discussion as its an extra Gcode command that is not needed but not harmful as the printer is already operating at that bed temperature so it will be just ignored.

Fixes #5485 
Fixes #4676
Fixes #3015
Fixes #1853

### CODE REVIEW

**Comment by buzzhuzz** [comment]
Looking at the change I see why it is hard to reproduce: ```m_last_bed_temperature``` has random value unless explicitly initialized to the given value.

That is due to C++  standards https://en.cppreference.com/w/cpp/language/default_initialization

> The effects of default-initialization are:
>-    if T is a (possibly cv-qualified) non-POD(until C++11) class type, the constructors are considered and subjected to [overload resolution](https://en.cppreference.com/w/cpp/language/overload_resolution) against the empty argument list. The constructor selected (which is one of the [default constructors](https://en.cppreference.com/w/cpp/language/default_constructor)) is called to provide the initial value for the new object;
>-    if T is an array type, every element of the array is default-initialized;
>-    otherwise, no initialization is performed (see [notes](https://en.cppreference.com/w/cpp/language/default_initialization#Notes)).

**Comment by igiannakas** [comment]
Exactly this. Which puzzles me as to why the constructor for this variable was commended out - this change was introduced in Bambu studio when porting prusa slicer since its first release and inherited over by orca. However I cannot understand why Bambu would remove the constructor initialisation for this 🤔

**Review by SoftFever — APPROVED** [review]
Thanks for taking care of this issue.
I merge it s omore people can test it.

**Comment by igiannakas** [comment]
> Thanks for taking care of this issue. I merge it s omore people can test it.

thx! its a trivial change, shouldn't break anything :) :P (famous last words :P )

**Comment by fabio-s-franco** [comment]
This one have been driving me crazy. I am not sure where this is coming from, but for some reason it keeps bumping my bed temperature on second layer, causing the print to warp:

image

I tried already changing the filament's other layers temperature, but still, this stubborn gcode keeps showing up:
image

There is no filament gcode and the only override is retraction length.

My print start gcode is:

```gcode
PRINT_START BED_TEMP={hot_plate_temp_initial_layer[0]} EXTRUDER_TEMP={nozzle_temperature_initial_layer[0]} RETRACT_LENGTH={(is_nil(filament_retraction_length[0]) ? retraction_length[0] : filament_retraction_length[0])} RETRACT_SPEED={(is_nil(filament_retraction_speed[0]) ? retraction_speed[0] : filament_retraction_speed[0])} UNRETRACT_EXTRA_LENGTH={(is_nil(filament_retract_restart_extra[0]) ? retract_restart_extra[0] 
```

I have just moved from PrusaSlicer and not off to a good start. So some of the parameters above may not be needed (like pressure advance I no longer put in filament gcode, which is a nice one).
There is nothing on layer change gcode that could cause this.

I don't have that temperature set anywhere.

If this is something else completely, I can create another issue. Or maybe I just don't know how to find whatever is setting that temperature.

**Comment by igiannakas** [comment]
Can you attach a project file so we can see/replicate the issue please?

**Comment by Wang-Thunder** [comment]
> > Thanks for taking care of this issue. I merge it s omore people can test it.
> 
> thx! its a trivial change, shouldn't break anything :) :P (famous last words :P )

Are you using a different bed type under Plate Settings? I have noticed that the filament temperature settings only apply to the "Smooth/High Temp PEI Plate". I wasn't able to find a spot to change the temperature of the other plates anywhere.

**Comment by igiannakas** [comment]
You can enable multiple plates on your printer profile (printer settings). Then all the plates will show in your filament profiles

**Comment by fabio-s-franco** [comment]
Sorry, I forgot about this issue and I know what caused it.

It basically stemmed from opening a 3mf file saved in another slicer (in my case the original file came from PrusaSlicer).
To fix I can instead import objects from the 3mf file (insteading of loading it as a project).

So as a practice since then, I never open a 3mf project file created in one slicer, into another slicer.

**Pull request merged**
