### PR TITLE
Port "No Unsupported Perimeters" feature from SS

### LINKED ISSUE #2402: Port add sacrificial bridge layer under holes from SS
Reference to this SS feature in Ellie's tuning guide:

https://github.com/AndrewEllis93/Ellis-SuperSlicer-Profiles#superslicer-option

This would help a lot with not having to deal with supports under holes.

example of how it would work:
image
image
image

### PR DESCRIPTION
**Pull request by Ocraftyone**
- [x] Implement Feature
- [x] Test Feature
- [ ] Add config manipulation

Original Feature from SS
image

fixes #2402

### CODE REVIEW

**Comment by Ocraftyone** [comment]
This needs testing. I wasn't able to get it going for myself in my implementation or in SuperSlicer, so I must be doing something wrong. I need someone who is familiar with the feature.

**Comment by SoftFever** [comment]
> This needs testing. I wasn't able to get it going for myself in my implementation or in SuperSlicer, so I must be doing something wrong. I need someone who is familiar with the feature. This only works with classic perimeter generation

Fantastic.
I will help testing and troubleshooting tomorrow

**Comment by tome9111991** [comment]
Btw.
Here the susi wiki for this feature
https://github.com/supermerill/SuperSlicer/wiki/No-perimeters-on-bridge-area

**Comment by SoftFever** [comment]
Looks like it didn't work.
Screenshot 2023-12-20 at 2 39 54 PM

[hole.3mf.zip](https://github.com/SoftFever/OrcaSlicer/files/13723929/hole.3mf.zip)

**Comment by Eldenroot** [comment]
Yes, it is not working. There was a special testing .stl for this feature, I need to Google it.

**Comment by Eldenroot** [comment]
Well, anybody any clue where the problem is?

**Comment by Noisyfox** [comment]
The issue is caused by `PrintObject::detect_surfaces_type()`.

**Comment by Eldenroot** [comment]
Good job @Noisyfox !

**Comment by Noisyfox** [comment]
Next question: do we want to add support for arachne?

**Comment by igiannakas** [comment]
> Next question: do we want to add support for arachne?

Yes 👌🏻👏🏻🎉

**Comment by Eldenroot** [comment]
> Next question: do we want to add support for arachne?

SURE thing!

**Comment by Noisyfox** [comment]
> > Next question: do we want to add support for arachne?
> 
> SURE thing!

Not sure how difficult it might be then. Are you going to do that?

**Comment by Ocraftyone** [comment]
I have to be honest, a lot of the backend goes over my head as I am not entirely oriented in it. How different is arachne? Is it possible it is a drop in replacement?

**Comment by Noisyfox** [comment]
image
Seems to be working fine.

**Comment by Ocraftyone** [comment]
> Btw. Here the susi wiki for this feature [Wiki: No perimeters on bridge area (supermerill/SuperSlicer)](https://github.com/supermerill/SuperSlicer/wiki/No-perimeters-on-bridge-area)

This wiki does a decent job of explaining. This whole option seems to be very experimental by the tone of the wiki.

**Comment by Noisyfox** [comment]
> > Btw. Here the susi wiki for this feature [Wiki: No perimeters on bridge area (supermerill/SuperSlicer)](https://github.com/supermerill/SuperSlicer/wiki/No-perimeters-on-bridge-area)
> 
> This wiki does a decent job of explaining. This whole option seems to be very experimental by the tone of the wiki.

I saw that before but I still don't quite understand those two options. IMO the only useful one is the "Fill the voids with bridges" option. Like, what do these bridges do? Make no sense to me.
image

**Comment by Noisyfox** [comment]
These two options don't work in this PR at the moment.

**Comment by Ocraftyone** [comment]
> I suspect it might relate to the `const coordf_t bridged_infill_margin = BRIDGE_INFILL_MARGIN;` line.

That was an educated guess on my part. SS has a config field that allowed the user to set 

> IMO the only useful one is the "Fill the voids with bridges"

That was what I was going to do originally, but there was some interest in having all of the functions ported. I don't know if the limited functionality they provide is worth porting.

**Comment by Eldenroot** [comment]
Thank you for fixing the "core" part of this feature. Actually I am not sure what to do with other options... maybe it could be useful in some "edge" cases... there is a wiki post about it but...

**Comment by Noisyfox** [comment]
IMO the only advantage those two options offer is that you can (sort of) turn them on for the entire model? Compare to the "fill void with bridges" option which you should only enable for certain area that has flat counter bore (because it could mess up with counter bore cones, as the wiki describes). Though I don't think that would justify the extra effort to make those options work, and the confusion they might cause.

**Comment by Noisyfox** [comment]
image
image

**Comment by Eldenroot** [comment]
Great, anybody else for testing? I will try tomorrow. Thx!

**Comment by Noisyfox** [comment]
Any progress on this one?

**Comment by SoftFever** [comment]
> Any progress on this one?

Haha, ain't you the one who's making progress here? 

Joking aside, I will start reviewing and testing on it.
Well done, all!

**Comment by SoftFever** [comment]
Made some adjustment to the names.
Also added tooltip
Screenshot 2024-01-28 at 6 07 57 PM
Screenshot 2024-01-28 at 6 08 11 PM

**Review by SoftFever — APPROVED** [review]

**Comment by SoftFever** [comment]
Thanks @Ocraftyone for the initial port work.
Thanks @Noisyfox to make it work properly.
Thank you to everyone who participated in the discussion and testing as well!
Merged.

**Comment by SoftFever** [comment]
Some testing results:
Screenshot 2024-01-28 at 9 17 14 PM
counterbole_hole2
counterbole_hole

**Comment by Ocraftyone** [comment]
I really like the new names. Much more intuitive!

**Comment by Gerbz1** [comment]
Let me know if I shouldn't post this here, im new to github. 

This setting seems to cause some issues with bridging over blind holes. I'll use the benchy as an example.
Untitled
With 'bridge counterbole holes' disabled the second layer looks pretty good, its bridging over the text (im not sure why its using sparse infil and bridges instead of making the whole layer infil the same direction though)


.
Untitled
With partial bridge or sacrificial layer the bridge looks weird, it's making the perimiters of the first layer even though there's a bridge layer in between. 

Here's the bottom layer as reference for the text
image

**Pull request merged**
