### PR TITLE
Show both layer time and tick info when tick is highlighted

### PR DESCRIPTION
**Pull request by Noisyfox**
This addresses the concern at https://github.com/SoftFever/OrcaSlicer/pull/2305#issuecomment-1745470779

image

### CODE REVIEW

**Comment by Noisyfox** [comment]
Hold on... Just realized that the layer time is the time when current layer is completed, however pause happens at the beginning of current layer. This is confusing.

**Comment by discip** [comment]
Uh! That's a shame. 😅

Coming from Cura, this is what happend to confuse me as well!
But I think that's intentional, just in case someone needs to insert _**'custom code'**_ before the first layer.
Thinking loud: _But then again it's not possible to insert _**'custom code'**_ at the end of the last layer this way._

1. Perhaps this behavior could be changed so that _**'custom code'**_ is inserted at the end of a layer.
And if someone needed to insert code before the first layer, this could be achieved by changing the start g-code. 🤷‍♂️

2. Or just show the time of the previous layer.

What do you think?

**Comment by Noisyfox** [comment]
> 2\. Or just show the time of the previous layer.

This will be the easier solution, however it might be inaccurate due to the existence of the before/after_layer_change gcodes.

**Comment by Noisyfox** [comment]
But then, how accurate do we actually need? I think it's perfectly fine to use the previous layer's end time as a good estimation.

**Comment by discip** [comment]
> But then, how accurate do we actually need? I think it's perfectly fine to use the previous layer's end time as a good estimation.

That should suffice, because ideally you should be there before the actual pause so that you can immediately resume printing.

## Thank you a lot for taking this on! 😃👍

**Comment by discip** [comment]
> But then, how accurate do we actually need? I think it's perfectly fine to use the previous layer's end time as a good estimation.

That should suffice, because ideally you want to be there shortly before the actual pause so that you can immediately resume printing.

## Thank you a lot for taking this on! 😃👍

**Comment by discip** [comment]
Thank you!

**Review by SoftFever — APPROVED** [review]

**Pull request merged**
