### PR TITLE
Fixes for new icons

### PR DESCRIPTION
**Pull request by yw4z**
### Code Changes

- [x] **Sidebar / Parameter icons**

> Quality > Wall Generator > param_wall_generator.svg
> Quality > Walls and surfaces > param_wall_surface.svg
> Quality > Bridging > param_bridge.svg
> Quality > Overhangs > param_overhang.svg
> Strength > Support Tree > param_support_tree.svg
> Overhang Speed > param_overhang_speed.svg
> Speed > Jerk(X/Y) > param_jerk.svg

- [x] **Filament Settings icons**

> Filament > Print Temperature > param_extruder_temp.svg
> Filament > Bed Temperature >param_bed_temp.svg
> Cooling > Cooling specific layer > param_cooling_specific_layer.svg
> Cooling > Part Cooling Fan > param_cooling_part_fan.svg
> Cooling > Auxiliary part cooling fan > param_cooling_aux_fan.svg
> Cooling > Exhaust Fan > param_cooling_exhaust.svg
> Multi Material > Wipe tower parameters > param_tower.svg
> Multi Material > Toolchange Parameters > param_toolchange.svg

- [x] **Machine Settings icons**

> Basic Information > Printable Space > param_printable_space.svg
> Basic Information > Cooling Fan > param_cooling_fan.svg
> Basic Information > Extruder Clearence > param_extruder_clearence.svg
> Basic Information > Adaptive Bed Mesh > param_adaptive_mesh.svg
> Basic Information > Accessory > param_accessory.svg
> Multi Material > Single Extruder Multi Material Setup > param_multi_material.svg
> Multi Material > Wipe tower > param_tower.svg
> Multi Material > Single Extruder Multi Material Parameters > param_settings.svg
> Extruder > Size > param_extruder_size.svg
> Extruder > Layer Height Limits > param_layer_height.svg
> Extruder > Position > param_position.svg
> Extruder > Lift Z Enforcement > param_extruder_lift_enforcement.svg
> Extruder > Retraction when swithing material > param_retraction_material_change.svg
> Motion Ability > Jerk Limitation > param_jerk.svg

- [x] **Placeholder icons**

> Timestamps > custom-gcode_time.svg (there is an icon existing but not compatible with current design this will fit better)
> Presets > Print Settings > process.svg
> Presets > Print Settings > Quality > custom-gcode_quality.svg
> Presets > Print Settings > Strength > custom-gcode_strength.svg
> Presets > Print Settings > Speed > custom-gcode_speed.svg
> Presets > Print Settings > Support > custom-gcode_support.svg
> Presets > Print Settings > Other > custom-gcode_other.svg
> Presets > Print Settings > Notes > custom-gcode_note.svg
> Presets > Filament Settings > Filament > custom-gcode_filament.svg
> Presets > Filament Settings > Cooling > custom-gcode_cooling_fan.svg
> Presets > Filament Settings > Setting Overrides > custom-gcode_setting_override.svg
> Presets > Filament Settings > Advanced > custom-gcode_advanced.svg
> Presets > Filament Settings > Multi Material > custom-gcode_multi_material.svg
> Presets > Filament Settings > Notes > custom-gcode_note.svg
> Presets > Printer Settings > Basic Information > custom-gcode_object-info.svg
> Presets > Printer Settings > Machine G-Code > custom-gcode_gcode.svg
> Presets > Printer Settings > Multi Material > custom-gcode_multi_material.svg
> Presets > Printer Settings > Extruder > custom-gcode_extruder.svg
> Presets > Printer Settings > Motion Ability > custom-gcode_motion.svg
> Presets > Printer Settings > Notes > custom-gcode_note.svg

- [x] **Add ability to pulling icons from tabs for gCode Editor to show them in placeholders and compare window**

- [x] **Object list > Height range icons for layer menu item**

Screenshot-20240501114115

- [x] **Object list > Height range add / delete buttons (previous code uses add_filament / delete_filament)** 

before
Screenshot-20240507143003

after
Screenshot-20240501114104

- [x] Compare window > Updated undefined category icon with low resolution compatible one. Previous code used question icon that used for dialogs

| Before | After |
|-------|-------|
| Screenshot-20240507143116 | Screenshot-20240507143131 |

### Fixes

- [x] **Object list > Support / Seam painting icons ( previous ones not compatible with low resolution & Dark theme)**

Screenshot-20240501120440

- [x] **SVG and Emboss Gizmos > Changed warning icon with obj_warning.svg . because exclamation.svg is used for dialogs and not compatible with low resolution**

| Before | After |
|-------|-------|
| Screenshot-20240502002041 | Screenshot-20240502002642 |
| Screenshot-20240502003520 | Screenshot-20240502002923|

- [x] **Updated warning icon on dialogs. Changed obj_warning.svg icon with exclamation.svg . because exclamation.svg designed for dialogs**

| Before | After |
|-------|-------|
| Screenshot-20240514160312 | Screenshot-20240514160013 |

- [x] **Combo Box icon size for dropdown arrow**
> I was changed icon resolution on combo box code on previous commit and resolution of arrow icon set for it. reverted icon res back to 16x16

| Before | After |
|-------|-------|
| Screenshot-20240507142741 | Screenshot-20240507142727 |

- [x] **Gizmos > Keyboard cheat sheet icon resolution fix**
> Icon appears on > Variable Layer Height, Cut, Support Painting, Seam Painting, Color Painting, Measure
> Problem with this icon they defined 30, 22 resolution on GLGizmosManager.cpp but gizmos uses  ImVec2(font_size * 1.8, font_size * 1.3) for resolution. Resolution ratio is not matching and using font size as a different ratio is not a good choose
> Let me know if you have simpler solution

Screenshot-20240502012153

- [x] **Notifications > Swapped collapse / expand arrow directions**
> Problem is notifications expands bottom to top and collapse button icon not looks right
> I was used directions from original source but they already set wrong. so changed that in this commit

| Before | After |
|-------|-------|
| Screenshot-20240507023132 | Screenshot-20240507023225 |
| Screenshot-20240507023141 | Screenshot-20240507023233 |

- [x] **Gizmos > Vertically centered icons rendered blurry / pixelated**
this should fix more. included to this commit because its already a orca change. i can this as separate commit if its not

| Before | After |
|-------|-------|
| Screenshot-20240511160712 | Screenshot-20240511160543 |
| Screenshot-20240511160720 | Screenshot-20240511160905 |

### Icon updates
- [ ] Toolbar > Auto Orient
- [ ] Plate > Auto Orient
- [ ] Toolbar > Lay on surface
- [x] Toolbar > Variable Layer height
- [x] Top Bar > Calibration tab icon (Matched icon name that used on code)
- [x] Checkboxes > matched disabled color and fixed an  alignment problem

### New icons
- [x] Cross Hatch fill pattern
- [x] Parameters > Skirt group

### CODE REVIEW

**Comment by olcayoren** [comment]
Hello, there seems to be a problem with the icon in the picture, it would be nice if you edit it, thank you.
Ekran Resmi 2024-05-02 21 49 41

**Comment by yw4z** [comment]
this fixed in this commit, is that screenshot from your compiled source from my branch?

**Comment by olcayoren** [comment]
> @olcayoren this fixed in this commit, is that screenshot from your compiled source from my branch?

I tried Pr-5239.

**Comment by yw4z** [comment]
@olcayoren thats for color fixes not includes this fixes. can you try this one

**Comment by olcayoren** [comment]
> @olcayoren thats for color fixes not includes this fixes. can you try this one

Thanks 
Ekran Resmi 2024-05-02 22 02 27

**Comment by yw4z** [comment]
> @yw4z As previously mentioned the arrows to expand / collapse the **`Daily Tips`** are mixed up.
> 
> Should be pointing up:
> 
> image
> 
> Should be pointing down:
> 
> image

@discip i checked icon and problem is not icon. problem in on code. here is same icon used on gcode view
Screenshot-20240507020904
direction for fold icon used correctly on gcode view. Foldable areas mostly works top to bottom but daily tips works bottom to top so i will change code of daily tips to fix problem

**Comment by discip** [comment]
The original state was already wrong. 😊
It should work as this was already reported on March 9th:
https://github.com/SoftFever/OrcaSlicer/pull/4368#discussion_r1518417369
https://github.com/SoftFever/OrcaSlicer/pull/4368#discussion_r1521049461

**Comment by discip** [comment]
@yw4z
> i checked icon and i used same directions (with original source) for notifications arrows .

The original state was already wrong. 😊

It should work as this was already reported on March 9th:
https://github.com/SoftFever/OrcaSlicer/pull/4368#discussion_r1518417369
https://github.com/SoftFever/OrcaSlicer/pull/4368#discussion_r1521049461

**Comment by discip** [comment]
@yw4z
> i checked icon and i used same directions (with original source) for notifications arrows .

The original state was already wrong. 😊

It should work as this was already reported on March 9th:
https://github.com/SoftFever/OrcaSlicer/pull/4368#discussion_r1518417369
https://github.com/SoftFever/OrcaSlicer/pull/4368#discussion_r1518417541

**Comment by yw4z** [comment]
@discip done. let me know if there are another problems

**Comment by discip** [comment]
@yw4z
## Thank you! 👍
Will do, should I encounter any.

**Comment by discip** [comment]
@yw4z
Maybe the following one could be interesting:

image

The marked value can't be changed as soon as **`Reverse only internal perimeters`** is checked.
So it would make sense to hide the entire entry when the checkbox above is checked.

@igiannakas
Is my observation correct or did I miss here something?

**Comment by igiannakas** [comment]
> @yw4z Maybe the following one could be interesting:
> 
> image
> 
> The marked value can't be changed as soon as **`Reverse only internal perimeters`** is checked. So it would make sense to hide the entire entry when the checkbox above is checked.
> 
> @igiannakas Is my observation correct or did I miss here something?

The value can be changed but it’s not really recommended to deviate from the default 0%

**Comment by discip** [comment]
@igiannakas
> The value can be changed but it’s not really recommended to deviate from the default 0%

No, as mentioned above: As soon as **`Reverse only internal perimeters`** is checked, the value always changes back to **`0%`**. Regardless what value or  unit and even under which **OS** _(Manjaro | Windows)_.

Maybe macOS is an exception here. If I remember correctly, you're using macOS right?

**Comment by igiannakas** [comment]
> @igiannakas
> 
> > The value can be changed but it’s not really recommended to deviate from the default 0%
> 
> No, as mentioned above: As soon as **`Reverse only internal perimeters`** is checked, the value always changes back to **`0%`**. Regardless what value or unit and even under which **OS** _(Manjaro | Windows)_.
> 
> Maybe macOS is an exception here. If I remember correctly, you're using macOS right?

AH yes you're right. Forgot how I implemented it! Indeed, it can be hidden; but then the user may wonder what is going on :)

**Comment by yw4z** [comment]
@igiannakas 
### 1
• Edit icons repeating too much on filaments section or gizmos and it increases contrast too much
• It changes contrast ratios for sidebar titlebar and its contents and it increases separation between that areas
• With same contrast ratio ui elements starts to mix together
• This icons for controls / inputs. thats the reason i didnt add color to them to reduce clutter
•  about disabled state of icons, they are elements of input boxes if input box is not disabled you can use it. just give a time you will get used to over time

here is comparison with opacity vs without opacity
Screenshot-20240509185115

You can try to increase opacity of that icons for experiment. just open svg with text editor and change opacity value
icons > delete.svg, edit.svg, save.svg, search.svg

Search icon is rounded and i used less opacity on that because of anti aliasing. it will be rendered differently on every system there is no solution to fix it. also you can change opacity value for search icon but you cant get a better balance between dark / light theme

### 2
that icons still work in progress already changed in this commit. you can build from my branch

Screenshot-20240509190748

### 3
also this icon still work in progress. we are discussing with softever. but we couldnt decide final usage yet
here latest changes
• badge icons smaller
• used brush icons for seam and support painting
• used spray for color painting but will try bucket
Screenshot-20240509190755

**Comment by igiannakas** [comment]
Try using with light mode - dark mode has inherently more contrast. Maybe bumping up the opacity for icons globally when in light mode may be a way forward?

**Comment by yw4z** [comment]
@SoftFever what is your opinion on contrast of icons with @igiannakas 's comments. i have to change all icons if there is a problem with contrast. also requires some changes on code side to swap icon colors for dark / light theme

**Comment by igiannakas** [comment]
> @SoftFever what is your opinion on contrast of icons with @igiannakas 's comments. i have to change all icons if there is a problem with contrast. also requires some changes on code side to swap icon colors for dark / light theme

Yeah I’m sorry to be a pain about this - as they are right now they are closer in opacity to the background elements (ie drop down border color for example) which indicates them as not clickable - see below for what I mean. There is very little visual distinction that the icon is enabled.

image

I’m sure we can get used to them in the long run - just being picky as it’s one of the things that was a bit jarring from a “new user” to the new icon set. Besides that they are very good actually and a significant improvement over the existing icon set!!!

**Comment by yw4z** [comment]
@igiannakas zip file contains 4 icon sets. each one with different opacities. 0.6 (currently used), 0.7, 0,8, 0.9

if we want to increase visibility of buttons 0.8 is best fit in my opeinion because titlebars has darker background and this shows icon color darker. so using icons with opacity gives them a balance

here is file for who want to compare
[icon_test.zip](https://github.com/SoftFever/OrcaSlicer/files/15268318/icon_test.zip)

**Comment by discip** [comment]
> AH yes you're right. Forgot how I implemented it! Indeed, it can be hidden; but then the user may wonder what is going on :)

No, I don't think so, because most likely users will think that their build is flawed in the sense that they cannot change that specific value, and sooner or later someone is going to report that _'issue'_. 😊

@yw4z
After that is cleared, would you mind implementing the corresponding suggestion? https://github.com/SoftFever/OrcaSlicer/pull/5221#issuecomment-2098483964

**Comment by igiannakas** [comment]
> @igiannakas zip file contains 4 icon sets. each one with different opacities. 0.6 (currently used), 0.7, 0,8, 0.9
> 
> if we want to increase visibility of buttons 0.8 is best fit in my opinion because titlebars has darker background and this shows icon color darker. so using icons with opacity gives them a balance
> 
> here is file for who want to compare [icon_test.zip](https://github.com/SoftFever/OrcaSlicer/files/15268318/icon_test.zip)

Tested both 0.8 and 0.9. They both look good - cannot pick one for definite as better than the other. See below.

Both ones convey a better "meaning" to the buttons that they are indeed active.

Thank you very much for this, this is good!

0.9:
image

0.8:
image

**Comment by SoftFever** [comment]
> @SoftFever what is your opinion on contrast of icons with @igiannakas 's comments. i have to change all icons if there is a problem with contrast. also requires some changes on code side to swap icon colors for dark / light theme

@igiannakas raised a very good point.
We can make the current line color darker?
Good thing is we are using SVG, we can search & replace the color

**Comment by SoftFever** [comment]
> @SoftFever i have tried codes on bitmapcache but they didnt work? is there another place for that feature

Yes, this is the place.
Or you can also directly search/replace in the SVG files itself as they are ASCII files.

**Comment by yw4z** [comment]
tried again, compiled and it didnt worked

bitmapcache.cpp > wxBitmap* BitmapCache::load_svg
```
    if (dark_mode) {
        replaces["\"#262E30\""] = "\"#EFEFF0\"";
        replaces["\"#323A3D\""] = "\"#B3B3B5\"";
        replaces["\"#808080\""] = "\"#818183\"";
        //replaces["\"#ACACAC\""] = "\"#54545A\"";
        replaces["\"#CECECE\""] = "\"#54545B\"";
        replaces["\"#6B6B6B\""] = "\"#818182\"";
        replaces["\"#909090\""] = "\"#FFFFFF\"";
        replaces["\"#00FF00\""] = "\"#FF0000\"";
        replaces["\"#009688\""] = "\"#00675b\"";
        replaces["\"#949494\""] = "\"#FF0000\""; // NEW LINE FOR REPLACE
    }
```
All icons uses #949494 color but they didnt turn red (#FF0000) when i switch to dark mode. am i missing some thing or there some thing different with my exported SVG's

**Comment by yw4z** [comment]
@igiannakas 
kept same icon color for dark mode

last commit
• Increases contrast of icons on light theme
• Removes opacity from edit, delete, search... icons
• Fixes different color for advanced toggle on dark mode
• Fixes checkboxes not aligned with other boxes
• Style fixes for checkboxes

@SoftFever you may want to check changes on BitmapCache.cpp. also please check my previous comment that describes problem

**Comment by igiannakas** [comment]
Awesome thank you very much! I’ll merge the Pr in my dev branch and give it a go. Thank you for this!!

**Comment by yw4z** [comment]
@igiannakas icons could be a bit more dark but secondary color (ORCA) loses visibility when it gets darker

**Comment by igiannakas** [comment]
> @igiannakas icons could be a bit more dark but secondary color (ORCA) loses visibility when it gets darker you can make them darker from BitmapCache.cpp > line 342 `replaces["#949494"] = "#7C8282"; // ORCA replace icon line color for light theme`

Merged your PR in my dev branch - it looks SO much better, thank you for this!

**Comment by SoftFever** [comment]
@yw4z 
I noticed a small artefact on plater icons
image
image

**Comment by yw4z** [comment]
@SoftFever Looks like a rendering issue because there is no elements on out of frame on icons.
i left 1px gap on right and bottom edge on most of icons to get odd number for perfect center but i guess its not important on plate icons. they will always blurred by antialiasing
also same issue visible on top border too if you look closely
i will change plate icons with that uses full icon frame soon

**Comment by yw4z** [comment]
@SoftFever updated them now

**Comment by SoftFever** [comment]
> @SoftFever updated them now

Awesome.
It looks good.

**Comment by SoftFever** [comment]
@yw4z 
All the changes look good to me.
Do you think the PR is ready?

**Comment by yw4z** [comment]
@SoftFever I'm happy with result. especially with toolbar icons. Do you have any doubt on fixes / toolbar icons?

**Comment by igiannakas** [comment]
Testing wise it’s been great here.

the only feedback I have is the paint icon in the model painting gizmo:
image

something a bit more intuitive other than the rectangle with the blobs on it would be nice - a bucket or something would really help clarify this icon. (Second to last icon on the gizmo)

**Comment by SoftFever** [comment]
> Testing wise it’s been great here.
> 
> the only feedback I have is the paint icon in the model painting gizmo. (Using old screenshot as am away from computer today)
> 
> IMG_3717
> 
> something a bit more intuitive other than the rectangle with the blobs on it would be nice - a bucket or something would really help clarify this icon. (Second to last icon on the gizmo)

@yw4z 
I think @igiannakas makes a good point here. I feel that the 'fill' and 'gap fill' are not intuitive too.

image

For the 'fill' icon, a bucket-style icon would be easier to understand as it has been widely used in paint applications like Windows Paint. 
image

Bambu's old icon is not bad; perhaps we could use a similar concept?

image

**Comment by yw4z** [comment]
@SoftFever @igiannakas 

Screenshot-20240519000720

Gap Fill
1- Original > Lines represents layers. created gaps between lines and added new lines with accent color to represents fill
2- Increased gap space compared to original one. its easier to identify compared to previous one
3- created gaps between lines and placed a drop

2 is my favorite but im ok with 3

Fill
1- Original > Designed a easy to identify shape with accent color that not looks similar to triangle tool
2- Used spray icon same as toolbar icon badge. I'm always picking spray because its easy to identify on this resolution compared to bucket
3- Used paint bucked and tried to fill icon frame as much as possible otherwise it will look small compared to other icons. thats why i didnt use 45 degree angle

2 is a good alternative because it already used on toolbar icon. it will improve consistency if used together.

i dont recommend to use it on toolbar icon because that icon has much smaller version on object list. Bucket is hard to identfy at that resolution and looks similar to object sinking icon
One downside, cosistency reduced a bit if toolbar icon uses spray and fill icon uses bucket

**Comment by SoftFever** [comment]
> @SoftFever @igiannakas
> 
> Screenshot-20240519000720
> 
> Gap Fill 1- Original > Lines represents layers. created gaps between lines and added new lines with accent color to represents fill 2- Increased gap space compared to original one. its easier to identify compared to previous one 3- created gaps between lines and placed a drop
> 
> 2 is my favorite but im ok with 3
> 
> Fill 1- Original > Designed a easy to identify shape with accent color that not looks similar to triangle tool 2- Used spray icon same as toolbar icon badge. I'm always picking spray because its easy to identify on this resolution compared to bucket 3- Used paint bucked and tried to fill icon frame as much as possible otherwise it will look small compared to other icons. thats why i didnt use 45 degree angle
> 
> 2 is a good alternative because it already used on toolbar icon. it will improve consistency if used together.
> 
> i dont recommend to use it on toolbar icon because that icon has much smaller version on object list. Bucket is hard to identfy at that resolution and looks similar to object sinking icon One downside, cosistency reduced a bit if toolbar icon uses spray and fill icon uses bucket

For the `fill` icon, I prefer option 3.

Now, for the `gap fill`, let me demonstrate the use case so that you might have a better idea of its usage. This tool is used to automatically absorb small color islands into the surrounding colors. Hence, neither the line (options 1 and 2) nor the water drop (option 3) are intuitive enough for its purpose, in my opinion.

image

**Comment by igiannakas** [comment]
Agreed. Option 3 for the fill is fantastic. Agree with Softfever above on the gap fill one - the Bambu one is I think quite good , just needs re styling?

**Comment by yw4z** [comment]
Screenshot-20240519183106

• made paint bucket a bit bigger so it will fit better with other icons. you can see comparison on bottom
• Function basically fixes small problems with painting so i thought medic / bandage icons can be used for that. photoshop already uses a bandage icon for patch tool
• Added a spatula as alternative. mainly used for filling gaps on mockups / clay models  / walls. also fits imo
• Just used dost with different sizes to represent gaps in last one

**Comment by igiannakas** [comment]
The bucket looks great! Much more intuitive. And the size feels ok from what I see

For the gap fill one, honestly no idea... I'd probably vote for either the spatula doing the wipe move or the rectangle with the dots - the only downside to the dots one is it may mean that you're creating a dot pattern when selecting this :P So maybe the spatula is better. 

Maybe post on discord and check what users think? Hmm

**Comment by SoftFever** [comment]
> Screenshot-20240519183106
> 
> • made paint bucket a bit bigger so it will fit better with other icons. you can see comparison on bottom • Function basically fixes small problems with painting so i thought medic / bandage icons can be used for that. photoshop already uses a bandage icon for patch tool • Added a spatula as alternative. mainly used for filling gaps on mockups / clay models / walls. also fits imo • Just used dost with different sizes to represent gaps in last one • Replaced height range icon on some alternatives that already used for height range in UI. but old one fits better in here imo
> 
> last alternative looks nice

The last row of icons looks good to me. For the gap fill icon, do you think it would be better to use irregular polygons or triangles instead of circles? As shown in the screenshot, those gaps are usually triangular.

image

**Comment by yw4z** [comment]
here is my selections
Screenshot-20240520154125

1- Dots
2- 1 big triangle and 3 small triangles to indicate it will work with different sizes of gaps
3- 2 triangles with border. this one has best contrast
4- 3 triangles. triangle is bigger and easier to identify compared to 2

and tries
Screenshot-20240520154132

• Many small triangles looks like shatter / shattering
• Not recommended to use only triangles without frame. it looked so weak visually
• 3 similar sized triangles looks like face from halloween :)
• Badges looked so small and hard to identify

**Comment by SoftFever** [comment]
> here is my selections Screenshot-20240520154125
> 
> 1- Dots 2- 1 big triangle and 3 small triangles to indicate it will work with different sizes of gaps 3- 2 triangles with border. this one has best contrast 4- 3 triangles. triangle is bigger and easier to identify compared to 2
> 
> and tries Screenshot-20240520154132
> 
> • Many small triangles looks like shatter / shattering • Not recommended to use only triangles without frame. it looked so weak visually • 3 similar sized triangles looks like face from halloween :) • Badges looked so small and hard to identify

Option 4 looks perfect to me!

**Comment by igiannakas** [comment]
Nice one on the skirt icon! thank you :)

**Comment by yw4z** [comment]
@SoftFever updated icons for fill and gap fill

Screenshot-20240520175115
Screenshot-20240520175131

and added new icon for skirt parameter (this parameter renamed currently as "Skirt" from "Bed Adhesion")
Screenshot-20240520175101

**Comment by SoftFever** [comment]
> @SoftFever updated icons for fill and gap fill
> 
> Screenshot-20240520175115 Screenshot-20240520175131
> 
> and added new icon for skirt parameter (this parameter renamed currently as "Skirt" from "Bed Adhesion") Screenshot-20240520175101

Awesome!
Thank you.
I will merge it into main branch so that more people can test it.

**Pull request merged**
