### PR TITLE
Add spacenavd support

### PR DESCRIPTION
**Pull request by RealDeuce**
Spacenavd is an open source driver for 6dof 3D mice.  When using libspnav, each program doesn't need to add support for new (or old) devices, and they don't need exclusive access to the serial or USB device, allowing it to be used by multiple programs open at the same time (ie: FreeCAD and OrcaSlicer) rather than only the first one to be opened getting the d vice and the other locked out.

### CODE REVIEW

**Comment by SoftFever** [comment]
Thanks @RealDeuce 
But could you please provide details about what problem/feature does this PR do?
I know it's about spacemouse, but without context it's hard to do code review.

**Comment by RealDeuce** [comment]
Initial SS commit to do the same thing: https://github.com/supermerill/SuperSlicer/commit/2b908bc196b4a71cd4c49f16a8283a34924babc7

**Comment by RealDeuce** [comment]
I updated the commit comment:

> Spacenavd is an open source driver for 6dof 3D mice. When using libspnav, each program doesn't need to add support for new (or old) devices, and they don't need exclusive access to the serial or USB device, allowing it to be used by multiple programs open at the same time (ie: FreeCAD and OrcaSlicer) rather than only the first one to be opened getting the d vice and the other locked out.

**Review by SoftFever — APPROVED** [review]
I can't personally test this.
But the changes looks good and safe to me.

**Comment by SoftFever** [comment]
Thank you very much!
Merged.

**Pull request merged**
