### PR TITLE
Fix for QOI thumbnails not working

### PR DESCRIPTION
**Pull request by Exerqtor**
Should remedy the issues mentioned in  https://github.com/SoftFever/OrcaSlicer/issues/2741

### CODE REVIEW

**Review by Ocraftyone — APPROVED** [review]
Looks good to me

**Review by Noisyfox — APPROVED** [review]

**Review by SoftFever — APPROVED** [review]

**Comment by SoftFever** [comment]
@Exerqtor  Thanks for the fix 👍 
@Noisyfox @Ocraftyone Thanks for the review

**Comment by lbibass** [comment]
This change broke PNG uploads to klipper. 


Screenshot 2023-11-16 at 12 33 05 PM

**Comment by SoftFever** [comment]
> This change broke PNG uploads to klipper.
> 
> Reverting this commit restored PNGs. Screenshot 2023-11-16 at 12 33 05 PM

Nice catch.
It broken all thumbnails.
Fixed in 9505f93717880ec375df27b9b35ea296a5cbc5ed

**Comment by discip** [comment]
Sorry for being late, but unfortunately this still breaks the thumbnail creation for BTT TFTs.

The extra line at the beginning and between thumbnails prevents this from working.

Maybe someone could change this so that it only applies to QOI. 😅

**Pull request merged**
