### PR TITLE
Prusa MINIIS custom g-code changes

### PR DESCRIPTION
**Pull request by koppensb**
# Description
Removed primetower for color change according to prusa slicer profiles
Moved G28 to another position so PINDA probe gets preheated. This gives a more consistent mesh bed levelling when printing from a coled state of the printer.

## Tests
Did the Prusa Mini Silicon Bed Leveling Mod https://github.com/bbbenji/PMSBLM and there I detected the problem with leveling from a cold state.

### CODE REVIEW

**Comment by discip** [comment]
@koppensb
Good evening, Sir,

I hope you're doing well and don't mind me reaching out for some assistance.

For context, I'm currently using a Prusa MINIIS with Orca, and I've encountered an issue. Specifically, the retract on the first layer seems to be malfunctioning. The filament appears to be slipping during retraction, causing it to behave incorrectly. I’ve reviewed the generated G-code but couldn't find any anomalies, so I thought I'd reach out to see if another owner of this printer might have encountered a similar issue.

Have you experienced something like this? If so, I’d greatly appreciate any advice or solutions you could offer.

Thank you in advance!

**Comment by koppensb** [comment]
Hi,

no I had not such a problem, but I am using another extruder so its possible thats the reason.
Another reason could be that your idler tension is too low. If you unload the filament, how is the surface of the filament? 
Can you feel the grooves of the extruder gear? I should be like ratchet if go over with your fingernails.

Greetings
Bernhard

**Comment by discip** [comment]
Good morning,
mine is also modified. 😊

Changes in particular:

1. Bondtech IFS Internal Filament Sensor Extruder Prusa Mini/Mini+
2. E3D Prusa Revo Prusa Mini High Flow X
3. Silicone bed mod

And as far as I can tell the idler tension seems to be as you described.

**Comment by koppensb** [comment]
Ok then we have the pretty same setup. I use a cm3d extruder which I printed myself. When did you start with using the MINIIS profiles? I updated them some time ago and maybe they did not on your system. When I do tests I have to delete the Orca config folder for changes to get appliedOn 11.03.2025, at 10:47, discip ***@***.***> wrote:﻿
  Good morning,
mine is also modified. 😊
Changes in particular:

Bondtech IFS Internal Filament Sensor Extruder Prusa Mini/Mini+
E3D Prusa Revo Prusa Mini High Flow X
Silicone bed mod

And as far as I can tell the idler tension seems to be as you described.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>



discip left a comment (SoftFever/OrcaSlicer#6067)
Good morning,
mine is also modified. 😊
Changes in particular:

Bondtech IFS Internal Filament Sensor Extruder Prusa Mini/Mini+
E3D Prusa Revo Prusa Mini High Flow X
Silicone bed mod

And as far as I can tell the idler tension seems to be as you described.

**Comment by discip** [comment]
> When did you start with using the MINIIS profiles? I updated them some time ago and maybe they did not on your system.

Right after you published it. 😊

> When I do tests I have to delete the Orca config folder ...

What exactly has to be deleted?
And what about all the modifications (Start g-code ...)? Aren't they also deleted?

**Pull request merged**
