### PR TITLE
AnkerMake Profile Additions

### PR DESCRIPTION
**Pull request by just-trey**
Let's try this again :) Thank you @SoftFever, for your patience here.

### CODE REVIEW

**Comment by SoftFever** [comment]
Thank you for PR and patience :)
I overall looks good.
I would like to discuss a few setting choics to determine if they were placed in that way intentionally or if there might be some mistakes:
1. The order of the overhang speed seems incorrect, and even when I reverse the order, the speeds appear to be quite conservative, especially for overhangs ranging from 10% to 25%. For instance, 25mm/s seems a bit slow. Is this intentional?
2. The bridge speed is set to 110mm/s, which might be a bit too fast for bridging. Is this a deliberate choice?
3. The acceleration for both sparse and solid infill seems very low, even lower than the outer wall acceleration. This appears somewhat unusual. Could you clarify the reasoning behind this?
image

**Comment by just-trey** [comment]
@SoftFever, thanks so much for the feedback. It really makes the work I put in worth it. You are the first person who really took a close look at those things, and I appreciate the commitment to make sure you are maintaining a quality repo. I have updated the settings based on your feedback. Please let me know if I missed something.

**Review by SoftFever — APPROVED** [review]
LGTM

**Comment by SoftFever** [comment]
> @SoftFever, thanks so much for the feedback. It really makes the work I put in worth it. You are the first person who really took a close look at those things, and I appreciate the commitment to make sure you are maintaining a quality repo. I have updated the settings based on your feedback. Please let me know if I missed something.

Thank you @just-trey 
I'm trying my best :)
I really appreciate your contribution 👍

**Pull request merged**
