### PR TITLE
202309 Add Flashforge printer profiles (2nd try)

### PR DESCRIPTION
**Pull request by FlashforgeOfficial**
Hi,
I have made some changes in profiles:
1、Added fdm_filament_XXX.json;
2、Adding complete models in the Flashforge.json;
3、As well as noting "type" in the beginning of every subfolder；

Please let me know how it works. Thanks!

### CODE REVIEW

**Comment by SoftFever** [comment]
@FlashforgeOfficial 
Unfortunately, it's still not functioning as expected.
I'd recommend beginning by copying profiles from existing vendors like Voron, Ratrig, Vzbot, Custom, etc.
From there, start with renaming the printer/process/filament names.
Once that's done, you can proceed to add new printer models, processes, and filament types.
Log files are available in %appdata%/orcaslicer/log to help you debug what's wrong.
Lastly, ensure you test the profiles to confirm they work before requesting a review.

**Review by SoftFever — CHANGES_REQUESTED** [review]
Unfortunately, it's still not functioning as expected.
I'd recommend beginning by copying profiles from existing vendors like Voron, Ratrig, Vzbot, Custom, etc.
From there, start with renaming the printer/process/filament names.
Once that's done, you can proceed to add new printer models, processes, and filament types.
Log files are available in %appdata%/orcaslicer/log to help you debug what's wrong.
Lastly, ensure you test the profiles to confirm they work before requesting a review.

**Comment by FlashforgeOfficial** [comment]
> Unfortunately, it's still not functioning as expected. I'd recommend beginning by copying profiles from existing vendors like Voron, Ratrig, Vzbot, Custom, etc. From there, start with renaming the printer/process/filament names. Once that's done, you can proceed to add new printer models, processes, and filament types. Log files are available in %appdata%/orcaslicer/log to help you debug what's wrong. Lastly, ensure you test the profiles to confirm they work before requesting a review.

Sure. Thanks, I will test ahead to make sure they work.

**Comment by mariuske** [comment]
Any progress on this @FlashforgeOfficial ? :)

**Comment by FlashforgeOfficial** [comment]
> Any progress on this @FlashforgeOfficial ? :)

Thank you for your attention! Recently I am doing updates my branch to match the profile format. A new PR will be submitted soon,

**Comment by mariuske** [comment]
Great, thank you for the update @FlashforgeOfficial! Looking forward to get support in OrcaSlicer as my Adventurer 5M Pro arrived today :)

**Pull request closed without merging**
