### PR TITLE
Integrate external purge estimates (eg Blobifier) to the filament consumption UI

### PR DESCRIPTION
**Pull request by igiannakas**
# Description
With external purging solutions becoming more common, I’ve come across a limitation when assembling mine - it is impossible to estimate the amount of filament purged during slicing!

For example, when using Happy Hare together with the blobifier, it is not possible currently to estimate the volume of filament purged, because there are no G1 Ex commands issued by the slicer, but rather the purge volumes are calculated and executed by the printer/ happy hare and blobifier software and macros themselves.

**This PR aims to address this limitation by tagging the purge commands as specially formatted comments and use that to calculate the projected flushed filament volume.** This is particularly useful in combination with Spoolman as you can actually compare now the projected filament use vs your available filament in the spool man UI.

This should be fairly accurate as the flush/purge volume matrix is read by Happy Hare and is used by the blobifier to execute the purge. Also this approach allows the user to apply the same correction variable to the volumes (variable_purge_length_modifier), if other than 0.

image

image

This also allows the user to include the combined filament consumption between external purge (in the blobifier) and any prime tower that the user may have enabled (eg. to ensure the nozzle is primed before printing).

image

To set it up, set the below in your Change Filament g-code:
```
T[next_extruder]
; FLUSH_START
; EXTERNAL_PURGE {flush_length_1+flush_length_2+flush_length_3+flush_length_4}
; FLUSH_END 
```

If your variable_purge_length_modifier is not 1.0, then you can adjust the calculated purge volume like so (eg. if the value is 0.6).

```
T[next_extruder]
; FLUSH_START
; EXTERNAL_PURGE {0.6*(flush_length_1+flush_length_2+flush_length_3+flush_length_4)}
; FLUSH_END 
```

Make sure purge in the prime tower is disabled:
image

## Tests

Tested with Bambu and Voron printers. As this is a comment in the Gcode and the code is only invoked when the external purge tag is present, there are no side effects.

### CODE REVIEW

**Comment by igiannakas** [comment]
Testing feedback on the above. Have been using this feature over multiple multi color prints and it's quite accurate as in within a few grams in total of the estimate

image

**Purge:**
Estimated: 95.39 grams
Actual: 96.19 grams
BBE7E0B6-58CD-4BD1-B126-4DE8214D9E94_4_5005_c

**Tower:**
Estimated: 19.98 grams
Actual: 20.39 grams


**Model:**
Estimated: 275.38 grams
Actual: 276 grams or so (no micro gram scale for this)


**All in all around 1.83 grams in total variance between printed and actual model.**

**Review by SoftFever — APPROVED** [review]
Looks good.
Thank you :)

**Comment by igiannakas** [comment]
> sorry Offtopic: @igiannakas where can i download your red nose reindear stl?
> 
> thank you

Its from here: https://cults3d.com/en/3d-model/home/christmas-multicolor-knitted-containers-not-needed-supports

There are also these ones that are free, from the same designer: https://cults3d.com/en/3d-model/home/santa-christmas-multicolor-knitted-container-not-needed-supports

IMG_4904

**Comment by Stevetm2** [comment]
This is great, I'll add it to my K2 printer profile, thank you. I noticed there is also flush_multiplier variable available, which is used like this...

; EXTERNAL_PURGE {flush_multiplier*(flush_length_1+flush_length_2+flush_length_3+flush_length_4)}

**Comment by joaco5guerreros-ops** [comment]
Hola, estoy usando la ad5x y tengo este mismo problema, no se calcular la cantidad de cacas o purgas que tiene en los cambios de color
image
WhatsApp Image 2026-03-18 at 23 56 54
los valores no coinciden con lo que estima, este es el gcode:
image
podrian ayudarme??

**Pull request merged**
