### PR TITLE
Add Dremel 3D20, 3D40, and 3D45

### LINKED ISSUE #1423: Dremel 3D45 support
**Is your feature request related to a problem? Please describe.**
I am unable to use my filament printer with your software, the Dremel 3D45.

**Describe the solution you'd like**
Support the Dremel 3D45 as a supported printer.

**Describe alternatives you've considered**
Other software.

**Additional context**
None.

### PR DESCRIPTION
**Pull request by cochcoder**
In this PR I added the profiles based as close to the ones in Dremel's slicer, [DigiLab](https://www.dremel.com/ap/en/digilab/software), however, a few QOL settings were added, such as combine infill and Arachne mode. One main concern I have is the start/end G-Codes as I copied them word for word from DigiLab, but I don't know if they will work as intended in Orca Slicer. I think that these printers will make a great addition to Orca Slicer as I only found them in DigiLab and Simplify3D, which DigiLab, in my experience, is based on a very old slicer (if not version), has a very limited feature set, and loves to freeze up and die. 

This PR is marked as a draft as the TO-DO list needs to be completed: 

- [x] Fix bug where printers are not applied when added *I need help with this one! 
- [x] Add bed models 
- [ ] Add bed textures 

Test the profiles and make any needed improvements: 

 - [ ] Dremel 3D20
 - [ ] Dremel 3D40
 - [ ] Dremel 3D45

Fixes #1423

### CODE REVIEW

**Comment by tuvinez** [comment]
any dates for working profile of dremel printers for OrcaSlicer?

**Comment by cochcoder** [comment]
> any dates for working profile of dremel printers for OrcaSlicer?

Not currently, I opened this as a draft due to a couple of reasons and has a low priority. Some of the main reasons this is a draft is that the profiles won't apply when selected (I need help on fixing this) and testing is needed as I don't personally own these machines but see a need for them to be included.

**Comment by SoftFever** [comment]
@cochcoder 
In case you don't know this yet, you can find what's error by clicking the link here:
image
It will tell you what issue does the profile has:
image

**Comment by SoftFever** [comment]
> > @cochcoder In case you don't know this yet, you can find what's error by clicking the link here: image It will tell you what issue does the profile has: image
> 
> I've looked into the issue and I can't find any way to resolve it (I used Creality's version of these files)

From the error message `can not find inherits fdm_process_common for fdm_process_dremel_common`, fdm_process_common.json is missing(either the file is missing or it's not listed in Dremel.json)

**Comment by cochcoder** [comment]
It's still having the issue where the profiles don't show up even when the printers are selected. I am trying to see if having one build plate model for two printers is the issue.

**Review by SoftFever — APPROVED** [review]
Thanks.
I fixed an issue that it won't load on Mac/Linux OS

**Comment by cochcoder** [comment]
@SoftFever I'm not sure about merging this PR quite yet as I have no clue if these machines will work without testing

**Comment by eduncan911** [comment]
Hello everyone and @SoftFever !

Eric Duncan here, (new) Lead Firmware Engineer for all Dremel Printers.  :-)

This was an excellent submission.  I apologize I didn't catch it in the PRs, as I have been actively developing on Orca for several months now - actually creating modules and tuned profiles to release so we can support our customers with hardened battle-tested profiles.

Kind of surprised this slipped past me.  I've been in the issues and PRs here, merging code for a while.  Sorry again!

---

Now the question is, what do we do with these base submissions here?

@SoftFever Does Dremel have a right to override them here?

I do not want to do that because that would be against the spirit of the author's (@cochcoder) hard work they put into this PR.  And personally, coming from open source myself, I do not want to do that.  

All of my Orca resources files are vastly different than this PR though, due to the Bambu limitations to profiles they did here, compared to Prusa branches and all other slicers. Read: I have like 90 new files to submit because of all the duplication required for the filtering of all conditions in the Bambu-version of profiles, across all the filament types and filters.  It's still a WIP at this time though, but I could open a PR soon.

Dremel company-wise, they have to be able to support customers with known good profiles.

So I am not sure about releasing this version of the Dremel profiles as "base" profiles at this time, as we all know how "modifying" a printer automatically copies the base, like for wifi IP.  

And because of that, feature, of these slicers, we would.never be able to update those users again to corrected profiles.

**Comment by eduncan911** [comment]
I've also been told I'm vastly over-thinking this, and to just submit all the updates always.  Lol

**Comment by cochcoder** [comment]
@eduncan911 Thank you for your response, I would be open to removing the 3D20 & 3D40 profiles as I haven't had anyone test those yet. However for the 3D45, I currently have a PR that is fixing all of the issues with it being able to print. I think that one should be left, if it works as expected after the PR, until the battle-hardened one is ready. Unless you think that the profiles will be ready before the main 2.1 release (which would be in around 18 days if it follows the same schedule of the 2.0 release). I ultimately leave this up to @SoftFever though.

**Comment by cochcoder** [comment]
I can rename the current profiles that would be kept so that when the profiles you are currently working on will be seamlessly merged and the values would change for the end user's, without breaking any custom profiles they made.

**Comment by cochcoder** [comment]
@eduncan911 Around what time should we expect a PR to add these printers if they were removed for the time being?

**Comment by SoftFever** [comment]
> Hello everyone and @SoftFever !
> 
> Eric Duncan here, (semi-new) Lead Firmware Engineer for all Dremel Printers. :-)
> 
> This was an excellent submission. I apologize I didn't catch it in the PRs, as I have been actively developing on Orca for several months now - actually creating modules and tuned profiles to release so we can support our customers with hardened battle-tested profiles.
> 
> Kind of surprised this slipped past me. I've been in the issues and PRs here, merging code for a while. Sorry again!
> 
> Now the question is, what do we do with these base submissions here?
> 
> @SoftFever Does Dremel have a right to override them here?
> 
> I do not want to do that because that would be against the spirit of the author's (@cochcoder) hard work they put into this PR. And personally, coming from open source myself, I do not want to do that.
> 
> However, all of my Orca resources files are vastly different than this PR though. It's due to the Bambu limitations to profiles they did here to their branch, compared to Prusa branches and all other slicers. Read: I have like 90 new files to submit because of all the duplication required for the filtering of all conditions in the Bambu-version of profiles, across all the filament types and filters. It's still a WIP at this time though across other slicers and priorities, but I could open a PR soon.
> 
> Dremel, company-wise, they have to be able to support customers with _known good profiles_.
> 
> So I am not sure about releasing this version of the Dremel profiles as "base" profiles at this time to end-users, as we all know how "modifying" a Built-In Printer automatically copies the base profile to user profiles, like for a simple WiFi IP address!! Argh.
> 
> And because of that "feature" of copying built-in profiles to user profiles in these slicers, we would never be able to update those users again to corrected profiles without causing more customer service calls and knowledge base articles to address how to purge an old vendor list for a new vendor list.

Hi @eduncan911 @cochcoder

Sorry, I overlooked the message here. 
Since the changes in this PR are not yet included in the official 2.1.0 release, it's fine to rename or change or delete files. It would be tricky if the profiles were widely adopted by users because renaming or deleting profiles would prevent loading user's custom settings. 
However, that is not the case here. Feel free to submit your changes via a PR.

**Comment by DrewWing** [comment]
Don't want to necro an old thread unnecessarily, but I do have a Dremel 3D20 running stock firmware (v1.8_20210804), so if anyone still needs testing feel free to ping me here or on discord.

**Comment by cochcoder** [comment]
> Don't want to necro an old thread unnecessarily, but I do have a Dremel 3D20 running stock firmware (v1.8_20210804), so if anyone still needs testing feel free to ping me here or on discord.

If you run into any issues using it on Orca, feel free to @ me on a new issue. I'll try to look into the issue, if you make it, once I get time.

**Pull request merged**
