### PR TITLE
Make Overhang Printable

### PR DESCRIPTION
**Pull request by Noisyfox**
This replaces PR #1556

### CODE REVIEW

**Comment by SoftFever** [comment]
Hey @Noisyfox @odie5533 ,

The PR looks to be in good shape. 
I made some fixes/changes below:
1. Fixed an issue where changing 'make_overhang_printable' related parameters wouldn't clear caches properly.
2. Tweaked the logic of the 'make_overhang_printable' parameter to work for per region/object/print level, and removed the 'make_overhang_printable_disable' parameter.
3. Set the default 'make_overhang_printable_angle' to 55 degrees.

Please review and test these changes. If everything looks good, we're good to merge it. 👍

**Comment by Noisyfox** [comment]
With the change of the settings logic, now you can enable this setting on a single object without enabling the global one, however it won't be affective because of https://github.com/SoftFever/OrcaSlicer/pull/1615/files#diff-ae94698c496da8738c4a6413f08caa1e42aa965ba9de3960207d41943816df9fR1179-R1181

which makes this a bit confusing:

image
image

**Comment by SoftFever** [comment]
> With the change of the settings logic, now you can enable this setting on a single object without enabling the global one, however it won't be affective because of https://github.com/SoftFever/OrcaSlicer/pull/1615/files#diff-ae94698c496da8738c4a6413f08caa1e42aa965ba9de3960207d41943816df9fR1179-R1181
> 
> which makes this a bit confusing:
> 
> image image

Agreed.
I have reverted that change.

**Comment by Noisyfox** [comment]
LGTM

**Comment by odie5533** [comment]
I have not tested a later build, but my brother had mentioned the early ones seemed to mark the interior as 'bridging' and so prints would take a lot longer, in some cases twice as long. Was this fixed or changed with some of the logic changes? Otherwise I can try testing it again to narrow down the issue.

**Comment by SoftFever** [comment]
@odie5533 
I'm not aware of the issue you mentioned.
Not sure if @Noisyfox know about this. 

It would be great if you can test with the latest build.

**Comment by Noisyfox** [comment]
> I have not tested a later build, but my brother had mentioned the early ones seemed to mark the interior as 'bridging' and so prints would take a lot longer, in some cases twice as long. Was this fixed or changed with some of the logic changes? Otherwise I can try testing it again to narrow down the issue.

I think that's the same issue as https://github.com/SoftFever/OrcaSlicer/pull/1556#issuecomment-1655632219 which should have been fixed.

**Comment by SoftFever** [comment]
> > I have not tested a later build, but my brother had mentioned the early ones seemed to mark the interior as 'bridging' and so prints would take a lot longer, in some cases twice as long. Was this fixed or changed with some of the logic changes? Otherwise I can try testing it again to narrow down the issue.
> 
> I think that's the same issue as [#1556 (comment)](https://github.com/SoftFever/OrcaSlicer/pull/1556#issuecomment-1655632219) which should have been fixed.

Great! I'm going to merge this PR.
If there are any issues, feel free to raise an ticket. @odie5533

**Review by SoftFever — APPROVED** [review]

**Pull request merged**
