### PR TITLE
Revert to WxWidgets 3.1.5

### PR DESCRIPTION
**Pull request by SoftFever**
Temporarily revert to wxWidgets 3.1. 
wxWidgets handles DPI automatically starting from version 3.2, while OrcaSlicer handles DPI independently.

It would be beneficial to have wxWidgets handle DPI in the future, but due to the amount of work and especially testing effort required, I've decided not to implement this for OrcaSlicer 1.9.

Now, scaling works as expected. The following screenshot is at a 200% scale.
image

-----------------For future reference----------------------
NOTE for future upgrade:
By disable Orca's DPI scaling  in `create_scaled_bitmap` function, I'm able to get most UI work with wxWidgets 3.2.
But there are two small UI glitches at 200% which I decide to not investigate at the moment.
glitches with 3.2:
15d99b5ee8ea266514634dacc225d856
cf2c7513df190d9d20e7f09cfe2a6810
@Ocraftyone @Noisyfox FYI in case you are interested to know the status of 3.2.

### CODE REVIEW

**Comment by Eldenroot** [comment]
What about to stay with v3.2 but use your method create_scaled_bitmap disabled ans fix 2 reported issued?

I am afraid that reverting back many new issues will pop up.

Or keep 2 branches

**Comment by SoftFever** [comment]
> What about to stay with v3.2 but use your method create_scaled_bitmap disabled ans fix 2 reported issued?
> 
> I am afraid that reverting back many new issues will pop up.
> 
> Or keep 2 branches

I'm not sure how many issues remain, to be honest. It requires a thorough overhaul of the DPI-related code, and extensive testing is needed before I feel comfortable releasing it. At this point, I've decided not to invest more effort in that.

**Comment by tsmith35** [comment]
It looks great now. Back to normal. The update to 3.2 will make for a nice post-holiday project.

Thanks, guys! Hope you all have a merry Christmas and get to see kids/family/people and all that good stuff.

**Comment by Ocraftyone** [comment]
@SoftFever Thank you for the update. I look forward to the headache 😜

**Comment by galetska228** [comment]
thx

**Pull request merged**
