### PR TITLE
Inner-Outer-Inner mode - additional fix where an external perimeter is shared between multiple islands in the same ordered_extrusions perimeter list

### PR DESCRIPTION
**Pull request by igiannakas**
Another PR on the sandwich mode wall ordering bringing it closer to perfection :)

When working on pressure equalizer I noticed an edge case with the inner-outer-inner algorithm where it failed to re-order the perimeters correctly, resulting in a noticeable layer bulge.

This is because a first internal perimeter is extruded before the adjacent external perimeter as seen below. This edge case occurs when an external perimeter is shared between multiple "islands" in the same ordered_extrusions perimeter list. Hence some first internal perimeters were extruded before the external perimeter as they belonged in a separate island.

**Before:**
We can see a bulge in the layer above the front hole bridges. We can also see a further bulges above the front "window".

Looking into the slicer layer view shows the reason - the external perimeter is extruded after a first internal perimeter.
Screenshot 2023-09-30 at 18 53 57
Screenshot 2023-09-30 at 18 54 18

**The fix**
The algorithm has been extended to always re-sequence the internal perimeters in the right way. It always brings any perimeter with inset_index 1 before any perimeter with inset_index 2 and higher. This results in all second+ perimeters being always extruded before the external perimeter (inset_index = 0) after the sandwich mode is applied.
Screenshot 2023-09-30 at 19 50 30

Screenshot 2023-09-30 at 18 56 00

**Print Test.** 
Can clearly see the improvement in layer consistency.
**After:**

**Before:**

I'd appreciate your review and inclusion in the next release if possible. Its another step in making this mode as perfect as possible :) 

The new code segment is below + minor alternations to the remaining algorithm to use the new reordered_extrusions vector.
```
                // Initiate reorder sequence to bring any index 1 (first internal) perimeters ahead of any second internal perimeters
                // Leaving these out of order will result in print defects on the external wall as they will be extruded prior to any
                // external wall. To do the re-ordering, we are creating two extrusion arrays - reordered_extrusions which will contain
                // the reordered extrusions and skipped_extrusions will contain the ones that were skipped in the scan
                std::vector<PerimeterGeneratorArachneExtrusion> reordered_extrusions, skipped_extrusions;
                bool found_second_internal = false; // helper variable to indicate the start of a new island
                
                for(auto extrusion_to_reorder : ordered_extrusions){ //scan the perimeters to reorder
                    switch (extrusion_to_reorder.extrusion->inset_idx) {
                        case 0: // external perimeter
                            if(found_second_internal){ //new island - move skipped extrusions to reordered array
                                for(auto extrusion_skipped : skipped_extrusions)
                                    reordered_extrusions.emplace_back(extrusion_skipped);
                                skipped_extrusions.clear();
                            }
                            reordered_extrusions.emplace_back(extrusion_to_reorder);
                            break;
                        case 1: // first internal perimeter
                            reordered_extrusions.emplace_back(extrusion_to_reorder);
                            break;
                        default: // second internal+ perimeter -> put them in the skipped extrusions array
                            skipped_extrusions.emplace_back(extrusion_to_reorder);
                            found_second_internal = true;
                            break;
                    }
                }
                if(ordered_extrusions.size()>reordered_extrusions.size()){
                    // we didnt find any more islands, so lets move the remaining skipped perimeters to the reordered extrusions list.
                    for(auto extrusion_skipped : skipped_extrusions)
                        reordered_extrusions.emplace_back(extrusion_skipped);
                    skipped_extrusions.clear();
                }
```

### CODE REVIEW

**Comment by SoftFever** [comment]
Thanks @igiannakas 
It works better now to ensure the printing order.

The only drawback we have now with the current approach is that the travel paths are optimized anymore.
sandwich

But consider nowadays printers can move really fast, I think it's a good trade off anyway.

**Comment by igiannakas** [comment]
Indeed paths are affected but only in cases where multiple islands exist, else this doesn’t do anything, it leaves them the same as before.

I’ve tried optimising the travel paths for this scenario but failed miserably - the junction.point distance between the start of the external perimeter (junction.front.p) and the end of the second internal perimeters (junction.back.p) don’t make sense - the closest paths had a longer distance on some occasions in the code.

I can commit that code if you want to see it - but I couldn’t make it work for now.

**Comment by igiannakas** [comment]
Code to check perimeter 2's and bring the closest one to the external perimeter forward based on distance:

```
                       for (arr_i = position; arr_i < reordered_extrusions.size(); ++arr_i) {
                         printf("Perimeter: extrusion inset index %d, ordered extrusions array position %d\n",reordered_extrusions[arr_i].extrusion->inset_idx, arr_i);
                        switch (reordered_extrusions[arr_i].extrusion->inset_idx) {
                            case 0: // external perimeter
                                if (outer == -1)
                                    outer = arr_i;
                                break;
                            case 1: // first internal wall
                                if (first_internal==-1 && arr_i>outer && outer!=-1){
                                    first_internal = arr_i;
                                }
                                break;
                            case 2: // second internal wall
                                if (second_internal == -1 && arr_i > first_internal && outer!=-1){
                                    second_internal = arr_i;
                                    // start scanning remaining second internal perimeters in case there is any perimeter that
                                    // has an end position closer to the first external perimeter starting position.
                                    // If one is found, swap positions with the currently identified second internal perimeter
                                    Point ext_start_position = reordered_extrusions[outer].extrusion->junctions[0].p;
                                    Point current_second_internal_end_position = reordered_extrusions[second_internal].extrusion->junctions.back().p;
                                    double cur_distance_sqr = (current_second_internal_end_position - ext_start_position).cast<double>().norm();
                                    
                                    printf("Current distance: Layer: %d, distance %f\n", layer_id, cur_distance_sqr);
                                    int closer_perimeter = -1;
                                    for(int closer_second_intenal = second_internal + 1;closer_second_intenal < reordered_extrusions.size(); ++closer_second_intenal){
    
                                        Point candidate_second_internal_end_position = reordered_extrusions[closer_second_intenal].extrusion->junctions.back().p;
                                        double candidate_distance_sqr = (candidate_second_internal_end_position - ext_start_position).cast<double>().norm();
                                        printf("Scanning for closer perimeters. LayerID: %d, perimeter:%d, distance %f \n", layer_id, closer_second_intenal, candidate_distance_sqr);
                                        if(candidate_distance_sqr < cur_distance_sqr && reordered_extrusions[closer_second_intenal].extrusion->inset_idx == 2 ){
                                            printf("REORDERED! LayerID: %d Original Distance: %f New Distance: %f, array position:  %d\n",layer_id, cur_distance_sqr,candidate_distance_sqr, closer_second_intenal);
                                            cur_distance_sqr = candidate_distance_sqr;
                                            closer_perimeter = closer_second_intenal;
                                        }
                                    }
                                    if(closer_perimeter > -1){
                                        printf("REORDERED! External Perimeter Index: %d LayerID: %d, Original Perimeter: %d, New Perimeter %d\n",outer, layer_id, second_internal, closer_perimeter);
                                        std::swap(reordered_extrusions[closer_perimeter],reordered_extrusions[second_internal]);
                                    }
                                }
                                break;
                        }
                        if(outer >-1 && first_internal>-1 && second_internal>-1 && ordered_extrusions[arr_i].extrusion->inset_idx == 0){ // found a new external perimeter after we've found all three perimeters to re-order -> this means we entered a new island.
                            arr_i=arr_i-1; //step back one perimeter
                            max_internal = arr_i; // new maximum internal perimeter is now this as we have found a new external perimeter, hence a new island.
                            break; // exit the for loop
                        }
                    }

```

Code that calculates whether paths are touching or are neighbouring - I may use that in a future revision to prevent re-ordering of perimeter inset index 1 when its not needed

```
                                 Polyline *internal_path = new Polyline();
                                Polyline *external_path = new Polyline();
                                bool lines_touching = false;
                                
                                for (const Arachne::ExtrusionJunction& junction : reordered_extrusions[arr_j].extrusion->junctions) internal_path->append(junction.p);
                                for (const Arachne::ExtrusionJunction& junction : reordered_extrusions[outer].extrusion->junctions) external_path->append(junction.p);

                                AABBTreeLines::LinesDistancer<Line> lines_internal{internal_path->lines()};
                                AABBTreeLines::LinesDistancer<Line> lines_external{external_path->lines()};
                                
                                for (size_t pt_idx = 0; pt_idx < internal_path->size(); pt_idx++)
                                    if (lines_external.distance_from_lines<false>(internal_path->points[pt_idx]) < (this->perimeter_flow.scaled_spacing() * 1.5f)) lines_touching = true;
                                
                                for (size_t pt_idx = 0; pt_idx < external_path->size(); pt_idx++)
                                    if (lines_internal.distance_from_lines<false>(external_path->points[pt_idx]) < (this->perimeter_flow.scaled_spacing() * 1.5f)) lines_touching = true;
                                
                                if(lines_touching) printf("LINES TOUCHING. LayerID %d, Perimeter index %d\n", layer_id, arr_j);
```

**Comment by igiannakas** [comment]
PS. the above scenario wasn't too bad in my test for some reason:

output

**Comment by SoftFever** [comment]
> Code to check perimeter 2's and bring the closest one to the external perimeter forward based on distance. The below doesnt work as expected - for some reason the second internal perimeter distances are weird. The closest perimeter visually has a much larger distance than one that is further away... So I gave up on making the below work + expanding it for a full perimeter re-order.
> 
> ```
>                        for (arr_i = position; arr_i < reordered_extrusions.size(); ++arr_i) {
>                          printf("Perimeter: extrusion inset index %d, ordered extrusions array position %d\n",reordered_extrusions[arr_i].extrusion->inset_idx, arr_i);
>                         switch (reordered_extrusions[arr_i].extrusion->inset_idx) {
>                             case 0: // external perimeter
>                                 if (outer == -1)
>                                     outer = arr_i;
>                                 break;
>                             case 1: // first internal wall
>                                 if (first_internal==-1 && arr_i>outer && outer!=-1){
>                                     first_internal = arr_i;
>                                 }
>                                 break;
>                             case 2: // second internal wall
>                                 if (second_internal == -1 && arr_i > first_internal && outer!=-1){
>                                     second_internal = arr_i;
>                                     // start scanning remaining second internal perimeters in case there is any perimeter that
>                                     // has an end position closer to the first external perimeter starting position.
>                                     // If one is found, swap positions with the currently identified second internal perimeter
>                                     Point ext_start_position = reordered_extrusions[outer].extrusion->junctions[0].p;
>                                     Point current_second_internal_end_position = reordered_extrusions[second_internal].extrusion->junctions.back().p;
>                                     double cur_distance_sqr = (current_second_internal_end_position - ext_start_position).cast<double>().norm();
>                                     
>                                     printf("Current distance: Layer: %d, distance %f\n", layer_id, cur_distance_sqr);
>                                     int closer_perimeter = -1;
>                                     for(int closer_second_intenal = second_internal + 1;closer_second_intenal < reordered_extrusions.size(); ++closer_second_intenal){
>     
>                                         Point candidate_second_internal_end_position = reordered_extrusions[closer_second_intenal].extrusion->junctions.back().p;
>                                         double candidate_distance_sqr = (candidate_second_internal_end_position - ext_start_position).cast<double>().norm();
>                                         printf("Scanning for closer perimeters. LayerID: %d, perimeter:%d, distance %f \n", layer_id, closer_second_intenal, candidate_distance_sqr);
>                                         if(candidate_distance_sqr < cur_distance_sqr && reordered_extrusions[closer_second_intenal].extrusion->inset_idx == 2 ){
>                                             printf("REORDERED! LayerID: %d Original Distance: %f New Distance: %f, array position:  %d\n",layer_id, cur_distance_sqr,candidate_distance_sqr, closer_second_intenal);
>                                             cur_distance_sqr = candidate_distance_sqr;
>                                             closer_perimeter = closer_second_intenal;
>                                         }
>                                     }
>                                     if(closer_perimeter > -1){
>                                         printf("REORDERED! External Perimeter Index: %d LayerID: %d, Original Perimeter: %d, New Perimeter %d\n",outer, layer_id, second_internal, closer_perimeter);
>                                         std::swap(reordered_extrusions[closer_perimeter],reordered_extrusions[second_internal]);
>                                     }
>                                 }
>                                 break;
>                         }
>                         if(outer >-1 && first_internal>-1 && second_internal>-1 && ordered_extrusions[arr_i].extrusion->inset_idx == 0){ // found a new external perimeter after we've found all three perimeters to re-order -> this means we entered a new island.
>                             arr_i=arr_i-1; //step back one perimeter
>                             max_internal = arr_i; // new maximum internal perimeter is now this as we have found a new external perimeter, hence a new island.
>                             break; // exit the for loop
>                         }
>                     }
> ```
> 
> Code that calculates whether paths are touching or are neighbouring. I used this to find exceptions where a perimeter 1 is touching an external perimeter that has already been extruded - I may use that in a future revision to prevent re-ordering of perimeter inset index 1 when its not needed
> 
> ```
>                                  Polyline *internal_path = new Polyline();
>                                 Polyline *external_path = new Polyline();
>                                 bool lines_touching = false;
>                                 
>                                 for (const Arachne::ExtrusionJunction& junction : reordered_extrusions[arr_j].extrusion->junctions) internal_path->append(junction.p);
>                                 for (const Arachne::ExtrusionJunction& junction : reordered_extrusions[outer].extrusion->junctions) external_path->append(junction.p);
> 
>                                 AABBTreeLines::LinesDistancer<Line> lines_internal{internal_path->lines()};
>                                 AABBTreeLines::LinesDistancer<Line> lines_external{external_path->lines()};
>                                 
>                                 for (size_t pt_idx = 0; pt_idx < internal_path->size(); pt_idx++)
>                                     if (lines_external.distance_from_lines<false>(internal_path->points[pt_idx]) < (this->perimeter_flow.scaled_spacing() * 1.5f)) lines_touching = true;
>                                 
>                                 for (size_t pt_idx = 0; pt_idx < external_path->size(); pt_idx++)
>                                     if (lines_internal.distance_from_lines<false>(external_path->points[pt_idx]) < (this->perimeter_flow.scaled_spacing() * 1.5f)) lines_touching = true;
>                                 
>                                 if(lines_touching) printf("LINES TOUCHING. LayerID %d, Perimeter index %d\n", layer_id, arr_j);
> ```

For that, one might have to check the Hausdorff distance between two perimeters @_@
That's an overkill for sure. 
I think the current trade off is not bad given nowadays printers can travel super fast.

**Comment by igiannakas** [comment]
That is a great idea! Maybe something like this simplified version? I may have a play with it at some point :)  

```
double euclideanDistance(const Point& p1, const Point& p2) {
    double dx = p1.x - p2.x;
    double dy = p1.y - p2.y;
    return sqrt(dx * dx + dy * dy);
}

double hausdorffDistance(const std::vector<Point>& set1, const std::vector<Point>& set2) {
    double maxDistance = 0.0;

    for (const Point& p1 : set1) {
        double minDistance = DBL_MAX;

        for (const Point& p2 : set2) {
            double distance = euclideanDistance(p1, p2);
            if (distance < minDistance) {
                minDistance = distance;
            }
        }

        if (minDistance > maxDistance) {
            maxDistance = minDistance;
        }
    }

    for (const Point& p2 : set2) {
        double minDistance = DBL_MAX;

        for (const Point& p1 : set1) {
            double distance = euclideanDistance(p2, p1);
            if (distance < minDistance) {
                minDistance = distance;
            }
        }

        if (minDistance > maxDistance) {
            maxDistance = minDistance;
        }
    }

    return maxDistance;
}

```

**Comment by SoftFever** [comment]
> That is a great idea! Maybe something like this simplified version? I may have a play with it at some point :) Not sure though it it will help with the problem of minimising travel distance between the last extrusion point of a second internal perimeter to the start of a first external perimeter which I was trying to optimise :)
> 
> ```
> double euclideanDistance(const Point& p1, const Point& p2) {
>     double dx = p1.x - p2.x;
>     double dy = p1.y - p2.y;
>     return sqrt(dx * dx + dy * dy);
> }
> 
> double hausdorffDistance(const std::vector<Point>& set1, const std::vector<Point>& set2) {
>     double maxDistance = 0.0;
> 
>     for (const Point& p1 : set1) {
>         double minDistance = DBL_MAX;
> 
>         for (const Point& p2 : set2) {
>             double distance = euclideanDistance(p1, p2);
>             if (distance < minDistance) {
>                 minDistance = distance;
>             }
>         }
> 
>         if (minDistance > maxDistance) {
>             maxDistance = minDistance;
>         }
>     }
> 
>     for (const Point& p2 : set2) {
>         double minDistance = DBL_MAX;
> 
>         for (const Point& p1 : set1) {
>             double distance = euclideanDistance(p2, p1);
>             if (distance < minDistance) {
>                 minDistance = distance;
>             }
>         }
> 
>         if (minDistance > maxDistance) {
>             maxDistance = minDistance;
>         }
>     }
> 
>     return maxDistance;
> }
> ```

hahaha, you are fast!
It's just came to my mind that check distance might not enough, it should also consider "contains" relationships.
But I feel there must be better ways to do that...
Anyways, as we both agreed, the current tradeoff if well worth it.

Let's merge this PR first.
Thank you so much for keep improving this features 👍

**Pull request merged**
