### PR TITLE
Best effort for pixel perfect icon rendering

### LINKED ISSUE #4328: Toolbar icons blurry
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.0

### Operating System (OS)

Windows

### OS Version

10 LTSC

### Additional system information

_No response_

### Printer

Creality K1

### How to reproduce

Changing window width aligns toolbar to perfect center that makes start point of toolbar as float number instead of int. that causes blurry images

### Actual results

here is comparison of perfect fit vs slightly shifted blurry icons

Screenshot-20240304024011

i changed window width few times to catch perfect fit

### Expected results

i guess current placement of toolbar if sidebar on left
start_point_of_toolbar = ((window_width - sidebar_width ) / 2 )- (toolbar_width / 2)

number should be convert to "int" after calculation to fix that otherwise window tries to render toolbar start with decimal numbers and that causes blurry images

### Project file & Debug log uploads

-

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by Noisyfox**
This currently requires the toolbar icon to have even size.

Fixes #4328

Before:
icon_before

After:
icon_after

Toolbar icons should be noticeably sharper.

### CODE REVIEW

**Comment by yw4z** [comment]
thanks for your efforts on this, i will report results
This problem also appears on popup windows of toolbar. especially on these places
- Emboss > alignment icons
- Emboss > buttons near Style dropdown menu
- Other > Keyboard cheat sheet button
i guess emboss popup aligns to right of window and bottom of window. icons looks blurry vertically and horizontally

**Comment by Noisyfox** [comment]
> thanks for your efforts on this, i will report results This problem also appears on popup windows of toolbar. especially on these places
> 
> * Emboss > alignment icons
> * Emboss > buttons near Style dropdown menu
> * Other > Keyboard cheat sheet button
>   i guess emboss popup aligns to right of window and bottom of window. icons looks blurry vertically and horizontally

Not sure if I could do anything about these.

**Comment by Noisyfox** [comment]
@yw4z Also I've noticed your comment about icon size using odd numbers https://github.com/SoftFever/OrcaSlicer/pull/4368#issuecomment-1986544994

Technically you're right but some of the existing code make the assumption that icon sizes are in even numbers and I'm not sure how well it might behave.

If you are planing to use icons with odd numbers, could you try using the binary of this PR and replace with your icons and see if they work well?

**Comment by yw4z** [comment]
No i didnt changed their resolution to reduce code changes
Screenshot-20240319054512
mostly they have blank 1px line 2 sides
I'm adding all required changes in that commit as a to-do list. still changing things but big part of work is done

**Comment by yw4z** [comment]
@Noisyfox changing this line to int fixed issue for toolbar popup icons. they are pixel perfect now :)

https://github.com/SoftFever/OrcaSlicer/blob/f3b3e927824339bd76346bbb40b417de51aba31c/src/slic3r/GUI/IconManager.cpp#L376

included this to my UI [commit](https://github.com/SoftFever/OrcaSlicer/pull/4368)

**Comment by Noisyfox** [comment]
> @Noisyfox changing this line to int fixed issue for toolbar popup icons. they are pixel perfect now :)
> 
> https://github.com/SoftFever/OrcaSlicer/blob/f3b3e927824339bd76346bbb40b417de51aba31c/src/slic3r/GUI/IconManager.cpp#L376
> 
> included this to my UI [commit](https://github.com/SoftFever/OrcaSlicer/pull/4368)

Popups? Did you mean those gizmo panels?

**Comment by yw4z** [comment]
yes also fixed blue on keyboard cheat sheet button

**Comment by discip** [comment]
@SoftFever
Since #4368 has been implemented, this PR should too. 😊
Otherwise the icons look somewhat blurry under Linux (Manjaro GNOME).

**Comment by Noisyfox** [comment]
> Moving sidebar toggle to vertically center and exclude from toolbar calculations.

One sidenote: make sure this won't overlap with the plate list on the preview view.

**Comment by discip** [comment]
@yw4z
@Noisyfox

What about moving the arrow to the top so it doesn't protrude into the workspace?
Something like this:
image
Maybe the design could be adjusted according to the theme.

**Comment by discip** [comment]
@yw4z
@Noisyfox

What about moving the arrow to the top, but without protruding into the workspace?
Something like this:
image
Maybe the design could be adjusted according to the theme.

**Comment by Noisyfox** [comment]
> @yw4z @Noisyfox
> 
> What about moving the arrow to the top, but without protruding into the workspace? Something like this: image Maybe the design could be adjusted according to the theme.

That's not supported yet.

**Comment by discip** [comment]
> That's not supported yet.

That's a pity.

**Review by SoftFever — APPROVED** [review]
Looks good
Thank you

**Pull request merged**
