### PR TITLE
Flying Bear 2 fixes & fix Flying Bear name

### LINKED ISSUE #4866: "FlyingBear Reborn3" is a mistake
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

There are two problem with that profile. 1, the picture is wrongly mirrored. 2, its name is Reborn 2, not Reborn3. Also, there is a missing space in brand's name, _Flying Bear_.
Orca's picture
image

Official picture
image

### Which printers will be beneficial to this feature?

All

### Describe the solution you'd like

- Replace printer's image preview
- Rename "FlyingBear Reborn3" to "**Flying Bear Reborn 2**"
- Eventually, rename all occurences of "FlyingBear" to "**Flying Bear**" (brand name contains a space)
image

Here is the png I've cut out and edge smoothed ready to use
[Reborn_2_preview.zip](https://github.com/SoftFever/OrcaSlicer/files/14871574/Reborn_2_preview.zip)

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by cochcoder**
Fixes #4866

This PR renames FlyingBear to Flying Bear, renames Reborn 3 to Reborn 2, changes the Reborn 2 cover, and fixes Reborn 2's bed size. However, this PR will most likely break any custom profiles that were based on the old profiles due to some of the fixes.

### CODE REVIEW

**Comment by cochcoder** [comment]
@SoftFever Please let me know if you're fine with the breaking changes or if you don't want to do those.

**Comment by Nathan22211** [comment]
flying bear does have a reborn 3 on their store, this doesn't do much,

**Comment by cochcoder** [comment]
> flying bear does have a reborn 3 on their store, this doesn't do much,

@ilko-k said this isn't the case in [this](https://github.com/SoftFever/OrcaSlicer/issues/4866#issuecomment-2090438409) comment.

**Comment by ilko-k** [comment]
There was a Reborn 3 for a short of time, and Orca's "Reborn3" preset was available (with wrong picture and name) before the official release of that printer so it made sense to me that it was a mistake when compared to the actual Reborn 2. I don't know why the R3 is no more sold and it's also weird they removed any information about it (there still were units in stock), could be because of some defects reported by users.

**Comment by SoftFever** [comment]
> @SoftFever Please let me know if you're fine with the breaking changes or if you don't want to do those.

Sorry for the late response.

Based on your and @ilko-k's discussion, would it make more sense to add the Bear 2 as a new model  without deleting or touching the Bear 3 model?

**Comment by ilko-k** [comment]
> > @SoftFever Please let me know if you're fine with the breaking changes or if you don't want to do those.
> 
> Sorry for the late response.
> 
> Based on your and @ilko-k's discussion, would it make more sense to add the Bear 2 as a new model without deleting or touching the Bear 3 model?

Yeah maybe, but if keeping it is decided, there are still things to correct (preview picture, brand name and printer name).

As for the Reborn 2, I own one so I could contribute for creating a new preset for it but I'll need someone to integrate it through github (I'm not familiar with PR and so)

**Comment by FlyingbearOfficial** [comment]
Hello, I am the Flyingbear official, our REBORN3 will be on sale soon, the REBORN3 here is not the same kind of model as the previous REBORN2, please be aware of that!  @SoftFever @cochcoder @ilko-k

**Comment by SoftFever** [comment]
> Hello, this is flyingbear official, REBORN3 will be on sale soon, the REBORN3 and REBORN2 are not the same machine, please be aware of that! thank you @SoftFever @cochcoder @ilko-k 

Hi
👍
Feel free to work with our awesome community to fix/improve profiles

**Comment by cochcoder** [comment]
> Hello, this is flyingbear official, REBORN3 will be on sale soon, the REBORN3 and REBORN2 are not the same machine, please be aware of that! thank you @SoftFever @cochcoder @ilko-k 

Thank you for reaching out and letting us know this

**Pull request closed without merging**
