### PR TITLE
Add Creality CR-10 SE profile

### PR DESCRIPTION
**Pull request by FerronN**
Hi,

I would like to add support for the Creality CR-10 SE with a 0.4, 0.6 and 0.8 nozzle.
People said I should create the profile and others will do the rest?

I can help if I know how. I've seen that I should add the specific nozzle machine configs to the 'filament.json'.
That's not so hard. But all the settings that are needed in the machine 'Creality CR-10 SE (<diameter> nozzle).json' is unkown for me.

I can find some corresponding values from creality print but not all.
It would be great if it can be described. But I would also be verry please if someone with experience can create the required files for this machine :)

### CODE REVIEW

**Comment by bistory** [comment]
Hi, I can suggest you to take inspiration from Creality Ender 3 V3 KE profiles which are better than K1 profiles (they use their own set of filaments so they can overload default settings easily).
K1 "HF PLA" profiles are hacky and should be avoided for new profiles ;-)

**Comment by FerronN** [comment]
@bistory Thanks, that's good to know. But which files need to be created/edited for it to show up in the interface?
Or should I first just create my own custom profile?

**Comment by bistory** [comment]
> @bistory Thanks, that's good to know. But which files need to be created/edited for it to show up in the interface? Or should I first just create my own custom profile?

You can check my PR here where I added K1C profile : https://github.com/SoftFever/OrcaSlicer/pull/3728
You need to create files with a prefix in filaments folder :-)

**Comment by ltgustavsen** [comment]
Maybe you can find some inspiration and values from two profiles I found. 

https://www.printables.com/model/709820-creality-cr10-se-orca-slicer-profile/files
https://www.thingiverse.com/thing:6349830

**Comment by SoftFever** [comment]
Seems this PR is not ready yet. I will temporarily close it as I'm trying to keep the pending PR list short. Feel free to reopen it when you think it's ready

**Comment by Adilrafiq001** [comment]
> Maybe you can find some inspiration and values from two profiles I found.
> 
> https://www.printables.com/model/709820-creality-cr10-se-orca-slicer-profile/files https://www.thingiverse.com/thing:6349830

I am the owner of the printable Orca profile. It has given me great results till now, however I have created it just for 0.4mm nozzle.  I too am looking if someone can take inspiration from my profile and create a compete set (including nozzle variations, different filament types, different qualities and soo on.. ) then it can be officially introduced in the Ocra OTA update.

**Pull request closed without merging**
