### PR TITLE
Fix overly persistent pressure advance pattern

### PR DESCRIPTION
**Pull request by thewildmage**
As first reported by @FillPavS in #1547:

> I've found a bug. When I create a temperature test, a PA test is added to it
> [...]
> I found out that the error appears after some actions. Here's what you need to do to reproduce-
> 
>     1. Create a PA test and click the slice button.
> 
>     2. Without closing the program, create a new project and do not save anything.
> 
>     3. Create any test - temperature, flow, retract and others.
> 
> 
> Now the PA test will appear with them until you restart the program.

They reported that this happened on Windows 10. This bug doesn't appear on MacOS, though I was able to confirm that the `Model.calib_pa_pattern` was still hanging around in the background there, too.

This PR should fix the bug.

### CODE REVIEW

**Comment by thewildmage** [comment]
@FillPavS or @SoftFever, can one of you please check to see if this fix works for you? Based on what I can see on my Mac, I think it's fixed, but I don't have a Windows machine to check there.

**Comment by SoftFever** [comment]
@thewildmage 
It's fixed.

One more thing though, can you adjust two settings for the PA pattern test: turn off skirt and brim? 
It causes troubles for small printers

**Comment by SoftFever** [comment]
@thewildmage 
I saw two crashes today when I was testing both the line and pattern method.
Here is call stack, any clue?
Crash 1:
```
Exceptions:

Exception Code :c0000005 ACCESS_VIOLATION

Exception Flag :0x0 NumberParameters :2 
Param 0 :0x0 
Param 1 :0x8 
Context :00000049CDF2E2C0 
ContextFlag : 0x10005f, EFlags: 0x10246 
Fault address:  0xE9D75CF8 0x7FFD:0xEC78A668 



Show CallStack:

7ffde9d75cf8:Slic3r::ConfigBase::get_abs_value [D:\a\OrcaSlicer\OrcaSlicer\src\libslic3r\Config.cpp][694]

7ffde9d75d20:Slic3r::ConfigBase::get_abs_value [D:\a\OrcaSlicer\OrcaSlicer\src\libslic3r\Config.cpp][698]

7ffdea56cc2e:Slic3r::CalibPressureAdvancePattern::line_width_first_layer [D:\a\OrcaSlicer\OrcaSlicer\src\libslic3r\calib.hpp][166]

7ffdea5652b3:Slic3r::CalibPressureAdvancePattern::DrawBoxOptArgs::DrawBoxOptArgs [D:\a\OrcaSlicer\OrcaSlicer\src\libslic3r\calib.hpp][192]

7ffdea56a26b:Slic3r::CalibPressureAdvancePattern::generate_custom_gcodes [D:\a\OrcaSlicer\OrcaSlicer\src\libslic3r\calib.cpp][379]

7ffdea9e1164:Slic3r::GUI::Plater::reslice [D:\a\OrcaSlicer\OrcaSlicer\src\slic3r\GUI\Plater.cpp][10373]

7ffdea9d3a93:Slic3r::GUI::Plater::priv::on_action_slice_plate [D:\a\OrcaSlicer\OrcaSlicer\src\slic3r\GUI\Plater.cpp][6142]

Call SymGetLineFromAddr64 ,Address ebb01662 Error:000001e7

Call SymGetLineFromAddr64 ,Address ebb0021f Error:000001e7

Call SymGetLineFromAddr64 ,Address ebb0060a Error:000001e7

Call SymGetLineFromAddr64 ,Address ebb008bf Error:000001e7

Call SymGetLineFromAddr64 ,Address ebb0014b Error:000001e7

Call SymGetLineFromAddr64 ,Address ebb0040b Error:000001e7

Call SymGetLineFromAddr64 ,Address ebb02cbb Error:000001e7

Call SymGetLineFromAddr64 ,Address ebb40614 Error:000001e7

Call SymGetLineFromAddr64 ,Address ebb4086a Error:000001e7

Call SymGetLineFromAddr64 ,Address ebb02640 Error:000001e7

Call SymGetLineFromAddr64 ,Address ebb062d7 Error:000001e7

Call SymGetLineFromAddr64 ,Address ebb6de08 Error:000001e7

7ffdea8da58e:Slic3r::GUI::GUI_Run [D:\a\OrcaSlicer\OrcaSlicer\src\slic3r\GUI\GUI_Init.cpp][64]
```
Crash 2:
```
Exceptions:

Exception Code :c0000005 ACCESS_VIOLATION

Exception Flag :0x0 NumberParameters :2 
Param 0 :0x0 
Param 1 :0x0 
Context :0000005A7B4E5DC0 
ContextFlag : 0x10005f, EFlags: 0x10202 
Fault address:  0xB05E11A2 0xCCCCCCCC:0xCCCCCCCC 



Show CallStack:

7ffdb05e11a2:Slic3r::Extruder::retract_restart_extra [D:\a\OrcaSlicer\OrcaSlicer\src\libslic3r\Extruder.cpp][175]

7ffdb080d789:Slic3r::GCodeWriter::retract [D:\a\OrcaSlicer\OrcaSlicer\src\libslic3r\GCodeWriter.cpp][610]

7ffdb089fcb7:Slic3r::CalibPressureAdvance::move_to [D:\a\OrcaSlicer\OrcaSlicer\src\libslic3r\calib.cpp][10]

7ffdb08a56c5:Slic3r::CalibPressureAdvancePattern::generate_custom_gcodes [D:\a\OrcaSlicer\OrcaSlicer\src\libslic3r\calib.cpp][372]

7ffdb0db1410:Slic3r::GUI::Plater::reslice [D:\a\OrcaSlicer\OrcaSlicer\src\slic3r\GUI\Plater.cpp][10375]

7ffdb0de24a7:Slic3r::GUI::Plater::priv::on_action_slice_plate [D:\a\OrcaSlicer\OrcaSlicer\src\slic3r\GUI\Plater.cpp][6143]

7ffdb0e30a21:wxEventFunctorMethod<wxEventTypeTag<Slic3r::GUI::SimpleEvent>,Slic3r::GUI::Plater::priv,Slic3r::GUI::SimpleEvent,Slic3r::GUI::Plater::priv>::operator() [D:\a\OrcaSlicer\OrcaSlicer\deps\build\OrcaSlicer_dep\usr\local\include\wx\event.h][441]

Call SymGetLineFromAddr64 ,Address b2271db2 Error:000001e7

Call SymGetLineFromAddr64 ,Address b227096f Error:000001e7

Call SymGetLineFromAddr64 ,Address b2270d5a Error:000001e7

Call SymGetLineFromAddr64 ,Address b227100f Error:000001e7

Call SymGetLineFromAddr64 ,Address b227089b Error:000001e7

Call SymGetLineFromAddr64 ,Address b2270b5b Error:000001e7

Call SymGetLineFromAddr64 ,Address b227340b Error:000001e7

Call SymGetLineFromAddr64 ,Address b22b0d64 Error:000001e7

Call SymGetLineFromAddr64 ,Address b22b0fba Error:000001e7

Call SymGetLineFromAddr64 ,Address b2272d90 Error:000001e7

Call SymGetLineFromAddr64 ,Address b2276a27 Error:000001e7

Call SymGetLineFromAddr64 ,Address b22de558 Error:000001e7

7ffdb0d0f012:Slic3r::GUI::GUI_Run [D:\a\OrcaSlicer\OrcaSlicer\src\slic3r\GUI\GUI_Init.cpp][64]
```

**Comment by thewildmage** [comment]
> One more thing though, can you adjust two settings for the PA pattern test: turn off skirt and brim?
It causes troubles for small printers

Done!

**Comment by thewildmage** [comment]
> I managed to figure out the reproducing steps:
> 
>     1. Do PA Pattern test
> 
>     2. Do PA Line test
> 
>     3. Crash
>        Make sure to autually slice the print for each step

I can't seem to get these crashes to happen on my Mac, which is making them tricky to diagnose. Which type of computer are you seeing them on, @SoftFever?

**Comment by SoftFever** [comment]
> > I managed to figure out the reproducing steps:
> > ```
> > 1. Do PA Pattern test
> > 
> > 2. Do PA Line test
> > 
> > 3. Crash
> >    Make sure to autually slice the print for each step
> > ```
> 
> I can't seem to get these crashes to happen on my Mac, which is making them tricky to diagnose. Which type of computer are you seeing them on, @SoftFever?

Pls ignore the first crash as it is caused by another PR :)
The second crash I can't figure out the steps to reproduce it.
It's probably related multiple filament and switch to different machines back and forth.

**Comment by SoftFever** [comment]
Nevertheless, this PR did fix the stated issue so I will merge it.
Thanks for the quick fix 👍

**Review by SoftFever — APPROVED** [review]

**Pull request merged**
