### PR TITLE
Drop object on the plate

### PR DESCRIPTION
**Pull request by vovodroid**
Add "Drop" object menu, placing object (modifier or negative) on the plate:

image

image

As far as I remember there is FR for this, just can't find it now.

### CODE REVIEW

**Comment by Eldenroot** [comment]
cooool! thx!

**Comment by yw4z** [comment]
keyshot uses "snap to ground" term for this feature. maybe we can use a better term for "drop"

**Comment by vovodroid** [comment]
I used Prusa term:

image

**Review by SoftFever — APPROVED** [review]
Works like a charm 👍 
Thank you

**Pull request merged**
