### PR TITLE
Support settings overhaul

### LINKED ISSUE #5456: Snug Support Interface Type Incorrect
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.0.0

### Operating System (OS)

Windows

### OS Version

Windows 10

### Additional system information

_No response_

### Printer

LH Stinger

### How to reproduce

1. Select Snug Supports
2. Switch to **Rectilinear (default)** interface and observed that it's **Rectilinear Interlaced** instead.

2024_05_25_5587_orca-slicer

### Actual results

**Rectilinear** and **Rectilinear Interlaced** are **swapped**.

### Expected results

Support interface follows the one set in the menu

### Project file & Debug log uploads

[infill support  error.zip](https://github.com/SoftFever/OrcaSlicer/files/15443711/infill.support.error.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by kisslorand**
# Description

This PR:
- unifies the pattern naming used in the support settings to be aligned with the naming and style of the infill pattern ones
- fixes a support interface bug when snug support is used (#5456)

# Screenshots/Recordings/Graphs
---
### Before:
Support Base Pattern

### After
Support Base Pattern
---
### Before:
Support Interface Pattern

### After:
Support Interface Pattern
---

## Tests

  Compiled and tested in Win11.

## What does it fix
  Fixes #5456

---

### Notes

With this PR "Rectilinear Grid" and "Rectilinear Interlaced" becomes obsolete as they were supposed to do the same as the regular "Rectilinear" used in sparse infill. "Aligned Rectilinear" used in sparse infill is added to the support pattern list as this style was already present in the pattern style but under  the wrong name of "Rectilinear".

### CODE REVIEW

**Comment by kisslorand** [comment]
I am not sure what you mean because the example you gave is listed in those circumstances when it's applicable.

image

**Comment by cochcoder** [comment]
Strange, it doesn't show up in Linux (I'm using the flatpak): 
image

**Comment by kisslorand** [comment]
Try it by selecting the following:
 - Type: Tree(auto)
 - Style: Tree Strong

**Comment by cochcoder** [comment]
Now it shows up. Shouldn't that be available for all tree support options, or am I missing something?

**Comment by kisslorand** [comment]
No, it shouldn't.
There are settings that are available (usable/taken into account) only for particular support type and style.

**Comment by SoftFever** [comment]
Hi @kisslorand 
Thanks for the PR
Here are some suggestions and feedback:
1. Let's avoid including too many changes in one PR. It's preferable to have smaller, focused PRs that address specific issues or features.
2. Please add explanations for the changes you made, either in the code comments or in the PR description. For example, I noticed you replaced smpRectilinearGrid with smpAlignedRectilinear but there are no comments about why you made this change, which makes it difficult for code reviewing.
3. Avoid reformatting code that is not relevant to the PR. It becomes very challenging to review code when there are hundreds or thousands of changes due to reformatting. as you can see below:
image

These changes will help streamline the review process. Thank you!

**Comment by kisslorand** [comment]
@SoftFever
Thank you for your feedback, much appreciated!

> 1. Let's avoid including too many changes in one PR. It's preferable to have smaller, focused PRs that address specific issues or features.

I usually separate issues in a PR but somehow I felt unifying the pattern naming and the bugfix of snug support felt related to me.

> 2. Please add explanations for the changes you made, either in the code comments or in the PR description. For example, I noticed you replaced smpRectilinearGrid with smpAlignedRectilinear but there are no comments about why you made this change, which makes it difficult for code reviewing.

"smpRectilinearGrid" became obsolete so it was removed, "smpAlignedRectilinear" was missing and it was added. It might seem one replaced the other but it's not the case, one was removed as becoming obsolete and aother one was added as it was miising according to the whole purpose of this PR.

> 3. Avoid reformatting code that is not relevant to the PR. It becomes very challenging to review code when there are hundreds or thousands of changes due to reformatting. as you can see below:

I am sorry for that, I have a plugin that does that automatically. I had to install that plugin because working on another repository, some guys were so obsessed about the "right" formatting and the zero tolerance they have about white spaces.
I will try to disable that plugin in the future PRs for this repository.

**Comment by SoftFever** [comment]
> @SoftFever Thank you for your feedback, much appreciated!
> 
> > 1. Let's avoid including too many changes in one PR. It's preferable to have smaller, focused PRs that address specific issues or features.
> 
> I usually separate issues in a PR but somehow I felt unifying the pattern naming and the bugfix of snug support felt related to me.
> 
> > 2. Please add explanations for the changes you made, either in the code comments or in the PR description. For example, I noticed you replaced smpRectilinearGrid with smpAlignedRectilinear but there are no comments about why you made this change, which makes it difficult for code reviewing.
> 
> "smpRectilinearGrid" became obsolete so it was removed, "smpAlignedRectilinear" was missing and it was added. It might seem one replaced the other but it's not the case, one was removed as becoming obsolete and aother one was added as it was miising according to the whole purpose of this PR.
> 
> PR description updated with: "With this PR "Rectilinear Grid" and "Rectilinear Interlaced" becomes obsolete as they were supposed to do the same as the regular "Rectilinear" used in sparse infill. "Aligned Rectilinear" used in sparse infill is added to the support pattern list as this style was already present in the pattern style but under the wrong name of "Rectilinear"."
> 
> > 3. Avoid reformatting code that is not relevant to the PR. It becomes very challenging to review code when there are hundreds or thousands of changes due to reformatting. as you can see below:
> 
> I am sorry for that, I have a plugin that does that automatically. I had to install that plugin because working on another repository, some guys were so obsessed about the "right" formatting and the zero tolerance they have about white spaces. I will try to disable that plugin in the future PRs for this repository.

From the user's perspective, it is essentially the same thing, aside from the name changes. 
For the sake of consistency and user conventions, I am inclined to accept the change. 
Regarding the bug fix, I see that it is not addressed in this PR. The behavior is still swapped.

Again, thank you for trying to help. 👍

**Comment by kisslorand** [comment]
@SoftFever 

> Regarding the bug fix, I see that it is not addressed in this PR. The behavior is still swapped.

You most probably tested only commit [Fix interface for snug support](https://github.com/SoftFever/OrcaSlicer/pull/5565/commits/041eee91411f1420c217f9fcaca05d211ff79da7).

This commit is dependent on the previous one: [Unified pattern naming](https://github.com/SoftFever/OrcaSlicer/pull/5565/commits/92383bd8f21604ae8d939bde6aeae66fc1644991)

Let me illustrate that the bugfix is effective:

Check the naming of the `Sparse infill pattern` and for the snug support `Interface pattern`:

Snug Support Rectilinear Top Interface

Snug Support AlignedRectilinear Top Interface

Also pushed a commit to revert the whitespace cleaning so it's now more easy to check the changes made in this PR


@discip 

Would you be so kind to also test the fix of this PR for the #5456 bug?
Compiled binaries of this PR are here: https://github.com/SoftFever/OrcaSlicer/actions/runs/10071498019

**Comment by discip** [comment]
@kisslorand
I tested what you asked for and must say that the icons are now correct, but the terms **`Rectilinear`** & **`Rectilinear Interlaced`** do fit better.

So basically:
this PR || better suiting
-|-|-
`Rectilinear`|=>|**`Rectilinear Interlaced`** or **`Rectilinear Grid`**
`Aligned Rectilinear`|=>|**`Rectilinear`**

Also:
If you switch **`Style`** (in **`Support`**) from **`Snug`** to **`Default`** or **`Grid`** the last interface layer is always the opposite of what was set.

**Comment by kisslorand** [comment]
> Also:
> If you switch **`Style`** (in **`Support`**) from **`Snug`** to **`Default`** or **`Grid`** the last interface layer is always the opposite of what was set.

Thank you very much for your input. Something is definitely wrong, that behaviour depends whether you have 2 or 3 interface layers and whether you have 0 mm or higher "Top Z distance". This inconsistency is present also in the nightly build, so it is an inherited bug, I will look into it.

**Comment by discip** [comment]
> that behaviour depends whether you have 2 or 3 interface layers and whether you have 0 mm or higher "Top Z distance"

1. Regarding the **`Top Z distance`** you are right: Only the value **`0`** produces the right result everything above that, doesn't.

2. But the amount of the **`Top interface layers`** has no impact on that.
Try typing in e.g **`7`**.

**Comment by kisslorand** [comment]
Typing 7 in the "Top interface layers" doesn't make it a valid parameter. You can select only between 0, 1, 2 and 3. Even if you type 7 you will only have 3 interface layers. Try the difference between 2 and 3 "Top interface layers" in both Snug and Default mode and you'll see what I am talking about.

**Comment by discip** [comment]
> Typing 7 in the "Top interface layers" doesn't make it a valid parameter. You can select only between 0, 1, 2 and 3. Even if you type 7 you will only have 3 interface layers.

Are you on Mac OS?
As on Linux and Windows you can enter what ever value you want and exactly that amount of layers is used.

@igiannakas
Could you please check if you are able to enter values greater than **`3`** for **`Top interface layers`**? If I remember correctly, you are running a Mac, right?

**Comment by kisslorand** [comment]
> Are you on Mac OS?
> As on Linux and Windows you can enter what ever value you want and exactly that amount of layers is used.

I am on Windows and just trying again it is working just as you said. I do not know why it didn't accept 7 before. Regardless of this number, the bug is still there, the last layer orientation of the support interface is borked.

**Comment by discip** [comment]
> Typing 7 in the "Top interface layers" doesn't make it a valid parameter. You can select only between 0, 1, 2 and 3. Even if you type 7 you will only have 3 interface layers.

Are you on Mac OS?
As on Linux and Windows you can enter what ever value you want and exactly that amount of layers is used.

In fact, **`2`** in **`Top interface layers`** is quite similar to **`0`** in **`Top Z distance`**, since the result is identical for any value above **`2`**.

@igiannakas
Could you please check if you are able to enter values greater than **`3`** for **`Top interface layers`**? If I remember correctly, you are running a Mac, right?

**Pull request closed without merging**
