### PR TITLE
CR-10 SE Config

### PR DESCRIPTION
**Pull request by bkonosky**
# Description

Fixed the Start G-code issues.
Updated the Max Speed and Max Acceleration with info from Creality's slicer.
Put in the correct build volume for the printer (220x220x265)
Added in more system default layer heights for the printer 0.12, 0.16, 0.24 and used the profile from the Ender-3 V3 KE as a base, since that's the printer closest to the CR-10 SE.

# Screenshots/Recordings/Graphs

## Tests

Sliced some objects, looked at the resulting gcode to make sure there wasn't obvious issues. Then sent them to the printer.

### CODE REVIEW

**Comment by cochcoder** [comment]
@bkonosky Can you make a PR request for #4793 and remove this one? This would avoid any merge conflicts that we will most likely run into once one of our PRs gets merged.

**Comment by bkonosky** [comment]
> @bkonosky Can you make a PR request for #4793 and remove this one? This would avoid any merge conflicts that we will most likely run into once one of our PRs gets merged. 

I can remove this PR, would you mind including the bed temperature set gcode into the start gcode for the CR10SE into yours?

**Comment by cochcoder** [comment]
> > @bkonosky Can you make a PR request for #4793 and remove this one? This would avoid any merge conflicts that we will most likely run into once one of our PRs gets merged.
> 
> I can remove this PR, would you mind including the bed temperature set gcode into the start gcode for the CR10SE into yours?

Done!

**Comment by cochcoder** [comment]
@bkonosky Can you please add these changes to a PR request to for this [branch](https://github.com/cochcoder/OrcaSlicer/tree/profile-fixes)? So I can include them in #4793.

**Pull request closed without merging**
