### PR TITLE
Adds rotate on stl import

### PR DESCRIPTION
**Pull request by iitsalex**
Opened a new CR since I didn't have permissions to re-open my old one. Rebased to latest upstream/main.

Closes https://github.com/SoftFever/OrcaSlicer/issues/1412

Old CR here: https://github.com/SoftFever/OrcaSlicer/pull/1777

### CODE REVIEW

**Review by SoftFever — CHANGES_REQUESTED** [review]
Hi @iitsalex 

This triggers CI/CD errors.
We automatically update locale files by script.
So we don't need to modify this file manually.

**Comment by SoftFever** [comment]
@iitsalex 
Thank you for the PR. 
It looks good. Once the po file is fixed, we are ready to merge.

**Comment by iitsalex** [comment]
> Hi @iitsalex
> 
> This triggers CI/CD errors. We automatically update locale files by script. So we don't need to modify this file manually.

I'm not too familiar with how the translations are handled lately. Where should the english translations go?

**Comment by l-ejs-l** [comment]
hey @iitsalex ! i think the  `msgid "°"` you added in line 215/216 already existed in line 257? im not sure but that seems to be the error with the po file.

**Comment by iitsalex** [comment]
@l-ejs-l I'm mainly not sure how to update the po file via script. I don't see any apparent script to do so 🤔

**Comment by l-ejs-l** [comment]
> @l-ejs-l ~I'm mainly not sure how to update the po file via script. I don't see any apparent script to do so~ 🤔
> 
> EDIT: @SoftFever Should I just add the translations to the OrcaSlicer.pot file?

i think so, and there's a script called `run_gettext.sh` i think this one updates the .po files from the pot file.

**Comment by SoftFever** [comment]
> @l-ejs-l ~I'm mainly not sure how to update the po file via script. I don't see any apparent script to do so~ 🤔
> 
> EDIT: @SoftFever Should I just add the translations to the OrcaSlicer.pot file?

I typically run the run_gettext.sh/bat --full script periodically to automatically generate/update the .pot/.po files. This way, contributors don't have to worry about updating the translation files themselves. However, updating them in PRs is also fine and causes no harm, although hand written item may be overwritten

**Comment by SoftFever** [comment]
Merged.
Thank you very much for the contribution 👍

**Pull request merged**
