### PR TITLE
Infimech official patch 33

### PR DESCRIPTION
**Pull request by InfimechOfficial**

### CODE REVIEW

**Comment by InfimechOfficial** [comment]
If there are any mistakes in any file, please contact me.

**Comment by SoftFever** [comment]
> If there are any mistakes in any file, please contact me.

Can you take a look at those conflicts?

**Comment by InfimechOfficial** [comment]
I submitted the profiles in a wrong way and now there are conflicts, what should I do?

**Comment by SoftFever** [comment]
> I submitted the profiles in a wrong way and now there are conflicts, what should I do?

Probably the easiest way is to start over with your changes applied to the latest [main](https://github.com/SoftFever/OrcaSlicer/tree/main) branch.

**Comment by SoftFever** [comment]
Feel free to re-open it when it's ready.

**Pull request closed without merging**
