### PR TITLE
Revert "Take filament flow ratio into account when displaying flow in gcode legend"

### PR DESCRIPTION
**Pull request by igiannakas**
Proposing to revert this change as explained here: https://github.com/SoftFever/OrcaSlicer/pull/5628#issuecomment-2298536914

Fixes: https://github.com/SoftFever/OrcaSlicer/issues/6478

### CODE REVIEW

**Comment by SoftFever** [comment]
Hmm, that's strange.
Yeah, I can reproduce it.

**Review by SoftFever — APPROVED** [review]
Thanks

**Comment by igiannakas** [comment]
No worries! Indeed it is strange this..

**Comment by ShantanuNair** [comment]
@igiannakas @SoftFever Sorry for the continuous tags, but could this be because print_flow_ratio is only what the speed cap considers
https://github.com/SoftFever/OrcaSlicer/blob/70931e5321fa66966a5bfb251efca0e82307d427/src/libslic3r/GCode.cpp#L5318-L5324
Here, _mm3_per_mm is only multiplied by print_flow_ratio. Only print_flow_ratios serves to impact the speedcap. This is why we see multiple reports of people saying they're getting flow rates beyond max volumetric speed (filament_flow_rate) - because there, they are actually setting the value which intends to be a corrective factor on the amount of plastic the hotend gets, and so by design apparently, since slic3r, doesn't impact speed capping. This is surprising for users because most users if setting a flow rate > 1, expect the volumetric speed limit to be applied to it, since they are intentionally pushing more plastic, and it's not a calibration step to get the extruder to account for slippage or filament diameter being off. Also, this means that once they've set the flow ratio with the expectation of more plastic flowing through it intentionally, the slicer thinks it's just performing a correction and so speed isn't capped according to it, resulting in a _lower_ speed (since it's not also divided by the >1 filament_flow ratio). But the extrusion per mm has taken this into filament flow ratio into account! Causing it to try and extrude the same amount but at a lower speed. Thus causing a higher flow rate. It is a fundamental bug imo.

Lmk if that's making sense, or if I got it all wrong:)

**Comment by ShantanuNair** [comment]
I looked into this and it's clear why this didn't work. The core issue is double counting filament ratio in the post‐processing code. By default, GCodeProcessor interprets the final G‐code’s E values (i.e., how many millimeters of filament are fed) and multiplies by the filament’s cross‐section to calculate volumetric flow. This is already capturing spool ratio’s effect if spool ratio is baked into the G‐code’s E steps.

When you added filament ratio again in GCodeProcessor, it effectively multiplied spool ratio twice – causing the “quadratically higher” or “inflated” flow values in the preview. That’s why users saw unexpected numbers, and the revert was done to remove the extra filament ratio factor and restore consistency.

**Comment by igiannakas** [comment]
Correct. This is as I mentioned here: https://github.com/SoftFever/OrcaSlicer/issues/9261#issuecomment-2792062277

gcode preview calculates the flow rate based on the real gcode movements.

**Pull request merged**
