### PR TITLE
Reworked splash screen

### PR DESCRIPTION
**Pull request by yw4z**
• Designed a custom build font for Orca Slicer logo
• Used svg image with full resolution that fills to splash screen. This will makes easier adding badge or applying custom designs for special days, events or releases 
• Improved visibility of logo on dark mode splash screen
• Also fonts not scaled with monitor scale on original code. Didn't tested on 4K monitor but that should create difference.
• Set all font sizes and start points with ratios so it should render on all resolutions. Tested on 1080p and 2k monitor with different scaling settings
• Removed "V" from version to reduce clutter

### DARK MODE
| Before | After |
|---|---|
| Screenshot-20240503235916  | Screenshot-20240504001031 |

### LIGHT MODE
| Before | After |
|---|---|
| Screenshot-20240503235958  | Screenshot-20240504000956 |

### CODE REVIEW

**Comment by SoftFever** [comment]
Looks awesome!
Though, for the icon could you use the one used in about dialog?
Screenshot 2024-05-05 at 7 09 47 PM

**Comment by yw4z** [comment]
@SoftFever are you sure? that font not looks modern

also i will send a separate commit for about page
Screenshot-20240505153620

**Comment by discip** [comment]
@yw4z
I also prefer @SoftFever 's choice.

**Comment by Ocraftyone** [comment]
+1 for @yw4z

**Comment by KrisMorr** [comment]
I'll stand somewhere in the middle. In my opinion, the font style is too modern compared to the entire Orca interface. The concept of the new logo is very good, but I would consider a font that fits better with the overall design.

**Comment by discip** [comment]
What I like about the original font is the heft it embodies, which makes it relatable to an Orca. (never seen a skinny one)

Also, the outline, if used correctly, lets it have a neatly clean touch.

@jeremytodd1
You are right about the implementation of the border not being up to the task.

What about using this font by Marc Lohner: **[Arlon](https://www.fontbros.com/font-family/arlon)**.

However, this is not a free font.
I have no idea how this could be handled correctly.

Here is a brief demo: (obviously I used 2 different weights)

image

**Comment by Ocraftyone** [comment]
> I'll stand somewhere in the middle. In my opinion, the font style is too modern compared to the entire Orca interface. The concept of the new logo is very good, but I would consider a font that fits better with the overall design.

@yw4z is currently doing a lot to overhaul the UI to modernize it. With the other updates, this new font should fit better

**Comment by discip** [comment]
What I like about the original font is the heft it embodies, which makes it relatable to an Orca. (never seen a skinny one)

Also, the outline, if used correctly, lets it have a neatly clean touch.

@jeremytodd1
You are right about the implementation of the border not being up to the task.

What about using this font by Marc Lohner: **[Arlon](https://www.fontbros.com/font-family/arlon)**.

However, this is not a free font.
I have no idea how this could be handled correctly.

Here is a brief demo:

image
_Obviously 2 different weights were used: (**Black** & **Medium**)_

**Comment by SoftFever** [comment]
> I'll stand somewhere in the middle. In my opinion, the font style is too modern compared to the entire Orca interface. The concept of the new logo is very good, but I would consider a font that fits better with the overall design.

This is exactly my thought!
The font itself is super cool, but somehow I feel it didn't match Orca's overall style(feeling?)

**Comment by yw4z** [comment]
what you guys think something about like this?
• much more bolder, blocky
• not fully rounded
needs more work on proportions but this will an idea

Screenshot-20240509182601

**Comment by discip** [comment]
The one on the right looks much better compared to the previous one!

**Comment by ramorimdias** [comment]
great job, I agreed that the splash screen could use some fresh look! 
I also prefer the right one! 

As for the icon itself, I found it weird the app icon with a circle and the splash with a square...

**Comment by SoftFever** [comment]
Haha, seems everyone prefer @yw4z design.
Let's give it a try!

**Review by SoftFever — APPROVED** [review]

**Comment by yw4z** [comment]
@SoftFever i'm planning to update all icons if everyone agrees on this
• Taskbar icon (planning to use rounded rectangle on all of that)
• Home page logo (just logo with rounded rectangle background)
• About page (shared this in this commit)
• Logo usages on calibration models (orca text on orca cube and string hell)

**Comment by SoftFever** [comment]
> @SoftFever i'm planning to update all icons if everyone agrees on this • Taskbar icon (planning to use rounded rectangle on all of that) • Home page logo (just logo with rounded rectangle background) • About page (shared this in this commit) • Logo usages on calibration models (orca text on orca cube and string hell)

Noooo, please keep them

**Comment by yw4z** [comment]
@SoftFever what about consistency :) did you say it for calibration models or all suggestions

**Pull request merged**
