### PR TITLE
Italian translation update

### PR DESCRIPTION
**Pull request by FabioForcina**
updating of new terminologies

### CODE REVIEW

**Comment by SoftFever** [comment]
@FabioForcina 
Can you take a look at the following errors?
```
 ./localization/i18n/it/OrcaSlicer_it.po:8709: 'msgid' and 'msgstr' entries do not both end with '\n'
./localization/i18n/it/OrcaSlicer_it.po:9161: 'msgstr' is not a valid C format string, unlike 'msgid'. Reason: In the directive number 1, the character 'r' is not a valid conversion specifier.
```

**Comment by FabioForcina** [comment]
HI ,

I solved the first problem.

For the second problem it depends on the percentage symbol on the 9159 row that translating the word "100% turns" into Italian does not find the first two letters "tu"
And therefore it generates that error, I propose this change that seems to be missed, I am attaching the file here, putting 100% in brackets (100%) so it no longer creates this error, otherwise I don't know what to do more, I have done many tests And this is unique that should not give problems
[OrcaSlicer_it.zip](https://github.com/SoftFever/OrcaSlicer/files/13715959/OrcaSlicer_it.zip)

**Comment by SoftFever** [comment]
> HI ,
> 
> I solved the first problem.
> 
> For the second problem it depends on the percentage symbol on the 9159 row that translating the word "100% turns" into Italian does not find the first two letters "tu" And therefore it generates that error, I propose this change that seems to be missed, I am attaching the file here, putting 100% in brackets (100%) so it no longer creates this error, otherwise I don't know what to do more, I have done many tests And this is unique that should not give problems [OrcaSlicer_it.zip](https://github.com/SoftFever/OrcaSlicer/files/13715959/OrcaSlicer_it.zip)

Hehehe, the app incorrectly think it's a "C format" string hence the error.
I have fixed them.
Let me know whether it look okay for you.

**Comment by FabioForcina** [comment]
> Hehehe, the app incorrectly think it's a "C format" string hence the error. I have fixed them. Let me know whether it look okay for you.

Excellent, we managed to understand the mistake .. however congratulations for the work you do

**Review by SoftFever — APPROVED** [review]

**Pull request merged**
