### PR TITLE
keep gettext happy

### PR DESCRIPTION
**Pull request by henrivdr**
@SoftFever here's the final commit which sorts out the gettext issues.
There were 3 msgids which caused it to move the strings to the comment section.
It also did a bunch of line splits.

It was intended to go in before your last translations commit.
Not sure if you can still merge it in. see my comment in #6673

### CODE REVIEW

**Review by SoftFever — COMMENTED** [review]
Thanks @henrivdr
I should have fixed all of the remaining issues after merging the previous PR.
Do you notice more strings to fix?

**Comment by henrivdr** [comment]
Yea, I'm stressed out about the deletions , and move to comments, done by gettext in your translations commit.
https://github.com/SoftFever/OrcaSlicer/commit/4de618ad1fa48f61788bdbb4bcbcef20852497ff.
I recall 3 of them which I had to fix.

Can you revert yours, then do this one, and then your's again?

**Comment by SoftFever** [comment]
I lost here.
I don't any need to be fixed now?
All the changes here are just line break positions

**Comment by henrivdr** [comment]
Ok, so then the deletions introduced in  https://github.com/SoftFever/OrcaSlicer/commit/4de618ad1fa48f61788bdbb4bcbcef20852497ff are not due to my missed commit.

Screenshot_2024-09-11-08-21-49-269

**Comment by SoftFever** [comment]
They are not.
They legit text changes

**Pull request closed without merging**
