### PR TITLE
Config changes for Creality K1/K1 Max

### PR DESCRIPTION
**Pull request by bistory**
Hi,
I'm using K1/K1 Max profiles since the release of 1.7.0. However, I saw some issues and some missing configurations in them.
That's why I commit updated configurations : 

- I cleaned up them a bit
- I added missing parameters
- Enabled auxiliary fan
- Changed nozzle type (For K1 only : default is brass, not hardened steel)
- I created new filaments types for high flow hotends from Creality to fix the flow parameter slowing down the printer

I will continue to improve the profiles in other PR when I will make other tests/calibrations.

Thanks !

### CODE REVIEW

**Review by SoftFever — CHANGES_REQUESTED** [review]

**Comment by SoftFever** [comment]
@bistory 
Thank you for the PR.
I have some comments, can you take a look?

**Comment by SoftFever** [comment]
> > @bistory Thank you for the PR. I have some comments, can you take a look?
> 
> Thanks, I understand your suggestions, however I have a problem with the previous profiles that have been submitted : they didnt't take into account the flow of the new hotends and this problem will continue with the new Ender 3 printers which arrives with higher flow hotends :-) Is there a way to keep the original profiles but change the flow for certain printers ?

Hi,
The existing generic filaments are meant for nomal normal flow hotend.
We should not rename/delete them as users have already create custom profile based them.

> Is there a way to keep the original profiles but change the flow for certain printers ?

The suggest way is to create new filament profile as you already did.
Something like `Creality Generic ABS HF`

**Comment by bistory** [comment]
> > > @bistory Thank you for the PR. I have some comments, can you take a look?
> > 
> > 
> > Thanks, I understand your suggestions, however I have a problem with the previous profiles that have been submitted : they didnt't take into account the flow of the new hotends and this problem will continue with the new Ender 3 printers which arrives with higher flow hotends :-) Is there a way to keep the original profiles but change the flow for certain printers ?
> 
> Hi, The existing generic filaments are meant for nomal normal flow hotend. We should not rename/delete them as users have already create custom profile based them.
> 
> > Is there a way to keep the original profiles but change the flow for certain printers ?
> 
> The suggest way is to create new filament profile as you already did. Something like `Creality Generic ABS HF`

Ok then, I will do that, however it will be confusing for people creating new profiles...

**Comment by bistory** [comment]
Now it should be OK, I reverted filaments changes, renamed new profiles to "HF" and fixed an issue you pointed 👍

**Review by SoftFever — APPROVED** [review]

**Comment by SoftFever** [comment]
LGTM
Thank you

**Comment by ThomasArb** [comment]
@bistory It may be cool to add the thumbnail sizes that the printer use to display the preview : "96x96" and "300x300". I don't know if it is possible or not in the default profile.

**Pull request merged**
