### PR TITLE
Changing the background color of the thumbnail

### PR DESCRIPTION
**Pull request by KrisMorr**
After fixing the rendering some time ago, it looks like you can go back to a dark background for the thumbnail.

thumbnail_new

For comparison, here's how it looked in version 1.8

thumbnail_old_v1 8

### CODE REVIEW

**Comment by Eldenroot** [comment]
Nice!

**Comment by SoftFever** [comment]
Will it causing opposite issues when we are not using dark theme?

**Comment by KrisMorr** [comment]
@SoftFever 
It seems that this .svg is only used in dark mode

thumbnail_new_w

**Review by SoftFever — APPROVED** [review]
Very nice.
Thank you!

**Comment by KrisMorr** [comment]
@yw4z 

This is the window that will appear after selecting the BambuLab printer and Print plate

**Comment by yw4z** [comment]
@KrisMorr thanks

**Pull request merged**
