### PR TITLE
Color fixes

### PR DESCRIPTION
**Pull request by yw4z**
this commit is part 2 for color fixes. part 1 was https://github.com/SoftFever/OrcaSlicer/pull/5239

### Dark mode support for sliced plates list > plate number
problem: text is hard to read on light theme

before vs after
Screenshot-20240615095443

### Flushing volumes button active state background color
left over green color from bamboo studio

before vs after
Screenshot-20240615095007

### Sidebar tab button background color on light theme
left over green color from bamboo studio. visible on bbl monitor & calibration tab and project tab

before vs after
Screenshot-20240615095630

### Sidebar arrow not visible
Before
Screenshot-20240618185703

After
Screenshot-20240618185732

### Home page
Selected tab color on light theme
Screenshot-20240615100836

Button hover background on light theme
Screenshot-20240615100838

Context menu item hover background on light theme
Screenshot-20240615101808

Darker background for thumbnail images on dark mode
before makes you blind :)
Screenshot-20240618184512

after
Screenshot-20240618184415

Also matched colors for dark theme

### Sidebar parameters group Title too bright on dark theme
Uses same color with tab text color
Screenshot-20240615110456

### Sidebar > Global > Search > Dropdown list > hovered item color
Screenshot-20240615112059

### Sidebar > Global > Search > Match border color with other input/combo boxes
improves visibility of border
Screenshot-20240615115205

### Added descriptions to state colors
Still its mess but better than without any descriptions
Screenshot-20240615123956

### Paint gizmos > remove background of non active Tool / Brush buttons on dark mode
buttons has no background on light mode. and readability improves without background
before
Screenshot-20240615132916
after
Screenshot-20240615132550

### Gizmos selected text background
before
Screenshot-20240618140327
Screenshot-20240618140338
after
Screenshot-20240618140318
Screenshot-20240618140348

### Keyboard shortcuts window selected tab background color
before
Screenshot-20240618141354

after
Screenshot-20240618141345

### About page > link color
before
Screenshot-20240618142829

after
Screenshot-20240618142846

### Project page > Add button
| Before | After |
|---|---|
| Screenshot-20240618154058 | Screenshot-20240618154027 |

### Project page > Return button text
before
Screenshot-20240618154154
after
Screenshot-20240618155335

### Match disabled text color of combo boxes with other input boxes while disabled state
before
Screenshot-20240618165156
after
Screenshot-20240618165204

also this makes  add printer window > combo boxes disabled text a bit more visible
Screenshot-20240618173706
Screenshot-20240618173658

### Use better background color for disabled elements on dark mode
old color has a different tone compared to panel background. also not fits well imo
old vs new
Screenshot-20240618165808

### BBL > Monitor tab > Add printer text and icon not visible on dark theme
before
Screenshot-20240618160043
after
Screenshot-20240618182453

### Better background color for row highlighting on dark theme
NOTE: color not changes while switching themes. its an existing bug
used same color on sidebar titlebar background. it creates enough separation
before
Screenshot-20240620080433
after
Screenshot-20240620080416

### Match style of gizmo combo boxes with regular combo box
target style
Screenshot-20240620083441
before
Screenshot-20240620083357
after
Screenshot-20240620083237

### Fixed broken color changes with latest merges
Selected tab underline color
Screenshot-20240618134237

### CODE REVIEW

**Comment by Eldenroot** [comment]
Please check my tickets for ui

**Comment by yw4z** [comment]
@Eldenroot from where? can you link it

**Comment by olcayoren** [comment]
@yw4z 
Hello, did you change the color of the writings on the license plate? thnx
Ekran Resmi 2024-06-15 21 58 32

**Comment by yw4z** [comment]
@olcayoren yes i did it in previous color fixes PR but softfever requested to revert back that change

**Comment by Eldenroot** [comment]
Would be great to transfer all unmerged changes and fixes -> and merge them¨. Thank you!

**Comment by olcayoren** [comment]
> @yw4z Hello, did you change the color of the writings on the license plate? thnx Ekran Resmi 2024-06-15 21 58 32

@SoftFever Hello, did it matter if the color remained orange? thnx

**Comment by yw4z** [comment]
@Eldenroot we are goin with baby steps instead making major changes as we discussed with @SoftFever . dont worry they are on my list. but i will try these changes with less code changes this time

@olcayoren @SoftFever here is removed things from that commit. Softfever wanted to use a secondary colors on these screens because he pointed many things started to use same colors and that made things hard to pick. Decided to keeping orange color as secondary color will make things easier to pick then we didnt touched that areas

Screenshot-20240617094309
Screenshot-20240617094415

I'm ok with this logic. only yellow code on gcode viewer is a bit too much for me :)

**Comment by SoftFever** [comment]
yeah, it's less dull with accent color there ;)

**Comment by SoftFever** [comment]
Thank you @yw4z 
Here are my feedback:
1. 
  image
  It definitely looks better. Have you tried with 3mf project as well? I worry we will have a mixed color bg.
image

2. 
image
It would be better to use a lighter color for hover effect

**Comment by yw4z** [comment]
@SoftFever
1- yes 3mf thumbnails uses transparent background. so there is no problem
Screenshot-20240629072525

2- i will recheck color for that and will revert that change if i cant find a better suggestion

**Comment by kylek29** [comment]
Not sure if you got these, but here's a few more I've noticed:

- Device -> "Status" View -> Calibration:
image

- Device -> "MicroSD" View -> Upper Right:
image

- Device -> "Update" View -> About Printer:
image

- Device -> Upper Left Printer Selector:
image

**Comment by yw4z** [comment]
@kylek29 thanks for reporting. problem is i don't have a BBL printer so i can't access all BBL related UI and can't confirm my code changes correctly applied. I'm not sure is there a method for creating virtual / dummy device

**Comment by yw4z** [comment]
@SoftFever i reverted color change for main tab bar hovered item background color as you requested and converted this commit to ready state. i will look again for that in new color fixes commit. will open new commit when when my list has 10+ items. didnt add new items to this commit because you already checked this one.

**Pull request merged**
