### PR TITLE
Fix start_gcode and 0.16mm parameters

### PR DESCRIPTION
**Pull request by FlyingbearOfficial**

### CODE REVIEW

**Comment by FlyingbearOfficial** [comment]
Hi, I updated some parameters, and checked the conflicts by tool, but I have not noticed any error messages, help me please.Thank you

**Comment by SoftFever** [comment]
> Hi, I updated some parameters, and checked the conflicts by tool, but I have not noticed any error messages, help me please.Thank you

Hi, thanks for the PR.
Can you take a look and solve the conflicts?
image

**Comment by FlyingbearOfficial** [comment]
> > Hi, I updated some parameters, and checked the conflicts by tool, but I have not noticed any error messages, help me please.Thank you
> 
> Hi, thanks for the PR. Can you take a look and solve the conflicts? image

Hello, I noticed that there is a conflicts in the prompts, but I have no idea what the cause of the conflict is, I just changed some very basic parameters!Could you please help me to figure out the reason?

**Comment by FlyingbearOfficial** [comment]
Hi, I am trying to solving this conflict

**Pull request closed without merging**
