### PR TITLE
Prusa MINIIS Profiles, changed to Pressure Advance UI settings, better processes for different nozzle sizes

### PR DESCRIPTION
**Pull request by koppensb**
# Description
**Filament Profiles**
Changed the Pressure Advance settings from custom filament g-code to the more obvious Orcaslicer UI settings. 
That requiried the use of filament profiles for every nozzle size. 

https://github.com/SoftFever/OrcaSlicer/issues/5056#issuecomment-2088907590

Changed cooling settings of the filament profiles for better cooling especially on short layer times.

**Processes**
Changed the speed settings of the different process for different nozzle sizes.

## Tests
As always settings got tested with a bunch of Benchys an Cali-Dragons.

### CODE REVIEW

**Comment by SoftFever** [comment]
Thanks @koppensb 
Seems it's not working as expected, I check the general ABS for 0.25 mm nozzle, as you can see the setting is not there
image

**Comment by koppensb** [comment]
@SoftFever Maybe you have some old version of the filament files, or I did something wrong with the pull. When I look at the settings within Orca I get the following.
ABS_0 25_nozzle

**Comment by koppensb** [comment]
@SoftFever Now I see your error. You selected the wrong Prusa Mini. You have to use the MINIIS not the Mini. I exclusively do changes for the Mini with Input Shaping with firmware version 5 and up.

**Review by SoftFever — APPROVED** [review]
Looks good

**Comment by discip** [comment]
@koppensb
@SoftFever
Despite being able to select the corresponding printer, it does not show up in the dropdown.

image

image

**Comment by discip** [comment]
@koppensb
@SoftFever

Despite being able to select the corresponding printer, it does not show up in the dropdown.

OS: Windows 10

image

image

**Comment by koppensb** [comment]
@discip Did you download the latest Nightly Build? I downloaded it for Mac since I have no Windows PC available right now and everything seems to work correctly.

**Comment by discip** [comment]
> Did you download the latest Nightly Build?

Yes I did.

**Comment by koppensb** [comment]
I installed the Nightly Build on a Windows VM and it works there too. So I would suggest the error is somewhere on your side.

**Comment by SoftFever** [comment]
> @koppensb
> 
> @SoftFever
> 
> 
> 
> Despite being able to select the corresponding printer, it does not show up in the dropdown.
> 
> 
> 
> OS: Windows 10
> 
> 
> 
> image
> 
> 
> 
> image
> 
> 

Can you delete the system folder under %roaming%/OrcaSlicer/system then try again?

**Comment by discip** [comment]
@SoftFever
## Thank you! 👍 That worked instantly!

**Pull request merged**
