### PR TITLE
Update Flashforge Printer Profiles for Guider3 Ultra 0320

### PR DESCRIPTION
**Pull request by FlashforgeOfficial**
Hi @SoftFever,

This is to restart a PR for Flashforge Printer Profiles for Guider3 Ultra. 
Below is the basic changes in the git bash window for a quick check:

$ git commit -m"Update Printer Profiles for Guider3 Ultra 0320"
[main 4ccefc7bc] Update Printer Profiles for Guider3 Ultra 0320
 23 files changed, 4407 insertions(+), 3 deletions(-)
 create mode 100644 resources/profiles/Flashforge/Flashforge Guider 3 Ultra_cover.png
 create mode 100644 resources/profiles/Flashforge/filament/Flashforge Generic ABS @G3U.json
 create mode 100644 resources/profiles/Flashforge/filament/Flashforge Generic ASA @G3U.json
 create mode 100644 resources/profiles/Flashforge/filament/Flashforge Generic HIPS.json
 create mode 100644 resources/profiles/Flashforge/filament/Flashforge Generic PETG @G3U.json
 create mode 100644 resources/profiles/Flashforge/filament/Flashforge Generic PETG-CF @G3U.json
 create mode 100644 resources/profiles/Flashforge/filament/Flashforge Generic PLA @G3U.json
 create mode 100644 resources/profiles/Flashforge/filament/Flashforge Generic PLA-CF @G3U.json
 create mode 100644 resources/profiles/Flashforge/filament/Flashforge Generic PVA.json
 create mode 100644 resources/profiles/Flashforge/filament/FusRock Generic NexPA-CF25.json
 create mode 100644 resources/profiles/Flashforge/filament/FusRock Generic PAHT-CF.json
 create mode 100644 resources/profiles/Flashforge/filament/FusRock Generic PET-CF.json
 create mode 100644 resources/profiles/Flashforge/filament/FusRock Generic S-Multi.json
 create mode 100644 resources/profiles/Flashforge/filament/FusRock Generic S-PAHT.json
 create mode 100644 resources/profiles/Flashforge/filament/Polymaker Generic CoPA.json
 create mode 100644 resources/profiles/Flashforge/filament/Polymaker Generic S1.json
 create mode 100644 resources/profiles/Flashforge/flashfoge_g3u_buildplate_model.STL
 create mode 100644 resources/profiles/Flashforge/flashforge_g3u_buildplate_texture.png
 create mode 100644 resources/profiles/Flashforge/machine/Flashforge Guider 3 Ultra 0.4 Nozzle.json
 create mode 100644 resources/profiles/Flashforge/machine/Flashforge Guider 3 Ultra.json
 create mode 100644 resources/profiles/Flashforge/machine/fdm_guider3_common.json
 create mode 100644 resources/profiles/Flashforge/process/0.20mm Standard @Flashforge G3U 0.4 Nozzle.json

Thanks! Let me know if there is any questions!

### CODE REVIEW

**Review by SoftFever — APPROVED** [review]
Looks good.
Thanks

**Comment by FlashforgeOfficial** [comment]
> Please help verify if the profile works as expected in the nightly build
Just did a quick test with these profiles to run with the Nightly Build portable version. The new profiles can also work as expected.  Thanks for the reminder and help!

**Comment by FlashforgeOfficial** [comment]
Just re-checked the profiles for G3U. Here is some error in the when loading a model in preview. Earlier I tried to put the profile in 1.9.1 and I didn't encounter this.  

g3u preview issue

G3U is a model with dual extruder. We saw the same issues on the dual extruder model from Raise3D in Orca 2.0 beta： 
raise3d preview issue

@SoftFever. Could it possibly be minor issue somewhere related to the 2.0 beta update? 
I am also doing more check on the profiles. 

Thanks!

**Comment by SoftFever** [comment]
> Just re-checked the profiles for G3U. Here is some error in the when loading a model in preview. Earlier I tried to put the profile in 1.9.1 and I didn't encounter this.
> 
> g3u preview issue
> 
> G3U is a model with dual extruder. We saw the same issues on the dual extruder model from Raise3D in Orca 2.0 beta： raise3d preview issue
> 
> @SoftFever. Could it possibly be minor issue somewhere related to the 2.0 beta update? I am also doing more check on the profiles.
> 
> Thanks!

The error message is about missing "G92 E0" in "Before layer change g-code"
image

This line of gcode is required when relative extrusion is used.

I'm doing the versioning work for 2.0 RC release, so I have updated your printer profile to fix this issue. 
The fix will be available in nightly build soon, please refer to this change:
https://github.com/SoftFever/OrcaSlicer/commit/19cde6989d0dc92cbe7448b5eef889a91c6ef8dd#diff-12bd387657eea2ac3f4ce28af7f66287e775a0d1a7a580208756fc3efdcca2f6

**Comment by FlashforgeOfficial** [comment]
> > Just re-checked the profiles for G3U. Here is some error in the when loading a model in preview. Earlier I tried to put the profile in 1.9.1 and I didn't encounter this.
> > g3u preview issue
> > G3U is a model with dual extruder. We saw the same issues on the dual extruder model from Raise3D in Orca 2.0 beta： raise3d preview issue
> > @SoftFever. Could it possibly be minor issue somewhere related to the 2.0 beta update? I am also doing more check on the profiles.
> > Thanks!
> 
> The error message is about missing "G92 E0" in "Before layer change g-code" image
> 
> This line of gcode is required when relative extrusion is used.
> 
> I'm doing the versioning work for 2.0 RC release, so I have updated your printer profile to fix this issue. The fix will be available in nightly build soon, please refer to this change: [19cde69#diff-12bd387657eea2ac3f4ce28af7f66287e775a0d1a7a580208756fc3efdcca2f6](https://github.com/SoftFever/OrcaSlicer/commit/19cde6989d0dc92cbe7448b5eef889a91c6ef8dd#diff-12bd387657eea2ac3f4ce28af7f66287e775a0d1a7a580208756fc3efdcca2f6) 


Cool, thank!

**Pull request merged**
