### PR TITLE
Small change on Toolbar order

### PR DESCRIPTION
**Pull request by yw4z**
Moved Emboss icon to next of Color paint
Currently Emboss placed between paint functions

@Noisyfox pointed reordering of all toolbar buttons requires major changes on code. so this small change will give a nice improvement for now

@Noisyfox guided which lines to change. i'm not experienced on C or rebuilding from source. not sure this commit has any problems

Here is current status how they look with new icons. wanted to group paint functions
Screenshot-20240319162607

### CODE REVIEW

**Review by Noisyfox — APPROVED** [review]
LGTM

**Review by SoftFever — APPROVED** [review]
Makes sense to me
Thank you both!

**Comment by yw4z** [comment]
@Noisyfox @SoftFever is this change work as expected? emboss not opening on my design branch

**Comment by Noisyfox** [comment]
image
Master build works fine.

**Comment by yw4z** [comment]
@Noisyfox after making a change on GLGizmoEmboss.cpp it fixed itself without reason. i guess it was related with visual studio quirks

**Pull request merged**
