### PR TITLE
Update the Sovol profiles to what Sovol provides themselves

### LINKED ISSUE #5310: Include Sovol SV08 printer profile
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

Sovol just released the profiles for their new SV08 printer: https://wiki.sovol3d.com/en/SV08 - Their instructions state that these files should be copied over to `resources/profiles`, but that is just not possible with the AppImage on Linux (unless you extract the image and launch the application always from there outside of the AppImage binary). Would it be possible to include these new profiles in OrcaSlicer? Then we wouldn't have to resort to workarounds. :slightly_smiling_face: 

### Which printers will be beneficial to this feature?

Klipper

### Describe the solution you'd like

Include the profiles for the SV08.

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by cochcoder**
Closes #5310

The only difference from what Sovol provides [here](https://drive.google.com/drive/folders/1KWjLxwpO_9_Xqi_f6qu84HRxZi26a_GN), is the version number change in Sovol.json being reverted and changing the sparse infill pattern to crosshatch.

### CODE REVIEW

**Review by SoftFever — APPROVED** [review]
LGTM
Thank you

**Comment by Nukle0n** [comment]
Trying to add Sovol SV08 presets to the list, it doesn't show up, even though it's ticked.

**Comment by cochcoder** [comment]
@Nukle0n have you tried restarting Orca Slicer? There is a bug where profiles will sometimes not show up until Orca Slicer is restarted.

**Comment by Nukle0n** [comment]
> @Nukle0n have you tried restarting Orca Slicer? There is a bug where profiles will sometimes not show up until Orca Slicer is restarted.

Tried, still doesn't show up.

**Comment by Nukle0n** [comment]
> Are you on Windows and did you use the installer for Orca Slicer? If you did try the [portable version](https://github.com/SoftFever/OrcaSlicer/actions/runs/9351297265/artifacts/1562995307), if that works, you'll need to clear your cache for it to work on the installed version.

I am on windows and am using the installer, I tried the portable version but it still appears to hook into my configurations, so it's not really portable in that respect, unless you need to set some launch variable to run it portable?

I'm not sure how you clear the cache, I'll try to look but please tell if you know a way to do so without deleting all my other configuration.

**Comment by cochcoder** [comment]
You'll need to delete `/Users/<your_user_name>/Library/Application Support/OrcaSlicer/system`, **DO NOTE** that this will most likely delete any custom configs you made, make sure to export/save these configs in a safe place before you do this.

**Comment by Nukle0n** [comment]
Ok i found the Orcaslicer folder in appdata/roaming and renamed the system folder because it had some sovol related files in there and after starting it up again the SV08 show up. My custom profiles are still there, they appear to be in the "User" folder

**Comment by Nukle0n** [comment]
But also even though I only have the 0.4 nozzle selected, all 4 nozzle sizes are now showing up in the menu.

**Comment by cochcoder** [comment]
> But also even though I only have the 0.4 nozzle selected, all 4 nozzle sizes are now showing up in the menu.

I'll look into it as soon as I can

**Comment by cochcoder** [comment]
I found the issue and now have #5615 to fix this, thanks for finding this bug!

**Pull request merged**
