### PR TITLE
Russian translation for OrcaSlicer V1.6.4

### PR DESCRIPTION
**Pull request by AndylgTom**
**Normal russian translation for OrcaSlicer V1.6.4**
Please replace the existing translation with my translation.

Advantages of this translation:
-A **normal** translation based on the Prusa slicer translation (the translation of which I have been supporting for a long time). The translation that is used now (by user stasyan68 ) is crude, there are a lot of errors and typos (roughly speaking promt, with minimal edits, which will be in this case very, very much). 
-Added missing lines

I also made a pull request for this translation for Bambu Studio (with small edits and add lines)

### CODE REVIEW

**Comment by SoftFever** [comment]
Thank you @AndylgTom 
Glad to have you here to help Russian lang users.

For the PR,  OrcaSlicer put Russian .po file in `localization\i18n\ru\OrcaSlicer_ru.po` .
Could you port your changes there?

**Comment by AndylgTom** [comment]
@SoftFever It's done. Right?

**Comment by SoftFever** [comment]
> @SoftFever It's done. Right?

The file should be named `OrcaSlicer_ru.po` and placed in: 
`localization\i18n\ru\OrcaSlicer_ru.po`.

There's already an existing file. I assume you made modifications based on that one? 
If so, simply overwrite it and double-check to ensure the translations are correct.

Additionally, there's a conflict in the `resources/i18n/ru/OrcaSlicer.mo` file. 
Please pull the latest changes from the main branch (softfever repo) and then regenerate the `.mo` file. 
Alternatively, you can leave it unchanged, as I regularly regenerate them.

**Comment by AndylgTom** [comment]
ОК.  
That's the way it was. I thought you asked me to rename .po to Russian.po. I misunderstood you. )
I changed it back to OrcaSlicer_ru.po. The OrcaSlicer.mo file is also fine.

**Comment by SoftFever** [comment]
> ОК.
> That's the way it was. I thought you asked me to rename .po to Russian.po. I misunderstood you. )
> I changed it back to OrcaSlicer_ru.po. The OrcaSlicer.mo file is also fine.

Thanks!
But I'm not able to merge the PR if the mo file has conflicts.

Screenshot 2023-08-27 at 2 37 11 PM

**Comment by AndylgTom** [comment]
Updated again. And now ok?

**Comment by SoftFever** [comment]
> Updated again. And now ok?

I can still see the conflicts.

**Comment by AndylgTom** [comment]
About the file *.mo, I don't understand what's wrong and how to solve it... these are some kind of permission access. 

The main thing is that there is a po file.

> > Updated again. And now ok?
> 
> I can still see the conflicts.

About the file *.mo, I don't understand what's wrong and how to solve it... 
The main thing is that there is a *.po file from which you will generate *.mo.

**Comment by SoftFever** [comment]
> > > Updated again. And now ok?
> > 
> > 
> > I can still see the conflicts.
> 
> About the file *.mo, I don't understand what's wrong and how to solve it... The main thing is that there is a *.po file from which you will generate *.mo.

The conflicts are showing up because your branch isn't synced with the target branch [SoftFever:main](https://github.com/SoftFever/OrcaSlicer/tree/main).
During that period, there was a change in that .mo file in the SoftFever:main branch, which is causing the conflicts.

I also noticed that your .po file was still  positioned incorrectly. I've fixed the issues in your branch. To sync up with these changes, please run the git pull command.

**Comment by AndylgTom** [comment]
Honestly, I don't understand where to click to make everything normal. This has never happened before. If it's like on the screen, then I did it.
image

**Comment by SoftFever** [comment]
> Honestly, I don't understand where to click to make everything normal. This has never happened before. If it's like on the screen, then I did it. image

No worries
For now, just click the "pull" button. It should sync your local main branch with the target branch.

I'll look into ways to streamline the translation upgrade process in the future.

**Review by SoftFever — APPROVED** [review]
Merged

**Comment by AndylgTom** [comment]
@lizardjazz1 Хотите ругаться, пишите в телегу, я отвечу на эти вопросы. Нефиг тут разводить холивар.

**Comment by lizardjazz1** [comment]
> @lizardjazz1 Хотите ругаться, пишите в телегу, я отвечу на эти вопросы. Нефиг тут разводить холивар.
А с чего Вы решили, что я собираюсь ругаться, правьте перевод нормально, не нужно, как Вы сами сказали, отсебятины.
Раз уж решили что Ваш перевод лучше, так поступайте соответственно.
P.s. А чего ж Вы в телегу не написали, перед тем, как выкатить Ваш перевод? Для перевода была создана целая группа, проводятся опросы среди 3д печатников, на то, какие определения лучше использовать для удобства понимания.

**Pull request merged**
