### PR TITLE
ENH: Better Scrolling Over Multiline Fields

### PR DESCRIPTION
**Pull request by Ocraftyone**
While scrolling over multiline option fields, the mouse scrolling is ignored and sent to the parent window. Scroll is transfered back to the field if it is in focus and is able to scroll.

### CODE REVIEW

**Comment by Ocraftyone** [comment]
Hmm. It should take over once it gets focus. Let me test RQ

**Comment by Ocraftyone** [comment]
@SoftFever I was a dumb dumb and used a function based on name rather than documentation 😆. Found a different way to determine if the control can scroll.

**Comment by SoftFever** [comment]
> @SoftFever I was a dumb dumb and used a function based on name rather than documentation 😆. Found a different way to determine if the control can scroll.

It works now.
I like how it scrolls now, thank you 👍

**Review by SoftFever — APPROVED** [review]

**Comment by Ocraftyone** [comment]
This has been bugging me since I started printing using prusa slicer. I can finally enjoy scrolling my custom gcode 😄

**Pull request merged**
