### PR TITLE
Turn off logo lamp on toolhead after print is complete.

### PR DESCRIPTION
**Pull request by tsmith35**
The logo lamp stays on after a print job completes. The only way to turn it off is to power cycle the printer. This change just turns off the lamp when the print job is done.

### CODE REVIEW

**Comment by SoftFever** [comment]
@tsmith35 
Thanks for the proposal.
I can imagine that some users may like it while others may not. 
For this reason, I prefer to keep the current behavior.

**Comment by tsmith35** [comment]
Is there a way to make it a menu option so it is a user-selectable behavior?

**Comment by SoftFever** [comment]
> Is there a way to make it a menu option so it is a user-selectable behavior?

It is possible. However, I'm not sure how many users will actually use it since it's not a common feature, but rather a personal customization. Hence, I would suggest users change the machine code themselves, as you have already figured out.

**Comment by tsmith35** [comment]
Understandable. Is there a file I can change that will persist through updates, or will I need to re-add the g-code after every update? Thank you for your assistance with this, by the way!

**Comment by SoftFever** [comment]
> Understandable. Is there a file I can change that will persist through updates, or will I need to re-add the g-code after every update? 

As long as you have save the machine preset as your custom printer, the change will persist.
image


> Thank you for your assistance with this, by the way!

You are welcome.

**Comment by SoftFever** [comment]
Closed per discussion.

**Pull request closed without merging**
