### PR TITLE
Bug: Corrected monotonic lines not respecting user infill / wall overlap setting

### PR DESCRIPTION
**Pull request by igiannakas**
Removed inherited setting from BBS where the monotonic line infill and top pattern did not respect the user set infill/wall overlap setting.

This can result in tiny holes on top surfaces if flow and PA are calibrated correctly. Now the infill pattern respects the user setting similarly to all other patterns.

User can achieve the same result as before by setting the infill/wall overlap to 0 (which was the one used by BBS and overriding the user setting).

Addressing issue #2827
63E0DCDB-A62F-4521-89BC-165FA7883159_1_102_o

**After:**

IMG_2771

IMG_2772

perfect overlap with no holes

### CODE REVIEW

**Comment by ShryuKt** [comment]
This one is not a "bug", it is a feature from Bambu.
"compare to Monotonic, Monotonic linear infill has no overlap with the perimeter" from the [Wiki](https://wiki.bambulab.com/en/software/bambu-studio/fill-patterns).

Maybe if you want this behavior, it would be better to add an option instead of changing the one who exist, like SS with "line" and "lined (filled)"

**Comment by igiannakas** [comment]
Debatable but I get the point. However the super sliver options are filled / not filled and that is purely controlling whether gap fill is applied. Superslicer always respects the overlap value as does Prusa slicer. Only bambu studio has elected to not respect that for this specific infill, when the user can simply set it to 0. Hence why I'm raising this PR.

TBF there are more issues with this implementation from BBS. It is not monotonic, despite what it says on the tin. Try a model with a couple of holes on it and you'll see it keeping the same direction over two lines in a row.

I will probably port the complete implementation from SS as it works fully there vs. BBS.

**Comment by igiannakas** [comment]
After shot: 

20% overlap, perfection on the top surface without any tiny holes 🎉

IMG_2772

**Review by SoftFever — COMMENTED** [review]
nice fix.
What BL did there doesn't make sense to me either

**Review by SoftFever — APPROVED** [review]

**Pull request merged**
