### PR TITLE
Adjustable infill wall overlap for top and bottom surfaces

### PR DESCRIPTION
**Pull request by igiannakas**
This PR allows for independent adjustment of the infill/wall overlap for internal solid and sparse infill and top and bottom surfaces.

**Benefits:**
1. A higher infill wall overlap for top and bottom surfaces can be beneficial in order to minimise the appearance of pinholes (slight gaps between the top solid infill and the walls)
2. A lower infill / wall overlap for internal surfaces and sparse infill can help reduce build up & accumulation of material close to the walls which lead to top surface over extrusion 

Before you could adjust the overlap as a global value attempting to find a compromise between slight pinholes on the top surface and not too much material build up where the nozzle met the walls in the internal solid infill. Now these can be adjusted separately so you can get the best of both worlds:
1. High overlap on top surfaces (30%+) to minimise pockmarks
2. Low overlap on internal surfaces (10-15%) to minimise material build up due to over extrusion against the walls

### **Images:**
**Before:**
image
30% overlap is a good value to use to have no top surface pockmarks. 

However this results in excessive overlap between internal walls and solid infill causing build up of material especially if many top/bottom surface layers exist
image

**After:**
Top surface at 30% - no pinholes 
image

Infill set to 0% (for demonstration purposes) - reduced over extrusion.
image

### **From Ellis' print tuning website:**
**When overlap is set too low**

We can see slight pinholes on the top surface. 

Here you can see that a lower overlap results in a cleaner top surface, with slight gaps appearing around the hexagon. A higher overlap is creating slight over extrusion at the edges of the model due to the over extrusion in the layers below due to material accumulation but the gaps on the hexagon are gone.

By allowing an independent setting of these two variables, a large top layer overlap can be set without creating over extrusion.

**Notes:** 
**This is still in testing from my side** - seeking for feedback as I am not 100% familiar with the affected code segments in the perimeter generator and may have made a mistake that results in edge case issues.

The previous value from any user presets are carried over and used for the infill overlap - the top overlap is set to a default of 25% as good default to minimise top surface pinholes as per Ellis' recommendations. 

The overlap variables are now assigned to their corresponding section in the UI - top and bottom shells contains the top and bottom overlap and infill contains the infill overlap.

### CODE REVIEW

**Comment by vgdh** [comment]
it can be a smooth transition like s S-curve from bottom to the top:
10%
10%

**Comment by vgdh** [comment]
it can be a smooth transition with function of an S-curve from bottom to the top:
10%
11%
12%
15%
25%
25%
........ all middle layers
25%
25%
15%
12%
11%
10%

**Comment by igiannakas** [comment]
> it can be a smooth transition with function of an S-curve from bottom to the top: 10% 11% 12% 15% 25% 25% ........ all middle layers 25% 25% 15% 12% 11% 10%

What the aim here is actually the opposite - lower overlap in the infill as you only need it to adhere the solid and sparse infill to the perimeters (so 10-15% overlap is plenty for that) and then go 25-30% or more on the top surfaces to cover any gaps due to the extrusion width. 

A curve is an interesting approach, will experiment with it.

the background to this Pr is I’m printing some ERCF parts and noticing some slight gapping on the top solid infill (pinholes) but increasing the previous overlap would cause over extrusion on the top surface.

**Comment by igiannakas** [comment]
Just wanted to give an update on testing this - have been using it for the past month or so daily when printing my stealthmax, ERCF components and others. So far from my testing it works ok and nothing appears broken - however my testing was exclusively on Arachne.

if anyone can test this using classic it would be much appreciated.

in terms of quality benefits it has benefited greatly especially with models where the top surface is printed at a steep angle compared to the external walls. There having a higher overlap leads to less pinholes while also allowing less over extrusion to come through from the layers below that are set to less overlap. (Last picture).

IMG_3469
IMG_3470
IMG_3471

**Comment by SoftFever** [comment]
Thanks.
From my own experience, this pinhole is super sensitive to filament type and flow rate.
It's a bit hard to get conclusive results.
I think there's no harm in introducing a new parameter here.

**Review by SoftFever — APPROVED** [review]

**Comment by igiannakas** [comment]
> Thanks. From my own experience, this pinhole is super sensitive to filament type and flow rate. It's a bit hard to get conclusive results. I think there's no harm in introducing a new parameter here.

Fully agree!! I’ve found the best success with a large overlap on top and bottom surface - 30%+ and very little overlap for internal infill - 5-10% just to get enough bonding with the walls without causing over extrusion. 

Have been pretty successful with the above PR since raising it, with around 1k print hours on the Voron 😀 so thank you for merging this 🙏🏻🙏🏻

**Comment by Fusiable** [comment]
Love the implementation of this feature. Thank you! I did notice that the "Rectilinear" infill only runs in one direction. Similar to aligned rectilinear. Maybe a bug?

**Pull request merged**
