### PR TITLE
Port Emboss & SVG gizmo from PrusaSlicer

### LINKED ISSUE #1801: change text shape algorithm (project every point perpendicular to the corresponding surface)
## First of all, thank you for this very much appreciated work, which I think will be what we've all been waiting for, one single tool to rule them all, by combining all the features we like on different slicers.
<br>

The current behavior of the **`text shape`** is not ideal when it comes to placing text as an imprint on a curved surface, since the word wraps around e. g. a cylinder, but the individual letters do not wrap around the object.

As a result, only parts of a letter are printed on a curved surface (see attached picture).
<br>

It would be really nice if the algorithm of the **`text shape`** tool would project every point of a single letter perpendicular to the surface on which it should be placed on (not like in prusa slicer! [not perpendicular to surface on every point]).
<br>

I'm sure it's not an easy task, but I think there are plenty of skilled programmers here who could do it.
If I could, I would definitely do it.
<br>

btw:
Since I am on it:
Maybe the _**cut** feature_ could be added to the **`text shape`** menu too. So users would not need to convert every text by hand to a **`Negative Part`**.

thanks in advance
kind regards

image

### LINKED ISSUE #2487: Add SVG emboss tool
We have text emboss tool, but an even better one would be SVG emboss tool, so that you can project any SVG graphics on a model. This has now been added to https://github.com/prusa3d/PrusaSlicer/releases/tag/version_2.7.0-alpha1, so I guess it's just a matter of picking up the right patches?

### LINKED ISSUE #2523: SVG support
Was SVG support from PrusaSlicer brought over to 1.8.0?

### LINKED ISSUE #2616: Text debossing/cut function
**Is your feature request related to a problem? Please describe.**
Please enable the option to add inward-bulging text to the 3D model.

**Which printers will be beneficial to this feature**
Not printer dependent

**Describe the solution you'd like**
A solution similar to the CUT or JOIN radio buttons in Prusaslicer

**Describe alternatives you've considered**
Complete port of the Prusaslicer complex text module

### PR DESCRIPTION
**Pull request by Noisyfox**
This PR ported the Emboss & SVG gizmo from PrusaSlicer.

- [x]  Port Emboss gizmo
- [x]  Port SVG gizmo
- [x] Use Orca color scheme for gizmo dialog
- [ ]  ~Support reading text info from old 3mf format~ Very unlikely: https://github.com/SoftFever/OrcaSlicer/pull/2819#issuecomment-1824405783
- [ ] LOTS OF TESTING

image
image

Fix #1801
Fix #2487
Fix #2523
Fix #2616

### CODE REVIEW

**Comment by discip** [comment]
# AMAZING! 😃👍
# Thank you so much!

**Comment by Noisyfox** [comment]
> # AMAZING! 😃👍
> # Thank you so much!
> Be sure to let me know if you need help testing. Regardless, I will do testing, but if there are specific scenarios that need testing, I'm happy to help.

Just use it normally and do whatever you usually do and see if any existing things are broken/changed. Thanks for your testing~

**Comment by Eldenroot** [comment]
Just one note - is possible (and it bothers me in Prusa Slicer / Bambu studio) - when you select the text, make the selected text in a different color? Now it is not easy to see sometime in the model... thank you

**Comment by Noisyfox** [comment]
> Just one note - is possible (and it bothers me in Prusa Slicer / Bambu studio) - when you select the text, make the selected text in a different color? Now it is not easy to see sometime in the model... thank you

Good idea, will try doing that.

**Comment by discip** [comment]
@Noisyfox
# Just wanted to thank you for your dedication and all the effort you put into this. 😃👍❤

Unfortunately, these days many people take such an attitude for granted.
But I know how rewarding it can be when someone lets you know their appreciation. Even if it’s just a _"thank you"_.
Hope this keeps your mood up.

**Comment by discip** [comment]
@Noisyfox
# Just wanted to thank you for your dedication and all the effort you put into OrcaSlicer. 😃👍❤

Unfortunately, these days many people take such an attitude for granted.
But I know how rewarding it can be when someone lets you know their appreciation. Even if it’s just a _"thank you"_.
Hope this keeps your mood up.

**Comment by SoftFever** [comment]
Bravo! 
image

**Comment by discip** [comment]
I don't know if this is already being worked on, but there are some differences in the dialog-UI:
**OrcaSlicer**|PrusaSlicer
-|-
image|image

**Comment by discip** [comment]
May I ask what the purpose of this in your screenshot is?

image

**Comment by Noisyfox** [comment]
> I don't know if this is already being worked on, but there are some differences in the dialog-UI:
> 
> **OrcaSlicer**	PrusaSlicer
> image	image

Yeah this is a known issue, some of the special icons haven't been ported over yet.



> May I ask what the purpose of this in your screenshot is?

Good question, I didn't add this option, it must be there but just been hidden under certain conditions.

**Comment by Noisyfox** [comment]
Update: It will be very unlikely that we are able to port the emboss tool while keeping compatibility with existing Orca/BBS 3mf file. Any existing texts will be converted to normal mesh object once opened using this build (but the file will not be modified unless you save it with the new build), means you can still slicing the file, move/rotate/scale/delete the text object (i.e., anything that you can do to a normal mesh object), but will no longer able to edit the text such as change text content, change font etc.

Same goes to the other way, project that has text (and SVG) added using this build can still be opened by BBS/old Orca, but the texts and svgs will be treated as normal object.

**Comment by discip** [comment]
So it means that projects created with current Orca will lose the text _(converted to mesh)_, but projects created with the implementation from this PR and onwards will be able to store text (not converted to mesh).

Right?

**Comment by Ocraftyone** [comment]
CI build should work normally if you have recently merged main. I did a major overhaul to it that allows the deps to be build on the fly with caching. @Noisyfox

**Comment by Noisyfox** [comment]
> May I ask what the purpose of this in your screenshot is?
> 
> image

Turned out this option is displayed when the selected font is a TrueType Collection file.

**Comment by discip** [comment]
@Noisyfox
# This looks great so far! 👍 

But there are still a few little quirks:

1. If you look closely on your first screenshot in the initial post, you'll find to the left of the lines: **_`Use surface`_** and **_`Per glyph`_** an incomplete 'revert symbol' &#10227;.
2. > > Just one note - is possible (and it bothers me in Prusa Slicer / Bambu studio) - when you select the text, make the selected text in a different color? Now it is not easy to see sometime in the model... thank you
   > 
   > Good idea, will try doing that.

   Seems like this got lost along the way. 😅

**Comment by discip** [comment]
@Noisyfox
> Turned out this option is displayed when the selected font is a TrueType Collection file.

Ah, ok. Thank you!

# This looks great so far! Thank you very much! 👍 

But there are still a few little quirks:

1. If you look closely on your first screenshot in the initial post, you'll find to the left of the lines: **_`Use surface`_** and **_`Per glyph`_** an incomplete 'revert symbol' &#10227;.
2. > > Just one note - is possible (and it bothers me in Prusa Slicer / Bambu studio) - when you select the text, make the selected text in a different color? Now it is not easy to see sometime in the model... thank you
   > 
   > Good idea, will try doing that.

   Seems like this got lost along the way. 😅

**Comment by discip** [comment]
@Noisyfox
> Turned out this option is displayed when the selected font is a TrueType Collection file.

Ah, ok. Thank you!

# This looks great so far! Thank you very much! 👍 

But there are still a few little quirks:

1. If you look closely on your first screenshot in the initial post, you'll find to the left of the lines: **_`Use surface`_** and **_`Per glyph`_** an incomplete 'revert symbol' &#10227;.
2. > > Just one note - is possible (and it bothers me in Prusa Slicer / Bambu studio) - when you select the text, make the selected text in a different color? Now it is not easy to see sometime in the model... thank you
   > 
   > Good idea, will try doing that.

   Seems like this got lost along the way. 😅

Unfortunately, there is something that causes the text to be ignored when slicing, even though it was originally used in the same project.

[debug_Mon_Nov_27_14_45_44_20176.log.0.txt](https://github.com/SoftFever/OrcaSlicer/files/13476329/debug_Mon_Nov_27_14_45_44_20176.log.0.txt)
[debug_network_Mon_Nov_27_14_45_45.log](https://github.com/SoftFever/OrcaSlicer/files/13476331/debug_network_Mon_Nov_27_14_45_45.log)
[distance-check.3mf.txt](https://github.com/SoftFever/OrcaSlicer/files/13476343/distance-check.3mf.txt)
[distance-check.gcode.txt](https://github.com/SoftFever/OrcaSlicer/files/13476361/distance-check.gcode.txt)

**Comment by Noisyfox** [comment]
> Unfortunately, there is something that causes the text to be ignored when slicing, even though it was originally used in the same project.

The issue is that the text is thinner than the first layer height so it get merged with the upper part. What you should do is either increase the text thickness to 0.2mm, or change your first layer to 0.1mm.

image

And if you want to emboss the text inside the bottom surface, instead of been bulged, then change the emboss type to modifier instead.

**Comment by Noisyfox** [comment]
For those two issues you pointed out, I am well aware of them, just haven't got enough time to deal with yet. I think I should be able to fix those before the next release though.

**Comment by discip** [comment]
> The issue is that the text is thinner than the first layer height so it get merged with the upper part.

Thanks for clarifying! 👍🏻
I couldn't get what setting was responsible for that. 😄

> I'm currently focused more on getting everything else right, then I could come back and fix those problems.

Take your time, I think we both agree on the fact that quality is priority Nr.1.

> And again, thanks for you extensive testing!

I'm just working with it and noticing things.
In my opinion, you deserve to be thanked, since you guys are doing the heavy lifting!

**Comment by discip** [comment]
> I got another idea. ...

Just my 2cents:

Unfortunately, I can't estimate the effort required to implement it.
Based on my experience, which obviously is very subjective, I think your initial approach is enough, as this is not interesting for those like me who use daily builds almost exclusively by default, since even old files would be resliced with the latest build anyway.

And those not updating their software as frequently, will still use the good old way as long as possible and at some point would have to rework all their files cause all the other settings don't match as well anyway.

# Kudos for all the effort you've put into Orca so far! 😃👍

**Comment by Noisyfox** [comment]
> 1. If you look closely on your first screenshot in the initial post, you'll find to the left of the lines: **_`Use surface`_** and **_`Per glyph`_** an incomplete 'revert symbol' ⟳.

This issue should have been fixed now.

**Comment by Noisyfox** [comment]
> Just one note - is possible (and it bothers me in Prusa Slicer / Bambu studio) - when you select the text, make the selected text in a different color?

BTW, you mentioned Prusa Slicer. Doesn't PS show the text in a different color when you selected?
image

**Comment by Eldenroot** [comment]
> > Just one note - is possible (and it bothers me in Prusa Slicer / Bambu studio) - when you select the text, make the selected text in a different color?
> 
> BTW, you mentioned Prusa Slicer. Doesn't PS show the text in a different color when you selected? image

Ok, my mistake. I use Green filament so IT has samé color

**Comment by Noisyfox** [comment]
> > > Just one note - is possible (and it bothers me in Prusa Slicer / Bambu studio) - when you select the text, make the selected text in a different color?
> > 
> > 
> > BTW, you mentioned Prusa Slicer. Doesn't PS show the text in a different color when you selected? image
> 
> Ok, my mistake. I use Green filament so IT has samé color

Yeah I was worried about the same issue. Do you have any preferred solution then?

**Comment by Eldenroot** [comment]
Use different color then filament color. Or use some borders around symbols...dont know

**Comment by discip** [comment]
@Noisyfox
About the colors:
1. I think it would be nice to have a color contrasting the material color.

2. And as we are on it, I would like to know what you think about upgrading the color scheme to pastel colors which are much easier on the eyes. 😃
Unfortunately I forgot in wich repo I saw a similar approach.

But here is a link regarding this topic with some useful color-combination-examples: [colour-combination](https://designwizard.com/blog/colour-combination/)

**Comment by Noisyfox** [comment]
image

How does this appear? Will this be good enough for you to distinguish the selected text from the rest of the model?

**Comment by Noisyfox** [comment]
> 2\. And as we are on it, I would like to know what you think about upgrading the color scheme to pastel colors which are much easier on the eyes. 😃
>     Unfortunately I forgot in wich repo I saw a similar approach.

I'm generally pleased with current color scheme tbh, which part specifically makes you think the current color scheme isn't easy on the eyes?

**Comment by discip** [comment]
> I'm generally pleased with current color scheme tbh, which part specifically makes you think the current color scheme isn't easy on the eyes?

Sorry, you are absolutely right.
After searching for contrasting colors and finding some very stressful examples I somehow linked this to the actual implementation. 🤦‍♂️😅
On the other hand I tended to prevent such unappealing color combinations. 😁

**Comment by Noisyfox** [comment]
> image
> 
> How does this appear? Will this be good enough for you to distinguish the selected text from the rest of the model?

Any thoughts on this one? @discip

**Comment by discip** [comment]
> How does this appear? Will this be good enough for you to distinguish the selected text from the rest of the model?

Sorry, I already started typing, but needed to pause due to my job. 😅

Unfortunately I'm not a fan of this type of visual, due to the fact, that it is not "clean" on some edges it appears thicker, on others thinner and on some there is nothing at all (referring to the current outline).

So either different/contrasting colors or uniform outline. I hope I don't come across as bold. 👉🏻👈🏻

**Comment by Eldenroot** [comment]
It is difficult, does Cura have this feature?

**Comment by Noisyfox** [comment]
> > How does this appear? Will this be good enough for you to distinguish the selected text from the rest of the model?
> 
> Sorry, I already started typing, but needed to pause due to my job. 😅
> 
> Unfortunately I'm not a fan of this type of visual, due to the fact, that it is not "clean" on some edges it appears thicker, on others thinner and on some there is nothing at all (referring to the current outline).
> 
> So either different/contrasting colors or uniform outline. I hope I don't come across as bold. 👉🏻👈🏻

https://github.com/SoftFever/OrcaSlicer/pull/2934

How about this one?

**Comment by discip** [comment]
Good morning @Noisyfox.
This is indeed a brilliant approach.

I hope you don't mind me being nitpicky once more:

1. I assume it would be best if all the edges were drawn like this, since it does look somewhat incomplete if some edges are only partially drawn.

image

2. Do you think it would be possible to add antialiasing to this new borders?

image

3. Is the text of the new gizmo going to look like this as well?

image

4. Maybe you could remove that outline when the object is selected as well?

image


Thanks in advance

**Comment by Noisyfox** [comment]
It will be a bit difficult to get complete outlines due to how this method works. It only render borders at where back faces (surfaces that face back from screen) contact front faces, so edges between two front faces won't be highlighted. Will need much more complicated edge-detecting shaders to do that which I think it's not worth the effort, we are not build a game engine right?

**Comment by Noisyfox** [comment]
I've disabled the selection outline on this branch, let's give it a try.

**Comment by discip** [comment]
# Thank you very much!

1. > It will be a bit difficult to get complete outlines due to how this method works. It only render borders at where back faces (surfaces that face back from screen) contact front faces, so edges between two front faces won't be highlighted. Will need much more complicated edge-detecting shaders to do that which I think it's not worth the effort, we are not build a game engine right? With that said I'll definitely try to do that one day when I get some extra time to play with shaders.

   Sorry, I wasn't aware of the fact that this would involve such an amount of additional work.
That is absolutely not intentional.
I asked because I thought that it would be as easy as the current solution. (Judging by the speed you implemented this with.)

2. > Though I'm not sure what's going on with this part... The front faces are missing for some reason...

   This is generated by the old text feature, as the build you provided seemed to be built on the current main branch. 😊

3. What about that one?

   > 2\. Do you think it would be possible to add antialiasing to this new borders?
   >
   > image

4. > I've disabled the selection outline on this branch, let's give it a try.

   ## Thank you! Looks much cleaner! 👍🏻
   
   image

**Comment by discip** [comment]
# Thank you very much!

1. > It will be a bit difficult to get complete outlines due to how this method works. It only render borders at where back faces (surfaces that face back from screen) contact front faces, so edges between two front faces won't be highlighted. Will need much more complicated edge-detecting shaders to do that which I think it's not worth the effort, we are not build a game engine right? With that said I'll definitely try to do that one day when I get some extra time to play with shaders.

   Sorry, I wasn't aware of the fact that this would involve such an amount of additional work.
That is absolutely not intentional.
I asked because I thought that it would be as easy as the current solution. (Judging by the speed you implemented this with.)

   It would help with rare cases like depicted here (green marking):

   image

2. What about that one?

   > 2\. Do you think it would be possible to add antialiasing to this new borders?
  
   Still an issue in your latest commit as shown in the screenshot above (purple markings).

3. > Though I'm not sure what's going on with this part... The front faces are missing for some reason...

   This is generated by the old text feature, as the build you provided seemed to be built on the current main branch. 😊

4. > I've disabled the selection outline on this branch, let's give it a try.

   ## Thank you! Looks much cleaner! 👍🏻
   
   image

**Comment by Noisyfox** [comment]
> 2\. What about that one?
>     > 2. Do you think it would be possible to add antialiasing to this new borders?
>     
>     
>     Still an issue in your latest commit as shown in the screenshot above (purple markings).

I couldn't make any promise on this one as antialiasing is quite a complicated topic on its own. I will try but I'm not sure how much I could do.



> 3\. > Though I'm not sure what's going on with this part... The front faces are missing for some reason...
>     
>     
>     This is generated by the old text feature, as the build you provided seemed to be built on the current main branch. 😊

The fact that I could not reproduce this issue with current main branch makes me less confident about that the same issue won't happen on this PR. Finger crossed.

**Comment by discip** [comment]
Good morning @Noisyfox,
first of all thank you very much for reacting in time! 👍🏻

> I couldn't make any promise on this one as antialiasing is quite a complicated topic on its own. I will try but I'm not sure how much I could do.

As mentioned above, I'm just suggesting, and you are among those in the know and able to assess whether a particular feature is worth implementing.
So, whatever you decide to do, we are the beneficiaries. 😁


> The fact that I could not reproduce this issue with current main branch makes me less confident about that the same issue won't happen on this PR. Finger crossed.

Maybe this is only a Linux (Manjaro) thing combined with a certain font.
Was not able to reproduce this with the new Emboss gizmo, so no actions required here yet.
Otherwise, I will let you know.

**Comment by Noisyfox** [comment]
> Maybe this is only a Linux (Manjaro) thing combined with a certain font.

Ah Linux! Time to start up my Linux VM then :)

**Comment by SoftFever** [comment]
@Noisyfox @Ocraftyone 

Just a heads-up, we have a few PRs that involve changes in a wide range of files. I'm planning to merge PR #2844 first, followed by this PR, then #2905.

Let me know if you have any concerns.

**Comment by Noisyfox** [comment]
> @Noisyfox @Ocraftyone
> 
> Just a heads-up, we have a few PRs that involve changes in a wide range of files. I'm planning to merge PR #2844 first, followed by this PR, then #2905.
> 
> Let me know if you have any concerns.

I'd prefer to merge 2905 first then this one, because I'll have to make some code changes that relate to 2905. PS' Emboss & SVG gizmo use some code from 2905 (because PS has wxwidgets upgraded too) that I have to change to use the old code. Once we have 2905 merged then I could change those changes back.

**Comment by SoftFever** [comment]
> > @Noisyfox @Ocraftyone
> > Just a heads-up, we have a few PRs that involve changes in a wide range of files. I'm planning to merge PR #2844 first, followed by this PR, then #2905.
> > Let me know if you have any concerns.
> 
> I'd prefer to merge 2905 first then this one, because I'll have to make some code changes that relate to 2905. PS' Emboss & SVG gizmo use some code from 2905 (because PS has wxwidgets upgraded too) that I have to change to use the old code. Once we have 2905 merged then I could change those changes back.

Okay, make sense

**Comment by Ocraftyone** [comment]
@Noisyfox @SoftFever Working on merge conflicts for my PR rn

**Comment by Ocraftyone** [comment]
@Noisyfox my PR should be finalized

**Comment by Eldenroot** [comment]
Better and better, I am waiting for any beta version of 1.9 release to test this on Win :) thank you!

**Comment by Eldenroot** [comment]
Can wwe get some ALPHA/BETA official release build when it gets merged? Alongside other changes from BL last merge? Thx!

**Comment by Noisyfox** [comment]
> Can wwe get some ALPHA/BETA official release build when it gets merged? Alongside other changes from BL last merge? Thx!

I think that's what we are aiming for.

**Comment by Noisyfox** [comment]
Ok I think scaling should be fixed now.

**Comment by discip** [comment]
Will let you know as soon as the build is compiled. 😊

**Comment by discip** [comment]
Thank you for being already on it, to fix the issue.

1. The scale function on its own does work again.

2. Unfortunately there is something going on if you scale an object prior to adding a text and try to rotate the text (no matter if the text-gizmo-rotation-tool or the main-rotation-tool is used) the text gets distorted. And the value for the angle changes too.

This was tested on Windows.

**Comment by discip** [comment]
# Awesome! Thank you that fixed it! ❤️😃👍

**Comment by Noisyfox** [comment]
> As long as the main object is not rotated everything works as expected, but as soon as you rotate it, the text rotation will be changed. But you won't notice until you save the project, open it again and try to manipulate the text either by clicking the text after the text gizmo was selected or by changing any value.

Should have been fixed now... Finger crossed.

**Comment by Noisyfox** [comment]
Noticed another issue... The from surface is wrong after saving & opening.

**Comment by Noisyfox** [comment]
> I'm sorry, but there is still something not right.
> 
> The previous distortion/rotation issue is gone and replaced by this movement in Y direction. moving [ moving ](https://private-user-images.githubusercontent.com/53649486/288874798-e2cf00a0-4c88-4401-9666-053c3f419e6a.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIwMDEwMDksIm5iZiI6MTcwMjAwMDcwOSwicGF0aCI6Ii81MzY0OTQ4Ni8yODg4NzQ3OTgtZTJjZjAwYTAtNGM4OC00NDAxLTk2NjYtMDUzYzNmNDE5ZTZhLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA4VDAxNTgyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNhNTVhYjEwMjUwNDU4OTAzY2RjNmI4YmY1MjQ3MTkzOWE1MmRmOWFkMDZkMWQ5ZTBjNzg5MTZhNDc0ZWYyOTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._XYVFXFth7edzBaWA-Nf9IWi54pkqTJ_6IYG0gVU_qQ) [ ](https://private-user-images.githubusercontent.com/53649486/288874798-e2cf00a0-4c88-4401-9666-053c3f419e6a.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIwMDEwMDksIm5iZiI6MTcwMjAwMDcwOSwicGF0aCI6Ii81MzY0OTQ4Ni8yODg4NzQ3OTgtZTJjZjAwYTAtNGM4OC00NDAxLTk2NjYtMDUzYzNmNDE5ZTZhLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA4VDAxNTgyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNhNTVhYjEwMjUwNDU4OTAzY2RjNmI4YmY1MjQ3MTkzOWE1MmRmOWFkMDZkMWQ5ZTBjNzg5MTZhNDc0ZWYyOTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._XYVFXFth7edzBaWA-Nf9IWi54pkqTJ_6IYG0gVU_qQ)

How could I reproduce this issue?

**Comment by discip** [comment]
> How could I reproduce this issue?

1. Create new project
2. Add primitive > cube
3. Place text on it
4. Save project
5. Open saved project
6. Select text
7. Open text gizmo
8. Click text (on the cube) or change any value
9. text on object moves

**Comment by discip** [comment]
> How could I reproduce this issue?

1. Create new project
2. Add primitive > cube
3. Place text on it
4. Save project
5. Open saved project
6. Select text
7. Open text gizmo
8. Click text (on the cube) or change any value
9. Notice how the text on the object moves

**Comment by Noisyfox** [comment]
> Noticed another issue... The from surface is wrong after saving & opening.

PS has the same issue though... And I found the current algorithm is in a situation that this cannot be fixed properly. I've already spent too much time on this issue so far and just won't be able to do anything to it. I'll just ignore this for now and see what PS will come up with.

**Comment by Noisyfox** [comment]
> > How could I reproduce this issue?
> 
> 1. Create new project
> 2. Add primitive > cube
> 3. Place text on it
> 4. Save project
> 5. Open saved project
> 6. Select text
> 7. Open text gizmo
> 8. Click text (on the cube) or change any value
> 9. Notice how the text on the object moves

This should have been solved now.

**Comment by Noisyfox** [comment]
> Shall we change the font color to black? It's barely visible It list item looks a bit too big too, what do you think@@ image

image
Updated.

**Comment by discip** [comment]
# Thank you very much! Finally solved! 😃👍🏻❤️

**Comment by SoftFever** [comment]
@Noisyfox  I did some preliminary tests, and it looks good! Do you have any other fixes planned for this PR?

**Comment by Noisyfox** [comment]
> @Noisyfox I did some preliminary tests, and it looks good! Do you have any other fixes planned for this PR?

No at the moment.

**Review by SoftFever — APPROVED** [review]
Looks good

**Comment by SoftFever** [comment]
> > @Noisyfox I did some preliminary tests, and it looks good! Do you have any other fixes planned for this PR?
> 
> No at the moment.

Cool, I'm merge it now.
It's driving me crazy to switch deferent version of deps when switching PR...

**Comment by FillPavS** [comment]
> > > @Noisyfox I did some preliminary tests, and it looks good! Do you have any other fixes planned for this PR?
> > 
> > 
> > No at the moment.
> 
> Cool, I'm merge it now. It's driving me crazy to switch deferent version of deps when switching PR...

Please note this bug caused by this commit.

**Pull request merged**
