### PR TITLE
fix processes for Creality Ender3V3SE 0.4 nozzle

### PR DESCRIPTION
**Pull request by sizzname**
After the last changes in v2 release, all the processes for the Ender-3 V3 0.4 is missing from the UI. I corrected the configuration, they reappeared, everything works.

### CODE REVIEW

**Comment by Haleysoftware** [comment]
Thank you for jumping on this. I'm looking forward to this update. Too bad there isn't an easy way to update user created profiles that will still be inheriting the old/wrong system profile. Or will they update? I'm not sure that's possible.

For the future users that see this. Check out the issue thread that I mentioned this pull request in for how to fix/update your user created profiles.

**Comment by sizzname** [comment]
Yes, user profiles will have to be manually edited. Is it possible to write some script for this?

**Comment by buzzhuzz** [comment]
Can confirm this fixes the problem.

I had to remove user config directory for Orca (~/.config/OrcaSlicer under linux) and configure it from scratch for changes to take effect.

**Comment by Koomongous** [comment]
Works perfectly. Replaced the files & edited my user profiles "inherited from" path. Cheers.

**Comment by Jesterovskiy** [comment]
@SoftFever when you will have time, pls check this PR :) thanks!

**Comment by SoftFever** [comment]
@sizzname and all,
Thanks for the fix and feedback.

Do you think if we can make the filename and profile name same as the one we had in v1.9.1 so that existing user profiles can still be loaded?

**Comment by sizzname** [comment]
> @sizzname and all, Thanks for the fix and feedback.
> 
> Do you think if we can make the filename and profile name same as the one we had in v1.9.1 so that existing user profiles can still be loaded?

To avoid confusion, it would be better to name the files uniformly since they have been renamed.
Users already have problems with existing profiles - they have "disappeared". So users manually edit their files. I think they can do it again)
And it would be possible to make some script that fixes files after installation.

**Comment by SoftFever** [comment]
> > @sizzname and all, Thanks for the fix and feedback.
> > Do you think if we can make the filename and profile name same as the one we had in v1.9.1 so that existing user profiles can still be loaded?
> 
> To avoid confusion, it would be better to name the files uniformly since they have been renamed. Users already have problems with existing profiles - they have "disappeared". So users manually edit their files. I think they can do it again) And it would be possible to make some script that fixes files after installation.

Noted, thanks!

**Comment by Jesterovskiy** [comment]
@sizzname @SoftFever can you help me to fix current profiles? I downloaded the nightly build but this has not fixed problem

**Comment by lefixx** [comment]
Still an issue after installing 2.1.0-dev

**Comment by lefixx** [comment]
\o/ fixed in V2.1.0 
image

**Pull request merged**
