### PR TITLE
Reworked Titlebar icons

### PR DESCRIPTION
**Pull request by yw4z**
Screenshot-20240303052426

Screenshot-20240303052034

• All icons pixel perfect now
• Used file icon for file menu
• Used hamburger icon for second menu
• Used line based icons for save, undo, redo
• Changed calibration icon because old design is looks small compared to new ones but tried to keep similar to old one • Changed minimize, maximize, restore, close buttons with simpler ones
• Total size for new icons reduced 7.5kb to 5.2kb
• Again icon resolutions was set wrong as 15x15px. corrected all as 18x18px. this fixed blurry icons • Aligned all icons to highlight box on hover
• there is also topbar_store, topbar_publish, topbar_open  is exist for titlebar images but i dont know how to see them in titlebar. you can remove these files if that features is already removed. i can rework them too if they can show with different config

### CODE REVIEW

**Comment by Eldenroot** [comment]
Brush is nice. But it depends on @SoftFever

**Comment by SoftFever** [comment]
@yw4z, fantastic.
Could you put them into a single PR(#4307)? 
It’d make it easier to test and discuss.

**Comment by yw4z** [comment]
i can open a discussion if you want. it would be better because i have drawn almost %80 of all icons and they are many things to discuss. and every time i create PR it will be hard to edit commit again and again

**Comment by SoftFever** [comment]
> i can open a discussion if you want. it would be better because i have drawn almost %80 of all icons and they are many things to discuss. and every time i create PR it will be hard to edit commit again and again

You can always push changes into the existing branch.
 It's way simpler than juggling multiple branches/PRs. 
Give it a shot, please. 
Hopping between several PRs is quite a hassle for me.

**Comment by yw4z** [comment]
im using [https://github.com/yw4z/OrcaSlicer/tree/icon-designs/resources/images](https://github.com/yw4z/OrcaSlicer/tree/icon-designs/resources/images) at the moment
is that ok to send all icon changes at one commit. there is too many changes. i will create pr when its perfected. still i'm not happy some of them
also we can use https://github.com/SoftFever/OrcaSlicer/discussions/4348 for any discussion

**Pull request closed without merging**
