### PR TITLE
More Linux build improvements

### PR DESCRIPTION
**Pull request by jamincollins**
# Description

fixing the echo'd command line
removing unnecessary modification of version.inc

# Screenshots/Recordings/Graphs

N/A

## Tests

Built and tested on Arch Linux

System specs:
Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
Samsung SSD 970 EVO Plus 1TB
32G RAM

### With precompiled headers

Full clean build (currently 509 targets), no cache:
RUNTIME: 0 hours, 28 minutes, 20 secconds

With hot cache:
RUNTIME: 0 hours, 26 minutes, 19 secconds

### Without precompiled headers

Full clean build (currently 506 targets), no cache:
RUNTIME: 0 hours, 44 minutes, 38 secconds

With hot cache:
RUNTIME: 0 hours, 5 minutes, 52 secconds

### CODE REVIEW

**Comment by jamincollins** [comment]
@SoftFever 

Sure, the existing state of the repository uses pre-compiled headers (aka PCH).  In _theory_ this _should_ improve build times.  However, in practice (via CI/CD and local builds) we can see that build times are still quite long.

An issue with PCH is that the results can't be viably cached (as shown in the above timings).  Technically, they can be (and are), but it still results in a time consuming final compile.

The changes in this PR disable PCH.  In doing so some files are missing references to headers they use that were present in the PCH and as a result need to be updated with an explicit inclusion of the header.

The benefit of disabling PCH is that the build results can now be truly cached and reused, as shown in the timing results above.

Independent verification of these improvements has been made by another member on the discord:
> @JaminCollins build only takes 90s now :cool_finger_guns:
image

Additionally, this PR makes some minor adjustments that allow compiling the source with `clang` which opens additional avenues of optimization investigation.

**Comment by SoftFever** [comment]
Hmm, there might be some misunderstanding on your side.
The pre-compiled header does not work like that. Orca uses 'pchheader.hpp' and the 'add_precompiled_header' CMake function for pre-compiled headers. You can turn it off by disabling 'SLIC3R_PCH' when configuring CMake."

**Comment by jamincollins** [comment]
> Hmm, there might be some misunderstanding on your side. The pre-compiled header does not work like that. Orca uses 'pchheader.hpp' and the 'add_precompiled_header' CMake function for pre-compiled headers. You can turn it off by disabling 'SLIC3R_PCH' when configuring CMake."

There is no misunderstanding, it's precise what it done in the commit 865b379. 

Once the pre-compiled headers are disabled, several files are missing their needed includes and fail to compile.  This is why the additions are included with that change.

The caching benefits are _very_ real.  I encourage you to re-examine these changes.

**Comment by tycho** [comment]
ccache refuses to cache code using precompiled headers (it's marked as an "uncacheable call"), which is what causes the build to take longer using ccache. While having PCH enabled speeds up first builds, the lack of cacheability is a huge loss. Disabling PCH causes the initial build to take longer the first time, but the cache wins are undeniable.

**Pull request closed without merging**
