### PR TITLE
Updated arc fitting pop up to clarify that this option should not be enabled for Klipper machines

### LINKED ISSUE #4216: Arc fitting not working using ender profile but works if I modify the bambu profile for the ender.
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

1.9

### Operating System (OS)

Windows

### OS Version

10

### Additional system information

Ryzen 3600 16fb ram rx 5700xt

### Printer

Ender 3 Pro 

### How to reproduce

If I have 2 instances opened up of Orca, one with bambu profile and the other ender profile I copied all settings over to the bambu for the ender and vice versa trying to get the arc fitting to work like the modified bambu profile that works on the ender 3 with arc fitting. Arc fitting does not work like it does on bambu profile while on ender profile despite any settings changes like slowing down for overhangs.

### Actual results

The ender profile does not incorporate the arc fitting properly on the chimney area of the 3d benchy (circular object) 

### Expected results

I should see G2 commands for arc circular motion on gcode for the chimney area on the 3d benchy but I do not.

### Project file & Debug log uploads

[](url)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Anything else?

Simple fix possibly for now is to add function of octoprint server add on for the bambu profile So i can quickly upload.

### LINKED ISSUE #5297: ARC fitting causing MCU TIMER TOO CLOSE
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.0.0

### Operating System (OS)

Windows

### OS Version

10

### Additional system information

_No response_

### Printer

Flsun v400

### How to reproduce

print multimaterial with arc fitting enable

### Actual results

crash in MCU TIMER TOO CLOSE always on the prime tower 

### Expected results

should not crash - issue already reported here https://github.com/SoftFever/OrcaSlicer/issues/1052

### Project file & Debug log uploads

[klippy (7).log](https://github.com/SoftFever/OrcaSlicer/files/15241117/klippy.7.log)

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Anything else?

printing without arc fitting enable works , the print is completed

### PR DESCRIPTION
**Pull request by igiannakas**
# Description

Klipper does not natively support arc commands at the motion controller level. Hence enabling arc fitting on Klipper is detrimental to print quality as line segments are converted to arcs in the slicer and back to line segments in Klipper.

The revised pop up wording clarifies that this option is not recommended for Klipper printers. 

Fixes #5297 
Fixes #4216

### CODE REVIEW

**Comment by discip** [comment]
@igiannakas
To make this even easier:
Why not just disable and hide this feature once you set **`G-Code flavor`** to **Klipper**? 😊

**Comment by igiannakas** [comment]
> @igiannakas To make this even easier: Why not just disable and hide this feature once you set **`G-Code flavor`** to **Klipper**? 😊

Because for some reason someone may want to use it I suppose…

**Comment by bistory** [comment]
From Orca 1.6.1 to 1.6.4 ( https://github.com/SoftFever/OrcaSlicer/releases/tag/v1.6.4 ), there was a note in the release not page encouraging people to enable Arc fitting.
But I totally understand your point, I will probably stop using it in my profiles ;-)

**Comment by igiannakas** [comment]
> From Orca 1.6.1 to 1.6.4 ( https://github.com/SoftFever/OrcaSlicer/releases/tag/v1.6.4 ), there was a note in the release not page encouraging people to enable Arc fitting. But I totally understand your point, I will probably stop using it in my profiles ;-)

No that note is enabling support in klipper because some non extrusion moves use arc commands. For example spiral z hop uses arcs. As this is not a printing command it doesn’t matter that arcs are used.

**Comment by bistory** [comment]
> > From Orca 1.6.1 to 1.6.4 ( https://github.com/SoftFever/OrcaSlicer/releases/tag/v1.6.4 ), there was a note in the release not page encouraging people to enable Arc fitting. But I totally understand your point, I will probably stop using it in my profiles ;-)
> 
> No that note is enabling support in klipper because some non extrusion moves use arc commands. For example spiral z hop uses arcs. As this is not a printing command it doesn’t matter that arcs are used.

Understood ! Thanks !

**Review by SoftFever — APPROVED** [review]
I totally agree here.
Enabling ARC fitting for Klipper is not recommended.

**Pull request merged**
