### PR TITLE
Merge upstream BBL changes up to 5th Dec (01.08.01.57) & fix issues with 1.8 BBL merge

### PR DESCRIPTION
**Pull request by igiannakas**
Merging changes since last BBL -> Orca feature merge. Hoping to save you some work :)

### CODE REVIEW

**Comment by Eldenroot** [comment]
Today a new version of BLS was tagged. New commits (few)

**Comment by igiannakas** [comment]
Updated to commits up to 5th December - 01.08.01.57

**Review by SoftFever — APPROVED** [review]
Looks good

**Comment by SoftFever** [comment]
Thanks man 👍

**Comment by igiannakas** [comment]
> Thanks man 👍

welcome :) Happy to help!

**Pull request merged**
