### PR TITLE
New YOLO flow rate calibration

### PR DESCRIPTION
**Pull request by SoftFever**
# Description

This test offers an alternative to the existing 2-pass flow rate calibration, requiring only a single print. The downside is that it relies on the initial value of the filament flow ratio not being too far off. However, given that Orca's current default profiles are quite reliable for most machines and users are familiar with the flow rate concept, this shouldn't be a problem anymore.

There are two YOLO versions:
- Normal YOLO: Calibration range [-0.05, +0.05], flow rate step is 0.01.
- YOLO (perfectionist version): Calibration range [-0.04, +0.035], flow rate step is 0.005.

The normal YOLO is highly recommended for everyone and is accurate enough for 99% of use cases, if not 100%.
Most people won't notice any difference in the test with a flow rate change of 0.005.

**NOTE**: In this new calibration test, the flow rate adjusts in a linear manner. For example, the -0.01 block indicates that the actual flow rate for this block is:
```
acutal_flow_ratio = filament_flow_ratio - 0.01
```

# Screenshots/Recordings/Graphs

https://github.com/user-attachments/assets/5b18ac46-e219-4547-a00e-41cf8f622d36

### CODE REVIEW

**Comment by igiannakas** [comment]
Hey Softfever! Excellent addition! Just one recommendation. Ideally we need 5-7 top layers to really show the flow rate variations plus a couple of layers of sparse infill to decouple the influence of any bed variation from propagating up. 

Basically would it be possible to make the models a little bit thicker? The Ellis print guide rectangles are just the right height :)

**Comment by igiannakas** [comment]
Also maybe do the increments  a bit smaller? Isn’t 0.05 a bit on the high side? What do you think?

**Comment by jeremytodd1** [comment]
I agree with @igiannakas with his model size concerns. I, as well as a handful of other people I know in the community, always scales up the z on Orca's flow rate tests to get around the issue. It'd be nice to resolve that.

**Comment by SoftFever** [comment]
> Also maybe do the increments a bit smaller? Isn’t 0.05 a bit on the high side? What do you think?

Damn, I placed the decimal wrongly.
It's supposed to be 0.005 gap

**Comment by SoftFever** [comment]
@igiannakas @jeremytodd1 
Currently, the combination of the block is:
- 1 bottom layer
- 3 sparse layers
- 4 top layers
- 35% sparse infill to ensure the first layer issues are offset without affecting top surface quality
- Thick internal bridge off to prevent any impact on the top surface

I noticed previously that two settings could ruin the calibration when the top/bottom thickness is set to, for example, 0.8-1mm, which squeezes the sparse layers.
I'm fairly confident that those who run into issues with the flow rate calibration do so because of these two settings.
This is no longer an issue; this PR ensures it will be set to 0.

I don’t mind increasing the thickness a bit more to make it safer. However, 3mm, as Ellis used in his cube, seems a bit excessive since we have more settings to leverage here.

I will make the following adjustments:
- 2 bottom layers
- 3 sparse layers
- 5 top layers

**Comment by igiannakas** [comment]
That should do it - personally I prefer a bit more top layers but equally on some occasions I’ve seen the Eli’s test showing me I’m ok with flow at 8 layers but then in the real world it is under extruding when doing 6 layers.  So leaving it at 5-6 top layers may be just fine :)

another thing I’ve noticed is layer height - at 0.2 I’ve been usually getting ok appearance but as soon as I drop to 0.16 or 0.12 it slightly under extrudes. May be worth considering a smaller LH but again will see through testing 🎉

finally 1 bottom layer may be pushing it a bit from an adhesion perspective? I’ve had the Eli’s cubes lifting their corners when using too few bottom layers but I see in this model the corners are rounded so this shouldn’t happen. Again something to test 😀

**Comment by SoftFever** [comment]
> another thing I’ve noticed is layer height - at 0.2 I’ve been usually getting ok appearance but as soon as I drop to 0.16 or 0.12 it slightly under extrudes. May be worth considering a smaller LH but again will see through testing 🎉
> 

I'm actually considering going in the opposite direction by increasing the layer height (LH) to amplify the visual difference between each testing blocks.

However, I believe it's impractical to chase that level of precision in flow ratio. At the end of the day, there are too many external factors that can affect flow, such as filament diameter inconsistencies, off-center extruder gears, stepper motor imperfection, and chamber temperature differences that cause changes in plastic shrinkage.

I personally only test down to a 0.01 resolution and then estimate a 0.00x number if necessary.

**Comment by igiannakas** [comment]
With that I agree! Same here - 0.01 and then I may bump it up a bit if it’s somewhere in between. 


I have noticed that the Voron with the G2E is much better behaved and more consistent compared to the X1C when printing different layer heights. Maybe it’s just a limitation of the printer ;) also the Voron is more consistent filament to filament from the same material “family” compared to the X1

**Comment by SoftFever** [comment]
> With that I agree! Same here - 0.01 and then I may bump it up a bit if it’s somewhere in between.
> 
> I have noticed that the Voron with the G2E is much better behaved and more consistent compared to the X1C when printing different layer heights. Maybe it’s just a limitation of the printer ;) also the Voron is more consistent filament to filament from the same material “family” compared to the X1

Now you tempted me to buy a Galileo 2 ;)

**Comment by discip** [comment]
@SoftFever
Unfortunately, this only works if the language is set to English. 🤔

I tried using German and French and in both cases the flowrate for every single specimen is **`1`**.

**Comment by pgifford** [comment]
> NOTE: In this new calibration test, the flow rate adjusts in a linear manner. For example, the -0.01 block indicates that the actual flow rate for this block is:
>
> `acutal_flow_ratio = filament_flow_ratio - 0.01`

I don't see this to be the case (build 23 Aug 2024 1544 UTC).  Referencing my screenshots below, filament flow ratio is 0.98. 

**0 block**
Actual =1, expected = 0.98

**-0.01 block**
Actual = 0.9898, expected = 0.97

yolo

---

yolo2

**Comment by samv** [comment]
Oh... "Flow ratio" affects "Top surface flow ratio" and "Bottom surface flow ratio"?  Darn, I've been setting both with my custom test prints and this might explain why I occasionally get weird results with it.

I looked at this and thought, hey, I did this too!  Except I used non–linear relative ratios, eg my 9-square test is -8, -4, -2, -1, 0, 1, 2, 4, 8.  I can also choose to use enough layers to trigger sparse infill regions, because I'm not 100% convinced that very shallow test squares are a meaningful test unless you have: (a) very accurate Z height measurement i.e. TAP, Klicky Probe, LIDAR, etc, and (b) a nearly flat bed such that the maximum adaptive mesh error across all areas the test prints in is less than ~25% of the initial layer height, something like that.

The nice thing about this is that if the all–in–one test doesn't work as well as hoped, you can run one again to refine the ratio.  Each time, the chosen square gets closer and closer;

For example, here is a 3MF with two 9–square tests with ratios as above, and two 25–square tests which range from -16 to 0.5 at twice the resolution: i.e., in √2 increments:

[test-flowrate-yolo-relative.3mf.zip](https://github.com/user-attachments/files/17015924/test-flowrate-yolo-relative.3mf.zip)

Using discrete objects like this also lets me mark the cubes as non–printable for ratios I don't think I need to check to focus on the range I do care about, without generating a new file.  

I can share the python script and OpenSCAD file if you're interested, but what would be amazing would be the ability to choose the thickness of this built–in all–in–one flow test, and/or to be able to use a geometric sequence of ratios (vs linear), then I wouldn't need my tool at all.  Thanks for working on this very useful calibration approach!

**Comment by samv** [comment]
Hey, I wrote a comment here describing a method I used, but it seems on closer inspection what you've done is close enough that it covers my general usage of flow rate adjustment.  I didn't see that the shapes had way more depth than the standard Bambu Studio calibration squares!  Nice!

**Comment by SoftFever** [comment]
> @SoftFever
> 
> Unfortunately, this only works if the language is set to English. 🤔
> 
> 
> 
> I tried using German and French and in both cases the flowrate for every single specimen is **`1`**.
> 
> 

I overlooked this message.
Must be the issue of , symbol in some language
Will take a look

**Comment by SoftFever** [comment]
It should be fixed now

**Comment by CristianGTR97** [comment]
I think it would be nice to allow to configure the flow rate range, like we do with the temperature test or pa test

**Comment by Rhodani** [comment]
I tried this calibration today, but when I slice it it shows all test subjects with the same flow. I even tried to print one and they all came out identical. I also checked flow pr item and they are all the same.

**Comment by igiannakas** [comment]
Effective top layer flow = object flow rate* filament flow rate * top layer flow rate.

**Comment by samv** [comment]
Some filaments seem tolerant of wide ranges of flow ratios, so occasionally you do end up with a whole plate of flow tiles that all look almost identical.  I've noticed this most on filled filaments, especially wood.  Presumably there are micro–cavitations between the filling and thermoplastic materials.  It's normally recommended to use the highest flow which looks good in this case, which helps make sure you're packing the right amount of material in and there are no invisible gaps.

**Comment by Traq-r** [comment]
The most obvious place I see overextrusion errors is when a monotonic layer is filled from two directions, causing the elephant's foot to progressively push ahead of the field as each line adds a bit more extra filament.  How difficult would it be to fill the top layer from opposite corners, so they meet in the middle of the tile? Underextrusion and "perfect" extrusion should look the same but overextrusion becomes glaringly obvious, unless I'm missing something about the geometry of the lines?

**Comment by SoCuul** [comment]
@SoftFever It looks like the [Calibration Tutorial](https://github.com/SoftFever/OrcaSlicer/wiki/Calibration) has not been updated to correctly reflect the new YOLO calibration options.

**Comment by KennyVB** [comment]
> @SoftFever It looks like the [Calibration Tutorial](https://github.com/SoftFever/OrcaSlicer/wiki/Calibration) has not been updated to correctly reflect the new YOLO calibration options.

erhm nothing in that link describes yolo

**Comment by SoftFever** [comment]
> > @SoftFever It looks like the [Calibration Tutorial](https://github.com/SoftFever/OrcaSlicer/wiki/Calibration) has not been updated to correctly reflect the new YOLO calibration options.
> 
> erhm nothing in that link describes yolo

Yes, that's one of the many things I want to do but I can't find time to do. I will try to update the tutorial soon.

**Comment by SoCuul** [comment]
> > > @SoftFever It looks like the [Calibration Tutorial](https://github.com/SoftFever/OrcaSlicer/wiki/Calibration) has not been updated to correctly reflect the new YOLO calibration options.
> > 
> > 
> > erhm nothing in that link describes yolo
> 
> Yes, that's one of the many things I want to do but I can't find time to do. I will try to update the tutorial soon.

What is the best way for the community to contribute to the wiki? Would cloning the wiki repository, pushing our changes to a new github repo, then asking you to cherry-pick them into the OrcaSlicer wiki repo be the best option?

**Comment by SoftFever** [comment]
> > > > @SoftFever It looks like the [Calibration Tutorial](https://github.com/SoftFever/OrcaSlicer/wiki/Calibration) has not been updated to correctly reflect the new YOLO calibration options.
> > > 
> > > 
> > > erhm nothing in that link describes yolo
> > 
> > 
> > Yes, that's one of the many things I want to do but I can't find time to do. I will try to update the tutorial soon.
> 
> What is the best way for the community to contribute to the wiki? Would cloning the wiki repository, pushing our changes to a new github repo, then asking you to cherry-pick them into the OrcaSlicer wiki repo be the best option?

YES!

Just need to clone the main OrcaSlicer project then modify the document in the doc folder. You can refer to this pull request: #6474

**Comment by SoCuul** [comment]
> > What is the best way for the community to contribute to the wiki? Would cloning the wiki repository, pushing our changes to a new github repo, then asking you to cherry-pick them into the OrcaSlicer wiki repo be the best option?
> 
> Just FYI—it is also possible to modify files in a repository and prepare a pull request right from the Github UI—for things like Wiki edits, this can be quite convenient. But whatever works for you!

I might be mistaken, but I was under the impression that GitHub Wikis rely on a separate repository (OrcaSlicer.wiki.git compared to OrcaSlicer.git), which makes this process much more difficult.

@SoftFever would you potentially be able to look into implementing something like this [GitHub action](https://github.com/Andrew-Chen-Wang/github-wiki-action) which syncs a public repository with the internal github wiki repository? It's what some other large projects do to allow for easy collaboration on the documentation. It would just push the public repository to the OrcaSlicer wiki repository every time a commit is made to the master branch.

**Comment by igiannakas** [comment]
To get the wiki updated you raise a Pr against these files here. A workflow is then run I think that publishes them to the wiki.

https://github.com/SoftFever/OrcaSlicer/tree/main/doc

**Comment by igiannakas** [comment]
No worries :)

**Pull request merged**
