### PR TITLE
update purge profiles

### PR DESCRIPTION
**Pull request by giveen**
Update Purge profiles for BBL printers, referencing [3317](https://github.com/SoftFever/OrcaSlicer/issues/3317)

https://www.printables.com/model/582382-bambulab-profile-for-up-to-60-purge-reduction/

### CODE REVIEW

**Comment by streetgt** [comment]
Great work.

**Comment by igiannakas** [comment]
I’ve been using something similar for a few months now with good success. However I think this needs to be setup as a new BBL printer profile, not a change to the existing profile because:
1. Give users the option to revert back to Bambu stock
2. There maybe edge cases where this extra retraction causes issues with nozzle heat break contamination. 

Thoughts?

**Comment by giveen** [comment]
> I’ve been using something similar for a few months now with good success. However I think this needs to be setup as a new BBL printer profile, not a change to the existing profile because:
> 
> 1. Give users the option to revert back to Bambu stock
> 2. There maybe edge cases where this extra retraction causes issues with nozzle heat break contamination.
> 
> Thoughts?

My reasoning behind the change is that its actually used already in Orcaslicer and I"m just carrying it through to all profiles.

https://github.com/SoftFever/OrcaSlicer/blob/main/resources/profiles/BBL/machine/Bambu%20Lab%20X1%20Carbon%200.4%20nozzle.json

As you can see, it was already put in place for the X1C 0.4 nozzle. The creator of the profiles has been highly praised for his work and its already being used in limited capacity in our Orcaslicer.

**Comment by SoftFever** [comment]
@giveen 
Thanks for the PR.
The link to the Printables appears to be invalid.

Meanwhile, are there explanations regarding which specific parts have been changed? 
What I've noticed in this pull request is that the files have been extensively changed, even in parts that seem unlikely to be relevant to the proposed changes. 
Which make future maintenance extremely difficult.
We should only change the relevant code to ensure that code review is feasible.

However, I need to evaluate the proposed changes further once the link is restored or more information is provided.

**Comment by giveen** [comment]
> @giveen Thanks for the PR. The link to the Printables appears to be invalid.
> 
> Meanwhile, are there explanations regarding which specific parts have been changed? What I've noticed in this pull request is that the files have been extensively changed, even in parts that seem unlikely to be relevant to the proposed changes. Which make future maintenance extremely difficult. We should only change the relevant code to ensure that code review is feasible.
> 
> However, I need to evaluate the proposed changes further once more information about the changes available and only the exact changes made to the PR are specified.

Stupid Printables database broken.

Now that you mentioned, I do see a lot of changes that should have not been in place. It should have only been start/end gcode changes. I'll go back and redo a new branch and do a new pull request  once I get that done.

**Pull request closed without merging**
