### PR TITLE
Merge some changes from BS 1.9

### PR DESCRIPTION
**Pull request by SoftFever**
The improvement over measurement feature is not included yet

### CODE REVIEW

**Comment by Eldenroot** [comment]
A1 printer profile changes and  auto z height added? Thx

**Comment by SoftFever** [comment]
Yes, it’s included nowSent from my iPhoneOn 15 Apr 2024, at 1:06 AM, Eldenroot ***@***.***> wrote:﻿
A1 printer profile changes and  auto z height added? Thx

**Comment by Eldenroot** [comment]
Please, could you merge 1.9 beta4 changes? I need them to be able to use newer firmware on my a1 printer. Thank you

**Comment by SoftFever** [comment]
> Please, could you merge 1.9 beta4 changes? I need them to be able to use newer firmware on my a1 printer. Thank you

Let me know how well it works: https://github.com/SoftFever/OrcaSlicer/pull/5181

**Comment by Eldenroot** [comment]
thx, will test

**Pull request merged**
