### PR TITLE
Add overhang threshold for scarf joint seam

### PR DESCRIPTION
**Pull request by SoftFever**
I didn't originally plan to add this feature to 2.0 as I wanted to do some more tests.
However, it turns out I don't have time to do more testing, so I will release it for more people to test.
Screenshot 2024-03-27 at 12 23 56 AM

### CODE REVIEW

**Comment by discip** [comment]
@SoftFever
Is the value supposed to be expressed in **`% (percent)`** rather than in **`° (degree)`**?

**Comment by vgdh** [comment]
> @SoftFever Is the value supposed to be expressed in **`% (percent)`** rather than in **`° (degree)`**?

I think percent is more representative, because overhang percent may be different with the same incline degree because different line width.

**Comment by SoftFever** [comment]
Yeah, unsupported area of the perimeter can describe the overhang precisely. If we use angle, the overhang situation will be very different between 0.1 layer height to 0.3 layer height even if the angle is same.

**Comment by psiberfunk** [comment]
@SoftFever , I think this is a good compromise/hack for overhangs, however I think we might be able to get more fundamental improvement out of #4386.   Have you considered if that's an easy or hard thing to do ?

**Pull request merged**
