### PR TITLE
Change from "Back" to "Return" in the project tab

### PR DESCRIPTION
**Pull request by KrisMorr**

### CODE REVIEW

**Comment by SoftFever** [comment]
Hi @KrisMorr 
Thanks for the PR.
Can you provide a screenshot?

**Comment by KrisMorr** [comment]
@SoftFever 
In Polish or German, the word corresponding to the English "back" often refers more to the physical side (e.g., the back of something) rather than the direction of movement. Therefore, in translations into these languages, words such as "return" or "go back" are more frequently used when talking about returning to a previous place or state.


screenshots project tab

**Comment by KrisMorr** [comment]
> Is "return" written in lower case by purpose ?

The lowercase 'return' is used intentionally and is conditioned by an existing string, which is also used  "return" to the previous page in Assembly View

return Assembly View

**Comment by SoftFever** [comment]
> @SoftFever In Polish or German, the word corresponding to the English "back" often refers more to the physical side (e.g., the back of something) than the direction of movement. Therefore, in translations into these languages, words like "return" or "go back" are used when talking about returning to a previous place or state.
> 
> screenshots project tab

Makes a lot of sense.  
I can confirm that in Chinese, it's also translated in that way.  
Using "return" instead of "back" – which is ambiguous as it could be interpreted as a noun like "back/front/left/right" – to a more explicit verb is definitely better.

**Review by SoftFever — APPROVED** [review]

**Pull request merged**
