### PR TITLE
Update Snapmaker profiles

### PR DESCRIPTION
**Pull request by macdylan**
Most of the parameters for Snapmaker printers in the repository are incorrect, particularly the absolute disk paths that include 'smfix', which causes a lot of confusion for users.
image

I've removed it and refined all the parameters, including the correct IDEX/Dual Extruder Module toolchange G-codes, more printers, and more filaments.

image
image

### CODE REVIEW

**Comment by macdylan** [comment]
Thx for the heads up. I've reviewed and tested, I believe there's no need to worry. Just overwrite with my files.

**Comment by SoftFever** [comment]
@macdylan, 
Thank you for the overhaul of the profiles for these models. Please note that this change will disrupt existing user profiles based on the old ones. Despite this, I plan to proceed with the merge, assuming there aren't many Snapmaker users(hopefully). I'll mention this in the release notes.

For future reference, we should try to avoid changing profile names to prevent such issues. Just a heads-up.

**Comment by Borlagio** [comment]
@macdylan
Thank you very much for the profiles!!! Would be possible to add also Artisan to the printers? Would be great!

**Comment by macdylan** [comment]
I don't have an Artisan printer, but according to the official website, its drive system structure is completely different.

The parameters I've posted have all been tested and verified, sorry but I can't provide parameters based on "guess"

**Comment by Borlagio** [comment]
Ok, thank you anyway!

**Pull request merged**
