### PR TITLE
Update QIDI profiles

### PR DESCRIPTION
**Pull request by Hukete**
1）add Q1 Pro profiles

### CODE REVIEW

**Comment by bistory** [comment]
Can you please avoid replacing textures and covers ? They have been optimized to save space ;-)

**Comment by SoftFever** [comment]
> Can you please avoid replacing textures and covers ? They have been optimized to save space ;-)

I've seen multiple profile contributors having trouble dealing with the image changes.
Many contributors are not familiar with Git.
I think it's not worth the hassles for the 4 MB saved...
Hence, I will not enforce the image thing anymore :(

**Review by SoftFever — APPROVED** [review]
looks good

**Comment by bistory** [comment]
> > Can you please avoid replacing textures and covers ? They have been optimized to save space ;-)
> 
> I've seen multiple profile contributors having trouble dealing with the image changes. Many contributors are not familiar with Git. I think it's not worth the hassles for the 4 MB saved... Hence, I will not enforce the image thing anymore :(

Ok 🙁

**Comment by bistory** [comment]
There is a visual artefact with the STL on this profile @Hukete ;-)

Capture d’écran 2024-03-19 à 07 54 31

**Comment by Hukete** [comment]
> There is a visual artefact with the STL on this profile @Hukete ;-)
> 
> Capture d’écran 2024-03-19 à 07 54 31

This is excluded bed area, There is a little bit of interference between the nozzle wipers and the extruder.

**Comment by bistory** [comment]
> > There is a visual artefact with the STL on this profile @Hukete ;-)
> > Capture d’écran 2024-03-19 à 07 54 31
> 
> This is excluded bed area, There is a little bit of interference between the nozzle wipers and the extruder.

Oh wow OK, it wasn't clear with those triangles :-)

**Comment by MarkusKgit** [comment]
Is there a reason you decreased the `filament_max_volumetric_speed` from 15 to 3 in the Generic PLA profile? I was wondering why the print time increased so dramatically and tracked it down to this change as my own PLA profiles are based off of this one

**Comment by SoftFever** [comment]
> Is there a reason you decreased the `filament_max_volumetric_speed` from 15 to 3 in the Generic PLA profile? I was wondering why the print time increased so dramatically and tracked it down to this change as my own PLA profiles are based off of this one

Nice finding.
Most likely a typo.
I'm going to change it to 12

**Pull request merged**
