### PR TITLE
Update build_release.bat

### PR DESCRIPTION
**Pull request by tsmith35**
Missing double-quotes after "Visual Studio 16 2019 on lines 32, 33, 44 and 45.

Double-quote should follow the text: 2019

### CODE REVIEW

**Comment by tsmith35** [comment]
@Ocraftyone this is to add the double-quotes back in

**Review by Ocraftyone — APPROVED** [review]
Looks great! Thank you for making this update 😄

**Review by Ocraftyone — APPROVED** [review]

**Comment by tsmith35** [comment]
@SoftFever is there anything else I need to do to allow this minor edit to be merged? :-)

**Comment by tsmith35** [comment]
This only affects compile attempts with VS2019. VS2022 is unaffected since it has the double-quotes.

**Review by SoftFever — APPROVED** [review]
Looks good.
Thanks for the patience. Was on a trip last week :)

**Comment by Ocraftyone** [comment]
> Looks good.
> Thanks for the patience. Was on a trip last week :)

Hope the trip was enjoyable! Thanks again for the fix @tsmith35 !

**Comment by tsmith35** [comment]
First accepted pull request! 😃

**Comment by tsmith35** [comment]
> Looks good. Thanks for the patience. Was on a trip last week :)

Without some downtime, there can be no uptime.

**Comment by Ocraftyone** [comment]
> First accepted pull request! 😃 

CONGRATULATIONS 🎉
Don't forget to claim the contributor role on discord if you want 😉

**Pull request merged**
