### PR TITLE
Added profiles for MK3.5

### PR DESCRIPTION
**Pull request by koppensb**
# Description

Added profiles for MK3.5. Copied most of the settings over from MINIIS and changed the speed and filament pressure advance settings according to profiles in PrusaSlicer

# Screenshots/Recordings/Graphs
Screenshot 2024-08-30 at 22 10 58
Screenshot 2024-08-30 at 22 11 51

## Tests

Tested with some Benchys for the different nozzle sizes. Everything seems to work as expected.

### CODE REVIEW

**Review by SoftFever — COMMENTED** [review]
Thank you
Could take a look at the errors reported by the automation test?

**Comment by koppensb** [comment]
@SoftFever  had case inconsistencies at naming some process files. All checks have passed now.

**Review by SoftFever — APPROVED** [review]
Looks good
Thank you
I noticed the MK4's cover image is used here.
I will fix it when updating profiles

**Comment by Oxaz94** [comment]
Hi, how can add this profiles in Orca Slicer?

**Pull request merged**
