### PR TITLE
Fix syntax errors in CR-10 SE G-Code

### PR DESCRIPTION
**Pull request by cochcoder**

### CODE REVIEW

**Comment by cochcoder** [comment]
Does it make a difference either \n is /n in the start or end G-Code?

**Review by SoftFever — APPROVED** [review]
Nice catch.
Thanks

**Comment by SoftFever** [comment]
> Does it make a difference either \n is /n in the start or end G-Code?

Yea, `\n` means start a newline, application will automatically substitute them 
While `/n` is a normal string, which can cause trouble as it will send as is to the printer

**Comment by Zarin-Igor** [comment]
Hello, thanks for adding Ender CR 10 SE. but unfortunately the cut doesn't work for me 
Снимок экрана 2024-04-01 212905

**Comment by cochcoder** [comment]
@Zarin-Igor I am aware of this issue and I have a PR that fixes it. Can you confirm that [this](https://github.com/cochcoder/OrcaSlicer/actions/runs/8492559239) fixes it?

**Comment by Zarin-Igor** [comment]
@cochcoder I'm not very computer savvy, I followed the link to download the latest version and reinstalled... it didn't help, the error is the same. I hope I helped.

**Comment by Zarin-Igor** [comment]
Am I correct in understanding that this will be fixed in the next public updates? and how often are public updates made? Thank you, sorry if the question is in the wrong place...

**Comment by cochcoder** [comment]
> Am I correct in understanding that this will be fixed in the next public updates? 

Most likely

> and how often are public updates made?

I imagine that they're usually made once enough features/bugs are fixed and the code is in good standing for when even more issues are reported.

**Pull request merged**
