### PR TITLE
Implemented minimum skirt extrusion length and draft shield parameter

### LINKED ISSUE #1068: Missing Minimal filament extrusion length skirt option
**Is your feature request related to a problem? Please describe.**
It's way easier to have constant minimum skirt than setting it per object (e.g for larger objects you need less loops than for smaller ones)

**Describe the solution you'd like**
Add an option to set minimal filament extrusion length

**Describe alternatives you've considered**
It's possible to change number of loops for each new project but that's bad UX imo

**Additional context**
 Available in PrusaSlicer

image

### LINKED ISSUE #1630: Draft shield w/ Brim feature PLEASE!
Printing in ABS w/o enclosure needs a Draft shield w/ Brim feature.  Can you please include a brim feature w/ skirt loops?  Thank you.

### LINKED ISSUE #3718: Backport Draft Shield support from Prusa Slicer
**Is your feature request related to a problem? Please describe.**
Up to BL X1/P1 series, there was no need for draft shields. However, OrcaSlicer support more printers than BambuStudio, and among them are open-frame printers.

**Which printers will be beneficial to this feature**
All ABS/ASA capable Artillerys, BIQUs, Comgrows, Voxelabs, and Flashforge Adventurer 5M, at least some of the RatRigs, all ABS/ASA capable Elegoo Neptunes, AnkerMake M5/C, All ABS/ASA capable Anycubics, etc.

**Describe the solution you'd like**
Back port the "Draft Shield" option from Prusaslicer - or at least, add a modifier to the skirt height definition that allows me to set the whole height automatically.

**Describe alternatives you've considered**
I can achieve the same behavior manually, but if I change layer height for instance, I have to re-slice, get that number, and manually feed into the form. 

**Additional context**
No additional context necessary.

### LINKED ISSUE #4408: More freedom for skirt and brim settings.
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

The problem is when I try to print aprts in ABS or Nylon or any other material that is prone to shrinkage/warping hence lifting off from the printbed I will use brim.  I also would like to have a very close skirt (aka draftshield) but when I make the brim wide then the Skirt moves away.  What I actually do from time to time in cad is that I draw a thick (0.7-.8mm) brim around the part and a 1-1.5mm thich draft shield around the part. So when the part tries to lift off it is held down by these "two sacrifical parts".

### Which printers will be beneficial to this feature?

All

### Describe the solution you'd like

I would like to be able to specify thickness of the brim and the placement of the skirt relative to the part, not the brim.

### Describe alternatives you've considered

Drawing this in CAD :(

### Additional context

Possibly add a sekond "Skirt"  name it draftshield..   Would be even more helpful against warping..

### LINKED ISSUE #5343: Skirt minimum extrusion length like superslicer
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

When i mounted an ERCF v2 to my 2.4, my normal purge line no longer worked, because of extruder sync. Therfore i began using skirts again.
My ERCF is set up to unload filament after each print, with a cutter, so a small piece of filament is left in the hotend. When starting a new print with a different filament, the print is not the right colour in the beginning so i purge into a skirt.
The problem is that with a small print the skirt is too small to properly purge the filament. The solution to that is up the amount of skirt lines. That however is a problem with bigger prints, because then it wastes too much time and filament on skirt, if i dont manually change the amount of skirt lines manually.

### Which printers will be beneficial to this feature?

All

### Describe the solution you'd like

The feature should have a minimum purge amount like SuperSlicer, where it makes the skirt bigger on small prints, and smaller on large prints to reduce waste
The feature in superslicer is called "Minimal filament extrusion length" in SuperSlicer

### Describe alternatives you've considered

_No response_

### Additional context

image

### PR DESCRIPTION
**Pull request by igiannakas**
## Description

For certain use cases it may be useful to implement a parameter that controls the minimum amount of filament in mm that is purged out at the skirt. For example, when no purge line is used a minimum skirt length can be employed to ensure the nozzle is primed.

In addition, certain use cases benefit from having the option to easily enable a draft shield - i.e. a skirt as tall as the object itself. This is useful when printing warp prone material in an open frame printer.

Finally split the adhesion options into two groups - one for skirt and one for brim, to clean up the UI

This is a localised change as the code was already present in the code base, just deactivated as the option was not exported in the UI.

## Screenshots/Recordings/Graphs

**Before:**
image

**After:**
**Skirt extrusion length:**
image

**Draft shield:**
image

## Tests

Validated with 0 minimum skirt length -> number of loops is respected
Validated with multi material selection -> first tool is used to print the skirt as expected
Validated draft shield functioning

## Limitations
Due to the way skirts are constructed in the slicer, having a greater than 1 layer skirt height or the draft shield active will result in the minimum extrusion amount being extruded for each layer where the skirt is printed. This may or may not be desirable. If not desirable, the user should set the skirt height to 1 layer.

## Fixes
Fixes #5343
Fixes #1068 
Fixes #3718
Fixes #1630
Fixes #4408

### CODE REVIEW

**Comment by netweaver1970** [comment]
works fine for me, thanks! 
I settled at 15mm, with Eryone ABS, 260 degr, on a Dragon HF. Maybe could go to 10mm but just errored a bit on the safe side.

**Comment by ahmetcemturan** [comment]
Tahnk you.   Unfortunately I can not test it but does it allow you to set the distance of the draftshield from the object?  I might need a wide skirt with a closely draftshield closely placed to the object  (e.g.for PA or PC).

**Comment by igiannakas** [comment]
Hi there

this PR implements a draft shield the exact same way as prusa slicer. Have a look there to confirm ;)

**Comment by ahmetcemturan** [comment]
Yes but we are better than PrusaSlic3r.. :)

**Comment by SoftFever** [comment]
@igiannakas 
Looks like the draft shield is not enabled.

**Comment by igiannakas** [comment]
hey @SoftFever not sure what you mean? what am I missing .......?

below is from the latest pr build 

image

**Comment by SoftFever** [comment]
> hey @SoftFever not sure what you mean? what am I missing .......?
> 
> 
> 
> below is from the latest pr build 
> 
> 
> 
> image
> 
> 

Hmm, I guess you have dev mode enabled in your settings that's why you can see the draft shield option.
We need to change draft_shield option from comDevelop to comAdvance to it available for normal mode

**Comment by igiannakas** [comment]
Duh I’m stupid haha! I’ll fix it

**Comment by igiannakas** [comment]
Done, updated to comAdvanced ;)

**Review by SoftFever — APPROVED** [review]

**Pull request merged**
