### PR TITLE
Minor improvements & fixes for Ender-3 V3 KE

### PR DESCRIPTION
**Pull request by cochcoder**
As mentioned with this [comment](https://github.com/SoftFever/OrcaSlicer/pull/4793#issuecomment-2173077164)

### CODE REVIEW

**Comment by Orel-A** [comment]
The `machine_pause_gcode` should remain the same, only `change_filament_gcode` should be changed to M600.
The M600 gcode is a pause and a retraction of filament:
image

**Comment by cochcoder** [comment]
> The `machine_pause_gcode` should remain the same, only `change_filament_gcode` should be changed to M600. The M600 gcode is a pause and a retraction of filament: image

Thanks for pointing this out! It has been reverted.

**Review by Orel-A — APPROVED** [review]
Looks good.

**Review by SoftFever — APPROVED** [review]
LGTM
Thanks

**Comment by Orel-A** [comment]
@cochcoder 
There is a problem with this line in Machine End G-code:
`G1 X5 Y5 F3000 ;Wipe out`
It caused me today an out of bound error. The print hanged without finishing and stuck there.
We should rethink these 3 lines:
```
G1 E-2 F2700 ;Retract a bit
G1 E-2 Z0.2 F2400 ;Retract and raise Z
G1 X5 Y5 F3000 ;Wipe out
```
What do you think?

**Comment by cochcoder** [comment]
> @cochcoder There is a problem with this line in Machine End G-code: `G1 X5 Y5 F3000 ;Wipe out` It caused me today an out of bound error. The print hanged without finishing and stuck there. We should rethink these 3 lines:
> 
> ```
> G1 E-2 F2700 ;Retract a bit
> G1 E-2 Z0.2 F2400 ;Retract and raise Z
> G1 X5 Y5 F3000 ;Wipe out
> ```
> 
> What do you think?

How tall was the print? I think it went up too high in the end due to not checking its current height.

**Comment by Orel-A** [comment]
It went out of bound on the X-axis.

**Comment by cochcoder** [comment]
Can you send me tbd project file?

**Comment by Orel-A** [comment]
The model file is under copyright license.
https://www.crealitycloud.com/model-detail/659aa4ff2063ad89b7be1e6a
The part being printed is the MOONLEFTUP.stl file.
Downsized to 80% (aside from the height) which is 216mm x 216mm x 30mm.

**Comment by cochcoder** [comment]
Are you able to recreate the error by using a small piece of a cube? If so can you upload that project file?

**Comment by Orel-A** [comment]
Here:
[Cube Error.zip](https://github.com/user-attachments/files/15945167/Cube.Error.zip)

**Comment by Orel-A** [comment]
Any conclusions?

**Comment by Orel-A** [comment]
@cochcoder 
I made some changes to the Machine End G-code that will also allow us to increase the printable height. I also removed the problematic "Wipe out" gcode line.
The `[stepper_z]` section in printer.cfg has a position_max of 246mm.

New code:
```
G92 E0 ;Reset Extruder
G1 E-1.2 Z{max_layer_z + 0.5} F1800 ;Retract and raise Z
{if max_layer_z < 50}
G1 Z{max_layer_z + 25} F900 ;Raise Z more
{endif}

G1 X2 Y218 F3000 ;Present print
M106 S0 ;Turn-off fan
M104 S0 ;Turn-off hotend
M140 S0 ;Turn-off bed

M84 X Y E ;Disable all steppers but Z
```

JSON:
```
"printable_height": "245"
"retract_lift_below": ["245"]
"machine_end_gcode": "G92 E0 ;Reset Extruder\nG1 E-1.2 Z{max_layer_z + 0.5} F1800 ;Retract and raise Z\n{if max_layer_z < 50}\nG1 Z{max_layer_z + 25} F900 ;Raise Z more\n{endif}\n\nG1 X2 Y218 F3000 ;Present print\nM106 S0 ;Turn-off fan\nM104 S0 ;Turn-off hotend\nM140 S0 ;Turn-off bed\n\nM84 X Y E ;Disable all steppers but Z"
```

**Comment by cochcoder** [comment]
> @cochcoder I made some changes to the Machine End G-code that will also allow us to increase the printable height. I also removed the problematic "Wipe out" gcode line. The `[stepper_z]` section in printer.cfg has a position_max of 246mm.
> 
> New code:
> 
> ```
> G92 E0 ;Reset Extruder
> G1 E-1.2 Z{max_layer_z + 0.5} F1800 ;Retract and raise Z
> {if max_layer_z < 50}
> G1 Z{max_layer_z + 25} F900 ;Raise Z more
> {endif}
> 
> G1 X2 Y218 F3000 ;Present print
> M106 S0 ;Turn-off fan
> M104 S0 ;Turn-off hotend
> M140 S0 ;Turn-off bed
> 
> M84 X Y E ;Disable all steppers but Z
> ```
> 
> JSON:
> 
> ```
> "printable_height": "245"
> "retract_lift_below": ["245"]
> "machine_end_gcode": "G92 E0 ;Reset Extruder\nG1 E-1.2 Z{max_layer_z + 0.5} F1800 ;Retract and raise Z\n{if max_layer_z < 50}\nG1 Z{max_layer_z + 25} F900 ;Raise Z more\n{endif}\n\nG1 X2 Y218 F3000 ;Present print\nM106 S0 ;Turn-off fan\nM104 S0 ;Turn-off hotend\nM140 S0 ;Turn-off bed\n\nM84 X Y E ;Disable all steppers but Z"
> ```

Sorry for taking so long to reply, I'll include the changes that you have, but I was thinking of adding a variable so that the wipe doesn't go over the max. 

What do you think about having the printer only check if it can go up 25mm rather than 50mm? This would mean that there would no longer be a 25mm gap from the print head and the top of the printer at the end of each print.

**Comment by cochcoder** [comment]
Is there a noticeable difference when the wipe gcode is removed?

**Comment by Orel-A** [comment]
It's useless since it's wiping on air, there is a 0.2mm gap. So basically it doesn't do anything.

**Comment by cochcoder** [comment]
@Orel-A 
I've included the changes in a per, except for `"retract_lift_below": ["245"]`, as this has to do with z-hops. 

Before I mark it as ready to merge, can you have it go up to 245 on the z axis and make sure that there are no issues with that change? I am weary about this change as it is above the build volume given by Creality.

**Comment by Orel-A** [comment]
> Before I mark it as ready to merge, can you have it go up to 245 on the z axis and make sure that there are no issues with that change? I am weary about this change as it is above the build volume given by Creality.

There are no issues because the previous Machine End G-code had a 5mm Z-axis lift at the end of each print, so 240 + 5 = 245mm.
And I had run a few prints in the past that reached this height by removing the 5mm lift.
I also confirmed it just now by running `G1 Z245`. It's working.

**Pull request merged**
