### PR TITLE
Updated Kingroon profiles

### PR DESCRIPTION
**Pull request by tadeu2**
Rewrited all files. Common settings on single file. New fork to avoid errors on main fork.

### CODE REVIEW

**Comment by SoftFever** [comment]
Thank @tadeu2 
There seems issues with the changes.
I can't reload the profile after applying the changes in the PR.
Can you take a look?

**Comment by tadeu2** [comment]
Yes, ofc

**Comment by tadeu2** [comment]
Fixed bug!

**Comment by tadeu2** [comment]
Did you test it? Thanks

**Review by SoftFever — APPROVED** [review]
LGTM

**Comment by SoftFever** [comment]
Thanks for contribution and patience.
It's tedious and time consuming work to test a PR...

**Comment by SoftFever** [comment]
Merged.

**Comment by tadeu2** [comment]
Dont worry! thanks for your time doing this marvelous job, its the best
slicer!

**Pull request merged**
