### PR TITLE
SS port - Change extrusion role gcode

### LINKED ISSUE #2339: Between extrusion role change G-Code (Dynamic PA macro)
**Is your feature request related to a problem? Please describe.**
No

**Which printers will be beneficial to this feature**
E.g. Voron/Klipper based printer/etc...

**Describe the solution you'd like**
Add custom between extrusion role change g-code like it is in SS

**Additional context**
I would like to add this custom g-code to use macros for dynamic PA (https://github.com/hadesz/v2blorgr-config/wiki/Dynamic-Pressure-Advance)

### PR DESCRIPTION
**Pull request by Ocraftyone**
Gcode that is run every time that the extrusion role is changed. Is helpful for those wanting to use dynamic PA scripts. Provides values for extrusion_role, last_extrusion_role, layer_num, and layer_z.

fixes #2339

### CODE REVIEW

**Comment by Ocraftyone** [comment]
The tooltip could probably get a reword. I will provide an image of SS original tooltip.
image
Also, what would you think about expanding the wiki to explain what variables can be used in which custom gcode?

**Comment by SoftFever** [comment]
> The tooltip could probably get a reword. I will provide an image of SS original tooltip. image Also, what would you think about expanding the wiki to explain what variables can be used in which custom gcode?

It is welcomed :)
Modifying WIKI documents here will automatically update the WIKI: https://github.com/SoftFever/OrcaSlicer/blob/main/doc/Home.md

**Comment by SoftFever** [comment]
@Ocraftyone 
do you mind to put the original author as co-author? https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors

**Comment by Ocraftyone** [comment]
@SoftFever sorry for the delay! I amended the original commit to include merill as a co-author and merged the main branch

**Comment by Ocraftyone** [comment]
@SoftFever this PR is ready to be merged. Proper attribution should be included now. Only thing would be if you want to change the tooltip wording.

**Review by SoftFever — APPROVED** [review]
Looks good

**Comment by SoftFever** [comment]
> @SoftFever this PR is ready to be merged. Proper attribution should be included now. Only thing would be if you want to change the tooltip wording.

Hi @Ocraftyone 
The tooltip looks good to me.
Thanks for your patience 👍

**Comment by Ocraftyone** [comment]
No problem!

**Comment by cpasoft** [comment]
The next step would be to add a Dynamic PA option to the Filament tab and be able to set the PA values for Default, Perimeter, ExternalPerimeter, OverhangPerimeter and so on there, rather than having to set them manually in the Change Extrusion Role GCode tab.

imagen
When this box is checked, the new dynamic PA values are displayed.

**Pull request merged**
