### PR TITLE
Lowering wipe tower margin

### PR DESCRIPTION
**Pull request by vgdh**
Fix the issue https://github.com/SoftFever/OrcaSlicer/issues/2824 . Lowered too big wipe tower margin.
Was.

Now:
Снимок

### CODE REVIEW

**Review by colabliondev — APPROVED** [review]
It works. 👍

**Review by CristianGTR97 — APPROVED** [review]
IT WORKS WELL. PLEASE APPROVE THIS

**Comment by vgdh** [comment]
> IT WORKS WELL. PLEASE APPROVE THIS

@SoftFever can you merge this PR?

**Comment by SoftFever** [comment]
If the brim for tower is enabled, it will increase the chance of generating gcode outside of the bed.
Considering there is a gcode boundary check, this change looks fine and acceptable to me.

Thank you.

**Review by SoftFever — APPROVED** [review]

**Pull request merged**
