### PR TITLE
Change NotoSansKR to NanumGothic for Korean font

### PR DESCRIPTION
**Pull request by Hotsolidinfill**
To solve problems (like PR #1912) caused by different font heights, change to a font similar to HarmonyOS Sans SC.

HarmonyOS-0
NotoSans-0
NanumGothic-0

### CODE REVIEW

**Comment by SoftFever** [comment]
@Hotsolidinfill @gobau 
Let's continue the discussion here since it's more relavent here.

@Hotsolidinfill Nice findings.
What tool do you use the check the characters in a font file? 
Do you want to check the other harmony os font here see if they contains Korean characters?
https://github.com/ajacocks/harmonyos-sans-font/tree/main

**Comment by Hotsolidinfill** [comment]
@SoftFever 
The tool is "fontforge". You can find it here.
 https://github.com/fontforge/fontforge

I've checked all harmony sans fonts, but could not find Korean glyphs any.

I'm not an font expert but I googled a little, and find out 1 font file can contain 65,536 glyphs max.
CJK shares some Chinese characters, and because the glyphs of Chinese characters are so extensive, it seems that the CJK font is made separately.(like Noto Sans)

In my opinion, it's best to manage Korean fonts separately for now.
Alternatively, there is a way to manage CJK fonts separately like PrusaSlicer, but I am concerned about UI issues.
(uses NotoSans and NotoSansCJK)

Do you have any idea?

in prusaslicer
ImFont* font = io.Fonts->AddFontFromFileTTF((Slic3r::resources_dir() + "/fonts/" + (m_font_cjk ? "NotoSansCJK-Regular.ttc" : "NotoSans-Regular.ttf")).c_str(), m_font_size, nullptr, ranges.Data);

**Comment by gobau** [comment]
Oh I agree with the FONT replacement.

As far as I know, Korean language is not supported for hamony os font.

Nanum Sans font is also better than Noto Sans font in Korean readability.

**Review by SoftFever — APPROVED** [review]

**Comment by SoftFever** [comment]
Thanks, merged

**Comment by SoftFever** [comment]
> @SoftFever The tool is "fontforge". You can find it here. https://github.com/fontforge/fontforge
> 
> I've checked all harmony sans fonts, but could not find Korean glyphs any.
> 
> I'm not an font expert but I googled a little, and find out 1 font file can contain 65,536 glyphs max. CJK shares some Chinese characters, and because the glyphs of Chinese characters are so extensive, it seems that the CJK font is made separately.(like Noto Sans)
> 
> In my opinion, it's best to manage Korean fonts separately for now. Alternatively, there is a way to manage CJK fonts separately like PrusaSlicer, but I am concerned about UI issues. (uses NotoSans and NotoSansCJK)
> 
> Do you have any idea?
> 
> in prusaslicer ImFont* font = io.Fonts->AddFontFromFileTTF((Slic3r::resources_dir() + "/fonts/" + (m_font_cjk ? "NotoSansCJK-Regular.ttc" : "NotoSans-Regular.ttf")).c_str(), m_font_size, nullptr, ranges.Data);

Yes, we might have to go that route eventually. As more languages get added, it might be necessary to separate CJK characters into one font file and rest languages into another(hopefully they can fit!). At that point, we'll also likely need to transition to a different font that supports a wider range of languages to ensure a consistent UI appearance.

**Comment by SoftFever** [comment]
But for now, it's looks good.
Merged!

**Pull request merged**
