### PR TITLE
QoL: 3D navigator

### PR DESCRIPTION
**Pull request by Noisyfox**
Initial work on adding a 3D navigator gizmo. Build on top of the amazing https://github.com/CedricGuillemet/ImGuizmo library by @CedricGuillemet.

orca_3d_navigator

Todos:
- [ ] ~Add text on faces (up, down, left, right, etc.)~ Nearly impossible
- [x] Show axis
- [x] Options to turn this on/off
- [ ] Maybe more?

### CODE REVIEW

**Comment by Eldenroot** [comment]
Show axis and arrows for easier navigation (Fusion 360 like). this is just great!

**Comment by Noisyfox** [comment]
image

**Comment by Eldenroot** [comment]
Now I just need better legends for flow, layer speed etc. from the latest Superslicer build :)

**Comment by Noisyfox** [comment]
> So text ia not possible right? I really like it! Thank you

Currently it's way too difficult to add text, due to the fact that this cube is actually rendered in 2d, not 3d (that's the limitation of imgui), and you can't easily do that to text, so unfortunately no text on faces at the moment.

**Comment by Noisyfox** [comment]
> Now I just need better legends for flow, layer speed etc. from the latest Superslicer build :)

I got some other things to do before that.

**Comment by TechDude23** [comment]
This is nice add on thank you for all the hard work but I miss the scarf joint seam option you did so I'm rolling back for now

**Comment by Eldenroot** [comment]
> > Now I just need better legends for flow, layer speed etc. from the latest Superslicer build :)
> 
> I got some other things to do before that.

I understand it. Thank you anyway. There are many nice cherry picks from superslicer latest releases. Maybe it would be worth to check them.

**Comment by SoftFever** [comment]
This is fantastic.
Works like a charm 👍 

@Noisyfox One last thing need to add though, cloud you add "ImGiozmo" into the license info page?
You can add it in function: 
`void CopyrightsDialog::fill_entries()`
Once it's added, we can view it here: 
image

**Comment by Noisyfox** [comment]
> This is fantastic. Works like a charm 👍
> 
> @Noisyfox One last thing need to add though, cloud you add "ImGiozmo" into the license info page? You can add it in function: `void CopyrightsDialog::fill_entries()` Once it's added, we can view it here: image

Done.

**Comment by SoftFever** [comment]
> > This is fantastic. Works like a charm 👍
> > @Noisyfox One last thing need to add though, cloud you add "ImGiozmo" into the license info page? You can add it in function: `void CopyrightsDialog::fill_entries()` Once it's added, we can view it here: image
> 
> Done.

Thanks 👍 
I found another issue on Mac.
We probable should handle DPI scale too.

Screenshot 2024-02-25 at 8 36 12 PM

**Comment by tkunchick** [comment]
I love the new view finder. Thank you very much.

Could we add a little home button to it to return to home view?

**Pull request merged**
