### PR TITLE
Hotkeys

### PR DESCRIPTION
**Pull request by jamincollins**
# Description

* Fixes how the hotkey dialog is displayed
* Sets the advertised (file menu) CTRL+Q hotkey for Linux and Windows

# Screenshots/Recordings/Graphs

Before:
image
image

After:
image
image

## Tests

Built and tested on Arch Linux.

### CODE REVIEW

**Comment by yw4z** [comment]
I will commit your branch my additions if you ok with this changes, updated colors for tabs on my branch

Screenshot-20240430132354

**Comment by SoftFever** [comment]
The cause looks like a font issue on Linux to me.
I'm not fully convinced that setting control's min size is a proper fix.

Also it create multiple issues on Windows
image

**Comment by yw4z** [comment]
@SoftFever i guess it was my mistake
`sel->m_tab_text->SetBackgroundColour(StateColor::darkModeColorFor(wxColour("#F8F8F8")));`
this lines should match with tab background

**Comment by yw4z** [comment]
@jamincollins perhaps problem is caused by bold font, frame calculated from normal font but text overflows when bold font used

**Comment by jamincollins** [comment]
> @jamincollins perhaps problem is caused by bold font, frame calculated from normal font but text overflows when bold font used

The problem was much more simple than that, they didn't really calculate the sizes:
https://github.com/SoftFever/OrcaSlicer/pull/5205/commits/3d7846d9330115b2573423e6221fdecb09b4e0e3

**Pull request closed without merging**
