### PR TITLE
Add Creality Print support

### PR DESCRIPTION
**Pull request by robertduplock**
# Description

Added support for Creality Print (E.g. Orca can upload and print directly to Ender 3 V3 KE)

# Screenshots/Recordings/Graphs

Video: https://www.youtube.com/watch?v=ONzaMJhj_Hk

## Tests

Tested in the video above on a Macbook Pro, Ender 3 V3 KE.
It should also be tested on Windows but I don't have a windows computer.

### CODE REVIEW

**Comment by SoftFever** [comment]
Thanks @robertduplock 
Does this work for all Creality printers like K1 or just Ender 3 V3 KE?

**Comment by robertduplock** [comment]
@SoftFever 
I believe it will work with the K1, and any Creality printer that uses the standard Creality web interface

For reference, I used [this](https://github.com/SoftFever/OrcaSlicer/issues/2103) is a basis for the API traffic, which is based on the K1, and it looks the same as the KE.

However, I do not have an actual K1 to test this.

**Comment by bistory** [comment]
Tested on a non-rooted K1C and it works perfectly @SoftFever !

**Comment by computergeek1507** [comment]
I tested it on a stock K1 Max and it work great.

**Comment by ywevis74** [comment]
Will the Creality K1 SE be added?

**Comment by bistory** [comment]
> Will the Creality K1 SE be added?

The system is the same so K1, K1C, K1 Max, SE, and probably K2 will be compatible.

**Review by SoftFever — COMMENTED** [review]
Looks good
Thank you!

**Comment by JamesHagerman** [comment]
I know at least 5 people that have been waiting for this. Any hint on what release/pre-release it'll be available in?

**Comment by robertduplock** [comment]
Thank you to everyone who helped test! 
It should work on most Creality printers that have a wifi enabled creality print support

**Comment by cdhunt** [comment]
Verified on Windows with V3 KE. The Device view suffers from the same "bug" as the browser: It seems like the WebSocket dies (idles out), and the UI freezes. A refresh fixes this in the browser but it seems like only closing and reopening Orca fixes it in app.

**Comment by hdevlaam** [comment]
I tested the connection with my V3 KE like in the video from 0:04. However I still get this error massage:

Could not connect to OctoPrint: HTTP 404: <!DOCTYPE html>
<html>
<head>
<title>404 Not Found</title>
</head>
<body>
<center><h1>404 Not Found</h1></center>
<hr>
</body>
</html>
Note: OctoPrint version 1.1.0 or higher is required.

**Comment by cdhunt** [comment]
@hdevlaam, There should now be a CrealityPrint option in the dropdown.

**Comment by TAPAKAHKA** [comment]
Connect with k1 max  - OK
But after send file i have error.
image

**Comment by nguyenvinhlinh** [comment]
> Connect with k1 max - OK But after send file i have error. image

I have tried with k1max, work well! no root!
image

**Comment by TAPAKAHKA** [comment]
Press "Test" - not working :)
image

**Comment by TAPAKAHKA** [comment]
o_O i solved the problem.
file name  must have only engish letter

**Comment by hdevlaam** [comment]
> @hdevlaam, There should now be a CrealityPrint option in the dropdown.

I hadn't noticed that. Thanks, now everything works fine.

**Comment by fortellerq** [comment]
Does anyone know if it means that we can trigger a print from OrcaSlicer to K1 Max that will enable LiDAR-based calibration? I guess I need to try out on my own, but maybe someone tried on their own already :)

**Comment by Ltek** [comment]
@robertduplock any chance you'd be able to get Lidar working? I opened this FR a year ago ... https://github.com/SoftFever/OrcaSlicer/discussions/3125#discussioncomment-11307103

**Comment by Orel-A** [comment]
@robertduplock 
There is a problem with the safe_filename() function. It's converting blank spaces to underscores but that's not really the issue.
The issue is that the HTTP request needs to encode the URI string. And the WebSocket JSON data doesn't need to be.
In JavaScript it's a simple function called encodeURIComponent()
In C++ Boost library it's boost::urls::encode - https://www.boost.org/doc/libs/master/doc/antora/url/reference/boost/urls/encode-09.html

**Pull request merged**
