### PR TITLE
Arachne "one top wall" fix and refactor

### LINKED ISSUE #3313: Perimeters offset too much for one wall on top surfaces
For lower top surfaces perimeters are shifted inward, especially when there are number of walls:

image

I guess instead of complex calculations here
https://github.com/SoftFever/OrcaSlicer/blob/7ab2fabe6a8b314facb05a0cea372f5b304dc63a/src/libslic3r/PerimeterGenerator.cpp#L885

something like `coord_t offset_top_surface = ext_perimeter_width;` could produce better result:

image

providing base for next layer external perimeter. Picture is from Prusa with ported code.

[Orca-Cube.zip](https://github.com/SoftFever/OrcaSlicer/files/13778968/Orca-Cube.zip)

### LINKED ISSUE #6000: One wall on top causes wrong wall generation in Arachne
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.1.1

### Operating System (OS)

Windows

### OS Version

Win10x64

### Additional system information

_No response_

### Printer

Custom

### How to reproduce

Slice attached project with Arachne and one wall on top surfaces enabled.

### Actual results

Invalid inernal wall
image

### Expected results

Round wall generated (screenshot with one wall on top disabled).

image

### Project file & Debug log uploads

[round.zip](https://github.com/user-attachments/files/16078332/round.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Anything else?

I didn't succeed to find Arachne setting to prevent it.

### PR DESCRIPTION
**Pull request by vovodroid**
This PR supersedes  _Reduce one top perimeter offset #6086_ and fixes  #6000 _One wall on top causes wrong wall generation in Arachne_ and  fixes #3313 _Perimeters offset too much for one wall on top surfaces_.

See previous discussion in **Reduce one top perimeter offset #6086**.

Changes:

1) Arachne one top level wall code was replaced by ported from Prusa, while keeping "One wall threshold" parameter.
2) Classic - perimeter offset was reduced to produce good result.

@igiannakas @Eldenroot FYI

### CODE REVIEW

**Comment by vovodroid** [comment]
@igiannakas I applied min with top to Prusa code, you can test it.

**Comment by igiannakas** [comment]
Think its still not 100% there, sorry :(

Project file from the last post in the previous PR. While it has fixed the nozzle crashing over the perimeters, even with 0 gap you still get walls coming through the top perimeters

image

Also the one wall threshold seems to be over compensating

image
Both above are at 300% threshold - left is the old version, right is the new.

The old 300% is closer to the new 100% (see below)

image

**Comment by igiannakas** [comment]
I think we're missing the re-expansion of the top surface after here:

  double min_width_top_surface = std::max(double(ext_perimeter_spacing / 2. + 10), scale_(config->min_width_top_surface.get_abs_value(unscale_(perimeter_width))));

             // Get top ExPolygons from current infill contour.
             Polygons upper_slices_clipped = ClipperUtils::clip_clipper_polygons_with_subject_bbox(*upper_slices, infill_contour_bbox);
             upper_slices_clipped          = offset(upper_slices_clipped, min_width_top_surface);

Maybe here we need to expand by the threshold?

top_expolygons = offset2_ex(top_expolygons, -top_surface_min_width, top_surface_min_width + float(perimeter_width));

But I may be wrong

**Comment by vovodroid** [comment]
> Maybe here we need to expand by the threshold?

I didn't see its effect, but here is something else.

Actually this code 
`double min_width_top_surface = std::max(double(ext_perimeter_spacing / 2. + 10), scale_(config->min_width_top_surface.get_abs_value(unscale_(perimeter_width))));`

prevents setting to min_width_top_surface to low value specified in printing profile.

So I tried
`double min_width_top_surface = scale_(config->min_width_top_surface.get_abs_value(unscale_(perimeter_width))));`

i.e. WYSIWYG)). You text model looks good with 0.06mm (so min_width_top_surface is 60000, vs previous limit 202841):

No holes
image

neither nozzle collisions:
image

Lesser value causes holes, large collisions.

Benchy also feels good with absolute zero)).

Try updated PR.

**Comment by igiannakas** [comment]
Hm, still not there yet I think

image
image

vs:

image

Basically the threshold shouldn't split a continuous polygon into multiple top surfaces - it's there to filter out small total top surface areas (i.e. smaller than X% of nozzle size/line width because very small extrusions cannot be reliably printed)

**Comment by igiannakas** [comment]
`Hence why in the code before the polygon was expanded after the "trimming" by the threshold area, so the top surface can be "re-unified" again into a single polygon, I think

**Comment by vovodroid** [comment]
Here is your benchy with latest code and zero threshold

image

Did you check latest commit https://github.com/vovodroid/OrcaSlicer/commit/80207d555585bd78c58f6bb0f02815e218b070e9?

**Comment by igiannakas** [comment]
Try with 300% threshold (that’s the default profile value) and you’ll see what I mean :) vs classic or the old Arachne

**Comment by vovodroid** [comment]
> Try with 300% threshold

Why use 300? 14% produce good result for text model. Probably it's worth to change default value to zero or something like 15%.

**Comment by igiannakas** [comment]
The original approach by expanding the upper polygons with a uniform offset, tends to merge adjacent top surface polygons. The prusa approach ensures that each top surface polygon meets the minimum width independently. However the filtering process can break up a single larger polygon into multiple smaller polygons if parts of it do not meet the width requirement, which is not the case in the old approach or the classic perimeter generator approach.

Basically the old approach merges polygons to create larger, unified top surfaces, while the new approach enforces the minimum width on each polygon segment individually, leading to more separated top surfaces. This explains why a top surface polygon spanning two perimeters is treated as one in the old code and as two in the new code.

I think this is happening because of this line here. The offsetting applied here involves both inward and outward adjustments, which can result in breaking up larger polygons into smaller segments if they do not meet the width criteria.

`top_expolygons = offset2_ex(top_expolygons, -top_surface_min_width, top_surface_min_width + float(perimeter_width));
`

Replacing it with the below should correct for this but I haven't finished compiling the code yet to test it with that one line change. Theoretically this offsetting approach expands the upper polygons, ensuring that any top surface is at least the specified minimum width.
`top_expolygons = offset_ex(top_expolygons, top_surface_min_width);`

**Comment by igiannakas** [comment]
> Actually what is problem with test projects in latest commit with adjusted threshold? Both cases look good for me.

It's what the setting means - basically it runs the risk of splitting surfaces when it doesnt need to. For all intents and purposes you can set a much higher value to filter small area polygons before without affecting large contiguous surfaces at all. For example 

image
Look on the side walls of the benchy (where it slopes up). The old 300% threshold didn't generate top fill for all as the polygon was smaller than the threshold. The new approach with 14% does. Because they are small, they will over extrude.

**Comment by igiannakas** [comment]
Setting the new approach to 300% breaks them up like this:

image

Even setting to 100% creates half filled top surfaces

image

**Comment by vovodroid** [comment]
> Because they are small, they will over extrude.

I guess linear/pressure advance can handle it, in conjunction with "Small area flow compensation". Chimney top also has small area. 

At least new version doesn't produce things like these
image
image

**Comment by igiannakas** [comment]
Im afraid it can't handle it fully. In general you want to avoid very small extrusion volumes for this reason - there must be a better way.

I'm trying to compile it now with a filtering change, checking the size of the polygon separately instead of using the threshold value to expand and contract the perimeters to create the top surfaces. TBC if this works, will post back.

```
            // Filter out small polygons
            ExPolygons filtered_top_expolygons;
            for (const auto &poly : top_expolygons) {
                BoundingBox bbox = get_extents(poly);
                if (bbox.width() >= min_width_top_surface && bbox.height() >= min_width_top_surface) {
                    filtered_top_expolygons.push_back(poly);
                }
            }
            top_expolygons = filtered_top_expolygons;
```

**Comment by igiannakas** [comment]
Yeah I know that's why I'm also so keen on getting this implemented, but it has to be right with the threshold handling :S

**Comment by igiannakas** [comment]
Using the radius filter instead of the split with the underlying paths is promising:

image

Now testing instead of filtering with bbox radius, to simply filter by the max as below:

```
                float top_surface_min_width = std::max<float>(float(ext_perimeter_spacing) / 4.f + scaled<float>(0.00001), float(perimeter_width) / 4.f);
                top_surface_min_width = std::max(min_width_top_surface,top_surface_min_width);
```

**Comment by vovodroid** [comment]
Are you straggling to get such picture - internal perimeter here and top surface in other places?

image

**Comment by igiannakas** [comment]
> Are you straggling to get such picture - internal perimeter here and top surface in other places?
> 
> image

That's expected as the width there is smaller than the threshold.

**Comment by igiannakas** [comment]
Getting closer:

Old - new at 300%

image

Old - New at 300%

New handles perimeters better:

image

Will revert back once final build is done and I'll post the revised code segment for your review

**Comment by igiannakas** [comment]
OK it worked perfectly.

This commit here contains the changes I've made:
https://github.com/igiannakas/OrcaSlicer/commit/4694448878aa248326eea522281c08f09fb2db3a

I'll post screenshots in a little while.

**Comment by igiannakas** [comment]
Screenshots:

**Before left / After Right**
Identical handling of one wall threshold
image


Improved handling of one wall top surface when subsequent layer is followed by thin walls
image

Improved handling of irregular shapes:
image

Improved handling of top surface before lettering:
image


**Further tweaking and tuning:**

`top_expolygons = offset2_ex(top_expolygons, -top_surface_min_width, top_surface_min_width + float(perimeter_width/2));`

The above contracts and expands the top surface polygon to, in effect, filter out the small areas. In addition in expands the polygon slightly (perimeter_width/2) to tuck the top surface under the next perimeter on top. **Prusa slicer has the expansion increase to be equal to perimeter_width**. This can cause nozzle collisions as thin features surrounded by top surface polygons are in effect "expanded into". Setting this value to a lower % (in this case perimeter_width/2) allows for more room for thin features to print, without the nozzle colliding over them. 

However - this does result in minor artefacting like the below because the top polygon is clipped with the perimeter next to it.
image

Potentially a value to try would be 80% of perimeter width - experiment in progress.

**Comment by igiannakas** [comment]
Also the code still fixes the below issues:

image
image

**Comment by igiannakas** [comment]
OK turns out 80% is the magic value - no more defects

image


Updated commit here: f192509e9818a731ec8c412264fcf3f18918da77

**Comment by vovodroid** [comment]
Great finding, so PS code does the same, just need to be configured and tuned.

> turns out 75% is the magic value - no more defects

I found 0.85 is better. No holes:

image

No nozzle crossing and artifacts:
image

From my POV benchy is also looking good
image

Regarding concern about small area of left strip - it's the same as others.

But 0.85 fits internal perimeters better than 0.75
image

Probably this
image

was caused by mismatch between threshold and coefficient, as they work together.

So I would leave it 0.85. Or add new parameter to configuration.

By a way, PS divides threshold by four, while in classic it's used "as is". May be not divide it for Arachne to make both methods closer one to another?

**Comment by igiannakas** [comment]
The threshold division in Bambu is because it’s expanding the polygon by that distance as a whole - so divide by 4 to get the expansion on each edge. 

Yeap let’s try 0.85 and see how it goes. I don’t feel that another parameter for this is needed, just need to test and find the right one and maybe tune with some user feedback. More options tend to confuse newer users as they are not familiar with what to tune for what (I’ve seen so many horror stories in users profiles over the past year or so!!).

Would you mind updating the PR with the changes from my commit last night? Thank you for the work btw, this is working very very well 🎉

**Comment by vovodroid** [comment]
Updated with 0.85

**Comment by igiannakas** [comment]
Ok compiled locally with 0.85 works well for these models. 

It might be worth trying a single perimeter letter to see how it prints as this is the only case where we may have an issue with the expansion going over the letter wall.

**Comment by vovodroid** [comment]
> trying a single perimeter letter

Like this?
image

**Comment by igiannakas** [comment]
Yeap. Does the top surface under the text slice correctly? Looks like it but I can’t judge as the letter is sitting on top of it haha!

**Comment by igiannakas** [comment]
> It sits just on top surface
> 
> image

Fantastic! So it looks good to go then. Maybe another test with a 2 perimeter text is all I can think off just to be on the safe side. But in any case I think this is done

**Comment by vovodroid** [comment]
> Maybe another test with a 2 perimeter text i

Nozzle crosses very narrow perimeter, but nothing crucial I guess

image

image

Universe is also not perfect)))

**Comment by igiannakas** [comment]
> > Maybe another test with a 2 perimeter text i
> 
> Nozzle crosses very narrow perimeter, but nothing crucial I guess
> 
> image
> 
> image
> 
> Universe is also not perfect)))

How does it look with 80% overlap? that is the parameter to tweak to make this work. Haven't had a chance to experiment with it but that expansion is what is causing the lines to draw over.

Practically this won't have any impact (it happened already today with the existing one wall implementation) but if we can fix that it would be awesome.

**Comment by vovodroid** [comment]
> How does it look with 80% overlap?

The same. The only value preventing nozzle crossing and producing better underlying result is 0.55
image

Internal perimeters offset with 0.55:
image

So we have two dimensional parametric space, and lock one parameter could be not optimal for certain case. I agree that too much parameters could be intimidating)), but there is no choice if one needs perfect result.

**Comment by igiannakas** [comment]
Leave it at 0.85 then - the small redundant wall line won’t be an issue and is an edge case compared to the bigger issue of not setting this correctly (as it will fragment walls - tested 0.55 yesterday).

**Comment by vovodroid** [comment]
Probably @SoftFever would like to add parameter. Now we can only wait for him.

**Comment by discip** [comment]
@vovodroid
@igiannakas
# Thank you for your effort on that one! 😃👍

ps:
I know this is off topic,
but would you mind having a look on the handling of the wall printing order when **`Extra perimeters on overhangs`** is activated.
Regardless of the **`Walls printing order`** these walls should always start on the inside. Otherwise it absolutely misses the point.
I'm aware of this being no easy task, but maybe you can think of a solution. 😊

thanks in advance

**Comment by jeremytodd1** [comment]
Does this pull request also resolve the issue shown in this post: https://github.com/SoftFever/OrcaSlicer/issues/5738#issuecomment-2173767603

**Comment by vovodroid** [comment]
@discip 
> I'm aware of this being no easy task

Nothing terrible, I've already made some changes in wall order, but they are based on my wall direction refactoring PR.

@jeremytodd1 
could please give test project?

**Comment by jeremytodd1** [comment]
@vovodroid 

You can find the model here:
https://www.printables.com/model/141746-the-office-sign

**Comment by vovodroid** [comment]
> Does this pull request also resolve the issue shown in this post?

No, it's for another things.

**Comment by jeremytodd1** [comment]
Got it.
The issue in that linked post might be another thing to look into, as it is another big issue on how Orca handles top layers in some cases. There is currently no way to tune for that issue in Orca.

**Comment by igiannakas** [comment]
OK found an issue with this option and how it interacts with precise wall. When both are enabled you can see artefacts in the benchy like the below

image

They look like perimeter calculation inaccuracies.

With precise wall disabled - tool path deviations are not present.
image

Unfortunately these are visible on the final print and they look like wall artefacts

I'm busting my head to figure out where these come from but I'm drawing blanks right now.

Project file: 
[One wall inaccuracies.3mf.zip](https://github.com/user-attachments/files/16402731/One.wall.inaccuracies.3mf.zip)

I won't be able to look into this issue for a little while but hope the above helps.

**Comment by vovodroid** [comment]
Can you highlight areas in question? I don't really see the difference)))

**Comment by igiannakas** [comment]
Yeah sure hope this helps:

IMG_4226

**Comment by vovodroid** [comment]
Fixed (I hope)), updated. Though I don't see meaning in precise wall option. Use "outer-inner" for it.

image

**Comment by igiannakas** [comment]
It increases the spacing between the first internal and the external perimeter when using inner outer mode. It helps slightly reduce surface issues when you’re forced to use inner outer (like some of the Voron parts for example)…

I’ll give it a test at some point and let you know.

**Comment by vovodroid** [comment]
> you’re forced to use inner outer (like some of the Voron parts for example)…

For instance? By a way, I implemented "Print overhang first", so one can use "outer-inner" for all, but overhangs.

**Comment by igiannakas** [comment]
Changing wall order sequence between two layers from outer inner to inner outer will result in layer surface discontinuities - so it’s generally preferable to stick to one wall order mode throughout the print.

that being said, which pr is it? Keen to test it!

**Comment by vovodroid** [comment]
> Changing wall order sequence between two layers from outer inner to inner outer will result in layer surface discontinuities

We are talking about steep overhangs anyway, so surface discontinuities is not issue here.

**Comment by vovodroid** [comment]
> that being said, which pr is it?

This. Added new commit to it.

**Comment by igiannakas** [comment]
Some feedback - have been using it for the past 3 weeks or so after the latest commit and it has been working great ;)

**Comment by vovodroid** [comment]
Now waiting for SoftFever ))

**Comment by SoftFever** [comment]
@vovodroid @igiannakas 
Thank you so much!

I can't repro the issue reported in #6000
But I do see there's improvements for #3313 and thin texts

**Review by SoftFever — APPROVED** [review]
LGTM
Thank you!

**Comment by discip** [comment]
@vovodroid
> @discip
> 
> > I'm aware of this being no easy task
> 
> Nothing terrible, I've already made some changes in wall order, but they are based on my wall direction refactoring PR.

Did you mean to look into this?
Or do you even have already a solution to this issue?

**Comment by vovodroid** [comment]
> Or do you even have already a solution to this issue?

I implemented 
image

but I didn't open PR, as this change is based on  `Remove "auto" wall direction option` #6193  PR which is still waiting.

**Comment by discip** [comment]
> I implemented

Would you mind sharing this build? 😅

**Comment by vovodroid** [comment]
It's included in my Orca fork.

**Comment by discip** [comment]
I was not able to find it in your fork. 🤷‍♂️
Could you please provide a link?

**Comment by vovodroid** [comment]
https://github.com/vovodroid/OrcaSlicer/commits/vvd/

Commit "Overhangs after"

**Comment by discip** [comment]
Ah, I see, I was hoping you had a compiled version.
Do you compile your builds locally?

**Comment by vovodroid** [comment]
> Do you compile your builds locally?

Sure, I use my fork for slicing.

**Pull request merged**
