### PR TITLE
Update OrcaSlicer.pot + fix

### PR DESCRIPTION
**Pull request by KrisMorr**
Errors related to the interpretation of % symbols during translation have been fixed (PrintConfig.cpp)

The missing translations in the application menu for macOS have been added

The /src directory has been scanned to detect any changes in i18n string.

A new OrcaSlicer.pot file has been generated to incorporate the latest changes.

### CODE REVIEW

**Comment by SoftFever** [comment]
> Errors related to the interpretation of % symbols during translation have been fixed (PrintConfig.cpp)

Thanks @KrisMorr 
Do you mind to explain this one more? Seems the current message works fine?

**Comment by KrisMorr** [comment]
@SoftFever 
The issue is that these errors cause a problem when a new POT file is generated. Information is then added to the string that it is a C-format (which causes a translation problem in the application). I reverted this change in PrintConfig.cpp because, for now, the .pot file is not generated automatically (there is some error somewhere). However, I removed the C-format information in the attached file OrcaSlicer.pot, which will prevent it from being added during the generation of .po >> .mo files.

I don't know if you're aware, but for the past few days, there's been an issue with **gettext**, and translation files (.mo) are not being generated.




This is one of the examples

Tr-DEerror1

**Comment by SoftFever** [comment]
> @SoftFever The issue is that these errors cause a problem when a new POT file is generated. Information is then added to the string that it is a C-format (which causes a translation problem in the application - screenshots below). I reverted this change in PrintConfig.cpp because, for now, the .pot file is not generated automatically (there is some error somewhere). However, I removed the C-format information in the attached file OrcaSlicer.pot, which will prevent it from being added during the generation of .po >> .mo files.
> 
> I don't know if you're aware, but for the past few days, there's been an issue with **gettext**, and translation files (.mo) are not being generated.
> 
> This is one of the examples (Deutsch)
> 
> Tr-DEerror1

Yeah, the wrong c-format tag were applied to these message. Nice catch.

I was referring to(and confused by ) the double %% changes in your previous changes.
I see you have fixed them, new changes looks good to me.
Thanks 👍

**Review by SoftFever — APPROVED** [review]

**Comment by SoftFever** [comment]
I've spent a bit more time on this issue and found something interesting. It turns out, we can use `// xgettext:no-c-format, no-boost-format` comments for messages that we don't want to treat as c-format. 
Since we're using the xgettext tool (check out the run_gettext.bat/.sh file that we use for Orca) to automatically generate the .pot file, any edits we make directly to the .pot file will end up being overwritten. Just thought you'd like to know!

https://github.com/SoftFever/OrcaSlicer/commit/9f7cec3f44e0d17d661bbacdce15a636d5f62891#diff-1f3ece8ce59b31e2795bdd7579e7f79c62a2e1ecdb02718d64b85967d85bb6a1

**Comment by KrisMorr** [comment]
**@SoftFever** 
Yes, but unfortunately, the list.txt is not up to date. After scanning the entire ./src, it generated around 200 strings for me. Of course, I don't know how many of them are used in OrcaSlicer and how many are remnants from Prusa integration, etc. Ideally, every time a new file with a string is added, it should be added to the list.txt for gettext.

**Pull request merged**
