### PR TITLE
Arachne: Fix an arithmetic overflow that causing extra points outside plate

### LINKED ISSUE #6949: Arachne leaves print area
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.1.1

### Operating System (OS)

Windows

### OS Version

Windows 10

### Additional system information

_No response_

### Printer

Bambu P1S

### How to reproduce

1. Switch Classic Generator to Arachne Generator
2. slice file

### Actual results

Phantom lines extend off to infinity.
Screenshot 2024-09-27 233915
image

### Expected results

No phantom lines are created.
image

### Project file & Debug log uploads

[Block52 3D Print ARACHNE-ERROR.zip](https://github.com/user-attachments/files/17172934/Block52.3D.Print.ARACHNE-ERROR.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Anything else?

This does not happen in 
- PrusaSlicer 2.8.1
- Bambu Studio 1.9.7.52

tested in OrcaSlicer 2.2.0-beta and 2.1.1

When switching wall generator from classic to Aranche, I get (in this one model) phantom lines that extend out of the printers build volume. In this example, the inner wall starts printing, then around line 387598 turns around, prints to X3624.45, and then comes back to the model and meets with the start of its inner wall.

### LINKED ISSUE #7321: A G-code path goes beyond plate boundaries in Orca for Bambu printers; Same 3MF in Bambu Studio slices with no issues.
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.2.0

### Operating System (OS)

Linux

### OS Version

Ubuntu 24 / Windows 10 (happens on both)

### Additional system information

_No response_

### Printer

Bambu Lab X1C; Bambu Lab P1S (same result for both)

### How to reproduce

1. Download 3MF attached
2. In Orca Slicer:
- set either Bambu Lab X1C or Bambu Lab P1S printer.
- choose 0.2 or 0.4 nozzle
- set the '0.20mm Standard' profile' (for 0.4 nozzle)
- choose No-brim (otherwise it will go out of the plate boundaries, but the SUBJ error is not brim related)
4. Slice
5. Observe the error. 

### Actual results

A SUBJ error is displayed. 

### Expected results

Slicer completes the plate without the errors. NOTE: Bambu Studio does that with the exact same model and settings without the issues.

### Project file & Debug log uploads

[Project.zip](https://github.com/user-attachments/files/17589294/Project.zip)
[debug.log.zip](https://github.com/user-attachments/files/17589298/debug.log.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

### Anything else?

See screenshots below.
NOTE 1: this MIGHT have been my local issue, like some filament/profile related, but I NEVER used 0.2 nozzle and I only enabled it for the testing purposes, yet I get the same error for 0.2 nozzle. Interesting enough, error does not appear for 0.6 and 0.8 (never used them either).
NOTE 2: if right pane is set to Line Type and Display checkbox for the Internal Solid Infill is checked, there are visible purple travels (lines) somewhere far far away from the model/plate boundaries.
NOTE 3: Bambu Studio does that with the exact same model and settings without the issues.
NOTE 4: Despite the logs saying 1.9.5.1, I sure DO have 2.2.0, at least thats what it says on About screen (Attached).

Screenshot from 2024-10-31 15-49-22
Screenshot from 2024-10-31 15-42-48
Screenshot from 2024-10-31 15-42-20
Screenshot from 2024-10-31 15-41-26

### PR DESCRIPTION
**Pull request by Noisyfox**
Fix #6949
Fix #7321

image

### CODE REVIEW

**Comment by Noisyfox** [comment]
Similar issue is observed in classic mode too, need further investigation.

**Comment by zapl** [comment]
FYI, just tested the windows installer generated from this build (click detail in checks above, look for upload job and in the logs you can find e.g. "Artifact download URL: https://github.com/SoftFever/OrcaSlicer/actions/runs/11650728839/artifacts/2137800791") and it did fix the issue for me. In my case some overhang lines going nowhere on a part of the nevermore filter (https://github.com/nevermore3d/Nevermore_Micro/blob/master/V6/STL/v6_Cartridge_Straight.stl) which would easily fit on a Voron2.4 300

**Comment by ndevenish** [comment]
This fixes the instances I have seen of this issue also.

**Review by SoftFever — APPROVED** [review]
LGTM
thank you

**Pull request merged**
