### PR TITLE
ENH: restore single instance

### PR DESCRIPTION
**Pull request by noobydp**
Single instance setting was recently added back to BambuStudio.
(See https://github.com/bambulab/BambuStudio/commit/809f82b520fb450a44a911aef56184748af05edd)

I have replicated the changes and tested on Windows manually opening STL files and also exporting to orca from Fusion 360.

I am unable to test Linux or Macos

### CODE REVIEW

**Review by SoftFever — COMMENTED** [review]
Thanks @noobydp
Could you take a look at the conflicts?

**Comment by noobydp** [comment]
I think I've done it, but I've never had to resolve a conflict on a PR before so please tell me if I got it wrong.

**Comment by Ocraftyone** [comment]
Awesome! This is something that I had on my list of things to do. One problem is that on WSL2 Ubuntu with single instance enabled I get a dbus error.

 `dbus[1342262]: arguments to dbus_message_new_method_call() were incorrect, assertion "iface == NULL || _dbus_check_is_valid_interface (iface)" failed in file ../../../dbus/dbus-message.c line 1367.
This is normally a bug in some application using the D-Bus library.
D-Bus not built with -rdynamic `

**Review by SoftFever — APPROVED** [review]
LGTM
Thank you!

**Comment by Ocraftyone** [comment]
@SoftFever did you get the Linux default tol or is that avWSL thing?

**Comment by Hawxxer** [comment]
Hi I got Issues with the combination of the feature "associate files to Orca Slicer". The first model starts OrcaSlicer but clicking on a second link for a model just ends up with nothing happening. Disabling the "Allow only one OrcaSlicer instance" and opening two links results in two instances as to be expected

**Pull request merged**
