### PR TITLE
Creality Ender 3 V3/KE important fixes and some fine-tunings

### PR DESCRIPTION
**Pull request by bistory**
This patch will avoid an error on Creality Ender 3 v3 KE profile which makes Orca unload the whole Creality configuration and force a restart in order to get the configuration back.
The problem is bad values are used for support_air_filtration, support_chamber_temp_control, support_base_pattern and support_interface_pattern.

Sorry for those mistakes but this PR should be merged before the final release...

### CODE REVIEW

**Comment by serniko97** [comment]
Hi, was there any particular reason to set the resolution for the thumbnails to 100x100 and 320x320 instead of 96x96 and 300x300?
I'm asking because I noticed in the G-code files that are pre-loaded the resolutions are 96x96 and 300x300 and this resolution is working fine on my K1.

**Comment by bistory** [comment]
> Hi, was there any particular reason to set the resolution for the thumbnails of the K1 to 100x100 and 320x320 instead of 96x96 and 300x300? I'm asking because I noticed in the G-code files that are pre-loaded the resolutions are 96x96 and 300x300 and this resolution is working fine on my K1.

It seems you are right, I pulled that change from a guy I trust without checking what Creality Print exports. I changed the sizes.
However, by default, Orca doesn't export 96x96 thumbnails and I don't have a preview in the file explorer of my printer, while I have when export in 96x96 is set.
I also checked and Creality Print exports the same thumbnails for V3 SE and KE.

**Review by SoftFever — APPROVED** [review]
Looks good

**Comment by bistory** [comment]
> Looks good

This is a duplicate of #3383 and should also fix #3033

**Comment by SoftFever** [comment]
> This patch will avoid an error on Creality Ender 3 v3 KE profile which makes Orca unload the whole Creality configuration and force a restart in order to get the configuration back. The problem is bad values are used for support_air_filtration, support_chamber_temp_control, support_base_pattern and support_interface_pattern.
> 
> Sorry for those mistakes but this PR should be merged before the final release...

No worries.
Thanks for working on this

**Pull request merged**
