### PR TITLE
Fix sidebar not shown when open 3mf file from command line arg

### PR DESCRIPTION
**Pull request by Noisyfox**
This fixes issue that the sidebar is missing if slicer is opened with command line arg, includes:

- Open 3mf file with file association
- Drag & drop 3mf file to slicer executable
- Run slicer from terminal with file path parameter
- Other similar situation that will pass a file path in main function parameter

### CODE REVIEW

**Review by SoftFever — APPROVED** [review]
Looks good

**Comment by RaySajuuk** [comment]
The side bar also having issue if OrcaSlicer is launched by double click 3mf file on Mac.

**Comment by Noisyfox** [comment]
> The side bar also having issue if OrcaSlicer is launched by double click 3mf file on Mac.

Doesn't this pr fix this as well?

**Comment by RaySajuuk** [comment]
I tested build for this PR still having issue with sidebar if I open the 3mf file in finder directly.
Screenshot 2023-12-19 at 1 19 46 AM

**Comment by Noisyfox** [comment]
Weird... Will take a look soon.

**Comment by RaySajuuk** [comment]
Confirm issue resolved.

**Pull request merged**
