### PR TITLE
Add a new filament named PLA Hyper

### PR DESCRIPTION
**Pull request by InfimechOfficial**

### CODE REVIEW

**Comment by InfimechOfficial** [comment]
Hi, I just fixed the InfiMech.json file and checked it with the tool, I have not found any error. So, what the conflict is

**Comment by SoftFever** [comment]
> Hi, I just fixed the InfiMech.json file and checked it with the tool, I have not found any error. So, what the conflict is

Cool, thank you.
Could you take a look at the conflicts?

**Comment by InfimechOfficial** [comment]
> > Hi, I just fixed the InfiMech.json file and checked it with the tool, I have not found any error. So, what the conflict is
> 
> Cool, thank you. Could you take a look at the conflicts?
Hi, I noticed being prompted for a conflict here, but I looked carefully at the code and used the tool to verify yesterday and didn't find anything unusual. I downloaded the modified  profiles and Orcaslicer is showing my machine normally as well.
It's very important to me to get all these issues fixed before the new version is released. Thanks a lot

image

**Comment by SoftFever** [comment]
> > > Hi, I just fixed the InfiMech.json file and checked it with the tool, I have not found any error. So, what the conflict is
> > 
> > 
> > Cool, thank you. Could you take a look at the conflicts?
> > Hi, I noticed being prompted for a conflict here, but I looked carefully at the code and used the tool to verify yesterday and didn't find anything unusual. I downloaded the modified  profiles and Orcaslicer is showing my machine normally as well.
> > It's very important to me to get all these issues fixed before the new version is released. Thanks a lot
> > 
> > image

I meant "fix the conflicts" ;)
But no worries, I've already resolved the conflicts for you. 

I'm about to merge it now.
Please download the nightly build and test it to see if everything works as expected.

**Comment by InfimechOfficial** [comment]
> > > > Hi, I just fixed the InfiMech.json file and checked it with the tool, I have not found any error. So, what the conflict is
> > > 
> > > 
> > > Cool, thank you. Could you take a look at the conflicts?
> > > Hi, I noticed being prompted for a conflict here, but I looked carefully at the code and used the tool to verify yesterday and didn't find anything unusual. I downloaded the modified  profiles and Orcaslicer is showing my machine normally as well.
> > > It's very important to me to get all these issues fixed before the new version is released. Thanks a lot
> > > 
> > > image
> 
> I meant "fix the conflicts" ;) But no worries, I've already resolved the conflicts for you.
> 
> I'm about to merge it now. Please download the nightly build and test it to see if everything works as expected.

Thank you, sir. I have not found any conflicts here, so I don't know how to "fix the conflics", Could you show me where the conflicts are, mabey I will fix these next time as well

**Pull request merged**
