### PR TITLE
fr:861 dynamically build handy models submenu 

### PR DESCRIPTION
**Pull request by ShaneDelmore**
For feature request 861, dynamically build handy models submenu list of models from user resources shape directory, followed by application resources handy_models directory.

This is a simple implementation with no caching and it does not have a gui like prusaslicer shape gallery does for users to add or remove models.

To use add a folder named shapes in your user application data directory and add stl or 3mf files. Underscores in the name will be replaced with spaces when generating the menu entries and the file extension will be discarded.

### CODE REVIEW

**Comment by ShaneDelmore** [comment]
This is targeted at https://github.com/SoftFever/OrcaSlicer/issues/861

**Comment by Noisyfox** [comment]
Maybe also rename the built-in model file names to make it consistent with current naming?  "ksr fdmtest v4" looks much worst than "Autodesk FDM Test".

**Comment by SoftFever** [comment]
Thanks Shane.

I'm not very conformable to iterate a folder when popup a context menu.
Plus, the handy_models folder is within the application folder which is not recommended to store user content.
If you are interested and want to take the challenge, port PrusaSlicer's shape gallery is more preferable. And from there we can further enhance that.

**Comment by ShaneDelmore** [comment]
I'll close the pr.

**Pull request closed without merging**
