### PR TITLE
Neptune 4 Plus Profile

### PR DESCRIPTION
**Pull request by w34sel**
complete with preview image and Elegoo PEI plate

### CODE REVIEW

**Comment by SoftFever** [comment]
Hi @w34sel

Thank you for the PR. I noticed it's duplicated with #2980. Both PRs look good, but in this case, I will proceed with the first one submitted.

For future submissions, I suggest turning off auto-formatting when editing JSON files, as it can make code reviews challenging. Additionally, for the cover image, a low-resolution PNG file would be preferred.

Thanks again for your contribution!"

**Comment by Georgelou35** [comment]
We have to download every file from neptune 4 plus separate??
i cant find anywhere to download it as a packet,

**Comment by w34sel** [comment]
@Georgelou35 
https://github.com/w34sel/3D-Printing

**Comment by Georgelou35** [comment]
Ah yeah yeah i find it..Im new at Github.Thank you very much my friend.

**Pull request closed without merging**
