### PR TITLE
Bug fix: VFA Test fix

### PR DESCRIPTION
**Pull request by igiannakas**
VFA Test has a bug where it would not run the vase mode algorithm if the user had the detect thin walls parameter selected.

image

This PR fixes this by deselecting the parameter in the calibration methods.

image

Softfever, I promise that's all from me this week :D

### CODE REVIEW

**Comment by Eldenroot** [comment]
You are on fire

**Comment by igiannakas** [comment]
> You are on fire

Time off work for Xmas and bored at home while wife is working 🤣

**Comment by Eldenroot** [comment]
Keep going ;) same here

**Review by SoftFever — APPROVED** [review]
Looks good

**Pull request merged**
