### PR TITLE
Adjusted Flashforge machine profiles

### PR DESCRIPTION
**Pull request by mariuske**
Added machine pause code for Flashforge printers to support pause action in firmware 2.3.6-2.1.9-20231101

### CODE REVIEW

**Comment by mariuske** [comment]
Also removed  redundant gcodes for Flashforge profiles:
image

**Comment by mariuske** [comment]
@FlashforgeOfficial - FYI

@SoftFever - Please merge this PR when you have the opportunity. Thanks!

**Review by FlashforgeOfficial — APPROVED** [review]
Awesome work! Thanks @mariuske

**Review by SoftFever — APPROVED** [review]

**Comment by SoftFever** [comment]
Thanks
Merged.

**Comment by 3DThingy** [comment]
This is Great! thank you all for your efforts!
Looking forward to 0.25mm & 0.8mm profiles.

**Comment by mariuske** [comment]
> This is Great! thank you all for your efforts! Looking forward to 0.25mm & 0.8mm profiles.

My pleasure @3DThingy ! I was planning to look into profiles for the 0.25/0.8mm nozzles next. Do you have the nozzles available and are able to verify an initial version? (I only have 0.4/0.6mm nozzles myself)

**Comment by 3DThingy** [comment]
yes, Just got them yesterday!!

**Comment by mariuske** [comment]
> yes, Just got them yesterday!!

Nice, I have a 0.25 nozzle on my way as well! Are you using Adventurer 5M or Adventurer 5M Pro?

**Comment by 3DThingy** [comment]
5M pro with 3.2.6 firmware

**Comment by mariuske** [comment]
> 5M pro with 3.2.6 firmware

I would definitely recommend upgrading to the latest firmware (2.3.7) as there are a few improvements in that one.

There's very limited specification for the 0.25/0.8 nozzles online. Are there any information with the package? Min/max layer height etc.

Are you on Discord btw? 

(Orca Slicer server: https://discord.gg/nMGFjuYEph)

**Comment by 3DThingy** [comment]
I haven't found 2.3.7, once I do I will upgrade.
No information was provided with the nozzles. Not sure, the profiles in Flashprint may help.
Just joined discord. Thanks for the invite

**Comment by mariuske** [comment]
Ok, noted. I'll look into it when I have time and ping you on Discord when I have some initial profiles ready for testing 👍

**Comment by FlashforgeOfficial** [comment]
We are working on

> > 5M pro with 3.2.6 firmware
> 
> I would definitely recommend upgrading to the latest firmware (2.3.7) as there are a few improvements in that one.
> 
> There's very limited specification for the 0.25/0.8 nozzles online. Are there any information with the package? Min/max layer height etc.
> 
> Are you on Discord btw?
> 
> (Orca Slicer server: https://discord.gg/nMGFjuYEph)

Hi @mariuske @3DThingy.  The new profiles setup for 0.25mm and 0.8mm are currently under testing. I will keep updating with you and see if more adjustments need to be mad for 0.25mm and 0.8mm profiles. Thanks!

**Comment by mariuske** [comment]
> We are working on
> 
> > > 5M pro with 3.2.6 firmware
> > 
> > I would definitely recommend upgrading to the latest firmware (2.3.7) as there are a few improvements in that one.
> > 
> > There's very limited specification for the 0.25/0.8 nozzles online. Are there any information with the package? Min/max layer height etc.
> > 
> > Are you on Discord btw?
> > 
> > (Orca Slicer server: https://discord.gg/nMGFjuYEph)
> 
> Hi @mariuske @3DThingy.  The new profiles setup for 0.25mm and 0.8mm are currently under testing. I will keep updating with you and see if more adjustments need to be mad for 0.25mm and 0.8mm profiles. Thanks!

Great news @FlashforgeOfficial ! I did start adding these profiles into the new profile structure, but without the actual values it would just be based on an educated guess for each value.

Let me know if you need any assistance adding the 0.25/0.8 profiles to the structure, I just need the tested values from you👍🏻

**Comment by 3DThingy** [comment]
> We are working on
> 
> > > 5M pro with 3.2.6 firmware
> > 
> > 
> > I would definitely recommend upgrading to the latest firmware (2.3.7) as there are a few improvements in that one.
> > There's very limited specification for the 0.25/0.8 nozzles online. Are there any information with the package? Min/max layer height etc.
> > Are you on Discord btw?
> > (Orca Slicer server: https://discord.gg/nMGFjuYEph)
> 
> Hi @mariuske @3DThingy. The new profiles setup for 0.25mm and 0.8mm are currently under testing. I will keep updating with you and see if more adjustments need to be mad for 0.25mm and 0.8mm profiles. Thanks!

Hi @FlashforgeOfficial are you any closer with 0.25 & 0.8 testing?

**Comment by FlashforgeOfficial** [comment]
> > We are working on
> > > > 5M pro with 3.2.6 firmware
> > > 
> > > 
> > > I would definitely recommend upgrading to the latest firmware (2.3.7) as there are a few improvements in that one.
> > > There's very limited specification for the 0.25/0.8 nozzles online. Are there any information with the package? Min/max layer height etc.
> > > Are you on Discord btw?
> > > (Orca Slicer server: https://discord.gg/nMGFjuYEph)
> > 
> > 
> > Hi @mariuske @3DThingy. The new profiles setup for 0.25mm and 0.8mm are currently under testing. I will keep updating with you and see if more adjustments need to be mad for 0.25mm and 0.8mm profiles. Thanks!
> 
> Hi @FlashforgeOfficial are you any closer with 0.25 & 0.8 testing?

Yes, I am on Discord. The profiles for 0.25mm and 0.8mm nozzles are almost ready and just need a bit more further testing. Won't take long time.

**Pull request merged**
