### PR TITLE
Thumbnails feature revamp.

### PR DESCRIPTION
**Pull request by SoftFever**
# Description

Support generating different size/format combinations, 
We can now specify thumbnails like this: `380x380/COLPIC, 210x210/COLPIC, 380x380/PNG`
This is useful for printers use multiply thumbnails for on device screen and web interface.
For example, Qidi X3 serial/Prusa MK4/MINI/Elegoo Neptune 4/etc...

Co-authored-by: Lukas Matena <lukasmatena@seznam.cz>

# Screenshots/Recordings/Graphs

image
image

## Tests

Tested with Voron 2.4/Prusa MK4

### CODE REVIEW

**Comment by astrojolo** [comment]
I confirm - still works on 2.1 beta, but not anymore on 2.1 RC.

**Comment by kiniad** [comment]
UPDATE: Still does not work on 2.1.1
For the at least for Qidi X-Plus 3 the COLPIC (gimage, simage) have to be at the end of the gcode, as it was before.

**Comment by tome9111991** [comment]
I can confirm not work on qidi x max3

**Comment by FMD14** [comment]
Hello, it doesn't work on an ELEGOO Neptune 4 Pro either.

**Comment by ipod9138** [comment]
We need the "Format of G-code thumbnails" Drop down back to select ColPic we have no thumbnails on the X3 series....again

**Pull request merged**
