### PR TITLE
Update OrcaSlicer_tr.po - TURKISH translation update

### PR DESCRIPTION
**Pull request by olcayoren**

### CODE REVIEW

**Comment by SoftFever** [comment]
You're quick!

I've updated the POT and PO files so that all translation-related PRs have the same base. This should help avoid conflicts after each PR merge. Unfortunately, it has caused conflicts in this PR. Could you take a look?

**Comment by KrisMorr** [comment]
resolved

**Comment by olcayoren** [comment]
> You're quick!
> 
> I've updated the POT and PO files so that all translation-related PRs have the same base. This should help avoid conflicts after each PR merge. Unfortunately, it has caused conflicts in this PR. Could you take a look?

Hello, I fixed the conflict. thanks.

**Review by SoftFever — APPROVED** [review]
Looks good.
Thank you 👍

**Pull request merged**
