### PR TITLE
added arabic language

### PR DESCRIPTION
**Pull request by AbdElhalim12**
# Description

Added Arabic Language, **Draft PR to Test** 

# Screenshots/Recordings/Graphs

### CODE REVIEW

**Comment by SoftFever** [comment]
@AbdElhalim12 
This is great!
Just a remind that please include only the necessary changes in the PR.
If you need help, please let me know

**Comment by AbdElhalim12** [comment]
Hey, Thanks.
I just can't find anything related to RTL widget so I can keep it left to right on Arabic language

**Comment by AbdElhalim12** [comment]
any help?

**Comment by SoftFever** [comment]
I'm not sure how wxWidgets handles different text orientation.
I'll keep this PR open for a while so that anyone familiar with this area can provide their input.

**Pull request closed without merging**
