### PR TITLE
Improve fuzzy skin with modifier

### LINKED ISSUE #2647: Fuzzy skin when blocked with modifier shows up as fuzzy line in model where edge of modifier is
### OrcaSlicer Version

1.7.0

### OS version

Windows 11

### Additional system information

_No response_

### Printer

Prusa MK3S+

### How to reproduce

Load model
Apply fuzzy skin
Load modifier
Set fuzzy skin off for modifier
See lines in sliced model
image
image

### Actual results

Top surface marred by fuzzy edges of modifiers that should not print at all.

### Expected results

No visual marring of the model to print.

### Project file & Debug log uploads

[BHZ top RB test OrcaSlicer 170.zip](https://github.com/SoftFever/OrcaSlicer/files/13282625/BHZ.top.RB.test.OrcaSlicer.170.zip)

##
[debug_Mon_Nov_06_17_36_11_11088.log.zip](https://github.com/SoftFever/OrcaSlicer/files/13294511/debug_Mon_Nov_06_17_36_11_11088.log.zip)
# Checklist of files to include

- [x] Log file
- [X] Project file

### LINKED ISSUE #5560: FUZZY SKIN
### Is there an existing issue for this feature request?

- [x] I have searched the existing issues

### Is your feature request related to a problem?

Only few option in fuzzy skina 

### Which printers will be beneficial to this feature?

All

### Describe the solution you'd like

Add some custom fuzzy skin on particular surface , like in Prusa slicer there is an outside wall only feature, I request to add a custom where to apply fuzzy skin only like your existing feature of (support painting), 

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Noisyfox**
# Description
Now using fuzzy skin on modifiers no longer generate extra perimeters between regions.
~~Currently I only completed the code for classic wall mode. Arachne still work-in-progress.~~

Note: the algorithm can be slow with complicated models when using multiple modifiers (clipping and reconstructing polygons with lots of points can be computational intense), though it shouldn't slow down when using only one modifier compare to the original algorithm.

Fix #2647
Fix #5560

# Screenshots/Recordings/Graphs

43d0b3f7816652ca49d68c9dd0336687
be0401d0b0ead3876077e29c97e668ed

### CODE REVIEW

**Comment by Noisyfox** [comment]
Currently there will a seam when multiple modifiers with different fuzzy settings intersect:

image
image

Will fix this soon.

**Comment by Noisyfox** [comment]
image
Somehow the modifier affects solid layers next to top/bottom layers. Weird...

**Review by SoftFever — APPROVED** [review]
LGTM
Thanks

**Comment by vgdh** [comment]
Wow. This is really great!

**Comment by northcoastam** [comment]
Great addition, thank you.

**Comment by dewi-ny-je** [comment]
It would be nice if the same was done for speed modifiers: if I set a modifier to change perimeter speed for a part of an object, the modifier adds a surface (with all that comes with it, so changes of travel, lines are broken, ...) on the interface. 

See this: https://3dprinting.stackexchange.com/questions/23331/how-to-change-print-speed-along-a-perimeter

image

Maybe check what caused the issue you solved just for fuzzy skin and solve it at the root?

**Comment by Noisyfox** [comment]
> It would be nice if the same was done for speed modifiers: if I set a modifier to change perimeter speed for a part of an object, the modifier adds a surface (with all that comes with it, so changes of travel, lines are broken, ...) on the interface.
> 
> See this: https://3dprinting.stackexchange.com/questions/23331/how-to-change-print-speed-along-a-perimeter
> 
> image
> 
> Maybe check what caused the issue you solved just for fuzzy skin and solve it at the root?

That won't be easy, but I'll look at this when possible.

**Comment by irowboat** [comment]
While I'm not manually assigning modifiers, color painting creates them and I have no control over it; and if someone were to use beam interlocking, things get crazy as seen here: https://github.com/SoftFever/OrcaSlicer/issues/5185#issuecomment-2358947450

Care to try that test case against your build?

**Comment by andrewboktor** [comment]
> Currently there will be a seam when multiple modifiers with different fuzzy settings intersect:
> 
> image image
> 
> Not sure how to fix this though.

This seam actually shows up even with a single modifier. @Noisyfox I'd look to possibly fix this. Do you understand why this seam occurs?
It seems to occur always on the "right" side of the plate, regardless of model orientation of modifier position.
image
Looking at the right side of the model, it's hard to see but it's there. I actually first spotted it on an actual print then made this super simple repro.

image
Affects Arachne only (I hope that's a huge clue to help solve it). Here's the exact same model with Classic wall generator
image

**Comment by andrewboktor** [comment]
I have narrowed down this seam to be caused by p.clipped being false for no good reason on a single point, causing the creation of a new segment and the seam is basically at the point in between the two segments.

**Comment by andrewboktor** [comment]
Confirmed my theory with some modifications to the debug svg 
image
So now we either need to rejoin these segments or prevent that "faulty" .clipped=false value!

**Comment by Noisyfox** [comment]
> > Currently there will be a seam when multiple modifiers with different fuzzy settings intersect:
> > image image
> > Not sure how to fix this though.
> 
> This seam actually shows up even with a single modifier. @Noisyfox I'd like to possibly fix this. Do you understand why this seam occurs? It seems to occur always on the "right" side of the plate, regardless of model orientation of modifier position. image Looking at the right side of the model, it's hard to see but it's there. I actually first spotted it on an actual print then made this super simple repro.
> 
> image Affects Arachne only (I hope that's a huge clue to help solve it). Here's the exact same model with Classic wall generator image

Could you open a new issue and also attach this test project? Thanks!

**Pull request merged**
