### PR TITLE
Fix processes not showing for Flashforge Guider 2s

### PR DESCRIPTION
**Pull request by cochcoder**
Mentioned by @AC5SHOT in #4591

### CODE REVIEW

**Review by AC5SHOT — APPROVED** [review]

**Review by AC5SHOT — APPROVED** [review]
Everything is safe for the guider 2s

**Comment by AC5SHOT** [comment]
Just double checking that the changes aren't visible in the beta build ?

**Comment by cochcoder** [comment]
> Just double checking that the changes aren't visible in the beta build ?

Are you not able to see processes on your system?

**Comment by AC5SHOT** [comment]
Hi, no not on any of the builds

**Comment by fabiopzanini** [comment]
> Olá, não, em nenhuma das compilações

Hello first congratulations for the brilliant work Orca Slicer is wonderful 

I'm also a FlashForge Guider 2S user and I can't see the default presets for this printer. I get a bug when trying to transfer some preset from the compare presets list right after saving that new preset, it disappears there list right after.

**Review by SoftFever — APPROVED** [review]
LGTM
Thank you

**Comment by cochcoder** [comment]
@AC5SHOT @fabiopzanini 

So sorry for the long wait, I think that the issue you experienced was the processes from this repo not properly replacing the ones you had due to the same version number. 

If you try the newest [nightly version of Orca](https://github.com/SoftFever/OrcaSlicer/releases/tag/nightly-builds), does the issue persist?

**Pull request merged**
