### PR TITLE
Add travel_slope option

### PR DESCRIPTION
**Pull request by vovodroid**
Add travel_slope option for slope/spiral z-hop travel angle like in PrusaSlicer. Increasing this angle over default 3 degrees could be useful in the case of curls, blobs, etc.

Default 3 degrees:
image

image

10 degrees:
image

Setting to 90 degrees results in Normal vertical lift (so Normal mode could be removed)
image

N.B. For whatever reasons I didn't succeed to add this option to Filament Overrides.

### CODE REVIEW

**Review by SoftFever — APPROVED** [review]
Looks good
Thank you!

**Comment by vovodroid** [comment]
What about adding this option to Filament Overrides?

**Comment by freighttt** [comment]
> What about adding this option to Filament Overrides?



> What about adding this option to Filament Overrides?

this would be great. not sure why it isnt a filament override

**Comment by vovodroid** [comment]
As I noted in the first message

> For whatever reasons I didn't succeed to add this option to Filament Overrides.

I've tried, but it just has no effect.

**Pull request merged**
