### PR TITLE
Prusa Mk3s Profiles and Ender3 Profiles for  0,2 0,4 0,6 and 0,8 nozzle

### PR DESCRIPTION
**Pull request by goyetus**
Prusa Mk3s Profiles for  0,2;0,4;0,6;0,8
Ender 3 Profiles  for  0,2;0,4;0,6;0,8

- 5 Different and independent Quality profiles for each Nozzle.
- Fine, Optimal, Standard, Draft and Superdraft

All working perfect in Orcaslicer last version.   Profiles direct from Prusa.

### CODE REVIEW

**Comment by goyetus** [comment]
a few more printers (mk3s and Ender3) with profiles for each nozzle.   All working fine,  ported from prusaslicer  to Orcaslicer.

**Comment by SoftFever** [comment]
@goyetus 

Thanks.
It seems it only contains ender-3 changes though, is this intended?

**Comment by goyetus** [comment]
Ummm, It must contain also MK3s  0,2 0,4 0,6 and 0,8 profiles
Let me check

**Comment by goyetus** [comment]
Ok,  close this Pull and open another with all the files.

**Pull request closed without merging**
