### PR TITLE
Fix -Wsubobject-linkage warning

### PR DESCRIPTION
**Pull request by buzzhuzz**
# Description

```
[8/476 0.2/sec] Building CXX object src/CMakeFiles/OrcaSlicer_profile_validator.dir/OrcaSlicer_profile_validator.cpp.o
In file included from /opt/packages/3d/OrcaSlicer/src/libslic3r/GCode.hpp:26,
                 from /opt/packages/3d/OrcaSlicer/src/libslic3r/calib.hpp:5,
                 from /opt/packages/3d/OrcaSlicer/src/libslic3r/AppConfig.hpp:12,
                 from /opt/packages/3d/OrcaSlicer/src/libslic3r/PresetBundle.hpp:5,
                 from /opt/packages/3d/OrcaSlicer/src/OrcaSlicer_profile_validator.cpp:3:
/opt/packages/3d/OrcaSlicer/src/libslic3r/GCode/SmallAreaInfillFlowCompensator.hpp:12:7: warning: ‘Slic3r::SmallAreaInfillFlowCompensator’ has a field ‘std::unique_ptr<{anonymous}::tk::spline> Slic3r::SmallAreaInfillFlowCompensator::flowModel’ whose type has internal linkage [-Wsubobject-linkage]
   12 | class SmallAreaInfillFlowCompensator
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Having tk::spline header-only implementation included from SmallAreaInfillFlowCompensator.hpp makes
SmallAreaInfillFlowCompensator::flowModel have separate (albeit the same) implementation in each translation unit.

In order to fix this issue, SmallAreaInfillFlowCompensator::flowModel converted to opaque 'pimpl'

## Tests

Fixes ~240 compilation warnings

### CODE REVIEW

**Comment by buzzhuzz** [comment]
@mjonuschat , could you please help review this change?

**Comment by buzzhuzz** [comment]
Just found that PR https://github.com/SoftFever/OrcaSlicer/pull/5963 adds warning suppression using pragmas. Unfortunately, this leads to `-Wunknown-warning` warnigs on clang builds:
```
/opt/3d/OrcaSlicer/src/libslic3r/GCode/SmallAreaInfillFlowCompensator.hpp:17: warning: unknown warning group '-Wsubobject-linkage', ignored [-Wunknown-warning-option]
In file included from /opt/3d/OrcaSlicer/src/libslic3r/GCode/SmallAreaInfillFlowCompensator.cpp:17:
/opt/3d/OrcaSlicer/src/libslic3r/GCode/SmallAreaInfillFlowCompensator.hpp:17:32: warning: unknown warning group '-Wsubobject-linkage', ignored [-Wunknown-warning-option]
   17 | #pragma GCC diagnostic ignored "-Wsubobject-linkage"
      |                                ^
```

Which adds extra points to this PR

**Review by SoftFever — COMMENTED** [review]
Thanks, it looks good.

I'm not very clear about the purpose of  `TK_SPLINE_OUTER_NAMESPACE` macro, could you explain it?

**Comment by buzzhuzz** [comment]
Types within anonymous namespace cannot be forward declared.

I've added a macro to keep an option to include spline.h  within anonymous workspace if needed.

**Comment by SoftFever** [comment]
Would it be simpler if we move the spline out of the anonymous namespace?
It's still in tk namespace, so I think it won't cause any issue

**Comment by buzzhuzz** [comment]
That would also work.

**Review by SoftFever — APPROVED** [review]
Looks good
Thank you

**Pull request merged**
