### PR TITLE
Try flatpak again

### PR DESCRIPTION
**Pull request by powpingdone**
# Description

From #5510 
> @powpingdone
> I noticed it causes build breaks: https://github.com/SoftFever/OrcaSlicer/actions/runs/9877669432/job/27279875122
> I've temporarily reverted the change. Could you take a look when convenient?

### CODE REVIEW

**Comment by SoftFever** [comment]
@powpingdone 
Now I think the build break is not related to your changes.
Please refer to https://github.com/SoftFever/OrcaSlicer/issues/5916
Seems the CI/CD for deps are broken due to GitHub runner changes

**Comment by powpingdone** [comment]
Got it. I assume that means that MPI is now needed for the build? (Numeric pulls in some dep that requires MPI iirc). @SoftFever

**Comment by SoftFever** [comment]
I doubt that's the case.
Most likely some cmake related issue in Boost itself.
But I have no idea at the moment either.

**Comment by c2h5oh** [comment]
@powpingdone cmake 3.30 has stopped special treatment of boost https://cmake.org/cmake/help/v3.30/policy/CMP0167.html#policy:CMP0167 so we have to make changes to use the generic way of finding it

**Comment by powpingdone** [comment]
[Closed by 002125fb](https://github.com/SoftFever/OrcaSlicer/commit/002125fbe4b364834dc0fc73dc6755866f6a8e23).

**Pull request closed without merging**
